### ISSUE TITLE
Allow custom links in ToC

### ISSUE THREAD

**Issue by SimenB** [facebook/docusaurus#1011]
## 🚀 Feature

E.g. when writing API documentation, there might be aliases between functions. It would be nice to have them listed in the ToC at the top of a file for easier discoverability.

See https://github.com/facebook/jest/issues/5061

## Have you read the [Contributing Guidelines on issues](https://github.com/facebook/Docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yup

## Motivation

See linked issue

## Pitch

See linked issue

**Comment by slorber** [comment]
This looks like a v1 issue and I'm not really able to understand if it's still relevant in v2, let me know if it is

--- 


The Docusaurus team is actively working on Docusaurus v2.

After a very long alpha, Docusaurus v2 is [now in beta](https://docusaurus.io/blog/2021/05/12/announcing-docusaurus-two-beta).
We believe that the v2 beta is already better than v1, and v2 is ready for maintstream adoption.

Apart from critical issues and security fixes, we don't plan to invest much time on Docusaurus v1 anymore.

We are all closing v1 issues. 
Maybe the current issue is already fixed in Docusaurus v2.
Please try to upgrade, and if the issue is still there on Docusaurus v2, open a new issue.
