### ISSUE TITLE
How to disable static site generation and SEO metadata

### ISSUE THREAD

**Issue by pfdgithub** [facebook/docusaurus#10192]
In my case, I use the browser route, and `docs.routeBasePath: "/"` configuration.
The docs is deployed behind traefik and nginx multiple gateways, and the customer network is is a private network.

Traefik uses the `stripprefix` middleware to strip the `xxx` prefix.
Nginx uses the `try_files $uri $uri/ /index.html` directive to find files.
When the url path triggers the gateway fallback, it will respond with the incorrect redirect path.

```
# url with filename
browser (/xxx/category/index.html) -> traefik (/category/index.html) -> nginx(/category/index.html) -> nginx status 200 -> traefik -> browser

# url with trailing slash
browser (/xxx/category/) -> traefik(/category/) -> nginx(/category/) -> nginx status 200 (rewrite to `/category/index.html`) -> traefik -> browser

# url without trailing slash
browser (/xxx/category) -> traefik(/category) -> nginx(/category) -> nginx status 301 (redirect to `/category/`) -> traefik -> browser (/category/) -> traefik status 404 -> browser
```

Due to the `/category` directory exists, nginx attempts to redirect to that directory.
However, nginx is unaware of the xxx prefix, so it responds with the incorrect redirect to `/category/`.
If the `/category` directory doesn't exist, nginx can respond with the correct rewrite to `/index.html`.

```
# url without trailing slash (`/category` directory doesn't exist)
browser (/xxx/category) -> traefik(/category) -> nginx(/category) -> nginx status 200 (rewrite to `/index.html`) -> traefik -> browser
```

I can't modify the configurations of traefik and nginx, and `trailingSlash: true` is not a perfect solution, so I can only clean up redundant directories after building.
Is it possible to allow disabling the Static Site Generation (SSG) functionality, as well as useless SEO metadata under a private network, such as allowing `url: "/"`?

_Originally posted by @pfdgithub in https://github.com/facebook/docusaurus/issues/3825#issuecomment-2138770571_

**Comment by slorber** [comment]
This is more a question than an issue, and should be a github comment instead

Also you posted the original content but did not clarify anything I asked for (cf my comment https://github.com/facebook/docusaurus/issues/3825#issuecomment-2138980198), which still makes things super hard to understand for me.

Remember Docusauurs is only responsible for building static files. Nginx/Traeffik is out of scope, and I don't know how these tools work.

You can disable SSG with the new v3.4 hash router.

Going to close for now because this is unactionable for me.
