### ISSUE TITLE
[@docusaurus/plugin-client-redirects] `Redirect file creation error` on windows 

### ISSUE THREAD

**Issue by axel7083** [facebook/docusaurus#10232]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [X] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

When defining urls that are the same except uppercases, we are getting an error on windows machine

### Steps to reproduce

1. on windows machine clone https://github.com/containers/podman-desktop
2. run `yarn` to install dependencies
3. run `yarn website:prod`

### Expected behavior

build should work the same on windows and on linux

### Actual behavior

```
[ERROR] Redirect file creation error for "~\podman-desktop\website\build\docs\Installation\windows-install\installing-podman-desktop-silently-with-the-windows-installer\index.html".

[ERROR] Error: Unable to build website for locale en.
    at tryToBuildLocale (~\podman-desktop\node_modules\@docusaurus\core\lib\commands\build.js:54:19)
    at async ~\podman-desktop\node_modules\@docusaurus\core\lib\commands\build.js:65:9
    at async mapAsyncSequential (~\podman-desktop\node_modules\@docusaurus\utils\lib\jsUtils.js:20:24)
    at async Command.build (~\podman-desktop\node_modules\@docusaurus\core\lib\commands\build.js:63:5) {
  [cause]: [Error: EEXIST: file already exists, open '~\podman-desktop\website\build\docs\Installation\windows-install\installing-podman-desktop-silently-with-the-windows-installer\index.html'] {
    errno: -4075,
    code: 'EEXIST',
    syscall: 'open',
    path: '~\\podman-desktop\\website\\build\\docs\\Installation\\windows-install\\installing-podman-desktop-silently-with-the-windows-installer\\index.html'
  }
}
```

The reason is because we define the following 

```json
{
  to: '/docs/installation/windows-install',
  from: [
    '/docs/installation/windows-install/installing-podman-desktop-silently-with-the-windows-installer',
    '/docs/Installation/windows-install/installing-podman-desktop-silently-with-the-windows-installer',
  ],
},
```

There is a small difference, the uppercase at `Installation`.

The error only appear when building on windows, in our pipeline, no issue raised.

### Your environment

- Public source code: https://github.com/containers/podman-desktop
- Public site URL: https://podman-desktop.io/
- Docusaurus version used: 3.4.0
- Environment name and version (e.g. Chrome 89, Node.js 16.4): chrome latest
- Operating system and version (e.g. Ubuntu 20.04.2 LTS): Windows

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by slorber** [comment]
This is most likely because your file system is case-insensitive, unlike your CI

The 2nd redirect file can only be created unless the file system is case sensitive and allow both files to exist.

What would you expect to happen, for both environments, in this case?

I'd recommend against emitting twice the file. Many hosts will support serving static files in a case-insensitive fashion and just emitting lower-case redirect files should be enough. 

For example Netlify:
- https://docusaurus.io/docs/introduction
- https://docusaurus.io/docs/INtroDuCTION

GitHub Pages:
- https://tutorial.docusaurus.io/docs/tutorial-basics/create-a-page
- https://tutorial.docusaurus.io/docs/tutorial-basics/CREATE-a-page


I think some hosts like Vercel are case sensitive. But the truth is, you shouldn't use client directs with any host that support server redirects instead. 

Server redirects are always a better option, and to my knowledge only GitHub pages do not support server directs, so the only good reason to use client directs is if you deploy to GitHub Pages (or similarly very limited host), which is case insensitive.

**Comment by axel7083** [comment]
Thanks for the amazing explanation 👍  !

> I don't think we really need to fix anything here. At best we could ignore the error, or emit a more user-friendly error message.

Yes this is what I expect, having either a more friendly error, or ignore it.

> But it looks good enough to me honestly, because you figured out that you had twice the same redirect already. The question is: why did you add twice the same redirect in the first place? Have you tried with only one redirect, and what motivated you to add a second redirect?

No idea; I arrived later after it was like this, and the person who did that is not here anymore.
