### ISSUE TITLE
Automatic Docusaurus Translation Lib

### ISSUE THREAD

**Issue by tcapelle** [facebook/docusaurus#10347]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Description

Thanks for the great product.

I am here to share a tool enabling you to translate your Docusaurus-based docs by leveraging GPT4. We have been using this tool to translate our full documentation into Japanese and Korean.

Give it a try: https://github.com/tcapelle/gpt_translate

Feel free to share

### Self-service

- [ ] I'd be willing to address this documentation request myself.

**Comment by slorber** [comment]
Thanks for letting us know

Unfortunately opening a documentation issue here is not really the way to market your tool 😅 it's unactionable so I'm closing.

**Comment by tcapelle** [comment]
Where do you recommend me to share? I can PR somewhere?

**Comment by slorber** [comment]
You can share it on Twitter, LinkedIn, Discord, Mastodon, or wherever devs usually promote their tools.

We have a resource page on which we could accept a PR: https://docusaurus.io/community/resources

But in its current form we wouldn't accept that link because the repository doesn't even explain how to use this tool with Docusaurus. We'd accept an article about using your tool in conjunction with Docusaurus.

Note that having your link in our docs doesn't guarantee traffic. Not many visitors browse this page 🤷‍♂️

**Comment by tcapelle** [comment]
I built this tool for internal use, but some people started using it outside. Will try to find time to write that piece, just trying to help people here.
