### ISSUE TITLE
Add Arabic translation

### ISSUE THREAD

**Issue by AbdelattyBadwy16** [facebook/docusaurus#10388]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Description

Adding the Arabic language to the site makes it more popular in the Arab community

### Has this been requested on Canny?

https://docusaurus.io/feature-requests/p/add-arabic-translation

### Motivation

I think this is help the arab user .

### Self-service

- [X] I'd be willing to contribute this feature to Docusaurus myself.

**Comment by Josh-Cena** [comment]
Please see https://github.com/facebook/docusaurus/tree/main/packages/docusaurus-theme-translations/locales; we already have `ar`. If it's not the particular dialect of Arabic you are looking for, you are welcome to submit a PR to add another locale, but none of the maintainers are Arabic speakers (or _your_ Arabic speaker), so this issue is unactionable. All theme translations, except a few, are all community maintained and we don't take feature requests for them.
