### ISSUE TITLE
Support auto generating the sidebar alphabetically by label

### ISSUE THREAD

**Issue by austinsasko** [facebook/docusaurus#10403]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Motivation

I would like to propose that the functionality for autogeneration of the sidebar add in support for sorting by labels too. Support was added for position frontmatter and the file/folder name. I would propose that support is added for a given label in a sidebar, if it exists, arguably more so than the file/folder name. 

The below screenshot shows an example where the folders are created automatically by the ID of a given datum, whereas the label of each is automatically adjusted in each _category_.json. You can see in the image that the label is not taken into account and the ordering is a mess, looks like there is no order whatsoever. Of course, I could automatically figure that out and add it in to the _category_.json `position` flag, however, it seems intuitive that the alphabetical sorting would treat the way that is being displayed to users as more important than the backend file folder name.

![image](https://github.com/user-attachments/assets/f45f4b96-e891-436d-9d64-046909b8f11b)

### Self-service

- [X] I'd be willing to do some initial work on this proposal myself.

**Comment by slorber** [comment]
Please create a minimal repro. Your screenshot is truncated and we don't see the underlying code that leads to that specific sidebar.

Remember that you can override the auto-generated sidebar logic, you can create your own conventions yourself by providing your own generator:
https://docusaurus.io/docs/next/sidebar/autogenerated#customize-the-sidebar-items-generator


You can also "reuse" our default generator and re-order the generated items. The only limitation currently is that the generated items do not have a `label` property by default, and this would require to use of the `sidebar_label` front matter. We could eventually consider adding the doc label to the sidebar item to make this easier.

Here's an example: https://stackblitz.com/edit/github-h1nm8w?file=docusaurus.config.ts

```ts
function sortSidebaItems(items) {
  const sortedItems = [...items];

  sortedItems.sort((a, b) =>
    a.label.localeCompare(b.label, 'fr', { ignorePunctuation: true })
  );

  // Resurcively sort items nested in categories
  return sortedItems.map((item) => {
    if (item.type === 'category') {
      return { ...item, items: sortSidebaItems(item.items) };
    }
    return item;
  });
}

        docs: {
          async sidebarItemsGenerator({
            defaultSidebarItemsGenerator,
            ...args
          }) {
            const items = await defaultSidebarItemsGenerator(args);
            return sortSidebaItems(items);
          },
       }
```


As you can see, there's not a single way to sort strings. You have to consider what it means to sort strings in the first place. In which locales? What to do with diacritics, accents, spaces, upper/lowercase etc...

The only API that is flexible enough to sort labels in all the fancy ways our users might want is... code. That's why we expose a low-level API instead of a higher-level convenient shortcut that only satisfies a single user.

We can consider making your use-case easier to achieve, but it will probably require you to at least provide a sort comparison callback for items. For example:

```js
async function sidebarItemsGenerator({
  defaultSidebarItemsGenerator,
  ...args
}) {
  return defaultSidebarItemsGenerator({
    ...args,
    sortItems: (items) => myCustomItemSorter(items),
  });
}
```

**Comment by austinsasko** [comment]
I understand what you are saying, however, I don't think this proposal should be reinventing anything. What I mean by that is in PR https://github.com/facebook/docusaurus/pull/6700 sorting was added alphabetically, but by file/folder name. I think that if we support ordering by label (if label exists for that) to the same method that the PR enhanced. If a label does not exist, it can fall through to the file/folder name (which if I recall correctly shows up as the "label" per se anyways). 

I can definitely solve this with changes on my end, however, it feels like PR 6700, when support was added for alphabetical sorting, should have considered labels in addition to file/folder names, so I am hoping to propose something to address that gap (in my opinion).

Example use case: 
We have a folder with a bunch of subfolders that are named identifiers/keys, as shown here:
<img width="257" alt="image" src="https://github.com/user-attachments/assets/4146a8c9-7ca4-4020-bbc3-7ddf2ce84729">

However, each folder has a _category_ file giving them a label that is not a random ID value, but then the sidebar still gets sorted as by their folder name, rather than how they are actually shown in the sidebar (for example the first 3 sidebar items would correlate to the folder 104, 105, and 128): 
![image](https://github.com/user-attachments/assets/b16d50d1-61ef-4777-894a-0803358b6642)

Ultimately, I believe that the original intention was to show a sidebar that is alphabetical when there is no positioning identified, however, I don't believe that labels were considered (whether due to feature limitations at the time or just lack of use cases). Considering labels into the picture of #6700 and the issue behind that, I think it is a definite gap with an opportunity for improvement.

**Comment by slorber** [comment]
Imagine someone else has the exact same files/folders as you do, and also give labels to their categories. But unlike you, they want the items to be ordered by numbers instead of labels. Now we implement your change and they are not happy because their sidebar order changed (a behavior change that may be considered a breaking change).

2 users with the same structure might think they both deserve their opinions to be made the default, but we can only pick one default behavior, and so far only one person complained and asked to change it: you. 

If you can rally other users under your cause, then this means you are not alone. If you can find open-source sites that want it so badly that they implemented it in userland with a custom generator, that means there's demand for it. 

Otherwise, we might change a default behavior to satisfy a single user, and this might lead many other users to be unhappy about the behavior change.

> > Ideally, this preference should be configurable in the config file so users can choose which they'd prefer.
> 
> Sorry, no; the default is only a really basic logic, and if you want any customization, you should use explicit sidebar positions or the `sidebarItemsGenerator` option.

@Josh-Cena answered that in the original issue and I still agree: we already provide low-level extension points that you can use to implement your custom sort logic.

> Ultimately, I believe that the original intention was to show a sidebar that is alphabetical when there is no positioning identified

I don't think it was the initial intention.

We didn't really think about a more complex logic at that time because it's not possible to find the "perfect" default order: everybody might have a different opinion about it. The goal is to provide simple a good-enough default that users can then customize if they need to.


More importantly, defining an explicit order ensures that users on Windows/macOS do not see different orders due to different OS or fs implementations. 

To make that happen we had to make arbitrary decisions. For example: if some items have positions and others do not, which items should appear first? Honestly, we don't care. One decision is not really better than the other. We had to decide on a default and give a way for users to take over with code if needed.

**Comment by austinsasko** [comment]
Very good points, I will take the custom generator route. Thanks!
