### ISSUE TITLE
Admonitions in MDX "partials" are not rendered properly

### ISSUE THREAD

**Issue by cemerick** [facebook/docusaurus#10576]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [X] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

When using an MDX partial (e.g. `_markdown-include.mdx`) that contains an MDX admonition:

```mdx
:::info[Broken admonition]

This admonition isn't rendered properly.

:::

import Admonition from '@theme/Admonition';

<Admonition type="info">
  <p>This admonition looks as expected.</p>
</Admonition>
```

The MDX-style admonition is not rendered properly (whereas the JSX one is).

Codesandbox URL below :-)

### Reproducible demo

https://codesandbox.io/p/sandbox/cocky-jackson-ny6mjg

### Steps to reproduce

1. Put an MDX-formatted admonition in an MDX file
2. Import that file as a "partial"
3. Include the partial in some JSX page

### Expected behavior

For the MDX-format admonition to appear with styling/icon/header as it would if the MDX file were visited directly.

### Actual behavior

The body of admonition is shown plainly, and the markup usually associated with an admonition is basically missing. What does come out is an HTML transliteration of JSX admonitions:

```html
<admonition title="..." type="..."> ...body... </admonition>
```

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by hunxjunedo** [comment]
@slorber let me investigate and work on this, kindly assign.

**Comment by slorber** [comment]
We don't assign issues here

If you have a solution to solve this bug, please submit a PR directly

**Comment by Josh-Cena** [comment]
The issue is that we use `MDXComponents` to map `<admonition>` to `@theme/Admonition`, but this mapping is absent for the fallback loader, I think.

**Comment by slorber** [comment]
I don't think that's the problem, MDXProvider is applied at the top of the page so anything imported from it should benefit from the provider.

Also, the partial is in the `pages` folder so the same remark plugins should apply to both the page and the partial. The partial shouldn't use our fallback loader. 

Will need to debug this to figure out what is happening exactly 😅

**Comment by slorber** [comment]
Oh, found the problem. @Josh-Cena was close.

It's not really a bug but a known limitation we have already documented. And it applies to other elements such as code blocks as well.

When importing MDX documents in a JSX page, you have to apply the MDX provider yourself so that all the "built-in" theme-classic components become accessible to that MDX content piece.

https://docusaurus.io/docs/markdown-features/react#mdx-component-scope

![CleanShot 2024-11-22 at 16 54 57](https://github.com/user-attachments/assets/6f1788d7-9d10-4f0f-8611-ac48a0a16a00)

This is because the MDX scope is a theme-classic feature, not a core feature, so we unfortunately can't apply it globally.
