### ISSUE TITLE
Sidebar with only external links fails

### ISSUE THREAD

**Issue by johnmcase** [facebook/docusaurus#10597]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [X] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

Creating a sidebar that has only `type: 'link'` items in it causes an error.  Error message is: `DocSidebarNavbarItem: Sidebar with ID "linksSidebar" doesn't have anything to be linked to.`

Reporduction:  https://stackblitz.com/edit/docusaurus-vttzpv?file=sidebars.js

### Reproducible demo

https://stackblitz.com/edit/docusaurus-vttzpv?file=sidebars.js

### Steps to reproduce

Create a sidebar that looks something like this:

```js
linksSidebar: [
    { type: 'link', label: 'Facebook', href: 'http://www.facebook.com' },
    { type: 'link', label: 'Google', href: 'http://www.google.com' },
    { type: 'link', label: 'Amazon', href: 'http://www.amazon.com' },
  ],
```

### Expected behavior

Sidebar is displayed

### Actual behavior

Runtime error

### Your environment

- Public source code:
- Public site URL:
- Docusaurus version used:
- Environment name and version (e.g. Chrome 89, Node.js 16.4):
- Operating system and version (e.g. Ubuntu 20.04.2 LTS):

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by slorber** [comment]
That's because you have a navbar item that tries to link to a sidebar:

```js
        {
          type: 'docSidebar',
          sidebarId: 'linksSidebar',
          position: 'right',
          lable: 'External links',
        },
```

This navbar item must be clickable, but your sidebar contains no page, only external link, so there's no URL the navbar item can link to. The error is on purpose to help you figure out this problem. This is not a bug.

Where do you expect your sidebar to be displayed exactly? On what precise URL is this supposed to be displayed? Since your sidebar contains no doc, it won't be displayed on any of your pages unless you use `displayed_sidebar: linksSidebar` on another doc. 

Having a sidebar full of external links is a weird pattern to use. Please explain your intent.
