### ISSUE TITLE
Add feature to track docs from different branches

### ISSUE THREAD

**Issue by SilleBille** [facebook/Docusaurus#1060]
## 🚀 Tracking docs from different branches

The current implementation allows reading docs from a *Single Branch* with *multiple dirs that point to different version docs*.

This feature would allow projects that base their *product version on different branches**. 

## Have you read the [Contributing Guidelines on issues](https://github.com/facebook/Docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## Motivation
After attending ATO2018 conference, @yangshun and I had a discussion regarding this feature. 

## Pitch
Project `ATO` has branches `ATO1` and `ATO2`. Each branch has a dir named `doc` that has that particular version's documentation (ie) `ATO1/doc` has `v1` doc and `ATO2/doc` has `v2` doc. Instead of forcing the project to move all their docs to a single branch, docusaurus should be able to accomodate the above mentioned project structure as well.

**Comment by yangshun** [comment]
Nice meeting you earlier @SilleBille! I don't have a good suggestion for that kind of branching model because if two docs are on different branches, it feels more correct to generate a website separately for each. Take Bootstrap for example, V4 dos are hosted at https://getbootstrap.com/docs/4.1/ and v3 docs at https://getbootstrap.com/docs/3.3/. They are separate websites. I don't think there are any site generators out there that support generating a site across multiple branches.

cc @endiliey and @JoelMarcey for opinions.

**Comment by endiliey** [comment]
I am not in a good favor of this issue >.<

Branching is actually a non easy concept and I think it's better to make things simple.

**Comment by SilleBille** [comment]
@endiliey  is right. This feature does makes things a little complicated. To answer @yangshun  there is readthedocs which actually supports such a feature.
