### ISSUE TITLE
optimize the size of bundle files

### ISSUE THREAD

**Issue by ydcteam** [facebook/docusaurus#10702]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Motivation

Hello, I have just started developing Docusaurus plugins. I have encountered a tricky problem: the size of bundle files are too large, affecting the speed of the browser site resources and causing long page loading times. How can I optimize the size of the bundle files? I have tried to configure webpack for code splitting, but the effect is not very satisfactory. Waiting for  some  suggestions with tks a lot.

### Self-service

- [ ] I'd be willing to do some initial work on this proposal myself.

**Comment by philippnagel** [comment]
@ydcteam which Docusaurus version are you using? The latest one with Rspack?

**Comment by slorber** [comment]
@ydcteam it's not clear to me:
- is this a complaint of Docusaurus bundle size being too large by default?
- is this you when implementing a plugin that increases that bundle size?

Those are quite different topics. 

We constantly try to reduce bundle size of the base Docusaurus site already, but it's not always so easy and we have limited bandwidth to do so.

For plugin authors, there are pitfalls to avoid for sure, but we can't help you much if you don't share your plugin code.

It's also worth mentioning what in your opinion shouldn't be in those bundles exactly? What should we strive to remove and why? And why/how do you see it as a performance problem?

I'm going to close because it's not really a concrete proposal and more a community question, but we continue discussing this topic here.
