### ISSUE TITLE
<summary> is not properly rendered as a title within <details> when a blank line is present

### ISSUE THREAD

**Issue by MongoRolls** [facebook/docusaurus#10758]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [X] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

<summary> is not properly rendered as a title within <details> when no blank
<img width="1910" alt="image" src="https://github.com/user-attachments/assets/203cefd8-7f4c-48a4-9224-2074a5229763" />
<img width="947" alt="image" src="https://github.com/user-attachments/assets/18150370-e5ba-4dad-a776-9806f1b47013" />

### Reproducible demo

https://codesandbox.io/p/devbox/purple-bush-wplmtd?file=%2Fblog%2F2021-08-26-welcome%2Findex.md%3A14%2C1-23%2C11&workspaceId=ws_W6TYUP64x6znduLNiDmQHh

### Steps to reproduce

1.
```
<details>
<summary>w2222</summary>
  
  222
</details>

<details>
<summary>w1111</summary>
111
</details>
```

### Expected behavior

like MDN:
<img width="859" alt="image" src="https://github.com/user-attachments/assets/a03547dc-4b02-4c40-9730-a24bdc32c732" />

### Actual behavior

<summary> is not properly rendered as a title within <details> when no blank

### Your environment

  "dependencies": {
    "@docusaurus/core": "3.0.1",
    "@docusaurus/plugin-ideal-image": "3.0.1",
    "@docusaurus/plugin-pwa": "3.0.1",
    "@docusaurus/preset-classic": "3.0.1",
    "@docusaurus/theme-search-algolia": "3.0.1",
}

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by slorber** [comment]
Your codesanbox is private and your bug report uses image, making it hard to copy/paste snippets and reproduce.

We use MDX, which by default has this behavior, as seen on the MDX playground: https://mdxjs.com/playground/

![CleanShot 2024-12-12 at 14 35 24@2x](https://github.com/user-attachments/assets/41d43d44-5a4e-49eb-ad67-28ae5a524876)

This is because in the 2nd case your summary is wrapped in a `<p>` element.

![CleanShot 2024-12-12 at 14 36 12@2x](https://github.com/user-attachments/assets/9374f431-e7e9-49bb-811d-b415194d06dc)

This is how MDX choose to behave when interleaving Markdown and JSX. Keep in mind that the summary content here is not HTML text, but can be Markdown as well, so it's normal that the behavior is slightly different from standard HTML markup.

```mdx
<details>
<summary>w1111</summary>

**111**

</details>
```

This is not a bug, this is just how MDX behave on purpose, and we don't plan to diverge from this behavior. 

There are many possibilities to solve your problem, read the MDX doc and use the MDX playground to figure out the best way to do it. One solution is to add line breaks, the other is to use JSX fragments:

```mdx
<details>
  <summary>w1111</summary>
  <>111</>
</details>
```

Maybe you'll find this resource helpful to better understand the paragraphs created by MDX: https://github.com/facebook/docusaurus/discussions/10580
