### ISSUE TITLE
autoplay attribute gets stripped on <video> tags

### ISSUE THREAD

**Issue by maxweisel** [facebook/docusaurus#10776]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [X] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

When using a <video> tag, I can use `width="100%"` and `controls` successfully, but if I add `autoplay` it gets stripped. I have graphics that I've rendered as video with no audio that I'm using in place of gifs since gifs can be massive. I'd like them to autoplay to match the behavior of gifs.

### Reproducible demo

https://codesandbox.io/p/devbox/intelligent-mopsa-qdeo7?privacy=public

### Steps to reproduce

I've added an example &lt;video&gt; tag to docs/intro.md. Run docusaurus and open up the sandbox and navigate to the intro.md page.

### Expected behavior

I'd expect the `autoplay` tag to make it to the generated page.

### Actual behavior

The tag appears to be stripped. The other tags (`width`, and `controls`) make it through fine.

### Your environment

- Public source code: Not public
- Public site URL: https://docs.normcore.io
- Docusaurus version used:
```
"@docusaurus/core": "^3.1.1",
"@docusaurus/preset-classic": "^3.6.3",
"@docusaurus/theme-mermaid": "^3.6.3",
```
- Environment name and version (e.g. Chrome 89, Node.js 16.4): Node 18 LTS, Chrome 131.0.6778.87
- Operating system and version (e.g. Ubuntu 20.04.2 LTS): macOS 14.4.1

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by slorber** [comment]
Going to close because the description is incomplete, the repro does not contain any `<video>` tag in `docs/intro.md`, no code snippet was provided and I don't know if you use MDX or CommonMark mode, so in its current state the issue cannot (yet) be considered as a bug.

Most likely, you are using MDX (the default), and your tags are JSX (not HTML). React uses camel case for props, so you need to use `autoPlay`, not `autoplay`.

The following works fine for me:

```mdx
<video controls width="250" autoPlay>
  <source
    src="https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4"
    type="video/mp4"
  />
</video>

```

While the following doesn't:

```mdx
<video controls width="250" autoplay>
  <source
    src="https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4"
    type="video/mp4"
  />
</video>
```

This is not a Docusaurus/MDX behavior, this is a React behavior.

You can test it in the MDX playground too, only the first video is playing:

https://mdxjs.com/playground/

![CleanShot 2024-12-19 at 10 30 27@2x](https://github.com/user-attachments/assets/47c31d44-c3ec-4d95-9946-75ae96901569)

If you want the HTML behavior instead of the React behavior, you would have to opt-in for the CommonMark mode: https://docusaurus.io/docs/markdown-features#mdx-vs-commonmark
