### ISSUE TITLE
Algolia placeholder does not work docusaurus.config.js file.

### ISSUE THREAD

**Issue by FlyNumber** [facebook/docusaurus#10774]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [X] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

According to https://docusaurus.io/docs/search#customizing-the-algolia-search-behavior

We can use

`placeholder`
type: string | default: "Search docs" | optional

The placeholder of the input of the DocSearch pop-up modal.

... this does not work and we get a TS error

`theme-search-algolia.d.ts(12, 5): The expected type comes from property 'algolia' which is declared here on type 'ThemeConfig'`

### Steps to reproduce

Add `placeholder` to Algolia field in Docusaurus config

### Expected behavior

Search box modal would use my value instead of the default "Search docs"

### Actual behavior

TS error

`theme-search-algolia.d.ts(12, 5): The expected type comes from property 'algolia' which is declared here on type 'ThemeConfig'`

### Your environment

- Public source code:
- Public site URL:
- Docusaurus version used:
- Environment name and version (e.g. Chrome 89, Node.js 16.4):
- Operating system and version (e.g. Ubuntu 20.04.2 LTS):

### Self-service

- [X] I'd be willing to fix this bug myself.

**Comment by slorber** [comment]
Note that you can already provide a custom label by using our i18n support: we consider those labels are translatable i18n english labels, so translating english labels will permit to customize the labels. You can also swizzle `@theme/SearchTranslations`.

Will be fixed in https://github.com/facebook/docusaurus/pull/10799 since I agree using our i18n system for customizing such label is a bit awkward and unintuitive if your site is not localized.
