### ISSUE TITLE
[Feature]: <FileTree> component

### ISSUE THREAD

**Issue by ianzone** [facebook/docusaurus#10780]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Description

This component shall render an interactive file tree. 

### Motivation

See [Astro FileTree](https://starlight.astro.build/components/file-tree/)

### Self-service

- [ ] I'd be willing to contribute this feature to Docusaurus myself.

**Comment by slorber** [comment]
We know that such a component can be useful, but as explained by our template, we expect you to provide a design.

Ideas can be submitted on our feature request tracker: https://docusaurus.io/feature-requests.

Also, since it's a React component, it can be implemented in userland first, and once it's working nicely, we can integrate it in Docusaurus core if this makes sense.
