### ISSUE TITLE
MarkdownBlock does not work for complex markdown

### ISSUE THREAD

**Issue by nareshbhatia** [facebook/Docusaurus#1158]
## 🐛 Bug Report

`MarkdownBlock` works for simple markdown, e.g.

```
<MarkdownBlock>
    [Markdown syntax for a link](http://www.example.com)
</MarkdownBlock>
```

But it does not work for complex markdown, e.g.

```
<MarkdownBlock>
Features
--------
- Feature 1
- Feature 2
</MarkdownBlock>
```

In this case, all markdown is output as text.

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/Docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## To Reproduce

```
<MarkdownBlock>
Features
--------
- Feature 1
- Feature 2
</MarkdownBlock>
```

## Expected behavior

Output should be an `<h2>` followed by `<ul>...</ul>` 

## Actual Behavior

Output is:

```
<div>
    <span>
        <p>Features -------- - Feature 1 - Feature 2</p>
    </span>
</div>
```

## Reproducible Demo

(Paste the link to an example repo, including a `siteConfig.js`, and exact instructions to reproduce the issue.)

**Comment by nareshbhatia** [comment]
A followup question: is there a way to include a markdown file inside `<MarkdownBlock>`? or some other way of including a markdown file inside a React component?

**Comment by endiliey** [comment]
Basically what we do on Docusaurus is that

!. We read the markdown files, and parses it as a raw string. Example: `doc1.md`
```js
const content = fs.readFileSync('/path/to/doc1,md/');
```

2. And then pass that string to `<MarkdownBlock />` component
```
<MarkdownBlock>
{content}
</MarkdownBlock>
```

From technical point of view, it's very likely that the buggy part is the string provided as the `MarkdownBlock` children props.

What happen for your test case ?

Note that
```
Features\n--------\n- Feature 1\n- Feature 2
```

could be different from
```
Features
--------
- Feature 1
- Feature 2
```

Because the newline string could be interpreted as just bunch of spaces depending on your code editor. 

To answer your question, maybe you can try using [fs](https://nodejs.org/api/fs.html) module provided by Node to read your file raw string.

**Comment by nareshbhatia** [comment]
Thanks @endiliey. I will give it a try when I have some time. In the meanwhile, I worked around this issue by writing regular JSX in my component.

Incidentally, I just published my site: https://nareshbhatia.github.io/mobx-state-router/. Looks great! Thanks for all your efforts. Love Docusaurus 👍

**Comment by AndrewDiMola** [comment]
Had the exact same issue with the MarkdownBlock render. I'm using multiple MarkdownBlock's whenever I need a line break to force proper behavior, but it doesn't feel right.
