### ISSUE TITLE
Section titles in sidebar as links

### ISSUE THREAD

**Issue by o-t-w** [facebook/docusaurus#1182]
I would like category titles in the sidebar to be clickable links rather than just titles. Currently, the documentation I am working with has main categories that I would like to link to markdown pages. The categories have subcategories that are separate markdown files and that need to be listed underneath the main category titles.

**Comment by tusharf5** [comment]
As of right now, there is no way to link main categories to (blog, page, href ) in `sidebars.json` in both v1 and v2.

```js
{
  "docs": {
    "My Example Category": [
      "examples",
      {
        "type": "subcategory",
        "label": "My Example Subcategory",
        "ids": [
          "my-examples",
        ]
      },
      "even-more-examples",
    ],
  }
}
```

I also don't think there is a good place in `sidebars.json` where we can add this information without majorly changing its structure. **( might be wrong here )** So maybe we can put a **new** `sidebarLinks` field to `siteConfig.js` which will contain a map of **[Category_Name]**::**[Link_Info_Object]** which we can use to link categories in the sidebar.

For each category object, the user can also provide a `subcategories` field which will contain information about linking of a subcategory. The subcategory link info can also be provided in `sidebars.json` since it will always be an object but then the user would have to provide this info at two different places.

```js
{
  "headerLinks": [],
  "sidebarLinks": {
    "Guides": { // should match the actual category label/key
       "doc": "installation", // link type
       "subcategories": [
          {
            "label": "My Sub Category" // should match with the actual subcategory label,
            "doc": "my-sub-category" // link type
          }
       ]
    },
    "Getting Started": {
       "page": "getting-started"
    },
    "API": {
       "href": "https://api.com"
    },
  },
  "headerIcon"
}
```

Any thoughts or recommendations on this @endiliey @JoelMarcey ? I would like to work on this : )

**Comment by waldyrious** [comment]
@endiliey can you please clarify how #1812 fixed this issue? I couldn't find anything in the opening comment or discussion thread of that PR seems to relate to the request in this issue, which is, quoting the comment above by @o-t-w:

> category titles in the sidebar to be clickable links [...] to markdown pages.

Also, the [preview link](https://deploy-preview-1812--docusaurus-2.netlify.app/) also doesn't seem to implement that request. Am I missing something?

**Comment by tusharf5** [comment]
@waldyrious Sadly, @endiliey is no longer with us. He inspired me to do open source.

**Comment by waldyrious** [comment]
OMG, I'm so sorry! I didn't know. Thanks for letting me know. :pray:

**Comment by waldyrious** [comment]
On the topic of my previous question, @tusharf5, who would be the right person to reach out to?

**Comment by tusharf5** [comment]
I am not really sure. Maybe you can try to submit a new issue and link this one to it.

**Comment by Josh-Cena** [comment]
@waldyrious maybe https://github.com/facebook/docusaurus/issues/2643 is similar to what you imagine?

**Comment by waldyrious** [comment]
@Josh-Cena that was exactly what I had in mind, yeah. I was puzzled because this issue seemed to be asking for the same thing, but was closed, so I was trying to understand if I either misunderstood this issue, or whether #1812 indeed implemented some solution to this that would also apply to #2643. Any insights would be appreciated.

**Comment by Josh-Cena** [comment]
Yeah, I think #1812 was mistakenly linked to this issue. We have so many issues requesting the same feature now 🌝 There's already a PR out there (two, actually) which got stalled

**Comment by slorber** [comment]
This will be implemented very soon as part of https://github.com/facebook/docusaurus/issues/2643, next item on my todolist
