### ISSUE TITLE
No branded docusaurus-init

### ISSUE THREAD

**Issue by JoelMarcey** [facebook/docusaurus#1196]
## 🚀 Feature

A no-branded, totally vanilla `docusaurus-init`

## Have you read the [Contributing Guidelines on issues](https://github.com/facebook/Docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## Motivation

via @jordwalke

## Pitch

Have a version of `docusaurus-init` that does not include any logos, images, etc. Just vanilla.

Could be run like `docusaurus-init --no-brand` or something.

**Comment by kyldvs** [comment]
I just ran into this too, was hard to make sure I found and removed all the branding. I think I still use a css class prefixed with fb in the footer I couldn't find to rename.

**Comment by ahmadalfy** [comment]
Can someone clarify what's the [hackathon](https://github.com/facebook/Docusaurus/labels/hackathon) tag? should contributors avoid doing efforts on it?

**Comment by ahtee** [comment]
@kyldvs mentioned that it took a while to remove all branding, and this is a no-branding discussion, but what if there was a central place where you could change the branding everwhere if you did have a brand? and if that field is empty or `null` then it removes all branding..?

**Comment by alexieyizhe** [comment]
@endiliey is anyone working on this? if not, I'd love to give it a shot 👍

**Comment by endiliey** [comment]
cc @yangshun

**Comment by fanny** [comment]
@yangshun I think that would be a good way to explore more the plugins config. What do you think?

**Comment by leeyspaul** [comment]
Reviving an old thread. What constitutes vanilla? I was browsing around and starting with `init` gave me a few reference to docusarus but not a lot. Thank you for the context in advance. :] 

@JoelMarcey

**Comment by slorber** [comment]
Not sure exactly either what should be done, but it looks related to https://github.com/facebook/docusaurus/issues/3489

**Comment by leeyspaul** [comment]
Yeah, it seems like #3489 is about splitting up the base template into a series of templates for different use cases. So this vanilla template would be the base perhaps.  

I think the maintenance factor is a valid concern too. Definitely still seems like an open and ongoing discussion. @fanny might have some creative ideas!

**Comment by slorber** [comment]
I'm considering that this issue is v1

v2 now has a classic template with no Facebook branding, and has a separate template for Facebook projects.

Considering the classic template as the "vanilla" template, but I'm not 100% sure to understand what vanilla means exactly here. v2 users don't complain much about having to remote existing branding.

---

The Docusaurus team is actively working on Docusaurus v2.

After a very long alpha, Docusaurus v2 is [now in beta](https://docusaurus.io/blog/2021/05/12/announcing-docusaurus-two-beta).
We believe that the v2 beta is already better than v1, and v2 is ready for maintstream adoption.

Apart from critical issues and security fixes, we don't plan to invest much time on Docusaurus v1 anymore.

We are all closing v1 issues. 
Maybe the current issue is already fixed in Docusaurus v2.
Please try to upgrade, and if the issue is still there on Docusaurus v2, open a new issue.
