### ISSUE TITLE
Content Index does not show on the right side on a page in IE and Edge browsers

### ISSUE THREAD

**Issue by wilsonyou** [facebook/docusaurus#1241]
## 🐛 Content Index does not show on the right side on a page in IE and Edge browsers
I test the docs as you suggest on my local computer and it works. But the following issue occurs:
Shown as below:

![image](https://user-images.githubusercontent.com/40747875/53157253-0d23ee00-35fc-11e9-8ed8-3815d157a0cb.png)

Could you help to figure out?

**Comment by CaptainT33mo** [comment]
Hi @wilsonyou , 
The reason right side sidebar is not visible in IE is because Docusaurus is using `@supports` **Feature Queries** which is not supported in **Internet Explorer** (see [this](https://www.caniuse.com/#search=%40support) link). However, **Edge** does support it so it will work perfectly fine in **Edge**.

I found **[Stickybits](https://css-tricks.com/stickybits-alternative-position-sticky-polyfills/)** as an alternative to `position: sticky;` for Internet Explorer. You can try using `**Stickybits**` in your project to resolve this issue.

Let us know if it resolves your issue.

https://dollarshaveclub.github.io/stickybits/

**Comment by slorber** [comment]
The Docusaurus team is actively working on Docusaurus v2.

After a very long alpha, Docusaurus v2 is [now in beta](https://docusaurus.io/blog/2021/05/12/announcing-docusaurus-two-beta).
We believe that the v2 beta is already better than v1, and v2 is ready for maintstream adoption.

Apart from critical issues and security fixes, we don't plan to invest much time on Docusaurus v1 anymore.

We are all closing v1 issues. 
Maybe the current issue is already fixed in Docusaurus v2.
Please try to upgrade, and if the issue is still there on Docusaurus v2, open a new issue.
