### ISSUE TITLE
Sidebar doesn't show for docs not in sidebars.json

### ISSUE THREAD

**Issue by feature** [facebook/Docusaurus#1296]
## 🚀 Feature

If you view a doc that isn't listed in the `sidebars.json`, the sidebar doesn't show. This makes page look a lot worse, breaks the consistency of the page layout with other docs, and makes it harder for users to navigate.

## Have you read the [Contributing Guidelines on issues](https://github.com/facebook/Docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## Motivation

Consistent layout between all docs, better navigation for users.

## Pitch

I think we should have an option to enable sidebars for all doc pages, regardless of their inclusion in the `sidebars.json`. as it sometimes may not be desirable to include all your docs in the sidebar, but you would still want the sidebar shown.

Related issue: #865

**Comment by feature** [comment]
Alternatively, I think it would be even better if we could include docs in the `sidebars.json`, and simply just hide them from the sidebar. My reasoning for not putting docs in the sidebars, is that it will become too cluttered, but I think this idea would solve the problem even better than my original proposal.

**Comment by amimas** [comment]
> Alternatively, I think it would be even better if we could include docs in the sidebars.json, and simply just hide them from the sidebar.

Not really sure what you mean here. But, wouldn't it be confusing to see a sidebar even when that page does not belong to a sidebar? How would you control the next/previous page navigation?

Also, currently you can actually have completely separate sidebars for different groups/types of docs.

**Comment by endiliey** [comment]
The reason why I closed #865 is because the issue was solved through [our Discord](https://discordapp.com/invite/docusaurus).

The thing is: We allow multiple sidebars so if one doc doesn't want to be listed in a sidebar, there is a confusion on which one to show. I f you want a consistency on page layout, you can always override the css.

I'm gonna take the same stance as last time and close up this issue. 
Reasoning
1. It is intended. 😉 
2. We're prioritizing v2 dev now (it's been quite delayed for some time) and avoiding feature request on v1.
