### ISSUE TITLE
Docusaurus v2: improperly escaped routes on Windows

### ISSUE THREAD

**Issue by nebrelbug** [facebook/Docusaurus#1350]
## 🐛 Bug Report

(A clear and concise description of what the bug is)

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/Docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## To Reproduce

(Write your steps here:)

1. `git clone` and `cd` Docusaurus repo
2. `yarn install`
3. `cd website`
4. `yarn start`

## Expected behavior

The local server will start

## Actual Behavior

A blank page shows up at localhost:3000, and the terminal says: 

> Module not found: Can't resolve '@generateddocusaurus-plugin-content-blologMetadata.json' in 'C:\Users\nebrelbug\Documents\Coding\Docusaurus\website\.docusaurus'./.docusaurus/metadata.js

## Reproducible Demo

Follow the steps to reproduce

## What I think is the issue:

If you look in `website/.docusaurus/routes.js` and `website/.docusaurus/routes.js`, you can see that many of the routes look like this: `'C:\Users\nebrelbug\Documents\Coding\Docusaurus\docs\api-commands.md'` when they should look like: `C:\\Users\\nebrelbug\\Documents\\Coding\\Docusaurus\\docs\\api-commands.md`

I'm guessing this has to do with the fact that Windows uses `\` for paths

**Comment by endiliey** [comment]
Thank you for reporting. It is very awesome to see a bug in v2 reported when we haven’t release even an alpha version of it yet 😂.

Things are still experimental on v2 and we still track things internally. I think its best to report such bug in our [Discord](https://discord.gg/CNft86U) for now at least until we release an alpha version of it so that people won’t get confused

By the way, thank you for being awesome 😊

**Comment by yangshun** [comment]
@nebrelbug Thanks for reporting! Would you have time to help fix this? The v2 team doesn't have Window devices so bugs like this got unnoticed. We'll definitely pay more attention to such issues in future.

**Comment by nebrelbug** [comment]
Thanks for fixing the issue @endiliey, and for the encouragement!
