### ISSUE TITLE
Unable to add inline graphic

### ISSUE THREAD

**Issue by emanic** [facebook/Docusaurus#1386]
## 🐛 Bug Report

I am not sure if this is a bug or a feature request but from my perspective, it seems like a bug.

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/Docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## To Reproduce

Example use case: instead of referring to a toolbar button by its name, I want to just insert an inline image of that button, because the toolbar button may not have any label associated with it and the picture will make it easier to find in any case.

I have some markdown like this:
```
Click the ![Create](assets/create-button.png) button.
```

## Expected behavior

```
Click the <picture> button.
```

## Actual Behavior

```
Click the

<picture>

button.
```

Docusaurus inserts line breaks before and after the image.

**Comment by amimas** [comment]
I ran into this issue recently when migrating some docs. Found out that some images of icons were showing up inline while most of the others weren't.

Only difference I could find was the image size. The ones that were showing up inline were very small image of some icons around 22px.

**Comment by endiliey** [comment]
This is because of docusaurus's default css on image

https://github.com/facebook/Docusaurus/blob/05ba7d835dc316b8f981e137e3935a51128ad2e4/packages/docusaurus-1.x/lib/static/css/main.css#L399-L405

If we change it to `display: inline`, this might be unwanted behavior for some site. Some site might indeed want it to be displayed in different block
To solve your solution, add this in your `custom.css`

```css
article p img,
article iframe {
  display: inline;
  margin-left: auto;
  margin-right: auto;
  max-width: 100%;
}
```
