### ISSUE TITLE
Remote Fetch Data

### ISSUE THREAD

**Issue by MateusAndrade** [facebook/docusaurus#1622]
Is there any way to request some remote data from my component? On this my Footer(which is generated by docusaurus).

I want to do something similar to this: 

```javascript
  fetchReposNumber() {
    try {
      fetch(url).then(
        response => {
          return response.json().data.length;
        }
      );
    } catch (error) {
        return 0;
    }
  }

 render() {
   return (
     <>
       {this.fetchReposNumber()} - Accounts
     </>
   )
 }
```

Im a newbie to docusaurus, and i apologize if this is a idiot mistake. :smile:

**Comment by yangshun** [comment]
Docusaurus 1 is using React as a templating engine only. Lifecycle and event handlers don't work because the browser only receives static HTML. You'll have to to inject scripts into your `render()` method to do that.

```
render() {
  return <div>
    <script dangerouslySetInnerHTML={{ __html: '<INSERT VANILLA JS' }}' />
  </div>;
}
```

Grep for `dangerouslySetInnerHTML` within Docusaurus website and see how it's done. Alternatively, you can write those logic in a separate script and include them via the `siteConfig` file.
