### ISSUE TITLE
Ignore `$ ` for clipboard copy

### ISSUE THREAD

**Issue by ericnakagawa** [facebook/docusaurus#1745]
## 🚀 Feature

When a code block has a leading "$ " at beginning of line, using the clipboard copy function copies in the entire text as is.

Ideally, it would ignore the "$ " in each line.

## Motivation

This is problematic in almost any developer site. The Dev experience for our users would improve with this feature.

## Pitch

This could improve copying from all sorts of code blocks "% ", "$ ", etc.

**Comment by ericnakagawa** [comment]
Also posted to Docusaurus 2 Canny, https://docusaurus-2.netlify.com/feedback/p/ignore-for-clipboard-copy

**Comment by endiliey** [comment]
I personally always recommend avoid writing $ in a codeblock especially if its a bash command. 

So 
```
git clone https://www.github.com/facebook/docusaurus.git
```

instead of
```
$ git clone https://www.github.com/facebook/docusaurus.git
```

While in some scenario we might want the user to not copy the $ button, in some scenario we actually might want the user to copy the $ button.

Consider a docs site which want people to copy a dummy markdown text
```
I have a story about dollar, i have five of them. Lets symbol them with a $.
$ $ $ $ $

This is good
```

There are also other programming languages out there or some API that might use $ or other symbol mentioned. It can be hard to tell when to remove $ safely

Opinions, anyone ?


<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by yangshun** [comment]
Maybe we could trim a leading `$ ` (dollar AND a space) from code block if it was present. I'm opting for not doing anything and prefer users just omit the `$` if they don't want people to be copying it.

**Comment by endiliey** [comment]
With current implementation of v2, user can easily override the CodeBlock source code with one single command (swizzle)

This make it easy for them to create very customized behavior. Example: 
https://twitter.com/dai_shi/status/1178673454419103750?s=20 can convert typescript to javascript code

Hence, i feel we should not doing anything in our side and let user customize their own
