### ISSUE TITLE
Unable to install in locked down enviroments

### ISSUE THREAD

**Issue by ConfuddledPenguin** [facebook/docusaurus#1758]
(wasn't quite sure what type of issue to flag this under)

## 🚀 Feature

In certian coorporate, regulated and/or security conscious firms external downloads are not tolerated, docusaurus has several dependencies which download binaries from 3rd party sources.

The dependencies in question are under imagemin:

* [imagemin-gifsicle](https://github.com/imagemin/imagemin-gifsicle) depends on [gifsicle-bin](https://github.com/imagemin/gifsicle-bin)
* [imagemin-jpegtran](https://github.com/imagemin/imagemin-jpegtran) depends on [jpegtran-bin](https://github.com/imagemin/jpegtran-bin)

Hoping opening this issue will trigger some action on the dependency authors to support the ability to speicify a 3rd party mirror for the binary, and this can be kept open to track progress.

Related issue on one of the mentioned projects https://github.com/imagemin/jpegtran-bin/issues/93

Related PR https://github.com/kevva/bin-wrapper/pull/73. This PR is based around the suggestions in the above issue, for bin-wrapper to support specifing a enviroment variable to check to find an alternative binary mirror location. 

## Have you read the [Contributing Guidelines on issues](https://github.com/facebook/Docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## Motivation

This would allow Docusaurus to be used in restrictive enrivornments.

## Pitch

Really keen to use docusuarus at work but this issue prevents us from doing so.

**Comment by checkflowio** [comment]
Yes, this is affecting me from using it at work too. It would be good to get this issue resolved.

**Comment by slorber** [comment]
The Docusaurus team is actively working on Docusaurus v2.

After a very long alpha, Docusaurus v2 is [now in beta](https://docusaurus.io/blog/2021/05/12/announcing-docusaurus-two-beta).
We believe that the v2 beta is already better than v1, and v2 is ready for maintstream adoption.

Apart from critical issues and security fixes, we don't plan to invest much time on Docusaurus v1 anymore.

We are all closing v1 issues. 
Maybe the current issue is already fixed in Docusaurus v2.
Please try to upgrade, and if the issue is still there on Docusaurus v2, open a new issue.
