### ISSUE TITLE
Relative URLs fail in combination with cleanUrl

### ISSUE THREAD

**Issue by Vinnl** [facebook/docusaurus#1774]
## 🐛 Bug Report

When [`cleanUrl`](https://docusaurus.io/docs/en/site-config#cleanurl-string) is `true`, relatively links in both `page.html` and `page/index.html` have the same target, whereas the former should e.g. be `target.html` and the latter `../target.html`.

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/Docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes.

## To Reproduce

(Assuming I haven't worked around it by the time this Issue is read:)

1. Visit https://vincenttunru.gitlab.io/tripledoc/docs/getting-started.html
1. Click "Cheatsheet" at the bottom of the page.
1. Now visit https://vincenttunru.gitlab.io/tripledoc/docs/getting-started/index.html
1. Click "Cheatsheet" at the bottom of the page.

## Expected behavior

The correct page to be shown in both step 2 and 4.

## Actual Behavior

The correct page is shown at step 2, but not at step 4.

## Reproducible Demo

As above: https://vincenttunru.gitlab.io/tripledoc/docs/getting-started/index.html

**Comment by slorber** [comment]
The Docusaurus team is actively working on Docusaurus v2.

After a very long alpha, Docusaurus v2 is [now in beta](https://docusaurus.io/blog/2021/05/12/announcing-docusaurus-two-beta).
We believe that the v2 beta is already better than v1, and v2 is ready for maintstream adoption.

Apart from critical issues and security fixes, we don't plan to invest much time on Docusaurus v1 anymore.

We are all closing v1 issues. 
Maybe the current issue is already fixed in Docusaurus v2.
Please try to upgrade, and if the issue is still there on Docusaurus v2, open a new issue.
