### ISSUE TITLE
Right TOC does not include headings generated outside of markdown

### ISSUE THREAD

**Issue by binarylogic** [facebook/docusaurus#1921]
## 🐛 Bug Report

This is for `v2`.  The right TOC for documentation pages does not include headings that were generated outside of the markdown syntax.

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## To Reproduce

1. Add a `<h2 id="my-anchor">Title</h2>` HTML tag anywhere in a documentation markdown file.
2. Notice it does not show up in the right TOC.

## Expected behavior

I expect for the title to show in in the right TOC just as it would if I provided a `## Title` line.

## Actual Behavior

The heading does not show up in the right TOC.

## Reproducible Demo

n/a

---

My primary issue with this is adding heading in custom components. Even when I import `Heading`:

```
import Heading from '@theme/Heading';

let Title = Heading('h2');

return (<Title>My title</Title>);
```

While this includes the appropriate anchor links, it still does not show up in the right TOC.

**Comment by endiliey** [comment]
This is intended. JSX and/or HTML tag is left as it is. If you try https://github.com/remarkjs/remark-toc, I believe it will produce the same behavior as well

You can check this behavior in v1 as well.
Changing this behavior will break everyone's URL.

![image](https://user-images.githubusercontent.com/17883920/67923882-b2f31800-fbe1-11e9-967c-a5cdd93d4947.png)

**Comment by binarylogic** [comment]
Hm, I disagree with this behavior, the purpose of the TOC is to summarize the content hierarchy which the `h*` tags represent. Is there no way to ensure a custom `h*` will be included there? This is particularly problematic for custom compnents that define their own headers.

Thanks for the help.

**Comment by binarylogic** [comment]
Cool! If I was to work on this would a PR be accepted?

> Changing this behavior will break everyone's URL.

Can you explain this? Why would someone be using `h*` tags if they were not headings?

**Comment by endiliey** [comment]
Well, if you can find a popular markdown parser that includes html `h*` tag as part of TOC, maybe we can talk further on a PR.

But as far as I know. All popular markdown TOC generator exclude JSX and/or HTML tag
- https://github.com/jonschlinkert/markdown-toc (Docusaurus v1 use Remarkable as markdown parser and this plugin)
- https://github.com/remarkjs/remark-toc (Docusaurus v2 use MDX as markdown parser which is powered by remark and this)

One example use case is this below. Using HTML `h*` tag intentionally means that it wont be included in the right sidebar. It seems more like a **feature** to me. Otherwise, how do we exclude certain `h*` tags ?
![image](https://user-images.githubusercontent.com/17883920/68318809-e8bb6380-00ef-11ea-84b8-639a24330f82.png)

**Comment by jacksongoode** [comment]
Hi.

I wanted to bring this topic back up since there doesn't currently appear to be a way to generate a TOC from an .mdx/.js - only through markdown. Is there a hacky way to achieve this through html alone?

I am rendering new pages with content in an mdx and it would be nice to have a TOC for them.

**Comment by jacksongoode** [comment]
> Hi @jacksongoode
> 
> I'd like to enable better MDX composition patterns (ie mdx partials/fragments) without loosing that TOC feature like we currently do.
> 
> Unfortunately have to finish i18n support in v2 first, but it's in my mind to work on this problem.

Great! In the mean time, is there any way to fake a markdown header (through js) for the TOC rules to interpret?

**Comment by slorber** [comment]
I don't know of a good way to do this unfortunately. 

This is not very convenient, but you can keep all the headings in original doc, and only put content in mdx fragments

**Comment by dustinkerstein** [comment]
I was just curious if anyone had come up with a good workaround for this. It would greatly simplify our content structure / reduce redundancy if this were possible. Thanks!
