### ISSUE TITLE
Javascript or Markdown?

### ISSUE THREAD

**Issue by zeineb** [facebook/docusaurus#1947]
Hello,

I have a question: when creating a new page, what makes us choose js over md?

Thanks.

**Comment by endiliey** [comment]
No really specific reasoning. It's by design ? 

It looks like you just deleted our lovely crafted [issue template](https://github.com/facebook/docusaurus/issues/new/choose). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue. 

Please note that this issue tracker is not a help form and this issue will be closed. 
If you have questions, please check [Stack Overflow](https://stackoverflow.com/questions/tagged/docusaurus) or [Discord](https://discord.gg/docusaurus) or [Twitter](https://twitter.com/docusaurus)
