### ISSUE TITLE
Docusaurus 1.* dependency highlightjs' version needs to be constrained

### ISSUE THREAD

**Issue by chenglou** [facebook/docusaurus#1954]
## 🐛 Bug Report

Docusaurus 1.* (tested on 1.9 til 1.14; might have missed a few in-between) has highlight.js as `^9.15.8`, which accepts `>9.16.1`. From my tests, docusaurus only works with highlight.js `<=9.15.10`

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## To Reproduce

(Write your steps here:)

1. clone https://github.com/BuckleScript/bucklescript.github.io.git
1. `cd website`
1. `yarn`

You'll see that the highlight on the front page works. However, remove this fix from me in package.json:

```
  "resolutions": {
    "highlight.js": "9.15.10"
  },
```
and remove `node_modules` and `yarn.lock`, then `yarn` again. It'll install a newer highlight.js, which gives plenty of CLI errors in docusaurus and the snippets fail to highlight.

**Comment by chenglou** [comment]
here's a stack trace:

```
TypeError: Cannot read property 'toString' of undefined
    at reCountMatchGroups (/Users/chenglou/Github/bucklescript.github.io/website/node_modules/highlight.js/lib/highlight.js:317:29)
    at addRule (/Users/chenglou/Github/bucklescript.github.io/website/node_modules/highlight.js/lib/highlight.js:378:20)
    at buildModeRegex (/Users/chenglou/Github/bucklescript.github.io/website/node_modules/highlight.js/lib/highlight.js:390:9)
    at compileMode (/Users/chenglou/Github/bucklescript.github.io/website/node_modules/highlight.js/lib/highlight.js:475:26)
    at compileLanguage (/Users/chenglou/Github/bucklescript.github.io/website/node_modules/highlight.js/lib/highlight.js:478:5)
    at Object.highlight (/Users/chenglou/Github/bucklescript.github.io/website/node_modules/highlight.js/lib/highlight.js:700:5)
    at Function.highlight (/Users/chenglou/Github/bucklescript.github.io/website/node_modules/docusaurus/lib/core/renderMarkdown.js:70:27)
    at Object.rules.fence (/Users/chenglou/Github/bucklescript.github.io/website/node_modules/remarkable/lib/rules.js:73:37)
    at Renderer.render (/Users/chenglou/Github/bucklescript.github.io/website/node_modules/remarkable/lib/renderer.js:71:39)
```

cc @yyyc514 who contributes to highlight.js. Sorry for the disturbance.

**Comment by endiliey** [comment]
I wonder if this should be considered as highlight.js bug too since `reason-highlight` is working fine in `<=9.15.10` but broke in `>9.16.x`. According to semver, by right nothing should break since it's only a minor bump. It's a regression, I do think this need to be reported to hljs.

For docusaurus side, its kinda a hard call to pin dependencies to specific version since that means we won't be able to receive patches update. But we don't really mind TBH

WDYT @JoelMarcey @yangshun 

Dear hljs maintainers (@yyyc514). Any thoughts ? Is this a regression

**Comment by yyyc514** [comment]
Would appear to be a regression at first glance.  A lot of internals have changed (despite the API and output remaining the same).  It appears `reason-highlightjs` is a grammar that has a self-referential ruleset at the top-level, which perhaps was supported previously, but the new processor doesn't like.

I will dig into more later and create and issue.

**Comment by yyyc514** [comment]
@chenglou Looks like it's your code?

https://www.npmjs.com/package/reason-highlightjs

I couldn't find a GitHub link though, so maybe you only packaged it?

```
  return {
    aliases: ['re'],
    keywords: KEYWORDS,
    illegal: '(:\\-|:=|\\${|\\+=)',
    // lol beautiful
    contains: MODULE_MODE.contains,
  };
```

You can't do that last line... because contains has a "self", but in this case it would refer to the top-level, which makes no sense since the top-level include no matchers...

You have to remember the ruleset is just static data that's compiled... so while you're MODULE_MODE rule looks ok on it's own the `self` is deceptive because it does NOT refer to  MODULE_MODE but instead refers to whichever parent the contains is inside of... which in this case you've switched.

I'm not sure what behavior this resulted in before, but I'd guess the child-rule was simply ignored... really this is an error with the grammar from where I stand though - one the new parser is just not swallowing silently like before.

**Comment by yyyc514** [comment]
See my additional thoughts on https://github.com/highlightjs/highlight.js/issues/2263.  Waiting to see if there is any additional information here before moving forward.

**Comment by endiliey** [comment]
Thanks a lot for the fast response @yyyc514 you are awesome 🙂.

I guess we’ll have to wait until @chenglou reply. I am not experienced with hljs language authoring so I cant comment much.

**Comment by yyyc514** [comment]
Thanks I try. Yes, seems now we wait.

**Comment by yyyc514** [comment]
@chenglou ping.

**Comment by chenglou** [comment]
Hello! Sorry for the delay. Yeah you're right; I've checked my grammar and the 'self' might not make sense. I intended it to be recursive (a Reason module can contain another module), but [this line](https://github.com/reasonml-editor/reason-highlightjs/blob/ba65f0409ec5c01479ca2e1560d8b2cbf7a59025/index.js#L321) already does it.

Sorry for the trouble! Closing this issue.
