### ISSUE TITLE
The same CSS files are injected several times when switching pages

### ISSUE THREAD

**Issue by lex111** [facebook/docusaurus#2006]
## 🐛 Bug Report

I noticed a strange bug when switching pages (Home -> Docs -> Blog) CSS styles are **duplicated** (re-injected as I understand it correctly).

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## To Reproduce

1. Open devtools and focus on styles (body eg)
1. Open Home page (https://v2.docusaurus.io/) and we can already see that the styles are duplicated!
![image](https://user-images.githubusercontent.com/4408379/69006156-50697e00-093c-11ea-9fb0-65b28d294c31.png)

1. Alright, go ahead, click on Docs (https://v2.docusaurus.io/docs/introduction) in navbar and check the styles in devtools again, now the styles are duplicated several times (**+3 new**)!
![image](https://user-images.githubusercontent.com/4408379/69006190-9d4d5480-093c-11ea-9c86-02b945a73aca.png)

## Expected behavior

Styles should not be duplicated (re-injected) when moving to other pages.

## Actual Behavior

For some reason, the same styles are injected, which overridden the earlier ones.

## Reproducible Demo

See To Reproduce section.

**Comment by endiliey** [comment]
Well, it's mostly because of https://github.com/facebook/docusaurus/blob/6204d9a9ec1a64cdbee53ca02c785da3380bf73e/packages/docusaurus-theme-classic/src/theme/Layout/styles.css#L8-L23

First of all, this requires a high level understanding of how webpack works.
The thing is, webpack mini-css-extract-plugin create one css file per js file and then the `splitChunk` try to cleverly take out a common one if possible but the algorithm is much more complicated than that because it tries to minimize number of request too https://webpack.js.org/plugins/split-chunks-plugin/#defaults

So https://v2.docusaurus.io/docs/introduction and https://v2.docusaurus.io/ actually both depends on Layout (which depends on that css) and both have their own extra css

This is just an illustration but i guess this can serve the purpose
Example `/docs/introduction` requires final css like this
```css
.body {
  margin: 0;
}
.content {
   flex: 1 0 auto;
}
```

And `/` final required css is like this
```css
.body {
  margin: 0;
}
.github {
   color: red
}
```

Here is the question. Do you think webpack will take out the common `body { margin: 0;}` ? 
Such that if i go to `/docs/introduction`, it will request `a.css` and this `common.css` ? and if i go to `/`, it will just request `b.css` since `common.css` has been loaded before 

Turns out that it doesn't, because the common.css is too small. and its just better to focus on one css request on first initial page load, thats why the reinjection happens.

Actually this is not happening to CSS only, there are lot of duplicated JS out there for all generated webpack projects.

**Comment by endiliey** [comment]
One solution is to move https://github.com/facebook/docusaurus/blob/6204d9a9ec1a64cdbee53ca02c785da3380bf73e/packages/docusaurus-theme-classic/src/theme/Layout/styles.css#L8-L23 to main bundle.

That's why people nowadays use css-in-js, it has better tree shaking ✌️

**Comment by yangshun** [comment]
It's what you said was true, it's weird behavior by webpack though. Reinjecting styles is a bad idea as precedence ordering matters. And I'd assume webpack wouldn't reinject the same style module again if the module has already been loaded before.

Regardless, this issue is probably something to do with webpack.

**Comment by endiliey** [comment]
Another solution is to extract all css into single file. But that is not a good idea as well since that means a lot of unused css in certain page. All has pros and cons.

I dont think this should be called as a bug, its not breaking any website. In fact, requesting one css file is better than requesting two files. Its also very small in size. It just happens to be the `body` selector so its noticeable.

Still better than going to https://docusaurus.io/docs/en/tutorial-setup and https://docusaurus.io/en/. Everytime new big css file is requested.

**Comment by endiliey** [comment]
> It's what you said was true, it's weird behavior by webpack though. Reinjecting styles is a bad idea as precedence ordering matters. And I'd assume webpack wouldn't reinject the same style module again if the module has already been loaded before.
Regardless, this issue is probably something to do with webpack.

But its actually two different files.

Page a need `a.css`
```css
.body {
  margin: 0;
}
.content {
   flex: 1 0 auto;
}
```
Page b need `b.css`
```css
.body {
  margin: 0;
}
.github {
   color: red
}
```

That's why going from pageA to pageB kinda override the same css.

**Comment by lex111** [comment]
In fact, I am observing such a issue in reusable components.

I have a [Showcase](https://github.com/CanopyTax/single-spa.js.org/blob/master/website/src/components/Showcase/index.js) component that is used on the [home page](https://single-spa.js.org/) and on the [Users page](https://single-spa.js.org/users/).

If I go to the first page first, and why go to the latter and look at devtools, I will see the following result:

![image](https://user-images.githubusercontent.com/4408379/69006803-85c69980-0945-11ea-8dda-895f9443dacf.png)

**Comment by endiliey** [comment]
Let me put more investigation sometimes next week

**Comment by endiliey** [comment]
I did an investigation. So the assumption was right, our best solution could possibly be grouping all the css file only into one file. Otherwise, code-splitting CSS will result all of above.

I just checked Gatsby https://github.com/gatsbyjs/gatsby/blob/67d8b6be93bb4971dadf6aa8e305af2b53560155/packages/gatsby/src/utils/webpack.config.js#L494-L506 and Vuepress https://github.com/vuejs/vuepress/blob/d2fef5d8f6f00aca13b5594c6084a54e1c8c3b18/packages/%40vuepress/core/lib/node/webpack/createBaseConfig.js#L275-L291

They all created one css file only 😢 

A very particular interesting stuff is that code-splitting css might cause issue on ordering
![image](https://user-images.githubusercontent.com/17883920/69007170-dc939980-096c-11ea-9448-ef4d7b1347fb.png)

If we don't want to do this, there's no good solution to fix this problem :)

**Comment by yangshun** [comment]
Yeah I agree. CSS is usually small in comparison to JS and it's ok to not split it.
