### ISSUE TITLE
[v2] Prefetching Invalid Script

### ISSUE THREAD

**Issue by arnohovhannisyan** [facebook/docusaurus#2164]
## 🐛 Bug Report

After loading the page on a production build, a `prefetch` link is made to an invalid script called `1be78505.undefined.js`, which causes an error since it doesn't exist.

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## To Reproduce

1. Navigate [here][prod] **or** build [this][repo] and start a web server

> Make sure the directory structure is correct. The `baseUrl` is `/vscode-syncify/`.

1. Open the console
1. Look for the 404 error
1. Check the `head` for the invalid prefetch link

## Expected behavior

There shouldn't be any invalid prefetch links.

## Actual Behavior

A prefetch link is added that points to an invalid script.

![image](https://user-images.githubusercontent.com/25834068/71569822-8f840680-2a86-11ea-892b-43f4fe60a570.png)

## Reproducible Demo

Hosted production build: [here][prod]

Repo: [here][repo]

[repo]: https://github.com/arnohovhannisyan/syncify-docs
[prod]: https://arnohovhannisyan.space/vscode-syncify

**Comment by endiliey** [comment]
fix will only come after new year. Most likely happening only in prod because of extra webpack optimization step that removes chunks that are too small, hence undefined contenthash. “webpackchunknames.contentHash.js”

Many options to fix this, with one of it just filtering out all those undefined prefetched links.
