### ISSUE TITLE
Add more social media integration

### ISSUE THREAD

**Issue by JoelMarcey** [facebook/Docusaurus#218]
... for things like the footer.

Twitter
Facebook (likes and shares)

**Comment by endiliey** [comment]
Hi, can I get more detail on this ?

Are we adding social media button so that:
1. User can follow the website twitter account (for twitter), like and share the facebook page (for facebook)
Example:
<img width="351" alt="socialmedia" src="https://user-images.githubusercontent.com/17883920/40069219-47869abc-589d-11e8-81b2-2d7b60a4e4d2.PNG">

2. or User can share the website link (e.g: docusaurus.io) on their twitter or facebook
Example:
<img width="952" alt="share" src="https://user-images.githubusercontent.com/17883920/40069314-7d478d6e-589d-11e8-9b01-a002798575e1.PNG">

**Comment by endiliey** [comment]
@yangshun 
I wanted to submit a PR, but the Facebook Like & Share button won't work because the Docusaurus app is not set to public mode

<img width="515" alt="app in dev" src="https://user-images.githubusercontent.com/17883920/40072868-d0f36faa-58a7-11e8-807f-c1153252a42f.PNG">


Actually this is related to https://github.com/facebook/Docusaurus/issues/625
The fix is to set the app to public, (but then again I don't have any permission to Docusaurus App)
<img width="941" alt="app ggg" src="https://user-images.githubusercontent.com/17883920/40073166-ad00cc2c-58a8-11e8-8515-22c7567227e0.PNG">

**Comment by yangshun** [comment]
Yep that is tracked at https://github.com/facebook/Docusaurus/issues/625

**Comment by endiliey** [comment]
@yangshun 
Thanks for the fast reply, I guess I had to wait for #625 to be resolved. Let me know if I can be of any help
