### ISSUE TITLE
MLH Fellowship 2020 Ideas List

### ISSUE THREAD

**Issue by yangshun** [facebook/docusaurus#2267]
*Note that all the projects listed here are targeting Docusaurus 2.*

### New Themes and Theme Gallery

**Difficulty**:  Medium

**Description**:  Docusaurus 2 introduces the concepts of themes and we have created an entirely new [CSS framework](https://facebookincubator.github.io/infima/) from scratch based on Docusaurus 1's theme. Some users will want to use their own CSS, for e.g. Bootstrap. Hence we want to add support for themes based on the popular CSS frameworks out there (e.g. Bootstrap, Bulma). It'd also be nice to have a gallery where we can showcase the themes.

**edit**: https://github.com/facebook/docusaurus/issues/3522

---

### Docusaurus Debug Dashboard

**Difficulty**:  Medium

**Description**:  A dashboard page that could be accessed during development to show the available routes for a Docusaurus site and also the list of swizzled components. This helps users to easily identify problems in a Docusaurus set up and enhances the user/developer experience. For example, a user can access http://localhost:3000/__docusaurus/debug to see helpful debug information.

This is similar to http://localhost:3000/rails/info/routes in Rails, [see the docs](https://guides.rubyonrails.org/routing.html#listing-existing-routes).

Bonus points if we can swizzle components from the UI!

**Edit**: done

---

### Docusaurus 1 to 2 Migration Command

Create a CLI command that can be run on Docusaurus 1 projects to easily move them to Docusaurus 2! There will still be some manual tweaking involved but at least it can help to get the trivial stuff out of the way.

This tool will essentially be a programmatic version of our [migration guide](https://v2.docusaurus.io/docs/migrating-from-v1-to-v2/).

**Edit**: done but can be improved here: https://github.com/facebook/docusaurus/issues/3520

---

### Docusaurus Doctor

**Difficulty**:  Hard

**Description**:  A command that can be used to check for common issues or recommend best practices within a Docusaurus website, for e.g. finding broken page paths, finding broken image paths, flagging unused assets, etc. Alternatively, these checks can be in the form of new ESLint rules/static analysis.

**edit**: not sure it's needed anymore?

---

### Offline Search

**Difficulty**:  Hard

**Description**:  Docusaurus uses Algolia as the default search service but internal docs cannot leverage on Algolia, which requires that a website be public. It could be possible to use lunr.js to build an index of the content and add search as a built-in feature to a Docusaurus website. This project is inspired by our [Canny Feedback board](https://v2.docusaurus.io/feedback/p/offline-search).

**edit**: pending PR: https://github.com/facebook/docusaurus/pull/3153

---

### Integrate Build Size Bot

**Difficulty**:  Easy

Integrate build size bot (or alternatives) to run on PRs to detect size regressions whenever changes are made to the repository. [Example of Next.js PR](https://github.com/vercel/next.js/pull/13799#issuecomment-639409718)

**edit**: https://github.com/facebook/docusaurus/issues/3521

---

### Keyboard Shortcuts

**Edit slorber** => https://github.com/facebook/docusaurus/issues/3020

**Comment by yangshun** [comment]
Docusaurus wasn't selected for Google Summer of Code 2020. I guess we can keep this open as the ideas are still useful

**Comment by yangshun** [comment]
Repurposing this list to be MLH Fellowship instead of GSoC.

**Comment by fanny** [comment]
# Summary

Hey, I would like to propose a new linter-plugin for Docusaurus, but I want to confirm it is out of the scope of those projects. I loved the idea of ​​the linter, but instead of look for URLs, and image paths or problems that happen when the user is moving from a different platform of ours, or v1, I would like to work more in semantic and structure.

# Basic example
The plugin linter could be work like the [eslint plugin](https://github.com/eslint/eslint), providing a series of default rules, initially, but also providing some customizations, for example using the eslint as the basis is possible `extend` some features. Here we can have the same approach, sometimes the site can have your own set of rules, like after each h1 has a paragraph, and the user could guarantee this, with your own rules.

# Motivation

Although we already have a good visual identity, some users can struggle difficulties in the website build, I mean in terms of content. How is the best way to structure the sites? After 3min of reading if we are presenting a concept, maybe it is good to include images or code to illustrate the concept. When including code, consider putting a playground or a more interactive thing?

# Detailed design

I know that sound a little bit abstract but would be like a style guide for sites, recommending that if you have so much text, it could be nice add images or try to put related links on the end of the page, with examples of the applications using the concept, etc.

I found a similar linter by [mozilla - doc linter](https://github.com/mdn/doc-linter-rules) that do a similar thing, they look for article-length or URLs in the title, our plugin can do the same to guarantee the consistency of the sites. To have a good foundation to build the rules, I thought in use guides like
[Google Technical Writing](https://developers.google.com/tech-writing/two), and also to do opinion research about which documentations are considered good and use their structure as a basis.


*I don't create a new issue, because I wanted to confirm if this idea is not to cover by the Docusaurus Doctor.*

**Comment by slorber** [comment]
# Docusaurus Social cards

You might have noticed that some people / companies have an automated way to generate social cards.

I think this would cool if by default, all Docusaurus docs/blogs would generate custom social cards, if the user did not define any custom social image.

This way, all Docusaurus links pasted to a social media would have a beautiful image. 

By default we could even include a discrete Docusaurus + Slash logo for growth hacking 🤪 

Vercel has a nice project to do this easily: https://github.com/vercel/og-image

We could fork this project, host our own variant (can be free on Vercel), and use it for D2 website, + allow other sites to use it as well.



Here's some examples of automated social cards:

![image](https://user-images.githubusercontent.com/749374/83897173-872aa880-a755-11ea-9cf5-dba1ecd7264a.png)

![image](https://user-images.githubusercontent.com/749374/83897249-a3c6e080-a755-11ea-875e-caec89b0c5ff.png)

![image](https://user-images.githubusercontent.com/749374/83897287-b214fc80-a755-11ea-8aa1-29eadf578d8f.png)

![image](https://user-images.githubusercontent.com/749374/83897394-d5d84280-a755-11ea-8f19-ff284d8ebc50.png)

**Comment by teikjun** [comment]
Hi @yangshun, @anshulrgoyal and I are thinking of working on _Docusaurus 1 to 2 Migration Command_. May I ask for a quick estimate for the difficulty level and priority level of this issue? Thanks!

**Comment by gedeagas** [comment]
> # Dynamic Social Cards
> 
> You might have noticed that some people / companies have an automated way to generate social cards that adapt to the underlying content (generating an image from query string params)
> 
> I think this would cool if by default, all Docusaurus docs/blogs would generate custom social cards, if the user did not define any custom social image.
> 
> This way, all Docusaurus links pasted to a social media would have a beautiful image.
> 
> By default we could even include a discrete Docusaurus + Slash logo for growth hacking zany_face
> 
> Vercel has a nice project to do this easily: https://github.com/vercel/og-image
> 
> We could fork this project, host our own variant (can be free on Vercel), and use it for D2 website, + allow other sites to use it as well.
> 
> Curretly, Docusaurus can have a default social card, but it's static and does not adapt to the content::
> 
> ![image](https://user-images.githubusercontent.com/749374/83898560-5fd4db00-a757-11ea-8021-7442ed6fa4c5.png)
> 
> Here's some examples of dynamic/automated social cards:
> 
> ![image](https://user-images.githubusercontent.com/749374/83897173-872aa880-a755-11ea-9cf5-dba1ecd7264a.png)
> 
> ![image](https://user-images.githubusercontent.com/749374/83897249-a3c6e080-a755-11ea-875e-caec89b0c5ff.png)
> 
> ![image](https://user-images.githubusercontent.com/749374/83897287-b214fc80-a755-11ea-8aa1-29eadf578d8f.png)
> 
> ![image](https://user-images.githubusercontent.com/749374/83897394-d5d84280-a755-11ea-8f19-ff284d8ebc50.png)

Interesting idea, i have somewhat simmilar project like this. 
https://og.agas.dev/**Contoh**%20Self%20Hosted%20Image%20Overlay%20Server.png?footer=Agastya%20Darma&md=1&imageUrl=https%3A%2F%2Fimages.unsplash.com%2Fphoto-1480796927426-f609979314bd%3Fixlib%3Drb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1950&q=80.png&fbclid=IwAR0Um7zFu-Q33nBhh2IeloEV4M-0ZLuL6bONoiQ4UL0ok3BnFQi9XQn7X-c. 

is anyone working on this?

**Comment by slorber** [comment]
Hi,

I've created a dedicated issue for dynamic social cards here: https://github.com/facebook/docusaurus/issues/2968

@Drewbi wants to work on this already

**Comment by anshulrgoyal** [comment]
Hi,
For the migration tool should we create a separate tool like `docusaurus-migrate` or we add it existing package?. I think new tool will be better.

**Comment by yangshun** [comment]
I'd say a new package within this repo. We don't want code to be all over the place otherwise it becomes hard to keep track. We'll also be the maintainers of it moving forward.

**Comment by slorber** [comment]
I think the question was more if we integrate the migration as part of the existing cli, or if we create a dedicated cli for migration. (in all case it stays on this repo).

I think it would be better to create a new package like "@docusaurus/migrate", because it's likely to be run one time with npx, and after the user don't need it anymore, so including this to core cli system is not very useful. It's a bit similar to "@docusaurus/init"

**Comment by yangshun** [comment]
Oh yes I fully agree. `@docusaurus/migrate` sounds good (hopefully we don't need it for a 2 to 3 migration hehe

**Comment by anshulrgoyal** [comment]
I want to work on the search feature.

**Comment by JoelMarcey** [comment]
@yangshun, @slorber -- which of these are actually completed? Thanks!

**Comment by slorber** [comment]
@JoelMarcey 

Docusaurus Debug Dashboard => done
Docusaurus 1 to 2 Migration Command => done (but could still be improved)

Offline Search => pending PR, will review it after i18n

Docusaurus Doctor => somehow related to the debug dashboard, and I'm not even sure this is needed anymore because we worked on making v2 much more failsafe and added broken links checking etc

Dynamic Social Cards => pending PR but need more work


Not started:
- New Themes and Theme Gallery (the bootstrap theme is quite basic, and could be enhanced)
- Build Size Bot
- Keyboard shortcuts

**Comment by slorber** [comment]
Meta issue for the MLH 2nd batch tasks: https://github.com/facebook/docusaurus/issues/3527

**Comment by sarthakkundra** [comment]
@yangshun Any plans of applying Docusaurus to GSoC 2021?

**Comment by yangshun** [comment]
We would try I guess.

**Comment by sarthakkundra** [comment]
D2 gas definitely matured a lot since the last application so I'm thinking it'll be worth a shot.

**Comment by sarthakkundra** [comment]
@yangshun if you're trying for GSoC 2021 I believe you will be brainstorming about possible projects. Contributing here for some time now and I think I might have some ideas. Should I create issues for them or mail someone?

**Comment by yangshun** [comment]
For maximum visibility sake, creating new issues would be good so that even if we don't apply for GSoC or don't get selected for it, others can still pick them up.
