### ISSUE TITLE
Pages with redirects instead of translations when docsUrl === '' and path to file includes 'en'

### ISSUE THREAD

**Issue by kav137** [facebook/docusaurus#2306]
## 🐛 Bug Report

When `docsUrl` is set to an empty string, localization enabled and path to the file contains "en" letters, then pages with redirects would be generated instead of pages with contents. So, it is impossible to reach the content 

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

yes

## To Reproduce

1. run `npm run examples translations` to make localization files available
1. enable any other language (let's say "ru") in `translations.js`
1. in docs folder create a folder named "components" (or any other name, containing "en" letters) and put .md file there
1. add a link to that file to `sidebars.js`, so that you can reach it
1. copy the content of docs folder to `website/translated_docs/ru` so that localized files are visible to the system
1. set `docsUrl: ''` in `siteConfig.js`
1. run `npm run build`

## Expected behavior
file `build/test-site/ru/components/myFile.html` contains data from the original file `website/translated_docs/ru/components/myFile.md`

## Actual Behavior
file `build/test-site/ru/components/myFile.html` contains redirection link to the file itself

Please, see the screenshot

![image](https://user-images.githubusercontent.com/10818831/74975466-22fb0780-5438-11ea-885a-3b0d9adf5e71.png)

## Reproducible Demo

https://github.com/kav137/docusaurusDocs/commit/5e54a032f6da40c821a0a0d1267d3da0d657c3d8

**Comment by slorber** [comment]
The Docusaurus team is actively working on Docusaurus v2.

After a very long alpha, Docusaurus v2 is [now in beta](https://docusaurus.io/blog/2021/05/12/announcing-docusaurus-two-beta).
We believe that the v2 beta is already better than v1, and v2 is ready for maintstream adoption.

Apart from critical issues and security fixes, we don't plan to invest much time on Docusaurus v1 anymore.

We are all closing v1 issues. 
Maybe the current issue is already fixed in Docusaurus v2.
Please try to upgrade, and if the issue is still there on Docusaurus v2, open a new issue.
