### ISSUE TITLE
[v2] Allow title and label for docs in sidebars.js

### ISSUE THREAD

**Issue by Soviut** [facebook/docusaurus#2337]
## 🚀 Feature

Currently, it only seems possible to specify `sidebar_label` in a page's frontmatter. It would be useful to be able to specify a `label` for `type: 'docs'` in `sidebars.js`.

```javascript
module.exports = {
  docs: [
    {
      type: "category",
      label: "Some Category",
      items: [
        {
          type: "doc",
          id: "doc1",
          label: "First document" // <--- like this
        }
      ]
    }
  ]
}
```

My assumption would be that anything specified in `sidebars.js` would override the frontmatter.

## Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## Motivation

I have a large set of markdown files that are imported on a regular basis from a separate code repo. It would be nice to avoid having to inject frontmatter into every one of those documents on import in order to get human readable labels on the sidebar.

## Pitch

Allow a `label` attribute on `type: 'doc'`, just like on `type: 'category'` and `type: 'link'`.

**Comment by yangshun** [comment]
@Soviut do you not need to specify the front matter at all for it to work? o.o

I feel this is duplicating features and just making the docs feature more complicated. Not in favor of adding this.

**Comment by Soviut** [comment]
It feels very inconsistent that I can specify a label for some sidebar items and not others.

The reason I proposed this is I have a lot of markdown fields being ingested from an external source into our Docusaurus project. None of which have frontmatter. It's far easier to write a bit of code in `sidebars.js` that walks the `/docs` directory and produces sidebar labels from the file names than it is to write another step into our ingestion process that adds frontmatter to all the files.

**Comment by LynxyssCZ** [comment]
Seconding this. We use Docusaurus for project documentation pages and having `README` and `CHANGELOG` in each repository is imo quite silly.

Adding the front matter is not really an acceptable solution, since it does not make sense when people are reading the actual `README.md` in the repo and we have formating validation on `CHANGELOG.md`

**Comment by amimas** [comment]
Just wanted to share my personal feedback. I am also using Docusaurus to build site where a considerable portion of the contents are coming from output of another repository (generated markdown files).

In my case, that repository has been updated so that generated the markdown files contain the necessary frontmatter. I think that's a reasonable ask because that's what those markdown files are for... to be used in docusaurus generated site. Why would anyone read/consume the contents using github's file viewer when a nice site is being created? Also, if the sidebar label is not set from the corresponding document itself, you don't really have a single source of truth for their changes.  With the current approach, it's easily traceable when the sidebar label of a given document changed and why, which is applicable to a document's title also. It shouldn't be controlled by an external configuration. Hope that makes sense.

I feel this feature will introduce unnecessary complications.

**Comment by Morriz** [comment]
Is it not possible to customize a sidebar title/label now without changing the page title?

**Comment by slorber** [comment]
@Morriz yes it is, using sidebar_label frontmatter.

**Comment by Morriz** [comment]
Is that documented? I could not find it

**Comment by Morriz** [comment]
Nevermind. Search worked. I expected it to be in one of the sidebar item types

**Comment by slorber** [comment]
This feature has been implemented in https://github.com/facebook/docusaurus/issues/4500 and you can pass doc.label in the sidebar file directly.

In general, we have made it easier for Docusaurus to work without any frontmatter, and in many cases you should be able to integrate better with external doc sets without having to inject frontmatter
