### ISSUE TITLE
table of content slugification differs from anchors slugification

### ISSUE THREAD

**Issue by chenglou** [facebook/docusaurus#2341]
## 🐛 Bug Report

If a header is called, for example, `Tips & Tricks`, the table of content section would slugify that as `Tips-amp-tricks` whereas the actual hash from the header is `tips-tricks`

**This is more problematic than a mismatching anchor**. Docusaurus uses scrollSpy, which fails to find the anchor like so:
<img width="521" alt="Screen Shot 2020-02-27 at 16 34 17" src="https://user-images.githubusercontent.com/1909539/75499506-00f50e00-597f-11ea-9ca1-efdc21309220.png">
This exception then blocks lots of other functionalities on the page (e.g. code tab switching)

### Have you read the [Contributing Guidelines on issues]

Yeah

## To Reproduce

(Write your steps here:)

1. Write any markdown doc, add a header `# Tips & Tricks`
1. Check console

The problem comes from these lines:
https://github.com/facebook/docusaurus/blob/6670c53d1838750de66ea2e6876da90d906428cb/packages/docusaurus-1.x/lib/core/toc.js#L40
https://github.com/facebook/docusaurus/blob/6670c53d1838750de66ea2e6876da90d906428cb/packages/docusaurus-1.x/lib/core/anchors.js#L25

If you `console.log(rendered)` in the first snippet, the **sanitization** turns `Tips & Tricks` into `Tips &amp; Tricks`. Whereas if you `console.log(textToken.content)` in the latter snippet, it's still `Tips & Tricks`.

cc @JoelMarcey

**Comment by JoelMarcey** [comment]
@chenglou Your website is still on v1 of Docusaurus, right?

cc @yangshun

**Comment by yangshun** [comment]
Yes this is v1.

**Comment by theosherry** [comment]
@chenglou @yangshun This issue was fixed with https://github.com/facebook/docusaurus/pull/2019

**Comment by yangshun** [comment]
Hmm @chenglou are you using the latest Docusaurus v1?

**Comment by slorber** [comment]
The Docusaurus team is actively working on Docusaurus v2.

After a very long alpha, Docusaurus v2 is [now in beta](https://docusaurus.io/blog/2021/05/12/announcing-docusaurus-two-beta).
We believe that the v2 beta is already better than v1, and v2 is ready for maintstream adoption.

Apart from critical issues and security fixes, we don't plan to invest much time on Docusaurus v1 anymore.

We are all closing v1 issues. 
Maybe the current issue is already fixed in Docusaurus v2.
Please try to upgrade, and if the issue is still there on Docusaurus v2, open a new issue.
