### ISSUE TITLE
Syntax highlight design was blocked due to MIME type

### ISSUE THREAD

**Issue by raisty** [facebook/docusaurus#2389]
## 🐛 Bug Report

If you define custom highlight design, you get the following error:
`The resource from “http://localhost:3000/docs/css/atom-one-dark.css” was blocked due to MIME type (“text/html”) mismatch (X-Content-Type-Options: nosniff).`

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

👍

## To Reproduce

(Write your steps here:)

1. Enable syntax highlighter in the config file.
2. Set up custom style and place it in the CSS folder
3. Link it in a config file.
4. Look into a console for errors.

## Expected behavior

There should be a correct MIME type.

(Write what you thought would happen.)

## Actual Behavior

Error: 
`The resource from “http://localhost:3000/docs/css/atom-one-dark.css” was blocked due to MIME type (“text/html”) mismatch (X-Content-Type-Options: nosniff).`

(Write what happened. Add screenshots, if applicable.)

## Your Environment

- Docusaurus version used: 1.14.4
- Environment name and version (e.g. Chrome 78.0.3904.108, Node.js 10.17.0): Node.js v10.15.3
- Operating system and version (desktop or mobile): MacOS Catalina

## Reproducible Demo

```js
  highlight: {
    // Highlight.js theme to use for syntax highlighting in code blocks.
    theme: 'atom-one-light',
    defaultLang: 'js',
    themeUrl: 'css/atom-one-dark.css',
  },
```

More info: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Content-Type-Options

(Paste the link to an example repo, including a `siteConfig.js`, and exact instructions to reproduce the issue.)

**Comment by slorber** [comment]
The Docusaurus team is actively working on Docusaurus v2.

After a very long alpha, Docusaurus v2 is [now in beta](https://docusaurus.io/blog/2021/05/12/announcing-docusaurus-two-beta).
We believe that the v2 beta is already better than v1, and v2 is ready for maintstream adoption.

Apart from critical issues and security fixes, we don't plan to invest much time on Docusaurus v1 anymore.

We are all closing v1 issues. 
Maybe the current issue is already fixed in Docusaurus v2.
Please try to upgrade, and if the issue is still there on Docusaurus v2, open a new issue.
