### ISSUE TITLE
Add feature image for social media for Docusaurus 1 blogs

### ISSUE THREAD

**Issue by vishwa306** [facebook/docusaurus#2425]
## 📚 Documentation

How do I set a "feature image" for my docusaurus blogs?

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)? Yes

Our docusaurus(v1) site contains several articles, each with its own set of images. How do I set one of those images as a featured image that would appear as a banner whenever we share the article link on social media like Facebook, Twitter or Linkedin? Currently, whenever we share any article from the blog, the same image is chosen as the feature image. Any help would be appreciated.

**Comment by vishwa306** [comment]
Is there any update on this?

**Comment by yangshun** [comment]
Closed by #2856 - https://v2.docusaurus.io/docs/next/blog#header-options

**Comment by yangshun** [comment]
We've added it in v2 - https://v2.docusaurus.io/docs/next/blog#header-options

It's unlikely we're going to add features to v1 now, but if someone wants to add support for it we're ok.

**Comment by slorber** [comment]
The Docusaurus team is actively working on Docusaurus v2.

After a very long alpha, Docusaurus v2 is [now in beta](https://docusaurus.io/blog/2021/05/12/announcing-docusaurus-two-beta).
We believe that the v2 beta is already better than v1, and v2 is ready for maintstream adoption.

Apart from critical issues and security fixes, we don't plan to invest much time on Docusaurus v1 anymore.

We are all closing v1 issues. 
Maybe the current issue is already fixed in Docusaurus v2.
Please try to upgrade, and if the issue is still there on Docusaurus v2, open a new issue.
