### ISSUE TITLE
Create default "Contributing to the docs" README from docusaurus-init

### ISSUE THREAD

**Issue by JoelMarcey** [facebook/Docusaurus#246]
`README` will have content such as:

- prereqs
- running locally
- directory structure
- configuration

Much of the README may be able to link to the docusaurus.io docs instead of repeating within the README itself. We can see.

**Comment by neilsutcliffe** [comment]
With regard to running locally, I found a few issues.

Cloning the repo directly, there will not be any translated files. Since the crowdin API key isn't included, then these files can't be downloaded either. I had to go ahead and delete the following line to get it to work temporarily

`{ doc: "installation", label: "Docs" },`

Also, the package.json has the following line

`"start": "../lib/start-server.js",`

which I had to change to the following

`"start": "node ../lib/start-server.js",`

[https://github.com/facebook/Docusaurus/pull/304](Relevant Pull Request)

**Comment by endiliey** [comment]
Duplicate #925
