### ISSUE TITLE
Support versioning of individual sections

### ISSUE THREAD

**Issue by aeneasr** [facebook/docusaurus#2528]
## 🚀 Feature

First of all, thank you for docusaurus - we use it exclusively in v1 for https://www.ory.sh/docs/ and it's been a treat!

Similar to Angular, React, and other ecosystems we have several projects (ORY Kratos, ORY Hydra, ...) that need documentation. Right now, we run one docusaurus installation for all these projects. This is very tricky from a versioning standpoint because it is not possible to select a specific version for one project.

For example, one project may be in v1.4.2 and another one may be in v0.3.2. It would be awesome if it was possible to version a section. I've created a small mock up using Docusaurus 1.0:

<img width="1108" alt="Bildschirmfoto 2020-04-04 um 10 52 59" src="https://user-images.githubusercontent.com/3372410/78422820-847eda80-7662-11ea-95d7-cb5c23a50786.png">

I'd be happy if there was some way to get this done with docusaurus. Maybe by using the new templating system (I haven't checked it out yet though!). If this is too much work / too breaking
I am also happy for pointers on how to achieve this using another way. Thank you!

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

yes

## Motivation & Motivation

I think this was covered in the first section, if not please let me know!

**Comment by fanny** [comment]
I think that would be a good addition, but I don't see many use cases for this feature, because if we have different projects why not create a specific documentation for each?

Right now, as far as I know, we can select an specific version for whole site and see a tag in each page like below: 

![F135E7CA-D285-412E-9041-104716717142_1_105_c](https://user-images.githubusercontent.com/14113480/78452487-cf4c2280-7661-11ea-839d-9b358e2c97c4.jpeg)

I think for implement this, we need to change our version system, current we have `/docs/versioned_docs` and the markdown files, probably we'll need to implement something like `versioned_docs/<project_name>/<version>/*.md` and in the docs common folder `docs/<project_name>`

**Comment by aeneasr** [comment]
> I think that would be a good addition, but I don't see many use cases for this feature, because if we have different projects why not create a specific documentation for each?

Yeah, I'm currently exploring to structure them individually (so one docusaurus "installation" per docs) and then just link between the projects. I also think that this would probably be a very edge case solution, especially - as I'm thinking about this - properly tagging / versioning each project will become kind of messy when automated.

Separating docs into different repos for each project probably makes more sense then trying to brute force this feature here.

**Comment by DaHolt** [comment]
I'd love it if this was possible. At the moment we're having to use four separate docs for each of our products due to each have different versions which is fine, but each one is a separate domain which isn't great. It would be really nice if we could do what we have the moment in one doc and therefore, all docs under one domain.

**Comment by yangshun** [comment]
Ideally want to have versioning on a sidebar-level, and not on a site-level. That was our oversight when we implemented versioning in v2.

**Comment by slorber** [comment]
Hey,

This is not properly documented (as there might be upcoming breaking changes in the config) but we can now have multiple instances of the doc plugin running on the same site.

We dogfood this feature on Docusaurus website itself:
- Docs (versioned doc instance): https://v2.docusaurus.io/docs
- Community (unversioned doc instance): https://v2.docusaurus.io/community

We don't need to version community, but this multi-docs-instance would permit to manage for example different versions for iOS/Android SDKs etc...

Also worth mentioning the new navbar item types like versionDropdown etc that you can use so that it's not needed anymore to hardcode all the dropdown values in your config (dropdown is generated automatically)

I'm closing this, because I think we addressed the problem (maybe not the exact way you have in mind though).

As this is a bit new, please talk to me on Discord if you need help to set this up, as you would be an early adopter.

**Comment by vjpr** [comment]
@slorber I just tried multiple instances with a setup similar to https://github.com/facebook/docusaurus/blob/master/website/docusaurus.config.js#L61

But it errors while looking for:
`docs/.docusaurus/docusaurus-plugin-content-docs/default/site-community-doc-1-md-87a.json'`

but the file is here instead:

`docs/.docusaurus/docusaurus-plugin-content-docs/community/site-community-doc-1-md-87a.json'`

The plugin seems to not be working with multiple instances...

**Comment by slorber** [comment]
Thanks @vjpr , noted to take a look at this soon. 
Do you mind opening a new issue for this?
