### ISSUE TITLE
ERRNAMETOOLONG - Long file names cause issues

### ISSUE THREAD

**Issue by dylandamsma** [facebook/docusaurus#2628]
## 🐛 Bug Report

When having long file names in large sub-directories, the build fails causing an error "ERRNAMETOOLONG" as shown in the picture below:

![image](https://user-images.githubusercontent.com/5804574/79693450-42c67480-829d-11ea-82e4-372010cdd642.png)

We're trying to make a good searchable website for the companies law in Malaysia. Steps to reproduce below.

## To Reproduce

(Write your steps here:)

1. Put the .md files of the law into your docusaurus project: https://github.com/kaunto/companies-act-2016
2. Try to start the dev environment using yarn start
3. Get error.

## Expected behavior

... Build as normal? :)

**Comment by yangshun** [comment]
Possible fix can be to learn from https://github.com/gatsbyjs/gatsby/pull/21518

**Comment by yangshun** [comment]
Can you rename the file to make it shorter for the time being?

**Comment by dylandamsma** [comment]
Would that change the url Path as well?

**Comment by dylandamsma** [comment]
It'd be a bit tricky though, there's 633 files like this, where this issue
probably would pop-up more than once. So I would have to either rename all
with some script which admittedly I can't do myself or fix the issue.

**Comment by AbhinavShah421** [comment]
Hey,
I am also facing this issue please let me know that what is the proper solution for this.

Error: ENAMETOOLONG: name too long, open '/home/kyle/Development/Forks/xr3ngine/packages/docs/.docusaurus/docusaurus-plugin-content-docs/default/site-docs-docs-server-classes-src-services-gameserver-subdomain-provision-gameserver-subdomain-provision-class-gameserversubdomainprovision-md-6cd.json'

**Comment by tsirlucas** [comment]
So, had the same problem and noticed that all the cases are related to this: `docusaurus-plugin-content-docs` its generating file names based in file paths [here](https://github.com/facebook/docusaurus/blob/0587d6d6e7520123cbf595f28e381636c7d5c416/packages/docusaurus-plugin-content-docs/src/index.ts#L287) which calls [this](https://github.com/facebook/docusaurus/blob/0587d6d6e7520123cbf595f28e381636c7d5c416/packages/docusaurus-utils/src/index.ts#L109)

So if you a deep tree of files in your docs, this will probably happen because `@site/path/to/file.md` becomes `site-path-to-file-md-{HASH_NUMBER_HERE}.json` and at some point this will become larger than 255 characters which is the file name limit for most UNIX file systems.

**Comment by tsirlucas** [comment]
@slorber Im working on a local fix for that and I can add a PR if you guys want. Only have one question: Would you rather have bigger file names hashed into something like `4d82ce9fc232c837c9ae53e33ab06f1c-a33.json` or just having part of the string removed (left|right) once we already have a small hash generated at the end of it? Or maybe just `4d82ce9fc232c837c9ae53e33ab06f1c.json`.

**Comment by slorber** [comment]
Thanks @tsirlucas 

I think if the hash is like 20 chars, you could truncate the filename at 235 chars? this way we'll stay under 255 chars and keep names readable?
