### ISSUE TITLE
A header tag (h1) with the name of `exports` causes algolia search to stop working

### ISSUE THREAD

**Issue by ranyitz** [facebook/docusaurus#2629]
## 🐛 Bug Report

A header tag (h1) with the name of `exports` causes algolia search to stop working. This may be an algolia bug, but I encountered it in the context of using docusaurus and i'm not able to tell whether it's an algolia or docusaurus bug.

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## To Reproduce

I created a repository which has the reproduction steps in the readme

https://github.com/ranyitz/docusaurus-algolia-exports-bug/blob/master/README.md

## Expected behavior

Search should work even if there is a h2 tag with the word exports in one of the documents.

## Actual Behavior

When there is a header tag with the word "exports" the search doesn't work.

## Your Environment

- Docusaurus version used: 1.14.4
- Environment name and version (e.g. Chrome Version 80.0.3987.163, Node.js v12.13.1):
- Operating system and version (macOS desktop):

## Reproducible Demo

https://github.com/ranyitz/docusaurus-algolia-exports-bug/blob/master/README.md

The instruction for a repro are inside. It's a newly generated project with algolia search enabled and the word `exports` as a `h1` tag in one of the example docs.

(The algolia configuration doesn't connected to anything, but you can see the bug without connecting it as well)

**Comment by s-pace** [comment]
👋 @ranyitz 

Thank you for rising this issue.

I am part of the DocSearch team.

It seems that the reproducible environment you are referring to does not have DocSearch enabled. [The algolia setting is not configured from the siteConfig.js](https://github.com/ranyitz/docusaurus-algolia-exports-bug/blob/master/website/siteConfig.js#L48).

[As you can see on the jest website](https://jestjs.io/docs/en/es6-class-mocks#mocking-non-default-class-exports) using docusaurus 1, you can still search for `exports` while `exports` being wrapped into a `<h3/>` header element:
![image](https://user-images.githubusercontent.com/32097720/91321210-acf8a400-e7be-11ea-8fdf-f3f6a2116cb9.png)

The issue you were struggling with might be due to another issue. There is currently an issue with [docusaurus v1 which does not display the "no result" dropdown](https://github.com/facebook/docusaurus/issues/3293#issuecomment-674964180). Another explanation might be that you were searching for a content that was not indexed[ by the DocSearch crawler](https://docsearch.algolia.com/docs/how-does-it-work/). The crawl happens every 24h and is only indexing the live version of the documentation.

**Comment by ranyitz** [comment]
Thanks @s-pace! It's important to note the docusaurus 2 doesn't have this bug, and I believe most of the community will move to use it sooner or later. Closing
