### ISSUE TITLE
[v2] The blog posts order is wrong

### ISSUE THREAD

**Issue by jk-gan** [facebook/docusaurus#2698]
## 🐛 Bug Report

In blog, there is a suggestion button for previous post and next post. However, the order is wrong. It will suggest the previous blog post in the "Next Post" button and vice versa.

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

yes.

## To Reproduce

1. create a new docusaurus v2 project
2. create few blog posts

**or**
1. go to docusaurus v2 blog page. For example, [this](https://v2.docusaurus.io/blog/2019/12/30/docusaurus-2019-recap)

## Expected behavior

The newer post should be showed on the "Next post" button and vice versa.

## Actual Behavior

The older post is showed on the "Next post" button and vice versa.

## Your Environment

- Docusaurus version used: v2.0.0-alpha.54
- Environment name and version (e.g. Chrome 78.0.3904.108, Node.js 10.17.0): Firefox developer edition 76.0b7, Node v13.5.0
- Operating system and version (desktop or mobile): macOS 10.15.4

## Reproducible Demo

go to docusaurus v2 blog page. For example, [this](https://v2.docusaurus.io/blog/2019/12/30/docusaurus-2019-recap)

**Comment by lex111** [comment]
I think it was done on purpose. @yangshun  isn't that right?

**Comment by yangshun** [comment]
Yes it's on purpose. It depends on perspective. If you view the posts as a list of entries in reverse chronological order (newest first, on the left), then the next post is an older post. Seems like Gatsby does the reverse of us. IMO we should just do what makes the most sense and what most blogs do. If someone is interested in researching and coming up with a conclusion, we could change it.

**Comment by lex111** [comment]
I think we can close this issue due to a long lack of response from the author.

**Comment by yangshun** [comment]
We can leave it open in case someone else wants to research and recommend something.

**Comment by teikjun** [comment]
Issue: Should the next button lead to **(A)** an older post or **(B)** a newer post?

## Which behavior makes more sense?
#### Scenario 1: User finishes reading the newest blog post and looks for another blog post
Let's try visiting the newest post in [Docusaurus](https://v2.docusaurus.io/blog/2020/01/07/tribute-to-endi) and [Gatsby](https://www.gatsbyjs.org/blog/2020-07-02-Gatsby-Days-Reconfigured-Sam-Julien/) as an example. 

Having the right button lead to the next oldest post seems more intuitive. This is probably because we associate the right button with proceeding forward, and left button with proceeding backwards (like the front and back buttons in your browser). In this scenario, option A seems more sensible.

#### Scenario 2: User finishes a random blog post and looks for an older blog post
Again, we can visit a random post in [Docusaurus](https://v2.docusaurus.io/blog/2018/12/14/Happy-First-Birthday-Slash) and [Gatsby](https://www.gatsbyjs.org/blog/2020-06-30-Gatsby-Days-Reconfigured-Colby-Fayock/) as example. 

When the user tries to look for an older post, it is likely that the user will think that the "previous" button will lead to an older post. After all, "previous" implies that something is older. In this scenario, I think that option B is more sensible to avoid confusion.

## Which behavior is more common?
I couldn't find any statistics on this, so I looked through blog sites at random. Here are some examples:

**Option A**
[Gitbook](https://blog.gitbook.com/product/boost-your-docs-with-advanced-branding) 

**Option B** 
[Rails](https://weblog.rubyonrails.org/page4/)
[Mozilla](https://blog.mozilla.org/blog/2020/04/08/our-journey-to-a-better-internet/)
[Instagram](https://business.instagram.com/blog/expanding-stories-ads-for-brands-to-facebook/)
[Uber](https://eng.uber.com/uber-data-platform-2019/)
[MaterialDesignBlog](http://materialdesignblog.com/creating-a-simple-material-design-action-button-with-css/)
[Gatsby](https://www.gatsbyjs.org/blog/2020-06-30-Gatsby-Days-Reconfigured-Colby-Fayock/)

Option B seems to be more common than Option A.

**Other options**
Some blog sites preferred to use "Older"/"Newer" instead, e.g. [Stripe](https://stripe.com/blog/page/2).
Many blog sites recommend blog articles without bothering about the chronological ordering, e.g. [Medium](https://medium.com/dailyjs/testing-react-an-overview-56204839cbad)

## Recommendation
Both options seem to be equally sensible, but Option B is more common compared to Option A.
So, I would recommend Option B: having the next button lead to a newer post instead of an older one.

Please let me know what you think! I'll make the changes to the blog (if needed).

**Comment by yangshun** [comment]
Thanks for doing the research! Let's go with the more popular option together with the naming change :)

**Comment by teikjun** [comment]
Roger that, I'll make a PR soon! :D
