### ISSUE TITLE
Sidebar doesn't generate if markdown files are not in root of docs folder.

### ISSUE THREAD

**Issue by Ultra-Instinct-05** [facebook/docusaurus#2727]
## 🐛 Bug Report
Not sure if this is a bug, but it seems the sidebar doesn't get rendered if the markdown files are present within sub directories of `docs`. Does that mean we are limited to having all markdown files within a single directory and can't organize it within  the `docs` folder ?

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?
Yes

## To Reproduce
1. Start a new project
2. In the `docs`, section have a structure similar as follows:
`folder_1 -> introduction.md`
`one.md`
`two.md`
3. In the `sidebars.json`, have the following :-
```json
{
  "docs": {
    "This is the introduction": ["folder_1/introduction"],
    "Numbers": ["one", "two"],
  }
}
```

## Expected behavior
The sidebar should be generated as :-
```
This is the introduction
    introduction
Numbers
    one
    two
```

## Actual behavior

Sidebar doesn't get rendered.

## Your Environment

- Docusaurus version used: ^1.14.4
- Environment name and version (e.g. Chrome 81.0.4044.129, Node.js 12.13.0):
- Windows 7 x64 OS.

**Comment by danyalasif** [comment]
Currently dealing with the same thing. I was looking into dynamically generating all the filenames and directories, but seems like it does not support having files in subdirectories inside docs folder. All the examples I'm seeing don't have any nested directories either

**Comment by amimas** [comment]
I'm using V1.14.4 with subfolder structure for organizing docs. It's been working fine for me.

It's hard to tell what's wrong from the above description. I'd suggest checking that the docs have `id` in the frontmatter and the same is being referred to from sidebars. It's most likely a misconfiguaration.

**Comment by slorber** [comment]
The Docusaurus team is actively working on Docusaurus v2.

After a very long alpha, Docusaurus v2 is [now in beta](https://docusaurus.io/blog/2021/05/12/announcing-docusaurus-two-beta).
We believe that the v2 beta is already better than v1, and v2 is ready for maintstream adoption.

Apart from critical issues and security fixes, we don't plan to invest much time on Docusaurus v1 anymore.

We are all closing v1 issues. 
Maybe the current issue is already fixed in Docusaurus v2.
Please try to upgrade, and if the issue is still there on Docusaurus v2, open a new issue.
