### ISSUE TITLE
Add ability to autogenerate docs md files from sidebar definition

### ISSUE THREAD

**Issue by wtrocki** [facebook/docusaurus#2787]
## 🚀 Feature

I have been using Docusaurus a lot recently writing pretty complex docs with more than 50 chapters. When building docs developers usually focus on the chapters first. 

I always need to manually create multiple files for docusaurus and put there headers. This takes a lot of time and it is error-prone. Instead of that we can automatically generate files using some script

## Implementation

Some simple script like this can be used to generate files automatically. 
Idea is to generate me files if they do not exist. 
 
```javascript
const sideBars = require("./sidebars.json");
const fs = require("fs");
const path = require("path");

if (sideBars && sideBars.docs) {
  for (const chapter of Object.keys(sideBars.docs)) {
    for (const element of sideBars.docs[chapter]) {
      const text = `
---
id: ${element}
title: ${element}
sidebar_label: ${element}
---

${element} TODO
`;
      const pathToFile = path.resolve("../docs/", element + ".md");
      if (!fs.existsSync(pathToFile)) {
        fs.writeFileSync(pathToFile, text);
      }
    }
  }
}
```

Then we can use it in website folder like this

> node generateDocsFiles.js

I know that it will be strange to request this to be in docusaurus, but decided to share this in case someone will look for something like that. 
Feel free to close

**Comment by amimas** [comment]
This does feel like a strange feature :smiley: 

The sidebar will have additional responsibility. Plus, once the files are generated, what happens with those entries in the sidebar config?

I think you can still script it the generation of those files but it doesn't need to be part of Docusaurus. For example, you have your own config file with necessary options and then add it to your npm script section for people to execute (i.e. npm run generateDocs).

Also, if you're using V2, I believe you don't have to set the id metadata anymore because that will be generated by docusaurus based on filename.

**Comment by wtrocki** [comment]
Great idea! Would team be ok to release simple package like `docusaurus-generator`

I have couple ideas like:

- generating docs files from sidebar.json. I
- generating react components for docusaurus like YouTube videos etc.

**Comment by amimas** [comment]
I suggest using your own script for generating markdown files. Might even extend it a step further so that the generated markdown files has skeleton/structure of the content. And your script doesn't need to take it's input from the sidebar. But you can make it's output to update the sidebar if you know the appropriate location of the new files in the sidebar.

There's no need for this script to be provided by docusaurus. Everyone will likely have their own requirements, if they need auto generated files.
