### ISSUE TITLE
Interactive / Life TypeScript code samples for 2.0

### ISSUE THREAD

**Issue by avkonst** [facebook/docusaurus#2824]
## 🚀 Feature

I have used Docusaurus 2.0 for documenting [Hookstate](http://hookstate.js.org/) - supercharged useState hook library for all possible state management needs. Docusaurus 2.0 was all very nice and working smoothly, although it was only alpha version. Thanks for this great quality!

One feature I would like to have built-in into Docusaurus is interactive / life Typescript code samples. You can see what I mean in [this page](https://hookstate.js.org/docs/nested-state): there is a code snippet and after this is life interactive example running.

Because this feature was not available in the Docusaurus, I have implemented [PreviewSample component](https://github.com/avkonst/hookstate/blob/master/docs/index/src/PreviewSample.tsx) to do it for me. The limitation of this custom solution is that source code for samples is effectively in separate files, which I need to load asynchronously from github when in runtime.

If it was available in Docusaurus, I would be able to achieve the same result by posting source code within the content of markdown files and annotating, which code samples should be turned into life. Not sure about the syntax, but maybe the following would work (notice `-life` suffix):

```tsx-life
// my code sample here
```

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

yes

## Motivation

I would like to retire my custom Typescript source code preview sample component and use more of the standard Docusaurus, which will likely be better styled, built, etc. I hope it will allow me to return code samples back to MD files.

## Pitch

(Please explain why this feature should be implemented and how it would be used.)

As you can see this feature is used almost on every page of the documentation for Hookstate. And I feel (and others confirmed) it makes the docs a magnitude better: clearer, easier, more concise. - It is what Typescript lib developers need for sure.

**Comment by yangshun** [comment]
We do have some support for live editing - Have you seen this - https://v2.docusaurus.io/docs/markdown-features#interactive-code-editor

**Comment by avkonst** [comment]
Yeh, I have forgotten that I have tried it some time ago. I abandoned to use after I could not make it working for me. The main problems were:

1. it did not work with external libraries (like `import`)
2. I could not use it with typescript
3. I could not disable editor mode (wanted view only, no edit), but it was minor
4. Also I needed to fold down source code or life view (because some of the samples are rendering large page, so I though 'hide sample' was important, but can live without it)

If 1 and 2 has changed recently, I would try it again.

**Comment by avkonst** [comment]
I have changed the title and the description of the ticket to target Typescript specifically.

**Comment by 9oelM** [comment]
Alright so I was writing a new issue for this because I NEED Typescript on Docusaurus, but since there's already an issue here, I will write it as a comment here.

![image](https://user-images.githubusercontent.com/22465806/103146174-f4049f00-4788-11eb-9cd5-89a1ced60eb3.png)
Right now we are using react-live to render React components live (at least in v2, I'm not sure about v1), and react-live does not support components in written in Typescript by default, as @avkonst has put it very clearly.

As mentioned by https://github.com/FormidableLabs/react-live/issues/8#issuecomment-613444102, it is easily possible to integrate Typescript. However I know that we very much care about bundle sizes.

So I guess we could add one boolean prop to know if the live code is using Typescript or something like that to either:
 1. conditionally import Typescript compiler, or
 2. dynamically attach `<script src="https://klesun-misc.github.io/TypeScript/lib/typescriptServices.js"></script>` inside `<head>`.

Please let me your thoughts 🙏🏼  @yangshun @slorber @lex111

**Comment by 9oelM** [comment]
If there is no quick progress on discussion for now.. I will write a simple plugin for this because i really need it.

**Comment by slorber** [comment]
@9oelM thanks for your suggestion. I won't be able to work on this soon so you'd rather try to make a plugin or submit a PR

**Comment by 9oelM** [comment]
@slorber thanks for the reply :) I will submit a PR soon.

**Comment by Josh-Cena** [comment]
Live editing + TypeScript are almost never going to work together, because this inevitably means porting the entire Babel runtime into the bundle, which isn't affordable for the Docusaurus core. There are TypeScript-optimized code blocks like [shiki-twoslash](https://www.npmjs.com/package/docusaurus-preset-shiki-twoslash), and if anyone really wants a live one, it would be doable in userland in a similar way we implemented the live codeblock, but I don't think it's worth adding in the core considering the inevitable overhead.
