### ISSUE TITLE
Double script injected by gtag plugin

### ISSUE THREAD

**Issue by irfan-maulana-tkp** [facebook/docusaurus#2876]
## 🐛 Bug Report

I am using plugin `@docusaurus/plugin-google-gtag` for adding analytics into my docosaurus project. But after looking into `build` directory I see this very same script is printed twice. I think it's not supposed to be duplicate.

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## To Reproduce

- Adding plugin via Yarn `yarn add @docusaurus/plugin-google-gtag`
- Add in config

```
plugins: [
    require.resolve('@docusaurus/plugin-google-gtag')
],
```
- Add in themeConfig

```
gtag: {
      trackingID: 'UA-25065548-2',
      anonymizeIP: true,
},
```

- Run build `yarn build`
- See the `build` directory, and open `index.html`

## Expected behavior

index.html only contains one script to initalize gtag

## Actual Behavior

index.html contains two script to initalize gtag

Screenshoot:
![Screen Shot 2020-06-04 at 11 30 43](https://user-images.githubusercontent.com/51905113/83715418-7a278f80-a657-11ea-8b4a-d80d46b29cca.png)

## Your Environment

- Docusaurus version used: `2.0.0-alpha.56`
- Environment name and version (e.g. Chrome 78.0.3904.108, Node.js 10.17.0): Node.js 10.16.3
- Operating system and version (desktop or mobile): MacOS Mojave 10.14.3 

## Reproducible Demo

https://github.com/mazipan/ebook-belajar-frontend

**Comment by lex111** [comment]
Remove the extra (unnecessary) plugin in the [`plugins` array](https://github.com/mazipan/ebook-belajar-frontend/blob/master/docusaurus.config.js#L112):

```
require.resolve('@docusaurus/plugin-google-gtag'),
````

You are using the `preset-classic` preset, which **[already](https://v2.docusaurus.io/docs/using-plugins/#docusaurusplugin-google-gtag)** includes the `plugin-google-gtag` plugin, so now in fact you call this plugin twice, which is why the result of its work is duplicated. The same goes for sitemap plugin.
