### ISSUE TITLE
Using _index id in sidebar.js

### ISSUE THREAD

**Issue by maximousblk** [facebook/docusaurus#2920]
## 🚀 Feature

Using `_index` in `sidebar.js` should link to the home page instead of `/_index`

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

yes

## Motivation

Currently I have a site where I have removed `index.js` and have `routeBasePath: '/'` so the docs page is the home page. Then I have a page with `id: home` and have `homePageId: 'home'` and `Home: ['home']` in sidebar.

So when I visit `localhost:3000/` I see the contents of `home` with the sidebar. but when I click on the link to the home page from the sidebar, I am redirected to `localhost:3000/home` which I do not want. And on top of that, the canonical URL of `localhost:3000/` is `localhost:3000/home` which is also reported in #2879

I also tried to set `id: _index` in markdown and `Home: ['_index']` in sidebar but that breaks it even further.

Now when I visit `localhost:3000/` I see the contents of `_index` with the sidebar. but when I click on the link to the home page from the sidebar, I am redirected to `localhost:3000/_index` which results in `404` error because the contents of the page are located in `localhost:3000/`.

## Pitch

My solution to this would be:

when I use `_index` in the `sidebar.js` then point it to the URL of the page with `id: _index` instead of `/_index`

**Comment by slorber** [comment]
Hi,

There are several fixes I've made to the way the `homePageId` is handled.

This should be fixed in https://github.com/facebook/docusaurus/pull/2905 and released soon, fixing the canonical url, and the sidebar link to the homepage which did not work properly in current version.

About the `_index` thing, I think the current doc is a bit misleading.

As far as I understand, it's just a "default value" for `homePageId`, so that if you have a `/docs/_index.md` or a document with `id: _index`, it gets automatically picked as the index of your site. 

If your document has `id: home`, then adding `Home: ['home']` to the sidebar should work.

Here are tests I've done on the upcoming version, tell me if you see a problem (the version dropdown links have not been updated for the test):

https://focused-hoover-167617.netlify.app/
https://focused-hoover-167617.netlify.app/next
https://focused-hoover-167617.netlify.app/2.0.0-alpha.50/

---

@lex111 what about having no default value for `homePageId`? Maybe this is confusing for the user? Without default value, we could even try to check if the user-provided id actually match a doc from the current version, and fail fast otherwise.

**Comment by maximousblk** [comment]
@slorber The test deployments you provided are the exact behaviour I am looking for.

Having no default value for `homePageId` should be better. otherwise you would have to add a step to make it work with the sidebar.

And If you want to have a Default value for the `homePageId`, it should be `README` as it would also be compatible with GitHub.

Looking forward to next release.

**Comment by slorber** [comment]
> @slorber The test deployments you provided are the exact behaviour I am looking for.

Great to know :)


> otherwise you would have to add a step to make it work with the sidebar.

In any case, you'd rather add the home doc to the sidebar, otherwise no sidebar would appear on it.

> And If you want to have a Default value for the homePageId, it should be README as it would also be compatible with GitHub.

README is not a Docusaurus document. Only docs under the /docs folder (configurable) are site documents (and I don't think setting docs folder to repo root would be a good idea). 

We don't have first class support for adding README to a Docusaurus 2 website, but you could simply copy the README to the docs folder at build time (it might be needed to "rewrite" the relative links of your README).

Someone seems to do this here: https://github.com/facebook/docusaurus/issues/2851#issuecomment-642694324

**Comment by maximousblk** [comment]
> README is not a Docusaurus document... and I don't think setting docs folder to repo root would be a good idea...

I was trying to say that if you visit the `/docs` folder on github, It would be convenient for it to work as expected. And this would help if you have more folders inside the `/docs` folder. So the documentation would work on github as well as on the production site as well.

In any case, README support is not the main concern of this issue and serves the same purpose as `_index` so as stated earlier, It would be better to just drop the idea of a default value for `homePageId`.

**Comment by tuler** [comment]
I'm confused. I'm trying to enable the docs-only mode. The sidebar is not being displayed for the home page I set as `homePageId` at `docusaurus.config.js`. I'm running 2.0.0-alpha.58.

**Comment by maximousblk** [comment]
@tuler you have to include the id of the home in the `sidebar.js`.

example:

```jsonc
// docusaurus.config.js

docs: {
  homePageId: 'home-page',
  // ...
},
```

```jsonc
// sidebars.js

module.exports = {
  docs: {
    'Getting started': ['home-page'],
    Docusaurus: ['doc1'],
  },
};
```

**Comment by tuler** [comment]
Does not work for me.

**Comment by slorber** [comment]
@tuler if you don't share any config of your setup, or github repro repository, it's really hard to help.

**Comment by tuler** [comment]
Sorry, just pushed an example
https://github.com/tuler/docusaurus-docs-only/commit/479ce5479d1f651a205f17e5d8ab9167b22801aa

The sidebar doesn't show up in the home page.

**Comment by slorber** [comment]
@tuler can you open another issue please?

I think you are right and there's something not working properly. This is weird because I got it working in this PR: https://github.com/facebook/docusaurus/pull/2905#issuecomment-642041503

**Comment by tuler** [comment]
https://github.com/facebook/docusaurus/issues/2985

Thanks
