### ISSUE TITLE
Documentation for docs-only mode leads to missing sidebar and navbar

### ISSUE THREAD

**Issue by teikjun** [facebook/docusaurus#3039]
## 📚 Documentation

After following the instructions to enable docs-only mode (https://v2.docusaurus.io/docs/docs-introduction/#docs-only-mode), the sidebar and navbar is missing from the page.

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?
Yes

### To Reproduce
1. Init a new docusaurus site
2. Follow the instructions found here: https://v2.docusaurus.io/docs/docs-introduction/#docs-only-mode

Your website should now look like this:
Website: https://docs-only-repro.vercel.app/
Repository: https://github.com/teikjun/docs-only-repro

### Proposed Solution
I believe the issue is caused by `/src/pages/index.js` mapping to the same route.
The docs page displays correctly after `/src/pages/index.js` is removed. 

<img src="https://user-images.githubusercontent.com/46853051/87046404-be481a00-c22b-11ea-8ceb-66f374ae4f39.png" width="600">

Currently, the documentation says that `/src/pages/index.js` does not need to be removed (unlike for blog-only mode).
I believe we should tell the user to remove `/src/pages/index.js` for docs-only mode as well.

**Comment by slorber** [comment]
Yes you are right.

Here the missing sidebar is due to having some kind of "merge" between the home page and the docs homepage. Basically / renders docs homepage, but receive as props the home page data 👎 

I fixed some things recently to avoid route conflicts and be sure that we never "merge" 2 routes together this way, but only have one route override the other one, but we don't have a way to warn the user for such existing overrides currently

=> https://github.com/facebook/docusaurus/issues/3041
