### ISSUE TITLE
Node 14+ dependency breakage alerts from docusaurus-init

### ISSUE THREAD

**Issue by fiendish** [facebook/docusaurus#3095]
## 🐛 Bug Report

Invoked dependencies alert that they are broken in the current version of Node.js (14+).

See the warnings for chokidar and fsevents. (of course the other warnings are bad too).
```
$ yarn global add docusaurus-init
yarn global v1.22.4
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 🔨  Building fresh packages...
success Installed "docusaurus-init@1.14.1" with binaries:
      - docusaurus-init

$ docusaurus-init
Website folder created!

Installing latest version of Docusaurus in website.

yarn add v1.22.4
warning package.json: No license field
info No lockfile found.
warning No license field
[1/4] Resolving packages...
warning docusaurus > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
warning docusaurus > crowdin-cli > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
warning docusaurus > @babel/polyfill > core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
warning docusaurus > react-dev-utils > fork-ts-checker-webpack-plugin > chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
warning docusaurus > markdown-toc > gray-matter > coffee-script@1.12.7: CoffeeScript on NPM has moved to "coffeescript" (no hyphen)
warning docusaurus > markdown-toc > remarkable > autolinker > gulp-header@1.8.12: Removed event-stream from gulp-header
warning docusaurus > react-dev-utils > fork-ts-checker-webpack-plugin > chokidar > fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
warning docusaurus > react-dev-utils > fork-ts-checker-webpack-plugin > micromatch > snapdragon > source-map-resolve > resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
warning docusaurus > react-dev-utils > fork-ts-checker-webpack-plugin > micromatch > snapdragon > source-map-resolve > urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
```
### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## To Reproduce

(Write your steps here:)

1. yarn global add docusaurus-init
1. docusaurus-init

## Expected behavior

I expect to not be told that components are broken unless I downgrade Node.js?

## Actual Behavior

It sounds like I'm being told that components are broken unless I downgrade Node.js.

## Your Environment

- Docusaurus version used: docusaurus-init@1.14.1
- Environment name and version (e.g. Chrome 78.0.3904.108, Node.js 10.17.0): Node.js v14.5.0, yarn v1.22.4
- Operating system and version (desktop or mobile): macOS 10.14.6

**Comment by slorber** [comment]
Apart from a few warnings logged, was it a problem for you and prevent Docusaurus from working?

Let's take an example: "react-dev-utils": "^10.2.1",

We are on latest version, it's not our fault if the transitive deps of our dep have warnings, you should report the problem directly to the intermediate packages

+ it's not because a lib is declared by a deep transitive dependency and breaks on node 14 that it will actually affect our code. Sometimes we don't use all the features of a transitive deps, and there's just no crash.


---


Not saying we should not fix those warnings in the long term, but it's probably not worth to open an issue for that, as we tend to upgrade dependencies anyway to stay up to date. 

These warnings come and go. If you want to submit a PR to fix the current ones, you are welcome, but I don't think it's absolutely worth it, as new warnings will appear.
