### ISSUE TITLE
[v2] /bin/sh: autoreconf: command not found

### ISSUE THREAD

**Issue by DyncMark** [facebook/docusaurus#3137]
There are some errors when I try initialization the  repo with `npm i` or `yarn`.

![image](https://user-images.githubusercontent.com/15116881/88633091-1feefc00-d0e7-11ea-9a5d-10a71e697b7b.png)

**Comment by slorber** [comment]
Can you retry and confirm it's not related to your connexion?
We can see it seems related to a timeout

![image](https://user-images.githubusercontent.com/749374/88642323-a0e6cd00-d0c0-11ea-834d-c084a27fdb03.png)


I'm closing since this is not really related to Docusaurus, and we likely can't do anything about it.

There are issues about this on the internet already, like https://github.com/imagemin/gifsicle-bin/issues/79
