### ISSUE TITLE
Allow all redirects declared in @docusaurus/plugin-client-redirects

### ISSUE THREAD

**Issue by martavis** [facebook/docusaurus#3165]
## 🚀 Feature

Allow any redirect that is declared, regardless if it would override an existing path.

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## Motivation

This error:
```
@docusaurus/plugin-client-redirects: some redirects would override existing paths, and will be ignored:
- {"from":"/search","to":"/searching/"}
```

I like Algolia's themed search page, but needed to modify it. Since there isn't a way to swizzle it, I had to copy it and create a new route `/searching`. So I don't want my audience to find the original `/search` page. 

## Pitch

This would give devs the freedom to choose what routes are redirected.

**Comment by slorber** [comment]
> Allow any redirect that is declared, regardless if it would override an existing path.

That looks like a hacky redirect from /search to /searching, why not fixing the problem at its root instead of working around the problem?

> I like Algolia's themed search page, but needed to modify it.

Why? Understanding the usecases you have is important to us.

> Since there isn't a way to swizzle it

Surprisingly, this is true, because it's not on the theme folder. I'd rather move it to /theme so that it can indeed be swizzled, and allow the user to pass his own impl too, like for the docs components:

![image](https://user-images.githubusercontent.com/749374/88923663-5c029800-d272-11ea-826e-37d598cf23ac.png)

Also, we could allow the user to customize the path of this search page at the same time

**Comment by martavis** [comment]
> Why? Understanding the usecases you have is important to us.
I needed to modify it because I would like the page to sit behind a login. My definition of modification is to add a higher-order component that checks authentication.

> why not fixing the problem at its root instead of working around the problem?
For me, swizzling the Search page would be the root fix since it has a lot to offer similar to the DocPage, but may need tweaking to fit specific needs. I can create another ticket if you're in agreement.

**Comment by slorber** [comment]
yes that seems better to allow swizzling, I'm closing, waiting for the other issue
