### ISSUE TITLE
Using multiple global css files

### ISSUE THREAD

**Issue by danielsxz** [facebook/docusaurus#3289]
## 📚 Documentation

I'm not sure how to use multiple global CSS files. Similar to Docusaurus v1, I wish to split up my CSS into multiple global CSS files. There isn't any information about this specific use case in the documentation.

My CSS files are difficult to separate in different modules, so using CSS modules is out of the question.
The other options is to import all my CSS files in the custom.css file using @import. I have more than 30 CSS files, so this would be verbose.

**Comment by slorber** [comment]
Hi,

Why do you think exactly it would be more convenient to maintain a list of css files in js config, instead of CSS ? At some point you have to define the files to include.

The theme classic offer you the ability to register a single css file. We could improve and allow to pass an array of css files instead but I feel it's unnecessary.

Nothing prevents you from writing your own local site plugin that does exactly what you want

https://v2.docusaurus.io/docs/lifecycle-apis/#getclientmodules

```js
module.exports = function mySitePlugin(context, options) {
  return {
    name: "my-site-plugin",
    getClientModules() {
      return ["css1.css", "css2.css", "css3.css"];
    }
  };
};
```
