### ISSUE TITLE
ThemeConfig: Navbar items href validation error

### ISSUE THREAD

**Issue by ataube** [facebook/docusaurus#3349]
## 🐛 Bug Report

I upgrade from 2.0.0-alpha.54 to 2.0.0-alpha.61, and get a validation error for the following config (which used to work before)

```js
themeConfig: {
      items: [
        {
          href: '/foobar',
          label: 'Foobar',
          position: 'left',
          target: '_blank'
        },
      ],
    },
  }
```

Error: `ValidationError: "navbar.items[0].href" must be a valid uri`

My webserver is hosting 2 sites, and I need to jump out from docusaurus to another static html side on path `/foobar`. The path has a dynamic base url, because the site gets hosted and different environment stages. It would be great if you support this again. 

Thanks

**Comment by slorber** [comment]
Hi,

Can you give more details please?

What are the fully qualified URL(s) this link should lead to?

Have you tried `to: /foobar` instead of href?

Honestly this part of the code is a bit messy and it's hard to change anything without introducing a breaking change.

At some point we should be able to tell the router if we should do a regular HTML navigation, or history.push(), and the current API surface does not help us to make this explicit, but using to + target=_blank should do the job

**Comment by ataube** [comment]
Hi, thanks for your feedback, using `to: /foobar` with target solves the problem. A more explicit api surface would be definitely nice to have.
