### ISSUE TITLE
Whole source color is picked up and transmitted while copy pasting 

### ISSUE THREAD

**Issue by harishbala1o** [facebook/docusaurus#3404]
I'm using the same code as mentioned in **code-blocks-buttons.js** for copy button function for a code block but source colour is picked up and transmitted while copy-pasting. A screenshot  is shared below for reference when a code is copied and pasted

![codeblock](https://user-images.githubusercontent.com/36741511/92221417-119cb880-eebb-11ea-8f07-805b8ab269a8.png)

**Comment by harishbala1o** [comment]
Hi hello is there any update on this?

**Comment by slorber** [comment]
The Docusaurus team is actively working on Docusaurus v2.

After a very long alpha, Docusaurus v2 is [now in beta](https://docusaurus.io/blog/2021/05/12/announcing-docusaurus-two-beta).
We believe that the v2 beta is already better than v1, and v2 is ready for maintstream adoption.

Apart from critical issues and security fixes, we don't plan to invest much time on Docusaurus v1 anymore.

We are all closing v1 issues. 
Maybe the current issue is already fixed in Docusaurus v2.
Please try to upgrade, and if the issue is still there on Docusaurus v2, open a new issue.
