### ISSUE TITLE
External component is not rendered within document

### ISSUE THREAD

**Issue by krakowski** [facebook/docusaurus#3409]
## 🐛 Bug Report

Placing `@material-ui/core`'s `Button` component inside a document results in the component not being rendered.

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

yes

## To Reproduce

1. Create a new project and add `@material-ui/core` dependency

```
npx @docusaurus/init@next init material classic
cd material && yarn add @material-ui/core
```

2. Place the following snippet somewhere within `docs/mdx.md`

```js
import Button from '@material-ui/core/Button';
<Button variant="contained">Docusaurus</Button>
```

## Expected behavior

The `Button` component should be rendered inside the document.

## Actual Behavior

The `Button` is not rendered inside the document.

## Your Environment

- Docusaurus version used:
  - `2.0.0-alpha.63`
- Environment name and version (e.g. Chrome 78.0.3904.108, Node.js 10.17.0):
  - `Chrome 81.0.4044.138` `Node.js 14.3.0`
- Operating system and version (desktop or mobile):
  - ```
     Type:          Desktop
     Distribution:	Manjaro Linux
     Release:	20.0.3
     Codename:	Lysia
    ```
- Dependencies:
  - ```
     "@docusaurus/core": "2.0.0-alpha.63",
     "@docusaurus/preset-classic": "2.0.0-alpha.63",
     "@material-ui/core": "^4.11.0",
     "@mdx-js/react": "^1.5.8",
     "clsx": "^1.1.1",
     "react": "^16.8.4",
     "react-dom": "^16.8.4"
     ```

## Reproducible Demo

https://github.com/krakowski/docusaurus-3409 (https://github.com/krakowski/docusaurus-3409/commit/e1cc088c8ff1973d86f9ac2883ff589b7d02b152)

**Comment by slorber** [comment]
Hi, you mean inside the MDX document?

Can you display what is the html output produced in the dom tree?

Can you produce a repro?

**Comment by krakowski** [comment]
Hi @slorber,

there is no sign of the component within the DOM. By "repro" you mean steps to reproduce this issue? I included them under `To Reproduce`. Additionally, I created a repository where the mentioned steps were applied.

https://github.com/krakowski/docusaurus-3409 (https://github.com/krakowski/docusaurus-3409/commit/e1cc088c8ff1973d86f9ac2883ff589b7d02b152)

**Comment by slorber** [comment]
@krakowski not 100% sure but I think you should add an empty like between the import and the comp usage.

I'm asking for source code and a live site version because it saves me time, and enable to debug this remotely without having to fork, clone, yarn install, run everytime, so if you can provide a live site on Netlify or something that's appreciated.

**Comment by slorber** [comment]
Pretty sure this is due to a missing line break, as I can reproduce an error on the MDX compiler.

You can try MDX syntax at https://mdxjs.com/playground

Unfortunately can't change anything about that. We'll likely update to MDX 2.0 when it's ready and maybe it fixes this issue, but don't know.

You should normally have an error with such code, as I can reproduce on our own website in dev mode by removing this empty line:

![image](https://user-images.githubusercontent.com/749374/92752617-604dc500-f389-11ea-9e21-e7dd15bad18b.png)

**Comment by krakowski** [comment]
Hi @slorber,

you are right, it is working with an empty line in front of the component, although I didn't get any errors on the command line... it is still showing `Compiled successfully` without an empty line and the component is not being rendered. In any case, thank you for your time investigating this! Next time I will definitely provide a live demo. :slightly_smiling_face:

It's also worth noting, that the preceeding line **must be completely empty**. Even a single whitespace causes the described behavior.

**Comment by slorber** [comment]
Great to know 👍 


Yes I think a totally empty line is required after ES imports, not sure exactly why but it's MDX specific.

Maybe try to paste your full markdown in the mdx playground and see if you get an error? that's surprising that you don't get an error
