### ISSUE TITLE
@hapi/joi is deprecated

### ISSUE THREAD

**Issue by atomicpages** [facebook/docusaurus#3430]
## 🐛 Bug Report

This isn't exactly a bug, but `joi` is moving out of the `@hapi` org. Probably a good idea of docusaurus v2 moves to the current version, too.

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes. I'd like to contribute this fix 😄 

## To Reproduce

No repro steps. This is purely for housekeeping.

## Expected behavior

N/A

## Actual Behavior

N/A

## Your Environment

- Docusaurus version used: `alpha.63`
- Environment name and version (e.g. Chrome 78.0.3904.108, Node.js 10.17.0): Node 12.14.0
- Operating system and version (desktop or mobile): macOS 10.15 (Catalina)

## Reproducible Demo

See deprecation notice: https://www.npmjs.com/package/@hapi/joi

**Comment by slorber** [comment]
Oh, thanks for letting me know, that can be annoying, as we recommend users to declare their own Joi schema in plugins.
Hope the old/new validation will be compatible with each others so that the transition is smooth.

I think we should upgrade to latest Joi, and also maybe expose Joi singleton in `@docusaurus/utils-validation` , and recommend plugin authors to use this singleton, so that when doing the switch, the users and plugin authors wouldn't need to know about it.

Related issue: https://github.com/sideway/joi/issues/2411

**Comment by atomicpages** [comment]
@slorber I'd like to stake claim for this issue 😄

**Comment by slorber** [comment]
Thanks

Before investing too much in this maybe it's worth to sync and describe
what you plan to do exactly

Le mer. 16 sept. 2020 à 03:33, Dennis Thompson <notifications@github.com> a
écrit :
