### ISSUE TITLE
Back to top button

### ISSUE THREAD

**Issue by lex111** [facebook/docusaurus#3513]
## 🚀 Feature

Feature request from [Canny](https://docusaurus.canny.io/feature-requests/p/back-to-top-button):

I think the back to top button in the v1 should be also implemented in v2. Long docs will need it.

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## Motivation

Many docs sites have a back to top button. Docusaurus v1 also had similar built-in feature. This is especially useful for long web pages.

## Pitch

- Better backward compatibility from v1
- Nice UX improvement

**Comment by michaelknowles** [comment]
The original design from v1 seems like a good start.  Are there other ideas?

**Comment by michaelknowles** [comment]
We could place the button above or to the side of the hamburger.

To the side seems like a good option since the hamburger will already be obscuring any text on this horizontal row.  Placing it above will mean another row of text is obscured.

Putting it as an option inside the hamburger doesn't sound great because I think scroll to top probably shouldn't take an extra click to get to.

**Comment by slorber** [comment]
It's worth mentioning this other issue: https://github.com/facebook/docusaurus/issues/2220

As users are not totally satisfied with the current mobile layout/navigation, we should think about what design we really want first, and where the back to top button would fit in this fixed design.

**Comment by Sayan-dev** [comment]
What if the **back-to-top** button is visible when the user is scrolling up...instead of the hamburger button and stays for few seconds, and then is replaced by the hamburger button if the user doesnot scroll up

**Comment by michaelknowles** [comment]
@slorber OK, I'll continue discussion on that issue.

**Comment by hamzahamidi** [comment]
I think the Back to top button should only be visible when scrolling.

**Comment by vickywane** [comment]
@lex111 @michaelknowles i could fix this by adding a round opaque arrow ( up or down) icon to scroll to the top. 

If we are worried about it obscuring other content, the button could be made to fade out on the screen after few seconds of inactivity using scrollEventListeners. 

I would like to implement this.

**Comment by EricAtMSFT** [comment]
I have a simple prototype working in my fork here: https://github.com/EricAtMSFT/docusaurus

I tried a few things and landed on the button being inline, materializing after 400px of vertical scrolling, displayed as a small overlay on the content so as to not disrupt the sometimes long side bar content. It has a gradient to make it less noticeable. On mobile it snaps to align with the Hamburger button on the bottom left.

Feedback welcome for iteration!

![image](https://user-images.githubusercontent.com/17344631/96205225-e6c26d00-0f1a-11eb-9104-28c2f5d3a640.png)

**Comment by Vishal19111999** [comment]
@lex111 Putting the "scroll to top" button along with the hamburger not only covers the screen but, it would be frustrating if someone clicked "scroll to top" instead of hamburger by accident

How about using something with the same hamburger, like holding the hamburger or swiping it or anything similar? as it would resolve both the issues I implemented correctly!

To say the very least, it can be a good silent temporary fix!

I can work on this if it sounds good!

(I am just a beginner, so ignore any mistakes)

![Group 420](https://user-images.githubusercontent.com/29145212/101991249-65e0e100-3cd1-11eb-809e-80b2d0b6c24a.png)

**Comment by Rahulm2310** [comment]
Is this issue available? I would like to help. Thanks 🙂

**Comment by slorber** [comment]
@Rahulm2310 I think we should not implement this feature until we have a clear idea what the UX on mobile should be => https://github.com/facebook/docusaurus/issues/2220

(if we did, it would only be temporary, so if you have a nice temporary solution to suggest, why not, but we may not keep it in the long term)

**Comment by technikhil314** [comment]
I too would like to help on this. 

And regarding the proposed solution by @Vishal19111999. I feel the long press can still be achieved with failr and less amount of code. But drag thing might ask for a big chunk of code that is well tested on all touch and pointing devices. 

Well I too am new to this community and in fact this would be my first ever contribution here. 
So please correct me if I am wrong anywhere.
