### ISSUE TITLE
V2: Enable feeds by default in blog plugin

### ISSUE THREAD

**Issue by nickmccurdy** [facebook/docusaurus#3720]
## 🚀 Feature

The blog plugin should enable feeds by default.

## Motivation

Docusaurus 1 enables both blogs and feeds by default. Docusaurus 2 extracts the blog into a separate plugin so it makes sense that blogs aren't enabled by default, however I would expect feeds to also be enabled by default with the blog plugin.

Additionally, feeds would be useful to most users as it's unlikely that blogs would be monetized for commercial purposes (see #3719 for more rationale).

## Pitch

The blog plugin should behave as if `feedOptions: { type: 'all' }` was in the configuration by default

**Comment by slorber** [comment]
Why not having a feed by default, but it's a breaking change.

Good first issue

**Comment by cindygu4** [comment]
Hi, I'm interested in taking on this feature if that's okay :)

**Comment by slorber** [comment]
yes thanks

**Comment by vikhramt007** [comment]
Me and @cindygu4 are working on this feature.
We're new to Docusaurus, so we just wanted to ask what enabling feeds by default looks like and how we can test it out.

**Comment by nickmccurdy** [comment]
@vikhramt007 @cindygu4 

> what enabling feeds by default looks like

I believe you can implement this by changing the [Joi `type` validation schema](https://github.com/facebook/docusaurus/blob/3ea2f8cfdeaa7aa611f93f27955835afa3716496/packages/docusaurus-plugin-content-blog/src/pluginOptionSchema.ts#L68-L73) to use `'all'` (which produces `['rss', 'atom']` in the internal config) by default.

> how we can test it out

Generating the site should get you `/blog/rss.xml` and `/blog/atom.xml` files.

**Comment by slorber** [comment]
yes changing the Joi default value could be enough.

you can test it with unit tests: missing blog feed config leads to rss+atom
you can test it locally with `yarn build:v2` and checking files in `website/build` as explained  by @nickmccurdy

**Comment by vikhramt007** [comment]
> yes changing the Joi default value could be enough.
> 
> you can test it with unit tests: missing blog feed config leads to rss+atom
> you can test it locally with `yarn build:v2` and checking files in `website/build` as explained by @nickmccurdy

@slorber 
Hi, we started  to work on this feature, and we would like some clarification on whether "missing blog feed configuration" means 
`feedOptions: {type: '', title: 'myblog'}`  or `feedOptions: {title: 'myblog'}` ?

If its the former, how would we change feedOptions.type so we don't receive any validation errors? If its the latter, how would we approach this?
Thanks

**Comment by cindygu4** [comment]
Hi @slorber,

@vikhramt007 and I wrote a unit test for this feature as shown below:
![Screen Shot 2020-11-25 at 3 11 28 PM](https://user-images.githubusercontent.com/43725481/100277060-8585b480-2f30-11eb-8f9c-e3f227259217.png)

We ended up doing so that type accepts an empty string parameter, `{type: ''}`. This is because we found that changing the Joi default value led to errors in other tests. Right now, our unit test case passes along with all the other unit tests. However, when we try to test it locally using `yarn build:v2`, we get a validation error telling us '"feedOptions.type" does not match any of the allowed types.' Are you aware of how `{type: 'all'}` is resolved since we didn't find it in `docusaurus-plugin-content-blog/src/types.ts` and we only found`export type FeedType = 'rss' | 'atom';`. 

Thanks!

**Comment by slorber** [comment]
Hi,

"" is not really a value we should accept

We should allow type: null undefined (= type: "all")
We should allow feedOptions: null, feedOptions: {title: "title"}

If other tests say something else, you should change these other tests so that they conform to what we actually want.

> Are you aware of how {type: 'all'} is resolved since we didn't find it in docusaurus-plugin-content-blog/src/types.ts and we only foundexport type FeedType = 'rss' | 'atom';.

Afaik it's only a shortcut in the schema, after normalization of options, you can't end up with a type: "all" code, so it's only in the Joi declaration file:

```
    type: Joi.alternatives().conditional(
      Joi.string().equal('all', 'rss', 'atom'),
      {
        then: Joi.custom((val) => (val === 'all' ? ['rss', 'atom'] : [val])),
      },
    ),
```

---

I merged this morning many changes  so you'd  rather update your branch asap to sync with recent code.

**Comment by cindygu4** [comment]
Hi @slorber,

Thank you for your help! It really helped clear up our understanding. We've been able to implement this feature and made a pull request a little bit ago :)

**Comment by slorber** [comment]
closed by https://github.com/facebook/docusaurus/pull/3842
