### ISSUE TITLE
DX Issues when getting started (Non-obvious errors with docusaurus-init)

### ISSUE THREAD

**Issue by filipdanic** [facebook/Docusaurus#379]
### Is this a bug report?
No, but it’s pretty important for general developer experience. 

### Have you read the [Contributing Guidelines](https://github.com/facebook/Docusaurus/blob/master/CONTRIBUTING.md)?

Yes

### Steps to Reproduce

1. Follow the guide over at https://docusaurus.io/docs/en/installation.html
2. Bootstrap the project with `docusaurus-init`
3. Run `docusaurus-start`

This will fail because there is no `docs` folder. This will not be visible in the CLI which just says to open `localhost:3000`. When you open that in a browser you are greeted with a white background and bunch of text.

The text does say: 

> Error: You have 'doc' in your headerLinks, but no 'docs' folder exists one level up from 'website' folder. Did you run `docusaurus-init` or `npm run examples`? If so, make sure you rename 'docs-examples-from-docusaurus' to 'docs'.

Which is great, but it’s easy to miss! It’s also not the best experience to be greeted with an error right off the bat. I noticed the error in the CLI, otherwise, it would have taken me a bit longer.

The same problem will happen with `blog` directory, but that’s fine once you realize the pattern I suppose.

### Expected Behavior

I’m by no means an expert on maximizing developer experience, but, it seems to me that:

1. This should have been mentioned as a note on https://docusaurus.io/docs/en/installation.html
2. The error should be more prominent.
3. There should have been a warning in the CLI from the start.

Thoughts? Would this be a good contribution opportunity?

**Comment by JoelMarcey** [comment]
Hi @filipdanic - thank you for filing this issue. I definitely can see validity in some of your points here. The reason we just don't use `docs` is because we didn't want to deal with the possible problems of clobbering or somehow merging with an existing `docs` folder.

We do mention that you have to do the renames here: https://docusaurus.io/docs/en/site-preparation.html#verifying-installation. That said, maybe that section should be moved to the bottom of the installation page instead? That might make more sense here - so it would fall under your option (1).

Do you want to try a PR to make that happen?

**Comment by filipdanic** [comment]
Yes, it seems like moving the whole `Verifying Installation` section to the `Installation` page would make sense. I can submit a PR for that.

**Comment by JoelMarcey** [comment]
@filipdanic Hi. Given that we moved the verifying installation section, do you think the developer experience is adequate now? Or do you want to propose other changes?

**Comment by filipdanic** [comment]
Looks good @JoelMarcey. 👍

**Comment by JoelMarcey** [comment]
Excellent. I will close out this issue then.
