### ISSUE TITLE
making it so docusaurus uploads to subdirectory instead of web root

### ISSUE THREAD

**Issue by terrafrost** [facebook/docusaurus#3809]
I posted this [on stackoverflow](https://stackoverflow.com/q/64971286/569976) but have not gotten a response, hence this post, here:

Anyway, from node_modules\docusaurus\lib\publish-gh-pages.js:

```
      const websiteURL =
        GITHUB_HOST === GITHUB_DOMAIN
          ? `https://${ORGANIZATION_NAME}.github.io/${PROJECT_NAME}` // gh-pages hosted repo
          : `https://${GITHUB_HOST}/pages/${ORGANIZATION_NAME}/${PROJECT_NAME}`; // GitHub enterprise hosting.
```

My question is...  why is the documentation being uploaded to a subdirectory? What if I wanted it uploaded to the root directory? How might I do that?

The front page of a docusaurus v1 website is more of a splash page with sections like "feature callouts", etc. Overall, it seems best suited to be a root page as it appears to be for https://hermesengine.dev/ , https://hydra.cc/ and pretty much every other facebook open source project.

Also, the HTML that docusaurus generates has `<link rel="stylesheet" href="/css/main.css"/>` in it, which works great when you're building your site with `npm run start` (which results in the files living in web root), but not so much when using publish-gh-pages.js since main.css then lives at `/${PROJECT_NAME}/css/main.css`.

So how can I do the same - make it so my docusaurus built website gets uploaded to web root instead of a subdirectory?

**Comment by slorber** [comment]
Hi,

We Docusaurus only provide a way to build a static/Jamstack website.

The path at which you deploy this static site is your responsibility, and its config is specific to the host, we don't control it not can document exhaustively the dozens of available hosting solutions. The only real thing in our control is the "baseUrl" param, so that the site built know its subdirectory. If you plan to host it at the root, you can use `baseUrl: /`.

First you should mention docusaurus v1 or v2? 
We recommend v2 now (like the sites you use as an example).

For Github Pages, you should read the doc here:
https://v2.docusaurus.io/docs/deployment/#deploying-to-github-pages

We won't duplicate the whole GH pages doc in our doc: if you want to host on GH pages you should refer to GH pages doc directly.

The sites you mention all use CName and  a custom domain. I don't think it's possible to host at the root without a custom domain.
