### ISSUE TITLE
Can't override theme css

### ISSUE THREAD

**Issue by Morriz** [facebook/docusaurus#3879]
## 🐛 Bug Report

I can't seem to add css theme overrides that work in builds.

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## To Reproduce

1. Install the demo and start the dev server with `npm start`
2. Override the `h1` size for small size screen (as the one in the classic theme is waaaaaay too big):

In `src/css/custom.css`:
```css
.docTitle_node_modules-\@docusaurus-theme-classic-lib-theme-DocItem- {
  font-size: 2rem; // <- example override
}
```
Observe that the override works in the browser

3. npm run build
4. serve the build and observe the font-size is still `3rem`

## Expected behavior

The css to stay overridden.

## Actual Behavior

The css modification doesn't work after the build.

## Your Environment

- Docusaurus version used:
- Environment name and version (e.g. Chrome 78.0.3904.108, Node.js 10.17.0):
- Operating system and version (desktop or mobile):

## Reproducible Demo

(Paste the link to an example repo, including a `siteConfig.js`, and exact instructions to reproduce the issue.)

**Comment by slorber** [comment]
Hi,

Do you see your own CSS in the build output?  
Is it a problem of your CSS not being present at all, or a problem where your CSS is overridden by the theme CSS?

Might be duplicate of https://github.com/facebook/docusaurus/issues/3678

**Comment by Morriz** [comment]
I observe the following:

build mode:
- The selector in the css is not rewritten in the build, but the build classes are, so they don't meet

dev mode:
- the custom css is placed before the theme css, which is the wrong order in dev already iyam (and yes, the other issue is targeting that problem)

So I would keep this issue open as it relates to not being able to specify certain selectors from the theme to override.

**Comment by lex111** [comment]
We are using CSS modules, so this class names like `.docTitle_node_modules-\@docusaurus-theme-classic-lib-theme-DocItem-` will not work in a production build. For this to work, you need to use substring matching selector:

```css
[class^="docTitle"] {
     font-size: 2rem;
}
```

But since we also use a lot of CSS vars, in this case you don't even need to create a separate CSS rule to change the font size for h1 doc element. Instead this, you can override the CSS var `--ifm-h1-font-size`.

**Comment by Morriz** [comment]
Thanks a lot. I was actually already doing that but didn't find it straightforward to use substring matching selector. I was hoping for a more elegant css solution. I love the vars, but the themes should be more easily overridable imo.

Closing for now

**Comment by slorber** [comment]
@Morriz you can override themes by using swizzle, as it gives you full control over generated HTML (including className)

In the future, we'll probably try to provide a few well-named class names that will be shared across all themes so that you can target them reliably in a future-proof way, but for now swizzle or substring selector is the best option
