### ISSUE TITLE
Ignore <code> tags inside mdx

### ISSUE THREAD

**Issue by ArtFlag** [facebook/docusaurus#3967]
## 🚀 Feature

I'm trying to have some tabs that show code blocks inside them. 

```
Tabs
  defaultValue="apple"
  values={[
    {label: 'Go', value: 'golang'},
  ]}>

  <TabItem value="golang">
  <p>Text</p>
      <pre>
      <code>
package main&#10;
import (
  "context"
  "encoding/json"
  "fmt"&#10;
)&#10;
func main() {
  configuration := package.NewConfiguration()
}
        </code>
      </pre>
  <TabItem>
```

The page in question fails to display because `:=` is an unexpected token, so it `package`. 
Basically a lot of keywords prevent the page from being displayed. 

It would be great to provide a way to ignore certain HTML code from being interpreted by the MDX parser. 

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)? 

yes 
## Motivation

`<code>` tags might often create problems inside MDX.

## Pitch

Maybe there could be a class provided by docusaurus, or a preset? 

```
ignore_html_tags = ["code"]
```

I'm not versed enough in React to propose a solution.

**Comment by slorber** [comment]
If you use the `<code>` jsx element through MDX, you'd rather pass the source code directly as a string instead of using JSX text elements.

But writing a js string element this way might be annoying, so you'd rather use the mdx interleaving feature.
For this to work, you have to add line breaks around the interleaved MDX (this is  a limitation of current mdx implementation, I think it will be better in 2.0).


![image](https://user-images.githubusercontent.com/749374/103290361-a6d33800-49e9-11eb-955d-6dd86f44a937.png)

**Comment by slorber** [comment]
> It would be great to provide a way to ignore certain HTML code from being interpreted by the MDX parser.

If you want MDX to be improved, you'd rather open an issue on MDX repo directly. We don't plan to add support for fancy features on top of it.
