### ISSUE TITLE
Add trailing slash to auto generated sitemap.xml

### ISSUE THREAD

**Issue by kkhoury38** [facebook/docusaurus#4134]
## 💥 Add a trailing slash to the urls generated in sitemap.xml

Urls in sitemap.xml are currently listed without a trailing slash (i.e. ./blog instead of ./blog/), while, when going to the page, it redirects to the url with a trailing slash (i.e ./blog redirects to ./blog/)

This results in google indexing the page with a "redirect error".  

A temporary fix for user created content pages is to add a trailing slash on the "slag" property value. This will not work though on all pages that are automatically generated by docusaurus. Pages include:

/blog
/blog/tags
/blog/tags/TAG_NAME

The proposal is to add a trailing slash to those urls when generating sitemap.xml

## Current version: 
@docusaurus/core: 2.0.0-alpha.69,
@docusaurus/preset-classic: 2.0.0-alpha.69,

## Example sitemap 
https://atman-iot.com/sitemap.xml

## Issue example 
- url in sitemap: https://atman-iot.com/blog
- actual page: https://atman-iot.com/blog/

**Comment by slorber** [comment]
I would suggest you should rather configure your host to serve the pages without the trailing slash (not always possible though...). Related to https://github.com/facebook/docusaurus/issues/3372.

Otherwise, there's already an option in the sitemaps plugin: https://v2.docusaurus.io/docs/next/api/plugins/@docusaurus/plugin-sitemap/
