### ISSUE TITLE
docs link is broken when  adding  routeBasePath: '/',

### ISSUE THREAD

**Issue by KishaniKandasamy** [facebook/docusaurus#4187]
// docusaurus.config.js
module.exports = {
  // ...
  presets: [
    [
      '@docusaurus/preset-classic',
      {
        docs: {
          routeBasePath: '/',
        },
      },
    ],
  ],
};
The docs link is broken when I add routeBasePath: '/', .Is there any solution to solve this ?

**Comment by slorber** [comment]
Hi,

Please include more context or we can't help you.
Use new.docusaurus.io to provide a repro.

Also this does not look like a bug but rather a question, and we have github discussions for that.

If you change the basepath for docs (if if it's / and not /docs), then for sure you have to fix all your site links that include `/docs/` because they are now broken.
