### ISSUE TITLE
V2 Ideal Image functionality

### ISSUE THREAD

**Issue by perrygovier** [facebook/docusaurus#4255]
## 🐛 Bug Report

The Ideal-Image plugin is not currently functioning as described on the [documentation page](https://v2.docusaurus.io/docs/api/plugins/@docusaurus/plugin-ideal-image). It does display an LQIP placeholder image, as described, but the various sizes of the image are not generated or used. The plugin does some processing as the filesize of the image changes (increases slightly), but it does not resize the images. The [React Ideal Image library](https://github.com/stereobooster/react-ideal-image) that I think this is based on is outstanding, so it'd be lovely if we can get it up and running. 

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## To Reproduce

I had an (unrelated?) issue getting it to work on codesandbox. The plugin had trouble resolving. [Here's the codesandbox demo](https://codesandbox.io/s/cool-archimedes-sy6gm?file=/src/pages/index.tsx).

Instead, I spun up a vanilla site and created a nearly identical test hosted on github. 
test code: https://github.com/ionic-team/docusaurus-test/blob/main/src/pages/test.tsx#L25-L48
source image: https://github.com/ionic-team/docusaurus-test/blob/main/static/img/open-graph.png
processed image: https://github.com/ionic-team/docusaurus-test/blob/gh-pages/ideal-img/open-graph.11d76e2.1200.png

(Write your steps here:)

1. Clone https://github.com/ionic-team/docusaurus-test
1. `npm i && npm run build && npm run serve`
1. visit http://localhost:3000/test

## Expected behavior

(Write what you thought would happen.)

You would expect each test image to be resized according to their description, many using the `srcset` `img` attribute to allow for different images at different screen sizes. 

## Actual Behavior

(Write what happened. Add screenshots, if applicable.)

The images used are full sized and only slightly different filesize than the original image. In fact, despite the many tests, only one png and one jpg are generated.  

Top: original image. Bottom: slightly modified but still full-sized image
![Top: original image. Bottom: slightly modified but still full-sized image](https://user-images.githubusercontent.com/571056/108571357-a4000f80-72d5-11eb-9bde-dfcba090b247.png)

Full-size image used when it should be smaller
![Full-size image used when it should be smaller](https://user-images.githubusercontent.com/571056/108571606-27216580-72d6-11eb-8ded-a29745ef4699.png)

## Your Environment

- Public source code: https://github.com/ionic-team/docusaurus-test
- Public site url: http://docusaurus-test.ionic.io/test/
- Docusaurus version used: 2.0.0-alpha.70
- Environment name and version (e.g. Chrome 78.0.3904.108, Node.js 10.17.0): Safari 14.0.3, node 14.12.0
- Operating system and version (desktop or mobile): Mac OS 11.2 Beta

## Reproducible Demo

If possible, use https://new.docusaurus.io to create a CodeSandbox reproducible demo of the bug.
http://docusaurus-test.ionic.io/test/

(Paste the link to an example repo, including a `docusaurus.config.js`, and exact instructions to reproduce the issue.)
https://github.com/ionic-team/docusaurus-test
https://github.com/ionic-team/docusaurus-test/blob/main/docusaurus.config.js

**Comment by slorber** [comment]
Hi,

I'm not too familiar with this plugin of our codebase and the original author is [not there anymore](https://v2.docusaurus.io/blog/2020/01/07/tribute-to-endi). 

Will have to retro-engineer bit all this a bit to understand what is happening, particularly as we seem to be using a fork https://github.com/endiliey/react-ideal-image)

We use it on Docusaurus site Showcase and it seems to actually resize images:

https://v2.docusaurus.io/showcase

![image](https://user-images.githubusercontent.com/749374/108753408-fc891400-7544-11eb-8f7b-8b6e6c60ad64.png)

And I also see that the smaller size of 640px is used if I simulate a 300px width mobile device (not much more, probably because of my retina screen at it may try to download x2 images?).

It does not seem to use srcset in our site showcase, but there's a srcset prop according to the doc here: https://github.com/endiliey/react-ideal-image
Maybe it's just a lack of documentation?

Note you probably know this already but this plugin only works for the production build, so the codesandbox may not be the most convenient way to debug this.

---

I don't have too much bandwidth currently to investigate this, unfortunately.

It is a plugin, so this means if you really need something right now, you could try to build your own solution.

**Comment by perrygovier** [comment]
Thanks, 

We have a ways to go in migrating our current site over, and this is a feature not implemented in our current site either. So fixing it means an SEO gain, but nothing is lost without it. An alternative approach would be to use an image processor proxy like Imgix. In the next few weeks, I'll evaluate whether it'd be better/faster for us to get this working or just use a proxy. Thanks and keep up the great work!

**Comment by michalsanger** [comment]
@perrygovier it's probably not obvious from the documentation, you should configure the plugin behaviour in `docusaurus.config.js`, not via props of `Image` component. See the Docusaurus config as an example:

https://github.com/facebook/docusaurus/blob/c8cf48a355b01356c0be541a4c16a1907ad0bc3a/website/docusaurus.config.js#L139-L147

**Comment by perrygovier** [comment]
Ah, that makes a lot of sense. Thanks!
