### ISSUE TITLE
Twitter Card Preview

### ISSUE THREAD

**Issue by enesozturk** [facebook/docusaurus#4260]
## 🚫 Questions and Help

Hi. Thanks for that wonderful library. I am trying to set a twitter card preview for my documentation. I am using v2. Firstly I used `image` and `twitterImage` in **themeConfig** in `docusaurus.config.js` like below but it did not work. 

```js
module.exports = {
  title: 'React Native Hold Menu',
  ...
  themeConfig: {
    twitterImage: 'img/og.png',
    image: 'img/og.png',
    ....
  }
};

```

After that I saw [Head](https://v2.docusaurus.io/docs/docusaurus-core#head) component in your documentation. Tried like below but did not worked either.

```js
function Home() {
  return (
    <Layout>
      <Head>
        <meta name="twitter:card" content={useBaseUrl('/img/og.png')} />
      </Head>
      <MyContent />
    </Layout>
  );
}

export default Home;
```

When I inspect my landing page I see below and in Twitter Card Validator I can not see the card.

```html
<meta name="twitter:card" content="summary_large_image" data-react-helmet="true">
```

Do I missing something? How can I do that for my landing page?

[Edit]: I also tried `image` in head of md files but I need it for my landing page. Not for documentation;

```md
---
id: getting-started
title: Getting Started
description: Lorem ipsum dolor si amet
hide_title: true
slug: /
hide_table_of_contents: true
image: /img/og.png
---

```

**Comment by slorber** [comment]
Hi,

As the issue template explains issues are not for questions.
Also please submit a repro using new.docusaurus.io with your exact setup, or provide a github repro repository.

`twitterImage` is docusaurus v1. Maybe you are reading the v1 doc instead of the v2 doc or mixing version. Make sure to read the appropriate version and help us help you by providing all the infos that could be useful, (including source code, visible site online), not just "I tried that but it didn't work".

**Comment by enesozturk** [comment]
Hi, thanks for responding. Sorry for being missed description of issue template. I will move issue to Discussions if I cannot solve. Firstly I was reading v1 and after a while noticed and checked v2 as well. 

The content of my issue not includes **just** "I tried that but it didn't work". I shared all my configs and code snippets and told what I did to solve. Thanks for resource, I will check.
