### ISSUE TITLE
theme-classic(v2): fonts do not render the same way across browsers

### ISSUE THREAD

**Issue by ArtFlag** [facebook/docusaurus#4276]
## 🐛 Bug Report

I'm not sure if I should put this as a bug, feel free to update.

The fonts do not render the same way in Firefox and Chrome (the only browsers I've tried).
It is particularly obvious in the sidebar and when overriding the title font, like in my case:

<img width="570" alt="fonts" src="https://user-images.githubusercontent.com/25686502/108861319-62ca7100-75ef-11eb-8bb3-4d43a19d6e02.png">

Everything is a little heavier on FF. I personally prefer the lighter font-weight we see in Chrome, I'm not sure which version is the orignal intent.

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## Expected behavior

The fonts should be closer in weight across browsers.

## Your Environment

Chrome: 88.0
FF: 86.0

**Comment by lex111** [comment]
Indeed, now we have such inconsistency in fonts. But that's because we don't specify the same font anywhere but we are relying on system font stack (see https://systemfontstack.com/ or https://www.digitalocean.com/community/tutorials/css-system-font-stack for more details).
As I understand it, many CSS frameworks follow this pattern, so we done same. If you don't like it, you can override CSS variable `ifm-font-family-base`.
