### ISSUE TITLE
Add a unique CSS class to body tag which uses the docs ID

### ISSUE THREAD

**Issue by Dannyholt** [facebook/docusaurus#4280]
## 🚀 Feature

Can we get some CSS classes to the `body` tag or maybe `main-wrapper` which uses the docs id. This would allow us to style specific docs without impacting other docs on the site which may not want/need that styling. Similar to what WordPress does on their `body` tag which uses the page or posts unique ID. 

The examples below grab the `getting-started` class from a doc with an ID of **getting-started**.

```html
<body class="getting-started" style="overflow: visible;">
```

```html
<div class="main-wrapper getting-started">
```

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## Motivation

Currently we have a sidebar category called **Getting Started** which has a several docs such as System Requirements, Installation, Configuration and so forth. We also have a **getting-started.md** doc which has a bunch of information and a list of all docs in the **Getting Started** category.

This list is quite long and so would benefit from some simple CSS to style the list items into two columns. At the moment, this isn't really possible without impacting other lists on the site.

## Pitch

This could be used in a variety of ways not just the simple scenario I explained above. I'm sure other users would find having a unique CSS class for a particular docs helpful in other styling scenarios as well.

**Comment by Simek** [comment]
Hi @Dannyholt, this PR should fix your issue:
* https://github.com/facebook/docusaurus/pull/4311

It have introduced the new `className` for the docs plugin pages wrapper:
> https://github.com/facebook/docusaurus/blob/master/packages/docusaurus-theme-classic/src/theme/DocPage/index.tsx#L57

CC: @lex111

**Comment by Dannyholt** [comment]
@Simek 

Unfortunately, this won't fix my issue as I would prefer to target specific docs via CSS whereas the `main-docs-wrapper` will appear on all docs as far as I can tell. :)

What I'm after is let's imagine we have a doc called `hello.md` the wrapper would add the docs `ID` as a class. For example:

```html
<div class="main-docs-wrapper hello">...</div>
```

Which you could then use to style elements for that doc only. For example:

```css
#__docusaurus .hello .markdown ul {
  column-count: 2;
}
```

**Comment by Simek** [comment]
Yeah, you are right, I didn't get the problem which you correctly. 

As a temporary workaround, if change should apply to only content of one, selected page, you can add `className` to the element or `div` wrapper with `className` around it. You can use HTML tags quite freely in MDX.

Here you can see the example of React Native components grid:
* https://github.com/facebook/react-native-website/blame/master/docs/components-and-apis.md#L21

**Comment by slorber** [comment]
This is quite related to https://github.com/facebook/docusaurus/issues/4322

We could add some unique classname to any doc/blog/markdown page to allow to target it more easily.
For docs, maybe a version classname could be useful too

**Comment by lex111** [comment]
Closing since partially it is implemented in https://github.com/facebook/docusaurus/pull/4511

**Comment by Josh-Cena** [comment]
Reopening, because we still can't use CSS to target a specific doc page. I think there's value in using doc ID as class name of each doc's wrapper.

**Comment by slorber** [comment]
> I think there's value in using doc ID as class name of each doc's wrapper.

The wrapper is a nested div, it's not the most flexible way to add a class.

What if the user wants to change the Docusaurus layout but only for a given doc instance, for a blog post, or a specific doc id? 

I know those are quite unusual edge cases, but it's better if we apply those classes to the HTML tag: it would be more flexible and always suit all use-cases.

---

The way we currently apply classes to the layout (pageClassName/wrapperClassName) is not the best option.

We can also see the problem in https://github.com/facebook/docusaurus/pull/6823#issuecomment-1058039483 where it's not easy to split the doc routes into multiple layers and still prevent useless layout unmounts/remounts.

We don't have an equivalent to `<Head><body className="docId"/></Head>` that would add a class to the wrapper from a child (+ SSR support), and it doesn't permit to target layout items with custom CSS


---

I think it's worth doing a breaking change on those CSS class names, moving them at the top HTML element, so that:
- it's more convenient to add such a className from anywhere (also simplified the https://github.com/facebook/docusaurus/pull/6823 refactor)
- more flexible in terms of CSS targeting possibilities

**Comment by Josh-Cena** [comment]
Oh yeah, when I say "wrapper" I don't necessarily mean one particular div, but just any enclosing element. Applying it to `html` makes sense as well.

If you are open to a breaking change, then why not 👍

**Comment by slorber** [comment]
As part of https://github.com/facebook/docusaurus/pull/6933, a doc route will now have the following classes on the top-level HTML element:

```
plugin-docs 
plugin-id-default 
docs-version-2.0.0-beta.16 
docs-doc-id-introduction
```

Are these class names looking good to you? 

Do you have a better suggestion?

Would using data-attribute be a better fit or a good-enough alternative? 
I mean something like:

```css
[data-docs-doc-id-introduction] .label { 
  color: red
}
```


---

Also, the "docs version" selector `docs-version-2.0.0-beta.16` was already there, but it looks suspicious to me to have dots 😅 not sure it's valid

**Comment by slorber** [comment]
The version html className is configurable through config so I guess it's good enough for now. We'd probably need some logic to sanitize random strings to valid classNames at some point though

**Comment by slorber** [comment]
also thinking we could add a `html_class_name` frontMatter if anyone has a need for this

**Comment by Josh-Cena** [comment]
> also thinking we could add a `html_class_name` frontMatter

Our pages plugin has an (undocumented) `wrapperClassName` front matter which IMO makes sense

**Comment by Samrose-Ahmed** [comment]
is it documented how to set a class name on the root? I am trying to add custom styles to the navbar of a page created through Layout component.

**Comment by slorber** [comment]
@Samrose-Ahmed you can definitively do that.

See https://docusaurus.io/tests : each section has a different navbar border, because each plugin/page has a custom HTML className to target more selectively

For custom React pages you'd have to use the following:

```js
<Head>
  <html className="my-custom-page-className"/>
</Head>
```

Note with Head, one HTML className overrides attribute of parents, in case you want to "compose" and avoid overriding a className set upper in the React tree, you'd have to use our undocumented helper:

```js
import {HtmlClassNameProvider} from '@docusaurus/theme-common';
```

**Comment by pavelkornev** [comment]
> ```js
> <Head>
>   <html className="my-custom-page-className"/>
> </Head>
> ```

@slorber is it possible to do the same on `<body/>`?

**Comment by slorber** [comment]
> > ```js
> > <Head>
> >   <html className="my-custom-page-className"/>
> > </Head>
> > ```
> 
> @slorber is it possible to do the same on `<body/>`? I mean i don't a Provider for the body.

Similarly you can copy/paste our `HtmlClassNameProvider ` code and make it work for body if you want to. We don't necessarily plan to provide or use this feature on Docusaurus, and adding a class to HTML is enough.
