### ISSUE TITLE
Bug:  `onBrokenLinks: 'throw'` incompatible with importing markdown files containing relative links from other folders.

### ISSUE THREAD

**Issue by rbalicki2** [facebook/docusaurus#4317]
## 🐛 Bug Report

`onBrokenLinks: 'throw'` incompatible with importing markdown files containing relative links from other folders.

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes.

## To Reproduce

* Set `onBrokenLinks: 'throw'`
* Import a file from another folder. e.g. import `folder/shared/SubComponent.md` from `folder/file.md`

### Case 1
* Include a relative link in that file, which is from the perspective of `folder/`
* `yarn build` fails at `SubComponent.md`, and the link is accurate

### Case 2
* Include a relative link in that file, which is from the perspective of `folder/shared`
* Link leads to a 404. `yarn build` fails at `file.md`.

**Comment by slorber** [comment]
I'm sorry but I have a hard time to understand your repro steps, probably because we use different terminology to express different things.

Do you have a repro (new.docusaurus.io is helpful) or a repo branch I can inspect with that error? (give me the doc path/url, and the md link snippet in that doc).

Do you have any concrete markdown code snippet to share? Do you have any error screenshot to show?

**Comment by Josh-Cena** [comment]
Here's what I tried:

`docs/intro.md`:

```md
import File from './subfolder/_file1.md';

<File />
```

`docs/subfolder/_file1.md`:

```md
[Relative link](../file2.md)
```

`docs/file2.md`:

```md
Hello
```

Both preview and build are successful. @rbalicki2 if you could elaborate on how to reproduce, maybe we'll reopen
