### ISSUE TITLE
allow redirects to RSS / atom

### ISSUE THREAD

**Issue by johnnyreilly** [facebook/docusaurus#4477]
## 🐛 Bug Report

I'm not sure if this is a bug or a feature request.  My blog used to live on blogger and exposed an atom feed at `feeds/posts/default`.  I thought I'd probably be able to implement a redirect to the `/atom.xml` to support people who haven't updated their feed readers.  Didn't work so I thought I'd raise here.

### Have you read the [Contributing Guidelines on issues]

Yes

## To Reproduce

```js
      "@docusaurus/plugin-client-redirects",
      {
        redirects: [
          {
            to: '/atom.xml',
            from: '/feeds/posts/default',
          },
        ],
      },
```

With this in place, run the build with `yarn build` and you'll get: 

```
Error: You are trying to create client-side redirections to paths that do not exist:
- /atom.xml
```

## Expected behavior

Maybe a `/feeds/posts/default` is created during the build?

## Actual Behavior

See above.

## Your Environment

- Public source code: https://github.com/johnnyreilly/blog.johnnyreilly.com/tree/main/blog-website
- Public site url: https://blog.johnnyreilly.com/
- Docusaurus version used: 72
- Environment name and version (e.g. Chrome 78.0.3904.108, Node.js 10.17.0): Node 14
- Operating system and version (desktop or mobile): Linux Ubuntu 20

## Reproducible Demo

You can see this failing on the GitHub Action associated with this PR:

https://github.com/johnnyreilly/blog.johnnyreilly.com/pull/29

You can see the code that generates the error here: https://github.com/facebook/docusaurus/blob/9bdb9eb6305af6b661c90ede7837ba4c7b670bce/packages/docusaurus-plugin-client-redirects/src/collectRedirects.ts#L58

**Comment by slorber** [comment]
Hi

`@docusaurus/plugin-client-redirects` can only create client-side redirects, and is expected to redirect to an existing Docusaurus page route. RSS feeds and sitemaps etc are not applicable because those files are created in a postBuild hook and are not actual SPA routes. We could enhance the plugin to support client-side redirects to RSS and sitemaps but I don't feel it's something I'd like to encourage.

I strongly discourage you to use a client-side redirect for your RSS feed, as it requires loading HTML and executing JS to actually perform the redirect, and I believe most RSS clients won't execute any JS at all to see if it performs any redirect, and will just follow server-side redirects.

Docusaurus can't do server-side redirects, and you have to set this up on your host provider like Netlify, CloudFlare, Vercel... 

Unfortunately GH pages (that you seem to be using) does not allow any server-side redirect option, so the only thing you can do  is use a better hosting solution like Netlify/Vercel, or put Cloudflare on top of GH pages (it will also improve perfs significantly)

**Comment by johnnyreilly** [comment]
Okay wait - I see what you mean. I'd browsed the `gh-pages` branch and spotted files like this which represented my redirects:

https://github.com/johnnyreilly/blog.johnnyreilly.com/blob/gh-pages/2020/12/azure-pipelines-meet-jest/index.html

I didn't open the files, but assumed it just contained the same content as the original file. I assumed they weren't actually redirects; more duplicate content sitting on the old URL, which were just going to `history.push` on load. I didn't realise it contained something like this:

```
  <script>
    window.location.href = '/2020/12/30/azure-pipelines-meet-jest';
  </script>
```

Now that I realise that, you're completely right. What I was suggesting would make no sense.

Incidentally, I do have Cloudfare in place for my blog - you're suggesting I set up a redirect there I guess?

**Comment by johnnyreilly** [comment]
Yeah - done: 

![image](https://user-images.githubusercontent.com/1010525/112041187-ff742600-8b3d-11eb-8114-5572c23279f9.png)

**Comment by slorber** [comment]
yes :)
