### ISSUE TITLE
CSS is different between local development build and built for prod

### ISSUE THREAD

**Issue by SimenB** [facebook/docusaurus#4518]
## 🐛 Bug Report

When running `docusaurus start` the CSS is different than running `docusaurus build` followed by `docusaurus serve`.

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yup

## To Reproduce

1. Check out https://github.com/facebook/jest/pull/11229
1. Run `yarn` from root
1. `cd` into `website/`
1. Compare `yarn docusaurus start` and `yarn docusaurus build && yarn docusaurus serve`

## Expected behavior

The website should look identical

## Actual Behavior

The CSS looks different

Dev:

![image](https://user-images.githubusercontent.com/1404810/112599636-819b6d80-8e10-11eb-944e-d7f3a570cbe7.png)

Prod:

![image](https://user-images.githubusercontent.com/1404810/112599690-8f50f300-8e10-11eb-990d-d9813744812c.png)

I assume this is some bug in the ordering of css files when built vs running in dev mode.

## Your Environment

- Public source code: https://github.com/facebook/jest/tree/master/website
- Public site url: https://jestjs.io/
- Docusaurus version used: `2.0.0-alpha.c32d8bd11`
- Environment name and version: Chrome 89.0.4389.90, Node v14.16.0
- Operating system and version (desktop or mobile): macOS Big Sur 11.2.3

## Reproducible Demo

Checkout the branch from https://github.com/facebook/jest/pull/11229 (https://github.com/SimenB/jest/tree/remove-sass), instructions are above in this issue (it's just "run the website"). From that PR you can also see that the netlify preview shows the same CSS as the local `docusarus build` version

**Comment by slorber** [comment]
Hi,

As explained in DM, this is not an issue with Docusaurus itself but rather it's an issue with the site that has conflicting CSS rules that are too dependent on CSS insertion order.

CSS is code-splitted by Webpack and lazy-loaded and inserted in pages on demand.

For example when you go to https://jestjs.io/help, the following CSS files load:

![image](https://user-images.githubusercontent.com/749374/112640703-dacfc500-8e41-11eb-8332-9f0d2a20353e.png)

Now when you navigate to the homepage you get new CSS files loaded on-demand:

![image](https://user-images.githubusercontent.com/749374/112640751-eae7a480-8e41-11eb-90c1-1ef63728c78f.png)

This order may be different according to the navigation patterns of the user, and you should make sure that one CSS chunk does not mess-up with another CSS chunk.

That's why we use CSS-in-JS or methodologies like BEM: to avoid polluting the global CSS namespace and preventing this kind of problem from happening.

You didn't have this on Docusaurus 1 because on each navigation you "reset" the page CSS as it's not a real SPA navigation. The problem appears in Docusaurus 2 because it's an SPA navigation, but you'll have the same problem with CRA, Gatsby, Next, VuePress...

Let's continue this in DM and find a solution for the Jest website.

May also be related to https://github.com/facebook/docusaurus/issues/3678

**Comment by SimenB** [comment]
I still think it's a bug that dev and prod do not agree on a fresh navigation (or refresh) on the same page. It's not about navigation in that case - some prod optimization breaks css insertion order. The fact other frameworks may or may not have the same bug doesn't make it any less of a bug.

But of course if we fix this for Jest it doesn't really impact me anymore, so I'm happy with that resolution 😀

**Comment by slorber** [comment]
It also affects other projects of the React ecosystem.

https://github.com/facebook/create-react-app/issues/7190
https://github.com/gatsbyjs/gatsby/issues/9733
https://github.com/gatsbyjs/gatsby/issues/9733

If you have any solution to fix this problem let me know, but I don't have any apart advising you to scope your styles and make them independent or insertion order and specificity issues. 

All this is why we invented CSS in JS:
https://speakerdeck.com/vjeux/react-css-in-js

![image](https://user-images.githubusercontent.com/749374/112658130-66058680-8e53-11eb-83ed-c6f4b1738408.png)

Here the problem is "non-deterministic resolution". It's not something new and it affects many sites for many years already.
