### ISSUE TITLE
Production build without SSR

### ISSUE THREAD

**Issue by msteller-connyun** [facebook/docusaurus#4537]
## 🚀 Feature

Allow production builds without SSR

## Motivation

I’v some custom plugins/webpack-loaders which seems to require the window object. 
Works fine in dev build, but fails to build for prod thanks to SSR.

I don’t need SSR, a normal SPA is good enough for my purpose.

`<BrowserOnly/>` is not resolving my issues.

## Pitch

Add a new flag to build

`build no-ssr`.

**Comment by slorber** [comment]
I don't think it is something we want to support unless there are strong args and many people asking for this. 

Docusaurus is focused on content-centric websites and SEO, SSR, Jamstack is important for such sites.

Why is your build failing? BrowserOnly may be not enough, you might also need a lazy require instead of a top-level ES import.

https://github.com/facebook/docusaurus/discussions/4514
