### ISSUE TITLE
Doc: Contextual search only works when algolia is active for 1 day

### ISSUE THREAD

**Issue by serut** [facebook/docusaurus#4555]
## 📚 Documentation

If you have a versionned documentation and you want to active Algolia search engine : 

- Day 0: You don't have any search engine on your documentation
- Day 1: You register to the DocSearch program
- Day 2: You receive your `apiKey` and `indexName`. You set these infos, plus `contextualSearch: true` inside the config file, but there is no result on your app, even if your documentation have been crawled by Algolia.
- Day 2.5: You deploy the search engine without `contextualSearch: true`, otherwise there is no result. As a sideeffect, as the Algolia plugin is now active, all your HTML files contains facets (version, language).
- Day 3.5: Algolia re-crawls your documentation and finds out facets. You can now active `contextualSearch: true` on your documentation.

To conclude, you should add to [Contextual search](https://docusaurus.io/docs/search#contextual-search) : 
If your documentation does not have the search bar active, your pages doesn't return yet the language and version that will be used by `contextualSearch` facets. First day, active the search bar without `contextualSearch`, wait for the next crawl and facets will be ready.

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

**Comment by slorber** [comment]
Doc PRs are welcome if you feel something should be improved here.

I believe you are wrong. Contextual search does not change anything to  how Algolia see the pages, so those pages are indexed the same say with/without contextual search. It only has an impact  at query time.

However, if Algolia crawl your site before your add the algolia plugin to your site, Algolia won't receive the proper meta tags. You really have to make sure the crawler has run after having deployed your site with the plugin installed, otherwise search meta tags are generic (because we might support other search backends in the future).

In general, if things don't work immediately with search, you'd rather ask Algolia Docsearch support to trigger a crawl.

**Comment by slorber** [comment]
@gulien your DocSearch config does not look like the std Docusaurus 2 config.

https://github.com/algolia/docsearch-configs/blob/master/configs/gotenberg.json

https://github.com/algolia/docsearch-configs/blob/master/configs/docusaurus-2.json

I suggest to get in touch with @shortcuts on DocSearch discord (KLM): he'll be able to migrate your site to a new system where you have access to a dashboard, upgrade your config appropriately etc

**Comment by gulien** [comment]
Thanks @slorber! It now works as expected 😄 

Just a quick follow up: one should always add the Algolia plugin before joining the DocSearch program. Otherwise, their config generator will not detect Docusaurus.
