### ISSUE TITLE
i18n "write-translations" command not creating folder for blog in locale

### ISSUE THREAD

**Issue by thisistaimur** [facebook/docusaurus#4724]
The i18n "write-translations" command does not create a folder for the default blog in the classic theme. I went through the examples in the Docusaurus showcase list, and none of them seem to have an implementation of a translated blog.

**Comment by slorber** [comment]
If the "write-translations" command does not create any folder for docs, it's because there's no json translation files extracted by the blog plugin to write there, and the main content of the blog is the markdown content.

But this does not mean it does not work, and you should just follow the tutorial, copying md files as documented here: https://docusaurus.io/docs/next/i18n/tutorial#translate-markdown-files

![image](https://user-images.githubusercontent.com/749374/116985709-255c2100-accd-11eb-9669-e46cd7a3e61b.png)

We'll add a translation example (eventually a starter template) where the translated files are on git and easier to inspect.

I'd also like to add/enhance the cli to support copying the md files, but for now, it is a manual step you have to do.

**Comment by thisistaimur** [comment]
Cheers @slorber, if this is not even a bug, I will close the issue. This is also good documentation for anyone else wondering about blog translations.
