### ISSUE TITLE
postcss V7 security vulnerability

### ISSUE THREAD

**Issue by WayneEllery** [facebook/docusaurus#4787]
## 🐛 Bug Report

Currently V1 of Docusaurus is using V7 of postcss which has a security vulnerability [CVE-2021-23368](https://nvd.nist.gov/vuln/detail/CVE-2021-23368). This vulnerability has been fixed in V8 in 8.2.10 but hasn't been backported to V7:  https://github.com/postcss/postcss/issues/1574

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

**Comment by HonkingGoose** [comment]
This `8.0.0` release tag fro PostCSS has links to migration guides and other advice, go to https://github.com/postcss/postcss/releases/tag/8.0.0 to see that full changelog.

For the maintainers convenience, I'll quote the breaking changes section:

> We try to avoid any breaking changes for end-users:
> - PostCSS 8 dropped **Node.js 6.x, 8.x, 11.x, and 13.x** versions support. All these versions have no security updates anymore.
>- We now serve ES6+ sources in the npm package **without Babel** compilation. If you are creating tools like CodePen and put PostCSS into the client-side JS bundle, you may need to run Babel on `node_modules/postcss` for old browsers.
> - We removed rarely used `postcss.vendor` API.

**Comment by WayneEllery** [comment]
Thanks for adding that @HonkingGoose. Based on the docs Docusaurus v1 is supported on >= 10.9 so upgrading to V8 would drop support for 10 - 13.

**Comment by slorber** [comment]
After discussions, we think that this issue is not too critical:
- it affects postcss.parse() (https://nvd.nist.gov/vuln/detail/CVE-2021-23368)
- It does not look like v1 code is running the affected code, as it has a very limited usage of postcss (only used for autoprefixing).
- a DOS attack is not a big deal for a static website as it does not impact your production production, only CI
- to trigger the DOS attack you would have to introduce some malicious CSS file through config, so basically it can only happen if you want to hack yourself?

In this case, requiring a NodeJS upgrade to our v1 users is more annoying for the community than having a theoretical security issue.

v1 is in low maintenance mode until we deprecate it at the end of the v2 beta. 
We'll continue to fix security issues until then but only if they are a real security risk for our users or if the fix is easy and is not annoying for the community.

I'll track the postcss issue and we can reconsider if the fix is backported to postcss 7
