### ISSUE TITLE
Footer links/columns "shift" to the right when navigating through site's "sections" on mobile

### ISSUE THREAD

**Issue by cheercroaker** [facebook/Docusaurus#485]
### Is this a bug report?

Yes.

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/Docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes.
I proudly contributed to 2 merged PRs recently—:tada:—but for this one I won't be able to directly bring a fix myself as easily (should be easy for a CSS Jedi though), hence this issue.

### Environment

Observed on Linux (Linux Mint 18.3 KDE) with Firefox & Chromium browser.
Node 8.9.4 / npm 5.6.0.
Latest (1.0.7) version of Docusaurus at least.

Can also be observed on the Docusaurus public website as well in the docs part (https://docusaurus.io/docs/).

### Steps to Reproduce

1. Have a running Docusaurus instance (e.g. the vanilla example one)
2. Open a browser and go to the docs part
3. Minimize browser width to simulate a small smartphone
4. Scroll down to the bottom of the page to display the footer
5. With the breadcrumb, select the second section of the docs
6. Scroll down to the bottom of the page to display the footer
7. With the breadcrumb, select the third section of the docs
8. Scroll down to the bottom of the page to display the footer

### Expected Behavior

At steps 4, 6 and 8, the footer should display links & columns aligned to the left of the page.

### Actual Behavior

- For the first section of the docs, step 4 is OK.
- Starting from the second section of the docs, step 6 is KO (links & columns are shifted to the right).
- For the third section of the docs, step 8 is KO (links & columns are even more shifted to the right).

Seems that after third section, footer links & columns are still "KO" in this sense but are "as shifted as the third section's footer")

### Reproducible Demo

One can directly see the the phenomenon by going to these URLs for steps 2, 5 and 7:

- [step 2](https://docusaurus.io/docs/en/installation.html)
- [step 5](https://docusaurus.io/docs/en/site-preparation.html)
- [step 7](https://docusaurus.io/docs/en/site-creation.html)

Or set up the example project and see it locally:
- step 4:
![01-docusaurusfirstsectionfooter](https://user-images.githubusercontent.com/18077405/37041493-a65e47ce-215c-11e8-9b9f-dc851b50f380.png)

- step 5:
![02-docusaurussectionselection](https://user-images.githubusercontent.com/18077405/37041533-b9e6fe58-215c-11e8-81ce-6888cf929f7a.png)

- step 6:
![03-docusaurussecondsectionfooter](https://user-images.githubusercontent.com/18077405/37041560-c874a628-215c-11e8-9644-1bccdf15d30e.png)

- step 8
![04-docusaurusthirdsectionfooter](https://user-images.githubusercontent.com/18077405/37041570-cd627b10-215c-11e8-9c64-b8020149dfc6.png)

See the "shifting"? :wink:

**Comment by No1illuminati** [comment]
no1illuminati69@gmail.com

On Mar 6, 2018 09:43, cheercroaker <notifications@github.com> wrote:
Is this a bug report?

Yes.

Have you read the Contributing Guidelines on issues<https://github.com/facebook/Docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues>?

Yes.
I proudly contributed to 2 merged PRs recently—🎉—but for this one I won't be able to directly bring a fix myself as easily (should be easy for a CSS Jedi though), hence this issue.

Environment

Observed on Linux (Linux Mint 18.3 KDE) with Firefox & Chromium browser.
Node 8.9.4 / npm 5.6.0.
Latest (1.0.7) version of Docusaurus at least.

Can also be observed on the Docusaurus public website as well in the docs part (https://docusaurus.io/docs/).

Steps to Reproduce

  1.  Have a running Docusaurus instance (e.g. the vanilla example one)
  2.  Open a browser and go to the docs part
  3.  Minimize browser width to simulate a small smartphone
  4.  Scroll down to the bottom of the page to display the footer
  5.  With the breadcrumb, select the second section of the docs
  6.  Scroll down to the bottom of the page to display the footer
  7.  With the breadcrumb, select the third section of the docs
  8.  Scroll down to the bottom of the page to display the footer

Expected Behavior

At steps 4, 6 and 8, the footer should display links & columns aligned to the left of the page.

Actual Behavior

  *   For the first section of the docs, step 4 is OK.
  *   Starting from the second section of the docs, step 6 is KO (links & columns are shifted to the right).
  *   For the third section of the docs, step 8 is KO (links & columns are even more shifted to the right).

Seems that after third section, footer links & columns are still "KO" in this sense but are "as shifted as the third section's footer")

Reproducible Demo

One can directly see the the phenomenon by going to these URLs for steps 2, 5 and 7:

  *   step 2<https://docusaurus.io/docs/en/installation.html>
  *   step 5<https://docusaurus.io/docs/en/site-preparation.html>
  *   step 7<https://docusaurus.io/docs/en/site-creation.html>

Or set up the example project and see it locally:

  *   step 4:
[01-docusaurusfirstsectionfooter]<https://user-images.githubusercontent.com/18077405/37041493-a65e47ce-215c-11e8-9b9f-dc851b50f380.png>

  *   step 5:
[02-docusaurussectionselection]<https://user-images.githubusercontent.com/18077405/37041533-b9e6fe58-215c-11e8-81ce-6888cf929f7a.png>

  *   step 6:
[03-docusaurussecondsectionfooter]<https://user-images.githubusercontent.com/18077405/37041560-c874a628-215c-11e8-9644-1bccdf15d30e.png>

  *   step 8
[04-docusaurusthirdsectionfooter]<https://user-images.githubusercontent.com/18077405/37041570-cd627b10-215c-11e8-9c64-b8020149dfc6.png>

See the "shifting"? 😉

**Comment by ajomadlabs** [comment]
Can I to take up this issue

**Comment by JoelMarcey** [comment]
@ajomadlabs Would love a PR for this. Thank you!
