### ISSUE TITLE
Embed React components in docs markdown?

### ISSUE THREAD

**Issue by JoelMarcey** [facebook/Docusaurus#489]
```
# MyTite
Hello

## MySubtitle
Hello

<react>
    <MyComponent prop1={} prop2={}/>
</react>
```

### Is this a bug report?

No.

### Have you read the [Contributing Guidelines on issues]

Yes

### Environment

N/A

### Steps to Reproduce

N/A

### Expected Behavior

N/A

### Actual Behavior

N/A

### Reproducible Demo

N/A

**Comment by Happy-Ferret** [comment]
Related: https://github.com/andreypopp/reactdown

**Comment by Happy-Ferret** [comment]
FYI.

Here's what a quick hack (static React Styleguidist build with custom template, the ``.html`` page moved to ``/pages`` and the ``.js`` files moved to ``/static/js``) looks like.

Everything but the code editor works right off the bat. The editor isn't properly loaded because the ``require`` inside the bundle file is wrong still.

![styleguidist](https://user-images.githubusercontent.com/1962554/37519988-98d9de9e-291b-11e8-8593-6add376aaa80.PNG)

Not sure if that would be an option or if React Styleguidist is too heavy a dependency.

It does add some niceties, like the aforementioned editor (provided I can get it to work).

**Comment by Happy-Ferret** [comment]
Live example:

https://anima-os.github.io/dev-corner/STK

**Comment by JoelMarcey** [comment]
@Happy-Ferret Cool! So if we integrate ReactDown, we could get this going, you think?

**Comment by Happy-Ferret** [comment]
Not sure about ReactDown. I was using StyleGuidist for my little PoC.
I have no experience with ReactDown. Only found out about it and thought it might be an option, too.

ReactDown is static though, from what I can gather. No live editing capabilities.

**Comment by gaui** [comment]
Would love to see MDX support like in [Docz](https://www.docz.site)

**Comment by endiliey** [comment]
Maybe in the future 😊 

![mdx-docusaurus](https://user-images.githubusercontent.com/17883920/48927422-baf60280-ef10-11e8-9e8f-b38b0a22d138.gif)
