### ISSUE TITLE
🐛  Prerendering fails when dependency includes `new URL('empty.js', import.meta.url);`

### ISSUE THREAD

**Issue by captbaritone** [facebook/docusaurus#4922]
## 🚀 Feature:

Some mechanism to avoid loading modules which are incompatible with prerendering

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## Motivation

I'm working on adding a "playground" page to the https://relay.dev docs, and that requires pulling in a Wasm module generated by wasm-pack. This module is incompatible with prerendering in multiple ways:

* References globals which are only available on Web.
* References import.meta.url.

I tried making this module import a lazy import (using `import(moduleName)`) and conditionally only importing it if `ExecutionEnvironment.canUseDOM`) is true, but it still seems to parse the module and error.

## Pitch

It would be useful if there was some way to conditionally import the module in such a way that it would not be parsed/validated/run when doing prerendering. (Ideally this could be done without forcing the import to become a runtime import).

If that's not feasible, another option would be a way to specify (via config?) that a given route should not be prerendered at all.

**Comment by captbaritone** [comment]
After a bit of digging, I think this might be a dupe of #2494.

**Comment by captbaritone** [comment]
It looks like the solution proposed in #2494 will not work in my case. It looks like the presence of a `require()` or `import()` is enough to trigger the error, even if that import is never actually performed during prerendering.


I suspect some transpilation step is converting `new URL('empty.js', import.meta.url);` into something that references `__filename` and some subsequent validation is erroring on undefined variables, all before the code is even executed.

Here's a minimal repro:

```Javascript
// some-page.js

// Use a variable to avoid triggering dead code elimination.
let temp = false;

// This always-false condition demonstrates that the error triggered even when the code does not execute.
// So `<BrowserOnly />` and friends are insufficient to resolve the bug.
if (temp) {
  require('./dependency.js');
}

export default function App() {
  return null;
}
```

```JavaScript
// dependnecy.js

new URL('empty.js', import.meta.url);
```

```JavaScript
// empty.js

// This file intentionally left blank
```

This results in the following error:

```
ReferenceError: __filename is not defined
error building locale=en
Error: Failed to compile with errors.
    at [...redacted...]Relay/oss/__github__/website/node_modules/@docusaurus/core/lib/webpack/utils.js:198:24
    at [...redacted...]Relay/oss/__github__/website/node_modules/webpack/lib/MultiCompiler.js:554:14
    at processQueueWorker ([...redacted...]Relay/oss/__github__/website/node_modules/webpack/lib/MultiCompiler.js:492:6)
    at processTicksAndRejections (internal/process/task_queues.js:76:11)
```

**Comment by slorber** [comment]
Will take a look tomorrow.

Can you tell me which error you had exactly?

Can you show me a successful integration of your playground in another
React App that I could try to port to Docusaurus?

Webpack 5 definitively process new URL() as part of its new asset system


Le lun. 7 juin 2021 à 22:10, Jordan Eldredge ***@***.***> a
écrit :

**Comment by captbaritone** [comment]
@slorber Thanks for looking! I'm guessing we had a race condition with our messages. My most recent comment gives a minimal repro (which has no dependency on our playground at all) and the error message.

Happy to provide more details if needed just let me know.

**Comment by slorber** [comment]
@captbaritone I really have a hard time understanding what you are trying to do:
- why is empty.js empty? I have no idea what's the purpose of this empty file
- why you need dependency.js? Why can't you use new URL in the page directly
- where are the mentioned files supposed to be located exactly?

> My most recent comment gives a minimal repro (which has no dependency on our playground at all) and the error message.

It would really help if you provide a real repo, or at least a CodeSandbox based on new.docusaurus.io

> It looks like the presence of a require() or import() is enough to trigger the error, even if that import is never actually performed during prerendering.

If there's a require() call is present but not run, Webpack/babel will still have to handle it otherwise the final file could contain modern syntax.

**Comment by captbaritone** [comment]
Thanks for taking a look. Sorry it's difficult to pin down.

`empty.js` needs to exist, but its contents are not important. If you don't supply an import path, Webpack won't interpret it as a dynamic import and thus the problematic transformation won't be applied. If you supply a path that is invalid you will get an error about not being able to locate the module, which obscures the error I'm reporting. So we need to point to a file that exits, but its contents are irrelevant (which is why I left it blank).

`dependnecy.js` is a third party module which I don't have easy control over. In practice we do own the module, but it's generated by [`wasm-pack`](https://rustwasm.github.io/wasm-pack/), so we don't have much control over its syntax.

---

## Here's a very simple way to reproduce:

Take any working docusarus site (version `2.0.0-beta.0`) and add the line `new URL('../empty.js', import.meta.url);` to one of its pages (ensuring `empty.js` points to a file that exists).

This will cause the error `ReferenceError: __filename is not defined` when prerendering (`yarn build`), but will work fine in the client (`yarn start`).

The fact that this code causes an build error is problematic because:

1. In our use case, that line exists in an NPM module that we can't easily change.
2. There's no way to have prerendering skip trying to prerender the page which includes it.

If that syntax can be made to work in pre rendering mode that would be ideal. If not, some workaround which allows us to avoid loading/transforming that module during prerendering would also help us work around the issue.

**Comment by slorber** [comment]
Sorry but I still can't understand where the files should be created
exactly.

A repro would really help, you can also open a PR modifying the docusaurus
site itself.

At least please provide absolute paths, not just the filenames.

Le mer. 9 juin 2021 à 22:38, Jordan Eldredge ***@***.***> a
écrit :

**Comment by captbaritone** [comment]
Sure.

Check out this repo: https://github.com/captbaritone/docusaurus-issues-4922

```
yarn
yarn build
```

That should trigger the error:

```
╭─[15:19]: jeldredge at jeldredge-mbp in ~/projects/repro on master*
╰─➤ yarn build
Using globally installed version of Yarn
yarn run v1.12.1
warning ../../package.json: No license field
$ docusaurus build

[en] Creating an optimized production build...

✔ Client


✖ Server
  Compiled with some errors in 16.78s



ReferenceError: __filename is not defined
error building locale=en
Error: Failed to compile with errors.
    at /Users/jeldredge/projects/repro/node_modules/@docusaurus/core/lib/webpack/utils.js:198:24
    at /Users/jeldredge/projects/repro/node_modules/webpack/lib/MultiCompiler.js:554:14
    at processQueueWorker (/Users/jeldredge/projects/repro/node_modules/webpack/lib/MultiCompiler.js:492:6)
    at processTicksAndRejections (node:internal/process/task_queues:76:11)

● Client █████████████████████████ cache (99%) shutdown IdleFileCachePlugin
 stored

✖ Server


error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Here's the commit that adds the code which causes it to crash: https://github.com/captbaritone/docusaurus-issues-4922/commit/4de256c89c564151083e6e5060bad9fbb02546b4

**Comment by captbaritone** [comment]
Ping @slorber in case this fell through the cracks.

**Comment by slorber** [comment]
So what I understand is that when you use:

```
new URL('../empty.js', import.meta.url)
```

Webpack will compile the app and output a main bundle with:

```js
__webpack_require__.b = require("url").pathToFileURL(__filename);
```

And our static site generator webpack plugin fails because __filename is not provided as globals (and it's the only usage).

I'm able to build successfully by tweaking a bit the webpack plugin locally (we have a fork already to we can patch it), just not sure about the potential side-effects.

---

I'm not even sure to understand why you want to use `new URL()` in the first place, but I think Webpack only starts to process those since Webpack 5

Isn't there a simpler way to integrate your playground in Docusaurus, not using it? Like put `static/empty.js` and just insert `/empty.js` in your page?

Is this issue really about Docusaurus? 
Have you been able to integrate this player in any other webpack-based app that could serve as an example? 
Is there an integration PR on relay repo that I can look at?

If you remove the usage of `new URL` and use `BrowserOnly` + a lazy require ( https://github.com/facebook/docusaurus/issues/2494#issuecomment-809440406) I don't see why it wouldn't work.

**Comment by slorber** [comment]
If you really need to use `new URL()`, you can try to unlock yourself from these build failures by doing this local modification:

`/node_modules/@docusaurus/core/lib/webpack/server.js`

```diff
            new static_site_generator_webpack_plugin_1.default({
                entry: 'main',
                locals: {
                    baseUrl,
                    generatedFilesDir,
                    routesLocation,
                    headTags,
                    preBodyTags,
                    postBodyTags,
                    onLinksCollected,
                    ssrTemplate,
                    noIndex,
                },
                paths: ssgPaths,
+                globals: {__filename: "main.js"}
            }),
```

Not 100% sure "main.js" is the correct value to set, but I suspect any value could do the job eventually

**Comment by captbaritone** [comment]
The instance of `new URL` is coming from a dependency which is generated using [wasm-pack](https://rustwasm.github.io/wasm-pack/) which generates a Wasm module and the JS glue code needed to run it. So changing away from `new URL` would require either convincing `wasm-pack` to emit different code or somehow have the dependency apply a patch on top of the code that `wasm-pack` generates.

An unconfigured version of Webpack 5 seems to build it just fine. I've build a minimal example which you can try here:

https://github.com/captbaritone/relay-compiler-playground-example

It uses Webpack (without any config) to build a page which includes our dependency `relay-compiler-playground` (which contains the use of `new URL()`) and seems to build and run fine.

The readme contains simple instructions to build and view it.

**Comment by slorber** [comment]
> An unconfigured version of Webpack 5 seems to build it just fine. I've build a minimal example which you can try here:

That's expected, the expected error does not come from React but from this Webpack plugin we use (not maintained anymore...): https://github.com/markdalgleish/static-site-generator-webpack-plugin

--- 

Have you tried to use my suggestion here?:

https://github.com/facebook/docusaurus/issues/4922#issuecomment-861710549

If I were to provide a fix in Docusaurus, that would basically to add this line. 

So the idea for me is that you modify your local docusaurus to add this line manually and see if you get unlocked and are able to integrate with your wasm playground. If it is successful I'd integrate this change in Docusaurus, otherwise we'd have to look for another solution. 

I'd prefer to avoid merging code in Docusaurus just to "give it a try", as I can't really tell for sure that it will actually solve your problem if I can't run your code/playground integration on my computer.

If you have a fork/branch on relay with your integration WIP, I can also try to run it and see if it fixes the problem.

**Comment by slorber** [comment]
@captbaritone I've made the required change.

Also made a POC, you can use this PR for inspiration: https://github.com/facebook/docusaurus/pull/5062

https://deploy-preview-5062--docusaurus-2.netlify.app/relayPlayground

![image](https://user-images.githubusercontent.com/749374/123406427-3299db80-d5ab-11eb-8c61-76579b7bdff0.png)


This works fine in dev/prod mode.

This is a quick-and-dirty integration, just a proof it can work. 

React-Live editor is nice to have syntax highlighting (transparent overlay over a textarea field)

Noticed that the `result.Ok` value does not look like a json AST but rather a plain string, maybe it's an error in your lib?

**Comment by slorber** [comment]
Note: you can use a canary release right now to test this on Relay site: https://docusaurus.io/community/canary

**Comment by captbaritone** [comment]
Thank you for this @slorber! (sorry for the very slow reply). I was able to get it working using this approach! I very much appreciate you taking the time to work with me to unravel this.

**Comment by slorber** [comment]
👍  that looks great 🤪  https://relay.dev/compiler-playground/
