### ISSUE TITLE
The text in previous/next buttons has changed 

### ISSUE THREAD

**Issue by Labirintami** [facebook/docusaurus#4929]
### Prerequisites

- [ X ] I'm using the latest version of Docusaurus.
- [ X ] I have tried the `npm run clear` or `yarn clear` command.
- [ X ] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.

### Description

Hi 

We updated the documentation to version 2.0.0-beta.ce0764033 and noticed that the text in the previous/next buttons has changed. 

When we used version 2.0.0-beta.1decd6f80, the text from the **sidebar_label** field was put into the button. 

And in version 2.0.0-beta.ce0764033 the text is substituted from the **title** field. 

We use the **title** field for search engine optimization.  

This text is good for search engine robots, but not for buttons previous/next.

https://www.screencast.com/t/Q9bpkEv1n

## Your Environment

- Public source code: https://github.com/DHTMLX/docs-suite/
- Public site URL: https://docs.dhtmlx.com/suita/chart/api/chart_eachseries_method
- Docusaurus version used: 2.0.0-beta.ce0764033

**Comment by lex111** [comment]
Hmm, this is actually the expected behavior. Frontmatter title is used by default for page titles, sidebar labels, and pagination buttons.

> When we used version 2.0.0-beta.1decd6f80, the text from the sidebar_label field was put into the button.

And this was bug that we fixed (see https://github.com/facebook/docusaurus/issues/4852).

@slorber maybe we need add ability to specify only meta title from new field in the frontmatter?

**Comment by slorber** [comment]
Thanks @Labirintami 

I think this is not 100% correct, we never used `sidebar_label` for pagination button.

Instead, we were using the title of your markdown content `# eachSeries()` for the buttons. But in practice this was not a great choice, because your markdown title may contain markdown syntax (for example, yu could use an inline code block for "# `eachSeries()`" instead of just a regular string) and this syntax should not appear in the button.

Think of the frontMatter.title as the pure string/text version, and the `# xyz` title as a MD title.
We can only use the text version of the title in meta title, pagination, sidebar etc, and we should avoid showing markdown syntax in such places.

If you really want a pagination label that is different from the frontMatter.title, I suggest we introduce a `pagination_label` frontmatter for that purpose.

This has already been discussed here: https://github.com/facebook/docusaurus/issues/4895

Do you think it's a good solution to solve your problem? I think it is because it gives clear expectations on how the doc label should be customized in each place, instead of having one 2 values that control 2+ places with unclear rules

**Comment by slorber** [comment]
> @slorber maybe we need add ability to specify only meta title from new field in the frontmatter?

In my opinion `frontMatter.title` already has this role of page meta title (and is a good fallback value for the md doc h1), so I'd rather introduce a `pagination_label` rather than a `meta_title`

**Comment by Labirintami** [comment]
Hi, @slorber!

Thank you for such a comprehensive and positive response!

We discussed your suggestion about `pagination_label` with the team. We like it.

It's a little intimidating to add `pagination_label` to 1500 pages of documentation, but I think we can handle it.

**Comment by hkogge** [comment]
Just fyi, the documentation for [`plugin-content-docs`](https://docusaurus.io/docs/api/plugins/@docusaurus/plugin-content-docs#markdown-frontmatter) (which comes with the default preset irc) says:

> `sidebar_label`: The text shown in the document sidebar **and in the next/previous button for this document**. If this field is not present, the document's sidebar_label will default to its title

Reading this, I would have expected `sidebar_label` being used for the pagination to be a feature instead of a bug. :)

**Comment by slorber** [comment]
Thanks @hkogge 

I guess it makes sense to restore that behavior and make sure `sidebar_label` is used in priority for the next/previous buttons then, particularly because order/navigation of the docs is created thanks to the sidebars file.

Should we still add `pagination_label`?

**Comment by hkogge** [comment]
> I guess it makes sense to restore that behavior and make sure `sidebar_label` is used in priority for the next/previous buttons then, particularly because order/navigation of the docs is created thanks to the sidebars file.
> 
> Should we still add `pagination_label` to ensure more flexibility?

Personally, I think it makes perfect sense to use `sidebar_label` for the next/previous buttons (as documented), for the exact reason you mentioned: the buttons are directly related to the sidebar anyway.

Then it wouldn't be needed to have an additional `pagination_label`, imo.

**Comment by slorber** [comment]
Thanks, let's not introduce any new frontmatter then, and do what our own doc says

https://github.com/facebook/docusaurus/pull/4970

please test it using the `@canary` dist tag

**Comment by slorber** [comment]
Finally, `pagination_label` will be added in beta.1 with https://github.com/facebook/docusaurus/pull/4982

**Comment by Labirintami** [comment]
Thank you so much!
