### ISSUE TITLE
More subtle color mode implementation options

### ISSUE THREAD

**Issue by jwitz** [facebook/docusaurus#4990]
## 🚀 Feature

It would be nice to have alternative implementation options for the color mode switch, configurable via `themeConfig`. Specifically, I was thinking:

- A switch in the footer
- A keyboard command

I tried looking for an easy solution (e.g. adding a color switch as an `item`) and haven't found one yet, apologies if there's already something out there for this!

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yep!

## Motivation

The default implementation of the color mode switch takes up a lot of valuable real estate in the navbar, especially for something that will only ever be toggled once by most users.

## Pitch

I'm not sure what would be the best implementation for a footer-based color mode switch. The simplest option seems to be an on/off configuration in `colormode` that defaults to `navbar` and can be set to `footer`. When set to `footer`, the switch would appear in the bottom righthand corner of every page. 

For the keyboard command, two values would need to be created: One to enable the keyboard shortcut, and one to override the default shortcut combination.

**Comment by slorber** [comment]
We support swizzling components so that you can implement all that yourself, and I don't think there are a lot of users looking for this being implemented.

I'd suggest to:
- open a canny feature request (https://docusaurus.io/feedback/) so that we can track if there is a real need for that feature, or if it's only you needing this
- implement this by yourself by swizzling on your own site, so that we can understand better exactly what you are looking for to be implemented inside Docusaurus

I'd rather see this in action on a real Docusaurus site, with a proper design, before even thinking porting it to Docusaurus core. If it's not possible/complicated to build it, I'm willing to provide support, try to make it possible and unlock you.

For now, I prefer to close this feature request.

Note we'll likely implement better support for keyboard shortcuts someday, as a more general issue, and toggling the theme can be one of those shortcuts: https://github.com/facebook/docusaurus/issues/3020

If we enable a toggle in footer I'd also see this as a more general feature, allowing to use custom footer item types maybe.
