### ISSUE TITLE
Unable to get static asset with i18n enabled. 

### ISSUE THREAD

**Issue by yeqingyan** [facebook/docusaurus#5019]
### Description
I enabled i18n, run `npm run start -- --locale zh-CN` and find out all static images in my page got broken. Looks at the source code I found that static image url `http://localhost:3000/img/red.svg` is no longer working. The image is served through `http://localhost:3000/zh-CN/img/red.svg` instead. Is it a bug or I missed config something? thanks!

**Comment by slorber** [comment]
This is on purpose, i18n is built by prepending a baseurl prefix to all URLs in dev (except the default locale).

The new "homepage" of your site is now `/zh-CN/`, not `/`, and images and all static assets are served from `/zh-CN/...` too.

Note if you only want a site in Chinese, you can use `{ i18n: {defaultLocale: "zh-CN"} }`. This will make sure that Chinese is served from `/` (in dev + prod). We'll add more options in the future so that you can specify the exact path you want on a per-locale basis.

In general, it is recommended to make your site not sensitive to baseurl changes (ie served from / or a subpath, it shouldn't break). You can require/import static assets instead, or use the [useBaseUrl](https://docusaurus.io/docs/docusaurus-core#usebaseurl) utils to prefix your paths with that baseurl. 

If you are translating your site to another locale, make sure it works under a baseurl too.

Note that images/svg may contain text, and we allow localizing images/svg:
- http://localhost:3000/img/red.svg may be the English svg
- http://localhost:3000/zh-CN/img/red.svg may be the Chinese svg
It may not make sense for your use-case, but it may make sense for certain static assets
