### ISSUE TITLE
".." maps to the parent path of baseUrl during development, but fails during build

### ISSUE THREAD

**Issue by pranabdas** [facebook/docusaurus#5024]
### Prerequisites
- [x] I'm using the latest version of Docusaurus.
- [x] I have tried the `npm run clear` or `yarn clear` command.
- [x] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.

### Description
My `docusaurus.config.js`: 
```js
module.exports = {
  ...
  url: "https://www.example.com",
  baseUrl: "/projetX/",
  ...
  themeConfig : {
    ...
    navbar: {
      items: [
        {
           to: "../",
           label: "Home",
           ...
        },
        ...
      ]
    },
    ...
  }
}
```

While developing, the project is served at `localhost:3000/projectX/`, the **Home** nab item maps to parent directory i.e., `localhost:3000`, but it fails while building the site (Error: Docusaurus found broken links).

I am not sure if it should be allowed refer to the parent directory of baseUrl, but perhaps it should be consistent for both development and build.

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

**Comment by slorber** [comment]
Please be much more exhaustive in your bug report, including versions used, etc, we have a template to fill on purpose.

> Error: Docusaurus found broken links

The broken link error message has **much more** details than that, please read the full message to understand your issue, and post it there in its entirety.

A repro or any way to see your problem live would also be useful, because in current state it seems hard to replicate.

I don't understand why you serve the project under baseurl `/projectX/` and want to link to `../` (ie go outside the Docusaurus site?), is this on purpose? What is hosted at the root of your domain? 

In general, you should absolutely avoid using relative links in the navbar. Remember that navbar is rendered on all your pages, and relative links are resolved according to current url, so on `/projectX/` it will resolve to `/`, but on `/projectX/docs/myDoc` it will resolve to `/projectX/docs/`, and this is very unlikely what you want. You'd rather have only absolute links in the navbar, because you generally want to target the same page, no matter where you are on your docusaurus site.

The broken link checker is a build-only feature. Unfortunately we can't technically make it work in dev too, it requires rendering all your pages to be able to capture broken links.

Closing because it is unlikely to be a bug.
