### ISSUE TITLE
Links to other docs pages are broken in github pages due to additional /

### ISSUE THREAD

**Issue by F43nd1r** [facebook/docusaurus#5026]
### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [X] I have tried creating a repro with https://new.docusaurus.io
- [X] I have read the console error message carefully (if applicable)

### Description

Deep links don't work correctly when deployed to github pages. Example:
[this link](https://f43nd1r.github.io/docusaurus-link-issue-reproducer/docs/tutorial-basics/create-a-page) points to `.../create-a-page`, but is redirected to `.../create-a-page/`. Displaying the page works, but clicking a link to another page (here `Congratulations`), loads `.../create-a-page/congratulations` instead of the correct `.../congratulations`

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## Steps to reproduce

Use https://new.docusaurus.io to create a CodeSandbox reproducible demo of the bug.

(Write your steps here:)

1. Clone Demo
1. Add a link to a doc page (2) to a docs page (1)
1. Deploy to Github Pages
1. Access page (1) via direct link
2. Click on the added link
3. Observe `Page Not Found`

## Expected behavior

Links to other pages behave correctly when the url has an additional slash appended.

## Actual behavior

Links to other pages don't work when the url has an additional slash appended.

## Your environment

- Public source code: https://github.com/F43nd1r/docusaurus-link-issue-reproducer
- Public site URL: https://f43nd1r.github.io/docusaurus-link-issue-reproducer/
- Docusaurus version used: 2.0.0-beta.1
- Environment name and version (e.g. Chrome 78.0.3904.108, Node.js 10.17.0): Github Pages
- Operating system and version (e.g. Ubuntu 20.04.2 LTS):

## Reproducible demo

https://github.com/F43nd1r/docusaurus-link-issue-reproducer

Go to https://f43nd1r.github.io/docusaurus-link-issue-reproducer/, click the link and then click on the congratulations link in the page.

**Comment by slorber** [comment]
That's funny because this issue is solved by the brand new beta.1 `trailingSlash` option.

https://github.com/facebook/docusaurus/issues/3372
https://github.com/facebook/docusaurus/pull/4908

For GH pages we now recommend using `trailingSlash: false` as it will emit `/x.html` instead of `/x/index.html` and prevent GH pages to add that trailing slash, breaking relative links resolution.

See also https://github.com/slorber/trailing-slash-guide to understand how GH pages behave.

https://docusaurus.io/docs/deployment#trailing-slashes

As this is a new option, please let me know if `false` is a good value for GH pages. If it is a good setting fr GH pages, we may add a warning on `docusaurus deploy` so that people always use `trailingSlash: false` with GH pages. Your feedback is important so let me know.

**Comment by F43nd1r** [comment]
> As this is a new option, please let me know if false is a good value for GH pages.

Yes.

> If it is a good setting fr GH pages, we may add a warning on docusaurus deploy so that people always use trailingSlash: false with GH pages.

That would be nice, although I'm deploying with a dedicated github action which doesn't use `deploy` (https://github.com/ACRA/acra/blob/master/.github/workflows/deploy-docs.yml#L25)

**Comment by slorber** [comment]
Thanks for the feedback.

For GH action deploy then we can't do anything apart from documenting it.

**Comment by F43nd1r** [comment]
> For GH action deploy then we can't do anything apart from documenting it.

Yeah, makes sense. Was just mentioning to say it won't affect me personally.
Thank you for the tip and replies :+1:
