### ISSUE TITLE
Netlify CMS

### ISSUE THREAD

**Issue by kaustubhk24** [facebook/docusaurus#5090]
## 📚 Documentation

Hello, I'm setting up v 2 for my app's documentation but I want to use netlify cms, I can't find related docs for cms, I tried myself but its working only for the blog, please help me

Also if we don't have netlify cms supported now, when we can expect ? 

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

yes

**Comment by slorber** [comment]
@kaustubhk24 Netlify CMS is a git-based tool, it can probably be configured for Docusaurus usage already and we don't provide anything to integrate with it.

There are a lot of CMS and we are a very small team, we can't have official support for all.
For now, it is your responsibility to figure out how to create the NetlifyCMS config with Docusaurus. 
If you come up with a good solution, any contribution in the form of a community plugin is more than welcome

By googling I was able to find this, maybe it will be helpful: https://github.com/Alexa-Green/docusaurus-netlify-cms/blob/master/static/admin/config.yml

Forestry is another popular Git-based CMS option, and I know there is a started: https://github.com/DirtyF/docusaurus-forestry-starter

---

In general, we'll try to improve how to reduce the contribution friction that users currently encounter when using Docusaurus, using CMSs (git-based or not), or other tooling (we are exploring StackBlitz).

It's unlikely we'll have official support and custom code/plugins for the CMSes, but at least we should provide you the right hooks to build such integrations yourself.

Closing since this is more a feature request suitable for our Canny board

**Comment by kaustubhk24** [comment]
Hello @slorber  Thanks for your guidance, I got a way to do this, I would like to share that, So what is process?

**Comment by slorber** [comment]
Great

The goal of our documentation is not to be exhaustive about all the CMS and hosting solutions and whatever tool can be used with Docusaurus. If you add a doc page and then don't update it over time, it becomes a burden for us maintainers.

If you were able to write such integration and it works fine, the best is to build a plugin, write a blog post, or anything that you can share with the community. If we accept it in the main repo, this means we accept to maintain it ourselves, which we probably don't want due to our very small team
