### ISSUE TITLE
Inline code style

### ISSUE THREAD

**Issue by Mihonarium** [facebook/docusaurus#5103]
### Description

In the latest Docusaurus versions, the inline code's background and borders became different from multiline code blocks. It doesn't fit the overall Docusaurus style.

Compare e.g. `npx @docusaurus/init@latest init my-website classic` to `http://localhost:300` block on https://docusaurus.io/docs/next#fast-track.

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes.

## Expected behavior

I expect the inline code to fit the overall Docusaurus styling and probably look like they looked in previous versions of Docusaurus or at least like version tags on top of the pages.

## Actual behavior

The inline code has a different background and borders of a distinctive color from the multiline code blocks.

**Comment by Mihonarium** [comment]
I'd also like to note that even GitHub changed the inline code styling with the latest themes, so the inline code doesn't have distinctive borders.
![image](https://user-images.githubusercontent.com/24436954/123992613-70946680-d9d4-11eb-8b6c-3f4ec0b79689.png)
![image](https://user-images.githubusercontent.com/24436954/123992690-830ea000-d9d4-11eb-8156-6211e0222be5.png)

**Comment by slorber** [comment]
Please include screenshot so that we can compare more easily.

> became different

Change is expected to happen, but you can override CSS to revert to previous behavior if you prefer it.

I honestly don't have a strong feeling about what is actually better. 

It now also looks more coherent with inline code blocks in admonitions

![image](https://user-images.githubusercontent.com/749374/123996278-72a7f680-d9cf-11eb-894a-0c497c4e913b.png)


@lex111 was changing the inline code blocks outside admonition made on purpose?

**Comment by slorber** [comment]
Prod: https://docusaurus.io/docs/installation

![image](https://user-images.githubusercontent.com/749374/123998149-7f2d4e80-d9d1-11eb-9ac3-2989eb7bb2c6.png)

---

Alpha.70: https://deploy-preview-3933--docusaurus-2.netlify.app/classic/docs/installation

![image](https://user-images.githubusercontent.com/749374/123998106-72105f80-d9d1-11eb-8f65-0884f84107a0.png)

---

> It makes some sense inside admonitions, but not outside.

This behavior was changed at least a few months ago and looks perfectly fine to me. 

It is a matter of taste and we won't be able to please everyone, and so far you are the only one complaining about this change, that you can revert with custom CSS anyway, so I'm going to close.

**Comment by lex111** [comment]
I agree that there should be consistency in the styles of different types of code blocks (inline or multiline). However, we should keep in mind that multiline code blocks have syntax highlighting, so that means depending on selected Prism theme by the end-user, the background of multiline code blocks most likely be different from inline code background specified in default styles (i.e. Infima).
 
Perhaps in this case it makes sense to set the background for inline code the same as in the Prism's GitHub theme. The new color is even better fit for current admonitions. @slorber WDYT?

| Before   | After    |
| -------- | -------- |
| ![image](https://user-images.githubusercontent.com/4408379/124004241-7ee87f80-d9e0-11eb-97dc-5c56886e1de2.png) | ![image](https://user-images.githubusercontent.com/4408379/124004052-4cd71d80-d9e0-11eb-993d-1a58d5d79a8e.png) |

**Comment by slorber** [comment]
Ok why not
