### ISSUE TITLE
Documentation is not updated to the current version (2.0.0-alpha.64 to 2.0.0-beta.3)

### ISSUE THREAD

**Issue by Labirintami** [facebook/docusaurus#5107]
## 🐛 Bug Report

Hello! 

We have documentation of the version:
  "@docusaurus/core": "2.0.0-alpha.64",
  "@docusaurus/preset-classic": "2.0.0-alpha.64"

https://github.com/DHTMLX/docs-richtext/blob/master/package.json
https://docs.dhtmlx.com/richtext/

We decided to update it to use 'trailingSlash: true'.

We wrote the command `yarn upgrade @docusaurus/core@latest @docusaurus/preset-classic@latest`

The documentation has been updated to: 
    "@docusaurus/core": "^2.0.0-beta.3",
    "@docusaurus/preset-classic": "^2.0.0-beta.3",

We wrote the command 'npx docusaurus --version' and made sure that the version 2.0.0-beta.3.

The documentation does not start: https://prnt.sc/17ptpgx and https://prnt.sc/17ptuh4

Can you please tell me how we can upgrade to the latest version?

**Comment by Josh-Cena** [comment]
You should have run `yarn install` as well, and then re-deploy your site

**Comment by slorber** [comment]
You have likely swizzled components.

It is now your responsibility to maintain them over time and ensure that your swizzled components stay up-to-date with theme evolutions of Docusaurus.

In particular, I believe you may have swizzled the DocItem component or something related to the doc page. Site fails because you need to fix the swizzled component.

The best solution is likely to delete your swizzled component, re-swizzle it, and then report the changes you made to the new version.

This is not something that we can provide support for, as explained in the Swizzle command breaking changes on theme components are expected:

![image](https://user-images.githubusercontent.com/749374/124094858-741e0100-da59-11eb-8083-17762804b50f.png)

**Comment by Labirintami** [comment]
Thanks for the tip! We redid the way we connected the comments and then we were able to update the documentation.
