### ISSUE TITLE
RFC: placeholder components after title, after content, after pagination, etc.

### ISSUE THREAD

**Issue by Josh-Cena** [facebook/docusaurus#5251]
## 🚀 Feature

**Update on how the API would like after some discussion:**

The `DocItem` component right now is something like:

```jsx
<div>
  <DocVersionBanner />
  <div>
    <article>
      <span>
        Version: {versionMetadata.label}
      </span>
      <TOCCollapsible />
      <div>
        <MainHeading>{title}</MainHeading>
        <DocContent />
      </div>

      <footer>
        <div>
          <EditThisPage />
        </div>
        <div>
          <LastUpdated />
        </div>
      </footer>
    </article>
    <DocPaginator />
  </div>
</div>
```

We can have additional placeholder components at some "anchor points", meant to be swizzled:

```diff
  <div>
    <DocVersionBanner />
+   <AfterVersionBanner doc={DocContent} />
    <div>
      <article>
        <span>
          Version: {versionMetadata.label}
        </span>
+       <AfterVersionBadge doc={DocContent} />
        <TOCCollapsible />
        <div>
          <MainHeading>{title}</MainHeading>
+         <AfterHeading doc={DocContent} />
          <DocContent />
+         <AfterMainContent doc={DocContent} />
        </div>

        <footer>
          <div>
            <EditThisPage />
+           <AfterEdit doc={DocContent} />
          </div>
          <div>
            <LastUpdated />
+           <AfterLastUpdated doc={DocContent} />
          </div>
        </footer>
      </article>
      <DocPaginator />
+     <AfterPaginator doc={DocContent} />
    </div>
  </div>
```

These anchor components are initially empty:

```jsx
export default function AfterHeading({doc}) {
  return null;
}
```

But users can swizzle these elements and add custom logic. All the doc's data is provided through props, including front matter, metadata, title, content, etc., from which the user can pick and display.

```jsx
export default function AfterHeading({doc}) {
  const {frontMatter} = doc;
  const {date, link} = frontMatter;
  return (
    <div className="alert alert--info margin-bottom--md" role="contentinfo">
      First published on <b>{date.toLocaleDateString()}</b>.
      <Link to={link}>Source link</Link>
    </div>
  );
}
```

Some use-cases:

- A metadata list displaying author, source link, publication date, etc., after the heading;
- GitHub status badges after the heading;
- A custom feedback widget at the bottom, just like the discussion in #4808;
- "Related links" at the bottom...

Benefits:

- Reduced code duplication: the same component doesn't have to be injected for every Markdown file, but is handled during doc loading;
- Reduced user burden: users don't have to swizzle the entire `DocItem` just to add one custom component, resulting in additional burden to keep it up-to-date in the future;
- Easy extensibility: this conforms to Docusaurus's [goal](https://docusaurus.io/blog/2021/05/12/announcing-docusaurus-two-beta#what-are-the-goals-of-the-beta) of making themes easily extended, since the user is only interacting with a very lightweight API;
- Not opinionated: all the logic is user-provided, and the Docusaurus doesn't provide any implementation details. This single generic API can satisfy a range of different needs.

---

<details>

<summary>Original proposal</summary>

Users may want a banner at the beginning of every documentation page containing some metadata like:

- Original source link, if this is an imported content;
- Author & Publish date (which may be different from the git info);
- Tags / thumbnail image.

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

### Has this been requested on [Canny](https://docusaurus.io/feedback)?

No

## Motivation

Additional front matter should not be eaten up by the renderer but should find a way to be displayed. This frees the user from copy & pasting the same component (or importing them) to every page.

## API Design

1. We will provide a `metadataBanner` option in `plugin-docs` (default is `false`). When set to `true`, a `@theme/docMetadataBanner` component will be injected at the beginning of every file—similar to the version banner. The `metadataBanner` option will also accept a string path to a user-defined component, or the user can choose to swizzle `@theme/docMetadataBanner` instead.
2. The `@theme/docMetadataBanner` component will receive `content` as props (typing similar to `DocItem.Props`) from which `metadata`, `frontMatter`, etc., can be extracted. 
3. The front matter that's already been picked up will be pruned, like:

```jsx
const {title, sidebar_label, id, /* ..., */ ...customFrontMatter} = frontMatter;
```

4. The default rendering method can be an info box:

```jsx
<div className="alert alert--info margin-bottom--md" role="contentinfo">
  <div className="margin-top--md">
    <ul>
      {
        Object.keys(customFrontMatter).map((key, i) => <li key={i}>{key}: {JSON.stringify(customFrontMatter[key])}</li>)
      }
    </ul>
  </div>
</div>
```

But users can easily customize it to show something they want, since they also know better of what custom front matter they have.

## Have you tried building it?

Did some preliminary work to demonstrate what it would look like:

![image](https://user-images.githubusercontent.com/55398995/127592844-0120d802-b845-4088-bc20-1a4fa72a0ea5.png)

(Note: I used `JSON.stringify()` to force all front matter to strings. In practice, the date may be rendered with `date.toLocaleDateString()`.)

</details>

**Comment by slorber** [comment]
> Additional front matter should not be eaten up by the renderer but should find a way to be displayed. 

This does not make too much sense to me. Some people have additional frontmatter and it's unlikely they'd want it to be displayed, because sometimes this frontmatter comes from a legacy system or is also consumed by another tool. It's hard to automatically guess which frontmatter is a good fit to be displayed.

An idea I have in mind is to have "placeholder slot components" like `<AfterDocTitle>`, meant to be swizzled (empty by default) and filled by your own rendering logic. Those components could receive the frontmatter and other useful doc data and do whatever they want, including displaying a banner.

> Users may want a banner at the beginning of every documentation page containing some metadata like

I find the placeholder system more convenient and generic. People may want to put this banner at the bottom instead of the top and it does not make sense to me to complicate the config with a "bannerPosition" config. `@theme/docMetadataBanner` naming also assumes that you want t render this as a banner, but what if user wants to render that as a ul/li list without a banner design?

So, my general idea is that we should allow users to solve this problem, but in a more generic way, that does not even involve the name "banner" because it assumes too much about what an user would want

**Comment by slorber** [comment]
Another important thing to mention: sometimes the markdown title is inside the MDX content (it may even contain a React component!)

It's not even possible in this case to anways interleave a banner between that title and the rest of the markdown doc because those are not "separated"

**Comment by Josh-Cena** [comment]
Users having legacy front matter is not an issue because they can disable this banner (which is disabled by default anyways).

The placeholder idea sounds cool and works. In this case we would have a `@theme/AfterDocTitle` component:

```jsx
function AfterDocTitle({frontMatter}) {
  return null;
}
```

When the title is set in Markdown, the user can disable the injection of `AfterDocTitle` via front matter (or we can do it automatically when the `title` field is undefined), and then manually insert the component at the desired position. In this case, we are not in a good position to do anything meaningful anyways.

An extra `position` option in the config doesn't complicate things a lot IMO🤔

My main point is that although it's not difficult to introduce the same component on every page (something that I'm currently doing https://github.com/Josh-Cena/Personal-page/blob/master/docs/Digital/1-note1.md), but if it can be handled during doc loading, a lot of duplicated code can be avoided.

**Comment by Josh-Cena** [comment]
In any case, does this sound worthy implementing in Docusaurus? It's better that I send a PR so we can have some solid code to discuss on...

**Comment by slorber** [comment]
> Agreed that the "banner" name carries too much implication about its implementation, but AfterDocTitle also hints its position, which can actually be at the bottom as you suggested. Maybe MetadataDisplay sounds better?

The goal is also to provide placeholder components to be able to set up things at the bottom, like a comment system, a voting system, or whatever. So you'll also have something like `AfterContent` and `AfterEditButton` (with better names of course). My goal is to figure out on all existing docusaurus sites what are the most common customizations that were made before deciding which placeholder components we should create and figure out good names. The goal is to avoid having to swizzle the full DocItem component.

> When the title is set in Markdown, the user can disable the injection of AfterDocTitle via front matter (or we can do it automatically when the title field is undefined), and then manually insert the component at the desired position. In this case, we are not in a good position to do anything meaningful anyway.

When the title is set in markdown, we wouldn't render a `@theme/AfterDocTitle` anyway so it does not make sense to provide an option to disable a behavior that we don't do in the first place. It's also a bit complicated to educate the users about the differences of using title in frontmatter vs in markdown, and those subtilities. For those reasons, I'd rather not introduce a `@theme/AfterDocTitle` because it would be a bit confusing as it would only work in some cases, not all.

> An extra position option in the config doesn't complicate things a lot IMO🤔

The need for a banner that you describe never came up so far, and new APIs are "forever" and always make a tool more complicated than one with less api. I'd rather build first raw primitive apis (even if less convenient) to make something possible and eventually create "shortcuts" for widely used patterns, instead of landing first the "shortcuts" and figure out that only 1 person uses them.

If only you has your use-case, we shouldn't modify Docusaurus to support it until many people also want this to happen. Instead we should allow you to do it yourself with lower-level primitives that are generic enough to be used in other niche use-cases. I agree it's less convenient for you but it's better for Docusaurus in general.

Eventually we can figure out generic ways to make your life easier.

In your position as you may be 100% sure that none of your docs use any md title, you could just create a very simple remark plugin that add the `<DocMetadataBanner frontMatter={frontMatter} />` to all your pages

Regarding the `import DocMetadataBanner from '../../src/components/DocMetadataBanner';` import, it's also possible with MDX to make the `DocMetadataBanner` available by default without importing. It's also something I want to add in a more generic way to Docusaurus, because writing the same imports everywhere is not very convenient and some comps like `@theme/Tabs` should probably be automatically available, so I'll add a generic api to easily register such MDX comps to reduce the MDX imports boilerplate.

> My main point is that although it's not difficult to introduce the same component on every page (something that I'm currently doing https://github.com/Josh-Cena/Personal-page/blob/master/docs/Digital/1-note1.md), a lot of duplicated code can still be avoided by handling it during doc loading.

If only you need this and it's already possible today, we shouldn't add this to Docusaurus. If you can find 5 other people doing this in userland already, maybe it's worth considering adding an opinionated feature for this. 

> In any case, does this sound worthy implementing in Docusaurus? It's better that I send a PR so we can have some solid code to discuss on...

I don't think it's worth it. I understand what you want to do and it's not really something I think we should add to Docusaurus until it's clear there's good traction.

**Comment by Josh-Cena** [comment]
Okay, let's keep the RFC up for now and see if there's more opinions on this.

`AfterContent` and `AfterEditButton` also sound like good ideas btw

**Comment by slorber** [comment]
Going to close, because I believe this is better solved by using `swizzling --wrap` (https://github.com/facebook/docusaurus/issues/5380).

Wrapping a component already allows to provides "before/after" hooks, and we just have to provide better fine-grained splitting of theme components to provide more convenient hooks for people to enhance existing theme components.
It wouldn't require defining explicit placeholders and finding good placeholder names.

Example here: https://github.com/facebook/docusaurus/discussions/5468#discussioncomment-1271232

**Comment by Josh-Cena** [comment]
I was more thinking of injecting components somewhere "between" two sections. But anyways, if we can make the component structure far more granular than it is currently, wrapping will definitely work

**Comment by slorber** [comment]
Yes, if each section is a separate theme component, the need to inject between the 2 sections should be covered :)
