### ISSUE TITLE
Layout shift when in docs sidebar when scroll bar appears

### ISSUE THREAD

**Issue by Josh-Cena** [facebook/docusaurus#5254]
### Prerequisites

- [x] I'm using the latest version of Docusaurus.
- [ ] I have tried the `npm run clear` or `yarn clear` command.
- [ ] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [ ] I have tried creating a repro with https://new.docusaurus.io
- [ ] I have read the console error message carefully (if applicable)

### Description

When a category is expanded, causing the scroll bar to appear, the container is also pushed narrower. This also occasionally causes word wrapping to change, creating an even more visible shift.

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## Steps to reproduce

It's already observed on the Docusaurus site. Navigate to https://docusaurus.io/docs, and expand the "Guides" section. On my screen, this is enough to show the scroll bar. All the arrows on the right are now pushed inwards by 7px (284px -> 277px), creating a quite visible shift.

Below is a more significant demo:

![Test](https://user-images.githubusercontent.com/55398995/127640483-bdba42f6-479f-4a3d-be3d-0f3370a0cc9e.gif)

Another bug that this demo exposes: when the container narrows, some text is pushed below the next category, because the next category does not move accordingly when the height changes. However, if the layout shift is fixed, it should go away as well

## Expected behavior

The layout should remain consistent.

## Actual behavior

The sidebar container is compressed by the scroll bar. This may be fixed by leaving some space (like 10px) as margin.

## Your environment

- Docusaurus version used: beta-4
- Environment name and version: Chrome 91.0.4472.164 and Safari 14.1.1
- Operating system and version: Mac OS 10.15.7

**Comment by slorber** [comment]
Agree this kind of layout shift is quite annoying.

We also have one when opening the search modal due to scrollbar locking.

This CSS property will likely solve the issue and be adopted soon, but for now it has 0% browser support 😅 : https://www.bram.us/2021/07/23/prevent-unwanted-layout-shifts-caused-by-scrollbars-with-the-scrollbar-gutter-css-property

Temporarily, we can try to add some extra padding when scrollbar is not here so that there's no width change when this happens

**Comment by Josh-Cena** [comment]
Turns out that simply removing the `thin-scrollbar` class fixes the layout shift:

https://github.com/facebook/docusaurus/blob/1f8fa5e859b71892db65c67853ddecc2dbc6101f/packages/docusaurus-theme-classic/src/theme/DocSidebar/index.tsx#L77

![Test](https://user-images.githubusercontent.com/55398995/129124452-a77e6c7f-ec81-4b78-ac70-ef7bd1191cc5.gif)

So the question is, how useful is a persistent scrollbar?

**Comment by slorber** [comment]
doesn't fix this for me @Josh-Cena 

it only fixes it with macos general setting that hides scrollbars unless during scroll.

In french:

![image](https://user-images.githubusercontent.com/749374/129200901-fa1343b3-d8cd-4600-847c-063a03fe1a1f.png)

Looks like what you have here?

**Comment by Josh-Cena** [comment]
Ah, don't even know there's such an option

![image](https://user-images.githubusercontent.com/55398995/129201327-b6a53754-6bf3-4d77-a796-45e93a78bb0e.png)

I have the first option, but no idea how it differs from the second one

**Comment by slorber** [comment]
I have the first option too so I guess it depends on other factors like my mouse? 
I don't think removing that class would solve the issue for most users, only a subset of macos users (and I'm not included with my current settings)

**Comment by slorber** [comment]
Actually disabling my mouse and using the trackpad solve the issue with this class removed and the "automatic" setting. So it's not a very reliable solution.

**Comment by Josh-Cena** [comment]
> so I guess it depends on other factors like my mouse?

Most likely, since I'm using trackpad; probably mouse causes the scroll bar to be always visible?

On the other hand, I have no clue why removing it makes the scroll bar float above the main container while before it squeezes in its own width.

**Comment by vlahovivan** [comment]
I have the same issue, but it happens only when there is a title longer than one row of text.

When the title is "Što je dinamičko programiranje?" ("What is dynamic programming?") I have this issue:

![image](https://user-images.githubusercontent.com/30372377/131989918-4b0ae7b7-f03b-406b-9e92-f5cfc4ba5006.png)

When the title is "Uvod" ("Introduction"), the issue is gone:

![image](https://user-images.githubusercontent.com/30372377/131990111-bfd181b4-e1c1-4cc9-a39e-4f87b22b8fe8.png)

I've tried both in beta-4 and beta-6, the behaviour is the same

**Comment by zxuqian** [comment]
> I have the same issue, but it happens only when there is a title longer than one row of text.
> 
> When the title is "Što je dinamičko programiranje?" ("What is dynamic programming?") I have this issue:
> 
> ![image](https://user-images.githubusercontent.com/30372377/131989918-4b0ae7b7-f03b-406b-9e92-f5cfc4ba5006.png)
> 
> When the title is "Uvod" ("Introduction"), the issue is gone:
> 
> ![image](https://user-images.githubusercontent.com/30372377/131990111-bfd181b4-e1c1-4cc9-a39e-4f87b22b8fe8.png)
> 
> I've tried both in beta-4 and beta-6, the behaviour is the same

Same here

**Comment by argyleink** [comment]
could temporarily set `overflow-y: scroll;` until `scrollbar-gutter` is out?? 

https://user-images.githubusercontent.com/1134620/137372959-dcbbd85e-ed59-4667-8303-ca9c19432f51.mp4

**Comment by slorber** [comment]
Thanks @argyleink, will see if it's a good temp solution for us. 

Having a scrollbar always visible is not so great but if it affects only a small number of users that can be good enough.

(for issue context, I asked how to solve this here: https://twitter.com/sebastienlorber/status/1448708892511416320)

**Comment by akeller** [comment]
> I have the same issue, but it happens only when there is a title longer than one row of text.

This looks consistent with our experience and @Josh-Cena's, so our temporary fix will be to shorten the title text length. With the addition of the scroll bar, titles that were previously only one row of text, become two, which is where we see the problem. I'll see if we can think of any creative solutions on our side to actually fix this.

**Comment by slorber** [comment]
This is fixed in https://github.com/facebook/docusaurus/pull/7134

This uses a new CSS property `scrollbar-gutter`, not yet supported by latest Safari, so it will be fixed in all browsers as time passes but not instantly.

Note: there's also a similar layout shift related to search, for which we have a separate issue: https://github.com/facebook/docusaurus/issues/7130
