### ISSUE TITLE
Canary version users are getting false positive update notices

### ISSUE THREAD

**Issue by Josh-Cena** [facebook/docusaurus#5378]
## 🐛 Bug Report

The version checker is not behaving correctly anymore after using `0.0.0` for canary versions.

![image](https://user-images.githubusercontent.com/55398995/129926014-f4d1c6bb-76c9-4274-bbe6-6b4ecccc7795.png)

If we are not in a good position to check whether `0.0.0-3934` is newer than `2.0.0-beta.4` (which is), we might just disable update noticing for canary versions.

_Also: maybe we can have a `yarn upgrade` tip instead of `npm i` if user has yarn, just like in `docusaurus-init`?_

**Comment by slorber** [comment]
I'll just disable the notifier in such case

> Also: maybe we can have a yarn upgrade tip instead of npm i if user has yarn, just like in docusaurus-init?

`docusaurus-init` is a different case: we check for the presence of Yarn installation, not Yarn being used in the project (because there's no project created yet)

We have code for that but it's just not reliable for workspaces.

```js
  const isYarnUsed = fs.existsSync(path.resolve(process.cwd(), 'yarn.lock'));
  const upgradeCommand = isYarnUsed
    ? `yarn upgrade ${siteDocusaurusPackagesForUpdate}`
    : `npm i ${siteDocusaurusPackagesForUpdate}`;
```

I've opened an issue there, as I think the condition above was inspired by this lib: https://github.com/sindresorhus/has-yarn/issues/11

**Comment by Josh-Cena** [comment]
Ah, that's right. The `npm i` is because I'm using a monorepo
