### ISSUE TITLE
yarn start errors out when building '@docusaurus/mdx-loader'

### ISSUE THREAD

**Issue by Hillsie** [facebook/docusaurus#5384]
### Prerequisites

- [x] I'm using the latest version of Docusaurus.
- [ ] I have tried the `npm run clear` or `yarn clear` command.
- [x] * I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages. (* Entire project)
- [ ] * I have tried creating a repro with https://new.docusaurus.io (*No. Cloned the repository)
- [x] I have read the console error message carefully (if applicable)

### Description
Running `yarn install` and then `yarn start`, the builder stack traces when building `'@docusaurus/mdx-loader'`.
At first I thought this might be me, so deleted, rinsed and repeated the clone. Same result. I also qualified what I had experienced, in Discord.

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues)?
Yup, I read the guidelines and followed the installation process as described, albeit direct from the repo.

I'm happy to raise a PR, as I believe I have found the type error on line 33 in `packages/docusaurus-mdx-loader/src/remark/toc/index.ts`. 

## Steps to reproduce

~Use https://new.docusaurus.io to create a CodeSandbox reproducible demo of the bug.~
I believe it is not possible to reproduce in CodeSandbox, as this is a stack trace during the build process.

1. `git clone git@github.com:facebook/docusaurus.git`
2. `yarn install`
3. `yarn start`

## Expected behavior
`lerna info run Ran npm script 'build' in '@docusaurus/mdx-loader' in 4.5s:`

## Actual behavior
```bash
lerna ERR! yarn run build exited 2 in '@docusaurus/mdx-loader'
lerna ERR! yarn run build stdout:
src/remark/toc/index.ts(33,12): error TS2345: Argument of type 'File' is not assignable to parameter of type 'Node | Node[] | null | undefined'.
  Type 'import("/openSource/docusaurus/node_modules/@babel/parser/node_modules/@babel/types/lib/index").File' is not assignable to type 'babel.types.File'.
    The types of 'program.body' are incompatible between these types.
      Type 'import("/openSource/docusaurus/node_modules/@babel/parser/node_modules/@babel/types/lib/index").Statement[]' is not assignable to type 'babel.types.Statement[]'.
        Type 'import("/openSource/docusaurus/node_modules/@babel/parser/node_modules/@babel/types/lib/index").Statement' is not assignable to type 'babel.types.Statement'.
          Type 'BlockStatement' is not assignable to type 'Statement'.

lerna ERR! yarn run build exited 2 in '@docusaurus/mdx-loader'
```

## Your environment

The versions of 
 - `yarn version 3.0.1`
 - `node version v14.4.0`
 - `Ubuntu 20.04.3 LTS`
 - `v2.0.0-beta.4`

## Reproducible demo
Happens with `yarn start`
~Use https://new.docusaurus.io to create a CodeSandbox reproducible demo of the bug.~

~(Paste the link to an example repo, including a `docusaurus.config.js`, and exact instructions to reproduce the issue.)~

**Comment by slorber** [comment]
I'm not sure to understand, is it a bug inside our monorepo or in your Docusaurus site?

I'm assuming it's an issue with our repo, because otherwise why clone the repo in repro steps?

```
git clone git@github.com:facebook/docusaurus.git
yarn install
yarn start
```

It's not clear to me where you run install/start, don't you `cd docusaurus` first?

I just did this and it worked:

```
git clone git@github.com:facebook/docusaurus.git
cd docusaurus
yarn install
yarn start
```

Note you are using Yarn 3, which is likely no maintainer currently uses. 
You'd rather stick to v1.22.1 if you want to contribute.

**Comment by Hillsie** [comment]
Noted. Thanks for the feedback. Yes, it's from the mono repo and a clone of the version  mentioned above. 
Nw, the difference is likely Yarn 3. Happy to close. Before I do, could you glance at this line? If you think it's yarn and the modules it pulls in, let me know and I'll close.

![Docusaurus5384](https://user-images.githubusercontent.com/17975287/130193945-309212ba-3fca-4f5f-a096-f4f3c81109a4.png)

**Comment by slorber** [comment]
Technically, this code is correct and is quite similar to the one documented here: https://babeljs.io/docs/en/babel-traverse

![image](https://user-images.githubusercontent.com/749374/130202601-31796efb-11bf-45c2-98ac-33d92ef73f70.png)

`File` is indeed a `Node`.

I suspect for some reason you end-up with a mismatch, maybe due to a duplicate dependency or something?

Try to run `yarn why @babel/types` and see if you have any duplicates.

Also, if you use Yarn 3 PNP linker, it may be worth trying the node-modules linker instead.

But I'd just suggest using Yarn 1 for now.

I'd be happy to move to newer versions someday but we don't officially support that today.

Going to close because I'm not sure there's anything to do here. 
Let me know if you still have problems with Yarn 1, or if you succeed to make it work with Yarn 3.

**Comment by Hillsie** [comment]
Update for prosperity sake. Finally, got it working with yarn 3.
TBH, not 100% sure what the factors here, but on Ubuntu I did the following.
1. removed any references to yarn. (TL;DR: PATH, .yarnrc,  ~/.yarn)
2. Installed yarn v1 via apt https://classic.yarnpkg.com/en/docs/nightly/
3. yarn install in docusaurus root folder
4. yarn run to see it work.
5. yarn set version berry
6. yarn install
7. yarn up (TBH, no idea if this has any impact)
8. yarn start
It started ...

**Comment by slorber** [comment]
I guess we'll never know 🤪 maybe when I'll upgrade to Yarn 3
