### ISSUE TITLE
Lit.Dev Support for Docusaurus 

### ISSUE THREAD

**Issue by JacobWeinbren** [facebook/docusaurus#5416]
### Prerequisites

- [x] I'm using the latest version of Docusaurus.
- [x] I have tried the `npm run clear` or `yarn clear` command.
- [x] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [x] I have read the console error message carefully (if applicable)

re: the code sandbox, I am not sure how to make one that supports building a library and hosting a site.

### Description

Lit.Dev, a web component library, is not supported in Docusaurus. You can see the full code on [the repo](https://github.com/JacobWeinbren/miliband-components), but I will summarise the key points below. 

1. Define an element

```ts
import { html, css, LitElement } from "lit";
import { customElement, property } from "lit/decorators.js";
import {classMap} from 'lit/directives/class-map.js';

@customElement("mili-button")
export class MiliButton extends LitElement {
//Emptied class
}
```

2. Import and use the element in the Docusaurus MDX

```js
import "../../../dist/components/mili-button";
<mili-button>Button 1</mili-button>
```

3. Run yarn build 

```bash
Docusaurus Node/SSR could not render static page with path "/components/button" because of following error:

ReferenceError: window is not defined
    at Module.5857 (main:4044:7)
    at __webpack_require__ (main:54275:42)
    at main:1765:874
```
I have tried the following solutions
- Emptying out the custom class
- Making the render function conditional on useIsBrowser()
```js
render() {
    const isBrowser = useIsBrowser();
    if (!isBrowser) {
       return null;
    }
    return html`
        <a role="button" class=${this.class}>
          <slot>
          </slot>
        </a>`;
  }
```
- Using JS instead of TS

```js
const isBrowser = useIsBrowser();
if (isBrowser) {
   customElements.define('mili-button', MiliButton);
}
```

- Loading the code in BrowserOnly

```html
<BrowserOnly>
      {() => {
        import "../../../dist/components/mili-button";
      }}
    </BrowserOnly>
```

None of these steps have worked, all returning the same error. I was helped by @Josh-Cena to look through these steps and I would like to thank them for their advice. 

Lit element has limited support for SSR, as far as I can gather. Is there any way to render a custom element that is not based in React within Docusaurus?

Best,
Jacob

**Comment by slorber** [comment]
Hey.

I don't think this can be qualified as a Docusaurus bug. 
If you want to integrate a browser-only lib with any React SSR framework (Docusaurus, but also Gatsby, Next, Blitz, Redwood, Remix...), it is your responsibility to handle that integration yourself correctly and ensure the browser-only code is never loaded/required/imported/run on Node.js.

I recently added more info about such integration:
https://docusaurus.io/docs/next/docusaurus-core#browseronly-example-library


```tsx
import BrowserOnly from '@docusaurus/BrowserOnly';

const MyComponent = (props) => {
  return (
    <BrowserOnly fallback={<div>Loading...</div>}>
      {() => {
        const LibComponent = require('some-lib').LibComponent;
        return <LibComponent {...props} />;
      }}
    </BrowserOnly>
  );
};
```

Your problem here is importing your code, not running it. 

Only your last solution looks like the good thing to do, but it's not valid code actually, because as dynamic `import()` calls return a promise, not a React component.

![image](https://user-images.githubusercontent.com/749374/130602197-eea9fedf-4bf6-495a-b7f6-3136461a2dc7.png)

Try replacing that with `require()`

I can't really provide more support, this is not a Docusaurus bug/issue

**Comment by tony** [comment]
@JacobWeinbren On Lit-element with Docusaurus beta 0, I'm able to `rollup` a lit-element element and include it via `scripts`:

- https://github.com/social-embed/social-embed/tree/%40social-embed/wc%400.0.3-next.5/packages/site
- https://social-embed.git-pull.com/
  This is proof that docusaurus can work with LitElement and probably other custom elements.

The problem is after beta 0 method stopped working. I brought this up in discussion here: https://github.com/facebook/docusaurus/discussions/5614
