### ISSUE TITLE
Centered Element on main page

### ISSUE THREAD

**Issue by Mysterious-Dev** [facebook/docusaurus#5483]
Maybe center the fourth element on HomePageFeatures

![image](https://user-images.githubusercontent.com/40738104/132015503-3e46a4d3-ba1b-4fcd-8f00-28ae4afdd2b7.png)

**Comment by slorber** [comment]
This is an init template that you can customize, the goal of Docusaurus is not to provide you with a perfect landing page and in the end you must customize it to your own needs.

If you need 4 items, you may as well use a 2 items per row grid instead of centering?

And you can already add classNames to offset that element to the center if you want to.

See the Docusaurus site:
https://docusaurus.io/

![image](https://user-images.githubusercontent.com/749374/132028250-74b2a31c-e41e-4112-9d74-753fb199c9fa.png)


I don't think we should do anything. If you still think we do, please open a PR with an implementation proposal.
