### ISSUE TITLE
Make all front matter used by the theme accept `desktop` and `mobile`

### ISSUE THREAD

**Issue by Josh-Cena** [facebook/docusaurus#5805]
## 🚀 Feature

Front matter should accept both a simple option:

```md
---
hide_table_of_contents: true
---
```

Or an object:

```md
---
hide_table_of_contents:
  mobile: true
  desktop: false
---
```

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues)?

Yes

### Has this been requested on [Canny](https://docusaurus.io/feature-requests)?

No

## Motivation

Extracted from #5686.

## API Design

Front matter has two uses: they are either picked up by the plugin as metadata, or by the theme to render certain elements, but usually not both. A non-exhaustive list:

- `sidebar_class_name`
- `hide_title`
- `hide_table_of_contents`
- `hide_sidebar` (not implemented yet)
- `hide_pagination` (not implemented yet, I think this can be useful to add? Hiding pagination at theme level instead of `pagination_next: null`, which disables pagination at plugin level)
- `toc_min_heading_level`
- `toc_max_heading_level`

This permits us to render different layouts on different screen sizes, while not altering any UX (e.g. we don't allow displaying _different_ sidebars because that's passed on by the plugin, neither do we allow setting a different group of authors).

In addition, different theme implementations can even use other key names, like `tablet`, `1440`, `997`, etc. So during validation, we should allow any string keys.

**Comment by slorber** [comment]
> Make all front matter used by the theme accept desktop and mobile

As explained in https://github.com/facebook/docusaurus/pull/5854#discussion_r741885050, I'd rather not introduce this to ALL frontmatter, but only if there's a strong use-case.

Supporting this config adds complexity to avoid layout shifts

> toc_min_heading_level

If we want a TOC to have different heading levels for mobile/desktop without hydration layout shifts, this means rendering it twice and adding a mediaquery to each TOC so that only one is displayed at the same time. This increases the HTML file size and code complexity for a questionable feature that I feel we don't really need. If the user is using a simple `boolean` instead of `{mobile: boolean, desktop: boolean}` we can optimize by rendering only once the TOC, and the HTML wouldn't grow for most users, but this still complicates our codebase for little value.

So I'd rather collect first strong use-cases for doing something differently on mobile/desktop, and implement each use-case separately

**Comment by Josh-Cena** [comment]
Makes sense yeah, let's do it for `hide_sidebar` and `hide_table_of_contents` for now since we do have use-cases. I do feel like sometimes we should render fewer heading levels on mobile considering it takes up scroll height but... until someone asks for it

**Comment by slorber** [comment]
> Makes sense yeah, let's do it for hide_sidebar and hide_table_of_contents for now since we do have use-cases.

Agree for these 2 configs.

Note that the TOC is a special case, and a good API might be more complex to support all use-cases:
- there's the right TOC, and it probably doesn't make any sense to render on mobile (where could we render it?)
- there's the collapsible TOC, and there may be value rendering it in desktop too? I don't know

>  do feel like sometimes we should render fewer heading levels on mobile considering it takes up scroll height but... until someone asks for it

Oh actually I'm a bit wrong above and the TOC is rendered differently on mobile/desktop, so technically it's quite similar to the sidebar case and we could adjust the TOC heading levels config according to the right TOC vs inline TOC, and it shouldn't introduce layout shifts because we already handled those mediaqueries

**Comment by techieeliot** [comment]
The comments on this issue are stale from last Hacktoberfest? Is the issue still relevant and claimed @slorber? 

I just found this repo from a dev.to article, so I'll head over to your discord to see some help getting started if not here on this issue then another one.

**Comment by slorber** [comment]
@sidharthk9 I don't think we support this kind of front matter yet, which this issue is about:


```md
---
hide_table_of_contents:
  mobile: true
  desktop: false
---
```


@Josh-Cena curious: who came up with the need for this? 

Is this a "cool feature we could have" or something someone really came up with a use-case for?

I think we could close this until someone has a concrete use-case for it.

**Comment by Josh-Cena** [comment]
Frankly I don't remember at this point... Pretty sure someone asked on Discord so I opened this issue. However, because TOC & sidebar are not rendered on mobile on startup, I don't think their customizations would lead to FOUC or the like.

**Comment by slorber** [comment]
will close this for now and we'll see if the need comes again
