### ISSUE TITLE
Using runtime: 'automatic' in custom babel.config.js causes "x is not a function" error

### ISSUE THREAD

**Issue by mtrucc** [facebook/docusaurus#5978]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [X] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

Hello , I want to ask what I need to solve

`Uncaught ReferenceError: require is not defined`

Error

So, I add code in  babel.config.js
The code is as follows, no error was reported during development, and an error was reported during construction
```
module.exports = {
  presets: [
    require.resolve('@docusaurus/core/lib/babel/preset'),
    '@babel/preset-env',
    ['@babel/preset-react', { runtime: 'automatic' }],
  ],
};
```
Error
```
Docusaurus Node/SSR could not render static page with path "/404.html" because of following error:

TypeError: (0 , docsClientUtils_1.getActivePlugin) is not a function
    at useActivePlugin (main:4377:548)
    at Navbar (main:5273:2821)
    at d (main:50423:498)
    at bb (main:50426:16)
    at a.b.render (main:50432:43)
    at a.b.read (main:50431:83)
    at Object.exports.renderToString (main:50442:138)
    at _callee2$ (main:4333:2450)
    at tryCatch (main:54378:40)
    at Generator.invoke [as _invoke] (main:54609:22)

Docusaurus Node/SSR could not render static page with path "/blog" because of following error:
```

### Steps to reproduce

https://stackblitz.com/edit/github-ygdu6n?file=babel.config.js
~~~
npm run build
~~~

### Expected behavior

can build no error

### Actual behavior

```
Docusaurus Node/SSR could not render static page with path "/404.html" because of following error:

TypeError: (0 , docsClientUtils_1.getActivePlugin) is not a function
    at useActivePlugin (main:11306:548)
    at Navbar (main:12202:2821)
    at d (main:62371:498)
    at bb (main:62374:16)
    at a.b.render (main:62380:43)
    at a.b.read (main:62379:83)
    at Object.exports.renderToString (main:62390:138)
    at _callee2$ (main:11262:2450)
    at tryCatch (main:66326:40)
    at Generator.invoke [as _invoke] (main:66557:22)

Docusaurus Node/SSR could not render static page with path "/blog" because of following error:

TypeError: (0 , docsClientUtils_1.getActivePlugin) is not a function
    at useActivePlugin (main:11306:548)
    at Navbar (main:12202:2821)
    at d (main:62371:498)
    at bb (main:62374:16)
    at a.b.render (main:62380:43)
    at a.b.read (main:62379:83)
    at Object.exports.renderToString (main:62390:138)
    at _callee2$ (main:11262:2450)
    at tryCatch (main:66326:40)
    at Generator.invoke [as _invoke] (main:66557:22)

Docusaurus Node/SSR could not render static page with path "/blog/archive" because of following error:
```

### Your environment

- Public source code:
- Public site URL:
- Docusaurus version used:
- Environment name and version (e.g. Chrome 89, Node.js 16.4):
- Operating system and version (e.g. Ubuntu 20.04.2 LTS):
Mac os big sur 11.5
Chrome 89, Node.js 16.4

### Reproducible demo

Thanks

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by Josh-Cena** [comment]
From the discussion on Discord, the OP is trying to use the React 17's [automatic JSX runtime](https://reactjs.org/blog/2020/09/22/introducing-the-new-jsx-transform.html) to omit the `import React from 'react';` line.

I'm somewhat sure that the bug is caused by a naive TS transpilation in our own docs plugin that causes Node `require()` / `exports` to leak into client side. The default Babel configuration makes this go away unnoticed.

**Comment by Josh-Cena** [comment]
@mtrucc After working on the Stackblitz repro, I think the problem is not caused by the `runtime: 'automatic'` but rather `preset-env`. Our own preset already comes with `preset-env` that's properly configured, so there's no need to include another copy of this preset.

So what's causing the error exactly? It's Babel being unable to interpret the target of transpilation. Server-side and client-side configuration are different:

https://github.com/facebook/docusaurus/blob/713d14569edde007a00d7f9c1e23943f003a625b/packages/docusaurus/src/babel/preset.ts#L18-L38

On server-side, we have to tell `preset-env` that it is node and we can use Node-specific syntax (e.g. `require` to import functions). Therefore, just adding an option fixed the transpilation problem:

```diff
module.exports = {
  presets: [
    require.resolve('@docusaurus/core/lib/babel/preset'),
-   '@babel/preset-env',
+   ['@babel/preset-env', { target: { node: 'current' } }],
    ['@babel/preset-react', { runtime: 'automatic' }],
  ],
};
```

Whether that's sufficient to fix all problems I'm not sure, but it does seem to make build succeed in your repo. After all, you don't really need the `preset-env` because we already ship our own preset packed with this.
