### ISSUE TITLE
Color Theme not Matching OS Settings

### ISSUE THREAD

**Issue by fishcharlie** [facebook/docusaurus#5982]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [X] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

The default theme for Docusaurus sites should match the OS theme (dark vs light mode). Currently it always defaults to light mode.

### Steps to reproduce

1. Open site

### Expected behavior

Default theme to match OS setting (dark mode vs light mode).

### Actual behavior

Always defaults to light mode.

### Your environment

- Public source code: https://github.com/dynamoose/dynamoose
- Public site URL: https://v3.dynamoose.pages.dev
- Docusaurus version used: 2.0.0-beta.9
- Environment name and version (e.g. Chrome 89, Node.js 16.4): Safari Version 15.1 (17612.3.5), Node.js 16.13.0
- Operating system and version (e.g. Ubuntu 20.04.2 LTS): macOS 12.1 Beta (21C5039b)

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by Josh-Cena** [comment]
Hi, Docusaurus has set `respectPrefersColorScheme: true,` in our website:

https://github.com/facebook/docusaurus/blob/cd96ce165c052fe1c6f82b9e1e41e31b03314722/website/docusaurus.config.js#L324

So on first visit to the website, the `prefers-color-scheme` is indeed respected. However, we also preserve the color mode you chose in local storage, so that on next visit, you still see the same color mode.

If you open Docusaurus website in a private / incognito window, you should see a default dark mode. I have confirmed with tests on Chrome and Safari.

If it's not the case for you, I suggest you open the browser console and enter `window.matchMedia('(prefers-color-scheme: dark)').matches`. If the return value is not `true`, that means your browser doesn't pick up your system preferences.

**Comment by Josh-Cena** [comment]
Just realized you are not talking about Docusaurus site but your own site. I had no idea why I misunderstood😅 Please read the docs: https://docusaurus.io/docs/next/api/themes/configuration#respectPrefersColorScheme
