### ISSUE TITLE
SEO Metadata for generated-index pages

### ISSUE THREAD

**Issue by dtbj** [facebook/docusaurus#6238]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Description

I want og:image for category index pages! docusaurus can also add support for different head tags if possible.

### Has this been requested on Canny?

no

### Motivation

This feature can help in SEO a lot. It's not requested by a lot of users, but it will be very useful like in adding different head tags on generated-index pages, for eg one can use og:image, share links to social apps and can gather traffic to their docusaurus website.

### Have you tried building it?

No I haven't tried and I can't, I am beginner just learning basics.

### Self-service

- [ ] I'd be willing to contribute this feature to Docusaurus myself.

**Comment by Josh-Cena** [comment]
👍Makes sense

**Comment by slorber** [comment]
Can you give a more concrete use-case?

- Do you have an existing site with such category index page
- Do you absolutely want a different image for each category? Why?
- Can you show the images you want to use exactly? (or create a mockup with https://excalidraw.com/)
- Where would you like to put this image in your Git repo? in `src/static` or somewhere else?
- What if we generated these images for you?
- Is image the only use-case you want to solve, or do you need the flexibility to use any kind of metadata? What is head tags? (keywords is a quite useless SEO meta today)

---

@Josh-Cena for me the most flexible option would be to recommend the generated index to link to a Markdown doc page instead of autogenerated, and use <head> as in https://docusaurus.io/docs/markdown-features/head-metadata

Having a good public API to do this could solve the issue in a more flexible way + offer an useful additional feature that we could document:
https://docusaurus.io/tests/docs/tests/category-links/with-category-name-doc

What do you think?

**Comment by dtbj** [comment]
> Do you have an existing site with such category index page
Yes I have, here you go: https://ncert.talentbrick.com/class-11 here we have to make users navigate and select what to learn then subject then chapter, so it will be really useful for us if we can add og:image and some other metadata to make it seo friendly.

> Do you absolutely want a different image for each category? Why?
Yes absolutely we need different image for each category page, coz we will have to change title and class in image.

>  Can you show the images you want to use exactly?
Just like YouTube thumbnail we try to make visitors attract and click on the link, here is the demo image
![demo](https://user-images.githubusercontent.com/87176273/148326987-3127696d-6b67-4aaa-9923-090240bb3b16.png)

> Where would you like to put this image in your Git repo? in `src/static` or somewhere else?
Yes for others static dir is the best place, but I use other repository at my subdomain for images.

> What if we generated these images for you?
It will be something great but all the images layout will be same we keep changing our images layout time to time to keep it modern (we use different layout og:image for each chapter you can see it by looking at the source) but if docusaurus will generate images automatically it will reduce some of our work. I am really looking forward to it.

> Is image the only use-case you want to solve, or do you need the flexibility to use any kind of metadata? What is head tags? (keywords is a quite useless SEO meta today)
I agree with you keywords are useless completely useless, but we need og:image and sometimes description tag (currently description is possible but it's using the same description from the page we need different description for page and different for google coz you know description is the part of website that also helps to interact user.)

**Comment by Josh-Cena** [comment]
Yes, we can definitely go without keywords, but since we have image anyways, why not keywords? `description`, `image`, and `keywords` are all props of `SEO` anyways, and it just happens that `description` is the one that gets rendered on the page🤷‍♂️

**Comment by slorber** [comment]
👍  thanks
