### ISSUE TITLE
autogenerated trim parent prefix

### ISSUE THREAD

**Issue by wenerme** [facebook/docusaurus#6255]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Description

trim

- java/
  - java-intro.md
- go/
  - go-intro.md

to

- java/intro
- go/intro

### Motivation

Current docusaurus will trim the number prefix, but when writing, if there are alot topic, usally will have same layout like

- java/
  - intro.md
- go/
  - intro.md

but for better writing experience will layout like

- java/
  - java-intro.md
- go/
  - go-intro.md

because this is easier for search like

![image](https://user-images.githubusercontent.com/1777211/147957438-daf5e9bf-b902-488a-9175-633b73a3de13.png)

that's why there are alot docs under same tags https://wener.me/notes/tags/faq

### Self-service

- [X] I'd be willing to contribute this feature to Docusaurus myself.

**Comment by slorber** [comment]
This is a quite specific, magic and opinionated feature, you should ask on our Canny board instead of this issue, and we'll see if there's enough interest, and I doubt we would enable this by default. So I'm going to close it for now.

You can already use a custom `slug: /java/intro` frontmatter in your docs to make this happen in userland, why is this necessary to implement it, isn't this workaround good enough.
