### ISSUE TITLE
BrowserOnly component API has a counterintuitive usage of props.children

### ISSUE THREAD

**Issue by octogonz** [facebook/docusaurus#6263]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [X] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

This is not exactly a bug, more like an API design flaw:  The `<BrowserOnly>` component expects its `props.children` to be a lambda function instead of ordinary JSX elements.  This is counterintuitive and seems unnecessary.

### Steps to reproduce

1. Try to write some code using the `<BrowserOnly>` component:

   ```ts
   // Try 1: "Uncaught TypeError: children is not a function"
   const MyComponent = (props) => {
     return (
       <BrowserOnly>
         {props.children}
       </BrowserOnly>
     );
   };

   // Try 2: Okay let's try the example from the website docs.
   // But still: "Uncaught TypeError: children is not a function"
   const MyComponent = () => {
     return (
       <BrowserOnly>
         {() => <span>page url = {window.location.href}</span>}
         {props.children}
       </BrowserOnly>
     );
   };

   // Try 3: Let's simplify it down to the bare minimum
   // "Uncaught TypeError: children is not a function"
   const MyComponent = () => {
     return (
       <BrowserOnly>
         Okay seriously what is going on here??
       </BrowserOnly>
     );
   };

   // Try 4: An accidental space character 🥴
   // "Uncaught TypeError: children is not a function"
   const MyComponent = () => {
     return (
       <BrowserOnly> </BrowserOnly>
     );
   };
   ```

2. After about 20 minutes of debugging and scrutinizing the docs and banging my head against the wall, what I realized is that this API expects the JSX child content to evaluate to a ***lambda function that returns elements***, not a regular JSX element.  Any stray space character will cause `props.children()` to fail when `BrowserOnly`  tries to invoke the object as a function.

   This API design does work if used correctly, but it goes against all intuition for how JSX notation is supposed to function.

 

## Suggested redesign

Instead of this:

**Current API design**
```ts
const MyComponent = (props) => {
  return (
    <BrowserOnly fallback={<div>Loading...</div>}>
      {() => {
        const LibComponent = require('some-lib').LibComponent;
        return <LibComponent {...props} />;
      }}
    </BrowserOnly>
  );
};
```

...what if the API was like this:

**Proposed API design**
```ts
const MyComponent = (props) => {
  const renderForBrowser = () => {
     const LibComponent = require('some-lib').LibComponent;
     return <LibComponent {...props} />;
  };
  return (
    <BrowserOnly renderForBrowser={renderForBrowser}>
      <div>Loading...</div>
    </BrowserOnly>
  );
};
```

  

### Self-service

- [X] I'd be willing to fix this bug myself.

**Comment by Josh-Cena** [comment]
Let me try to explain the current design.

Firstly, the children of a component is usually the center of this component. The component is called `BrowserOnly`, not `SSRFallback`, so the center of it is what's rendered in a browser. It's like a cardboard box to wrap a fragile vase. Therefore, we would never declare the fallback as children. You can even omit the fallback and just let it return nothing, which usually makes sense as well.

Secondly, I guess you understand why it's a function rather than a JSX component. The children must be lazy-evaluated because you may need to import a lib that calls browser APIs directly.

I think the only bad thing here is the error message "Uncaught TypeError: children is not a function". If we have a custom error message like "children must be a lazy-evaluable function so you can require() a browser-only library", would that be better?

**Comment by slorber** [comment]
Suspense will become more widely adopted, and I think there's value in having a similar API: the children is not the placeholder

https://reactjs.org/docs/concurrent-mode-suspense.html

```tsx
<Suspense fallback={<Spinner />}>
  <ProfilePage />
</Suspense>
```

---

Now, we designed this component that way also to avoid a potential pitfall that is quite easy to make for less experienced users (many don't understand well what lazy execution, SSR and hydration is, so we should nudge them to use good patterns).

Consider the following:

```tsx
const MyComponent = props => {
  return (
    <BrowserOnly>
      <main>
        <div>{/* Huge JSX Tree here */}</div>
      </main>
      <div>URL of the page is {window.location.href}</div>
    </BrowserOnly>
  );
};
```

Less experienced users will think this is fine, but it will still throw on the server due to using `window`. Even if the JSX is not outputted, it still has to be constructed, and eager evaluation leads to a failure such as `window is not defined`. We already recommend users to use BrowserOnly in the error log, but this would be confusing because the user is already using BrowserOnly

(also, we are constructing the JSX tree, and it will actually never be useful so it's a waste of computing resources, but it's a micro-optimization, not very important)

Now, for sure a solution could be:

```tsx
const Content = props => (
  <>
    <main>
      <div>{/* Huge JSX Tree here */}</div>
    </main>
    <div>URL of the page is {window.location.href}</div>
  </>
);

const MyComponent = props => {
  return (
    <BrowserOnly>
      <Content />
    </BrowserOnly>
  );
};
```

This would work but it's harder to teach why it's needed to users that are not so familiar with React.


---

> I think the only bad thing here is the error message "Uncaught TypeError: children is not a function". If we have a custom error message like "children must be a lazy-evaluable function so you can require() a browser-only library. Current type: string" (which will be helpful in case of the "accidental space"), would that be better?

Agree, IMHO we should just have a better error message in case children is not a function.

**Comment by octogonz** [comment]
> the children of a component is usually the center of this component. The component is called `BrowserOnly`, not `SSRFallback`, so the center of it is what's rendered in a browser.

For what it's worth, as a new adopter of Docusaurus, I initially had trouble understanding what the name `BrowserOnly` was referring to:  My docs don't have other output targets like PDF or DocFX.  Nor are they hosted by a Node.js service -- they are purely static CDN pages.  It seemed like my entire site was already "client-side" and "browser only," so what does this tag do? It took a bit of thinking to remember that Docusaurus has a SSR prerendering feature (that is only used during final deployment).

So if we were to change the API design, maybe the component could be renamed at the same time. Something like `<PrerenderPlaceholder>` or `<NoPrerender>`.  Just an idea.
  
> Therefore, we would never declare the fallback as children but put the browser-only component in props. You can even omit the fallback and just let it render nothing for SSR, which usually makes sense as well.

This could be solved by representing both as props:

**Proposed design #2**
```ts
const MyComponent = (props) => {
  const renderForBrowser = () => {
     const LibComponent = require('some-lib').LibComponent;
     return <LibComponent {...props} />;
  };
  return (
    // The "fallback" prop is entirely optional.
    <BrowserOnly renderForBrowser={renderForBrowser} fallback={<div>Loading...</div>} />
  );
};
```

Eliminating the child props entirely avoids the issues @slorber mentioned of accidentally referencing `window` or performing expensive rendering that gets discarded.

**Comment by octogonz** [comment]
> the error message "Uncaught TypeError: children is not a function". If we have a custom error message like "children must be a lazy-evaluable function so you can require() a browser-only library. Current type: string" (which will be helpful in case of the "accidental space"), would that be better?

This would certainly be an improvement independent of the API design questions. 👍

**Comment by Josh-Cena** [comment]
Sorry, not really willing to change the API. If you look at suspense, [Nuxt's `client-only`](https://nuxtjs.org/docs/features/nuxt-components/#the-client-only-component), or other SSR solutions, the escape hatch would all have the browser-only stuff as the children rather than as props. This is just more intuitive for most people: it's more a "wrapper" than a "higher-order component".

We can definitely improve on the docs and the error message about what SSR is, but it's good to keep a consistent API with other solutions out there.

**Comment by octogonz** [comment]
Makes sense -- thanks for the explanation and for improving the error message!

**Comment by slorber** [comment]
Yes, let's just keep the current API, and improve the error message.

It's in sync with the ecosystem, Suspense and what React developers are used to already. This popular blog post also mention a similar comp: https://www.joshwcomeau.com/react/the-perils-of-rehydration/#abstractions

Now if you have a concrete suggestion to make it clearer why Docusaurus needs this comp, PRs are welcome
