### ISSUE TITLE
RFC: Remove delay for PendingNavigation nprogress

### ISSUE THREAD

**Issue by dtbj** [facebook/docusaurus#6290]
### Have you read the Contributing Guidelines on issues?

- [x] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Motivation

I have discussed with Josh-Cena (Docusaurus Maintainer) and he confirmed that they have added a 1 sec delay in progress bar which is causing to progress bar to not show you may never ever seen progressbar on top, so if you want then spam in replies yes we want perfect loader and remove that useless delay.

Those who don't know what is preloader here is the image it's built into docusaurus but you may have never seen it just because of this 1 sec delay.
![image](https://user-images.githubusercontent.com/87176273/148633300-64a4744c-929b-43c5-a0cf-749e4ae1d45c.png)
See the blue color bar at top this thing is known as preloader when you navigate or click on any link the page changes but you don't see this loader just because of delay and sometimes you may feel like that docusaurus is lagging.

respond with reactions
👍 or 👎 or spam in replies :-)

### Self-service

- [ ] I'd be willing to do some initial work on this proposal myself.

**Comment by Josh-Cena** [comment]
For context of when it was first implemented: #1383

**Comment by dtbj** [comment]
> We probably don't want to enable this by default, but maybe give an option to customize that delay?

Yes please if possible give an option.

> What should such an API look like?
> Also what do we do with the onRouteUpdateDelayed event in such case?

No idea I am beginner learning basics.

**Comment by ramesh-dada** [comment]
I agree. Most people have good internet in this era the pre-loader is useless so make use of it by removing this delay.

**Comment by Josh-Cena** [comment]
@ramesh-dada The whole point of this delay is to NOT penalize those with good internet. If your page is able to load within 0.1s, you shouldn't see a flash of the progress bar.

**Comment by ramesh-dada** [comment]
> @ramesh-dada The whole point of this delay is to NOT penalize those with good internet. If your page is able to load within 0.1s, you shouldn't see a flash of the progress bar.

I agree with you also but I still think it makes user interface good still not sure btw I am also new in docusaurus so please don't ask me anything else, it was my opinion it's up to you what to implement or not..

**Comment by Josh-Cena** [comment]
Yes, being able to respond to every user input is always good UX, but a page loading in 0.1s is enough to be qualified as an effective response to user input. The only problem here is, do people get so impatient that they don't even want to wait for 1s?

**Comment by slorber** [comment]
We use link prefetching so usually the next page's js code is already available and ready for the React navigation to happen.

That React transition may still be long though, as React rendering can be expensive if the destination page is complex.

If the JS is already loaded, nprogress should never be displayed

Maybe we can reduce the nprogress delay if we detect that a bundle fetch remains required or is in-progress?

**Comment by Josh-Cena** [comment]
I looked around the code and I understand the code better now.

> If the JS is already loaded, nprogress should never be displayed

nprogress is never loaded if the JS already loaded. Progress bar starts when `preload` is called, and stops when `preload` finishes. When those JS bundles are already loaded, this step is a no-op and the progress bar is stopped before it even starts. The key here: **it's only possible because we have a slight delay**.

In practice, I don't think rendering a loading bar instantly is good UX. VuePress does this, but they don't have preload/prefetch either, so the UX is at least consistent (although I'd say much, much worse than what we have) and users can see that loading bar as an integral part of route transition. But for us, showing loading bars sometimes but not others is quite weird.

`react-loadable` that we use has a `200ms` default timeout: https://github.com/jamiebuilds/react-loadable#avoiding-flash-of-loading-component I think it would be better than `1s`.
