### ISSUE TITLE
Canonical tag contains duplicated base URL when trailingSlash is false

### ISSUE THREAD

**Issue by ltm** [facebook/docusaurus#6315]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [ ] I have tried the `npm run clear` or `yarn clear` command.
- [ ] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [ ] I have tried creating a repro with https://new.docusaurus.io.
- [ ] I have read the console error message carefully (if applicable).

### Description

If `baseUrl` is set to value other than `'/'` (e.g. `'/docusaurus-canonical/'`) and `trailingSlash` is set to `false`, the canonical tag of the main index page will contain a duplicated base URL. Note that this only applies to the canonical tag set by JavaScript and not the static HTML.

I suspect this is caused by the `shouldAddBaseUrl` check in `addBaseUrl()`:
https://github.com/facebook/docusaurus/blob/a2d2324ca71275f75ec5b9cde88fb10dfff26b44/packages/docusaurus/src/client/exports/useBaseUrl.ts#L37

Assuming `baseUrl` is `'/docusaurus-canonical/'` the URL of the main index page is `'/docusaurus-canonical'`, so `url` does not start with `baseUrl`.

### Steps to reproduce

1. Set `baseUrl` to a value other than `'/'`, e.g. `'/docusaurus-canonical/'`
2. Set `trailingSlash` to `false`
3. Serve the site from a web host that doesn't use trailing slashes (e.g. Vercel with `trailingSlash=false`)
4. Open the main index page in a browser

### Expected behavior

The canonical tag should contain the correct URL of the page, i.e. `${siteUrl}/docusaurus-canonical`.

### Actual behavior

The canonical tag contains a duplicated base URL, i.e. `${siteUrl}/docusaurus-canonical/docusaurus-canonical`:
![Screen Shot 2022-01-11 at 12 39 13 PM](https://user-images.githubusercontent.com/714118/148995945-f32ca40c-3cc2-45dd-81f4-e53af17885ec.png)

### Your environment

- Public source code: https://github.com/ltm/docusaurus-canonical
- Public site URL: https://docusaurus-canonical.vercel.app/docusaurus-canonical
- Docusaurus version used: 2.0.0-beta.14
- Environment name and version (e.g. Chrome 89, Node.js 16.4): Firefox 95
- Operating system and version (e.g. Ubuntu 20.04.2 LTS): macOS 12.1

### Reproducible demo

https://github.com/ltm/docusaurus-canonical

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by Josh-Cena** [comment]
Oh... yeah. Thanks for reporting! Very clear repro 👍

**Comment by slorber** [comment]
also weird duplicate `//` for the hreflang links 😅

**Comment by markharrison** [comment]
The title of this issue seems akin to my problem ...

Im finding that Google is finding but "Excluding" all my Doc pages - other than the root.

I notice when I browse to Doc page there a redirect (301) that adds a / onto the end of the URL.

This means the URL (which returns a 200) is in conflict with what is in the sitemap.xml ?

Is this an issue - or is there another reason Google is excluding Doc pages ?

---

as an aside - when I access a doc using the the side menu - i see the URL in the address bar doesn't have a trailing / 
kind of inconsistent ?

**Comment by Josh-Cena** [comment]
@markharrison Did you set the [`trailingSlash` config](https://docusaurus.io/docs/deployment#trailing-slashes)? You should, in order to ensure consistency in your URL. Your issue is unrelated to this one, which is about base URL, not about trailing slashes.

**Comment by kochis** [comment]
It looks like there was a change to the default canonical tag that introduced this behavior: https://github.com/facebook/docusaurus/pull/4109/files#diff-5a9766c1abdd0dbd7f0ebafa788297edbaf531835e8b55c6d542e727e4507affL94-L95

From what I can tell, this only occurs on the root page when using `baseUrl` (at least it does in our case, pages with a permalink have the correct `canonical` tag). This is likely due to the fallback when a permalink isn't present: https://github.com/facebook/docusaurus/pull/4109/files#diff-5a9766c1abdd0dbd7f0ebafa788297edbaf531835e8b55c6d542e727e4507affR61-R63

Not sure what the expected behavior is, but it also presenting as a bug for our use case as well.

**Comment by slorber** [comment]
Note:
- at build time, docusaurus outputs the correct canonical URL in the static HTML file
- this URL becomes wrong only at runtime, after React hydration, because it's reading the current history location, which is not the expected one.

We have many other places where we read current browser location.

Accessing your site through `/baseUrl` is likely to cause other problems in your site (now or later) that may stay unnoticed.

Maybe we want to add a warning in those cases, or do a redirect to add the trailing slash automatically? 

Would it be a good solution for your use-case?

**Comment by guerrero** [comment]
It seems that, if `trailingSlash` is `undefined` the problem is still present and the base URL is duplicated in the meta tags for canonical and hreflang.

Here's a link to a repo to reproduce the bug:
https://github.com/tinybirdco/clickhouse_knowledge_base/tree/332fa84e6b9a22f984e64415b7ccabfa1f5d2669

Once the trailing `trailingSlash` is set to false everything works as expected.

Sorry in advance if this comment in this closed issue is not the the right way to report this. If you prefer, I can create a new issue.

**Comment by slorber** [comment]
@guerrero that would help me review this faster if you opened a dedicated issue and where your repro code has a deploy preview showing the problem that I can inspect without checking out your repo

Also if you have similar problems in hreflang headers that's worth reporting too
