### ISSUE TITLE
light/dark theme widget appears right of custom search bar (in wrong spot)

### ISSUE THREAD

**Issue by mtooke** [facebook/docusaurus#7154]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [X] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

Hello,

In 2.0.0-beta-18, the dark/light theme widget now appears to the right of my search bar, rather than the left: 
![Screen Shot 2022-04-11 at 2 30 17 PM](https://user-images.githubusercontent.com/1414082/162827695-8d9f8962-c6e3-4899-925b-83d2a4d03d54.png)

In previous builds, this widget always appear to the left of the search bar. I assume this is a bug and not a new feature (main docusaurus site doesn't reflect this change).

### Reproducible demo

https://codesandbox.io/s/inspiring-surf-81gury

### Steps to reproduce

1. Swizzle and override the searchbar component.
2.  Add the following code:

 ```
   {
             type: 'search',
             position: 'right',
     },
```
...into the docusaurus.config,js file in the navbar items array.

3. Check that the search field is now left of the dark/light widget.

### Expected behavior

I expect the dark/light widget to appear left of the search bar.

### Actual behavior

The dark/light widget appears right of the search bar.

### Your environment

- Public source code:
- Public site URL:
- Docusaurus version used: 2.0.0-beta-18
- Environment name and version: Chrome Version 99.0.4844.84 (Official Build) (x86_64)
- Operating system and version (e.g. Ubuntu 20.04.2 LTS):

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by Josh-Cena** [comment]
Are you sure it's not like that in previous versions? I tried in beta.17 and a few older ones and got the exact same result.

The reason for that is because we render all navbar items declared in `themeConfig`, then render the rest (color mode toggle and search bar). If search bar is not part of theme config, it will be rendered as an extra item and hence right of the color mode toggle; if it's explicitly declared, it's a normal navbar item and therefore comes before the color mode toggle.

If you want to make it appear on the right anyways, why declare it as navbar item? This API is mostly useful to make it appear on the left instead.

I'll leave this open though, we have TODOs in our code about letting user specify the position of all navbar items, including the mobile sidebar toggle and the color mode toggle. That could solve the confusion here.
