### ISSUE TITLE
[Proposal] Cross repo publishing

### ISSUE THREAD

**Issue by gustavohenke** [facebook/Docusaurus#717]
### Is this a bug report?

No

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/Docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Skimmed through it, expect it to be the same as most other OSS projects

### Environment

Docusaurus ^1.0.15

### Steps to Reproduce + current behaviour

1. Have your docs code in a project repo. Make sure to have `master` checked out. 
2. Point your deployment to an user/org repo (`.github.io`) **that has no commits** (important)
3. Try publishing your docs, check that it works (it won't after #716 is merged)
4. Do some changes, then try publishing again.

After this, you'll get #406 thrown at your face.

The reason is that the publish script is not ready to deal with cross repo publishings.
It only knows how to deal within user sites (`master` publish target, `source` as source branch) or project sites (`gh-pages` publish target, `master` as source branch).

### Expected ~Behaviour~ Feature

Have some way of letting `docusaurus-publish` know we're doing a cross repo publishing.

### Reproducible Demo

[express-validator org](https://github.com/express-validator) is such a setup.

[Here's the `siteConfig.js`](https://github.com/express-validator/express-validator/blob/master/website/siteConfig.js), it has `projectName` set to `express-validator.github.io`, but the code is not in the org site repo.  
[When you go there, all you will see is the built HTML/CSS/etc](https://github.com/express-validator/express-validator.github.io).

**Comment by gustavohenke** [comment]
I'm willing to tackle this one if we agree on some way of implementing it.

I'm happy with having a env flag like `CROSS_REPO_PUBLISHING=true docusaurus-publish` for now, even though I know this is not very nice.

**Comment by endiliey** [comment]
@gustavohenke 
Could you tell us more on how do you plan to implement this ?

**Comment by gustavohenke** [comment]
A few ideas:
- A naive env flag that simply bypasses the branch check [here](https://github.com/facebook/Docusaurus/blob/49c27b733bf62506acff3c55f92143dc0ef3ed86/lib/publish-gh-pages.js#L71-L74) 🤢
- An elaborate git remote check.
  If the target is `.github.io`, but the repo that contains the docs sources isn't tracking a `.github.io` remote, then you can proceed publishing it.

**Comment by endiliey** [comment]
Tbh i think having to set an env flag and having to type `CROSS_REPO_PUBLISHING=true docusaurus-publish` is quite unnatural to do. 

My understanding is that you want separate code repository. One is the one that contains docs while another one is the published code (just the built html/css file). 

I think it's better to make it such that whether it's in the same repo / different repo, if I set my 'projectName' & 'organizationName` to something, I want my published codes (built HTML/CSS) to be there. 

What do you think ?

**Comment by bhouser** [comment]
As a developer, I find it valuable to have the docs in the same
repository.  The docs changes are then in the same commits/branches as the
corresponding code changes.

The ability the generate the documentation website from more than one
repository wozld he very useful at my company, where we are not using a
monorepo.

**Comment by JoelMarcey** [comment]
Do you think that this would be a super common use-case? If not, then I don't mind an environment variable that can be used and is documented (e.g., @gustavohenke naive flag idea). Otherwise, we should consider this some more -- maybe we still use the flag, but having something in the core code that works could be better.

**Comment by gustavohenke** [comment]
> if I set my 'projectName' & 'organizationName` to something, I want my published codes (built HTML/CSS) to be there.

So this would mean simply removing the branch check, I guess?

> Do you think that this would be a super common use-case?

I'm not sure. Perhaps?
I failed finding many projects that represent this, but a very popular one is Jasmine. Same setup:
[Source is here](https://github.com/jasmine/jasmine) and [docs are here](https://github.com/jasmine/jasmine.github.io).

My points in favour of this cross repo publishing is
- the coolest URL some folks can get is the `.github.io` one (without 💰)
- as a good practise, mindful OSS maintainers will keep docs close to sources, so a single PR can update all around the change.

**Comment by azu** [comment]
I've used cross repo publishing pattern.
Source repository and Website repository are in in a different place.

- Almin – Source [almin/website/](https://github.com/almin/almin/tree/master/website), WebSite: [almin.github.io](https://github.com/almin/almin.github.io)
   - Source repo includes website(Docusaurus). because I want to [update API document from source code](https://github.com/almin/almin/blob/master/tools/update-api-reference.sh)
- textlint – Source: [textlint/website/](https://github.com/textlint/textlint), WebSIte: [textlint.github.io
](https://github.com/textlint/textlint.github.io)

Currently, I use deploy shell script to deploy.

- https://github.com/almin/almin/blob/master/tools/push-to-github-io.sh
- https://github.com/azu/travis-scripts is a fork of [alrra/travis-scripts
](https://github.com/alrra/travis-scripts) for [some reason](https://github.com/alrra/travis-scripts/issues/31)

**Comment by JoelMarcey** [comment]
I definitely think the most common case if having the raw docs and site close to the source code, but the built rendered HTML on `gh-pages`.

We are definitely willing to consider a pull request that makes your use case easier for anyone who needs it, whether through a environment variable or a more substantial code change.

**Comment by endiliey** [comment]
Closed by #764
