### ISSUE TITLE
`utils.extractBlogPostSummary` naively cuts markdown at wrong places

### ISSUE THREAD

**Issue by chenglou** [facebook/Docusaurus#719]
### Is this a bug report?

Yes

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/Docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

### Environment

Docusaurus 1.1.5. The rest doesn't matter

### Steps to Reproduce

1. Create a new blog post
2. Write this exact content: https://gist.github.com/chenglou/2c7283a65804a0b481b932ae1c1ab18e#file-foo-md
3. run `docusaurus-build`

### Expected Behavior

Site publishes fine.

### Actual Behavior

**Entire doc site wiped** 😅

That blog post goes through https://github.com/facebook/Docusaurus/blob/fa20c93d5c1b5a9369cf1c5909955fc58f0dcb8e/lib/server/feed.js#L62 which naively trims the blog post content into something that ends with `##`. This then goes into https://github.com/facebook/Docusaurus/blob/fa20c93d5c1b5a9369cf1c5909955fc58f0dcb8e/lib/server/feed.js#L73 which uses Remark and produces a wrongly parsed markdown tree, which causes https://github.com/facebook/Docusaurus/blob/fa20c93d5c1b5a9369cf1c5909955fc58f0dcb8e/lib/core/anchors.js#L15 to call `toSlug` on an undefined string.

This throws and stops the async call. The async call's rejection isn't handled, so there was no stack trace. The result is that an arbitrary part of the doc site gets generated into `build`, most of which is missing.

The right way of handling this is to semantically trim the post content using Remarked, instead of cutting at 250 chars. Note also that you might be cutting halfway into a unicode char, which will also result in other kinds of invalid behaviors.

The other thing is that the high-level async rejection needs to be handled; otherwise it's almost impossible to debug this.

### Reproducible Demo

See above

**Comment by endiliey** [comment]
I can confirm this is a bug.
<img width="712" alt="bugg" src="https://user-images.githubusercontent.com/17883920/40870029-ce72e120-6658-11e8-9d17-ecb4bc5fa18f.PNG">

Your proposed solution on the right way seems good to me. Would love to see a PR from you for this @chenglou .

**Comment by endiliey** [comment]
This is weird, I removed my node_modules & reinstalled & added that docs from your gist and it works now.

<img width="763" alt="work" src="https://user-images.githubusercontent.com/17883920/40870411-492f026a-6661-11e8-8e46-3f47cded86fa.PNG">

@chenglou 
Did you get any error / the doc just went missing ?

**Comment by chenglou** [comment]
The output in `build` isn't useful; just partially synced files. Is there some weird caching? Or are you using another version?

But you do see how following that code path can lead to exceptions right?

**Comment by endiliey** [comment]
I'm using master branch of Docusaurus, but there isn't anything major difference from it to 1.1.5. 

I do agree that the code path can lead to exceptions though. A workaround for now is to properly add truncate mark instead of letting it automatically truncated on char 250.

Trying to figure out if we should agree on certain length to truncate but make sure that parsed markdown tree is correct

**Comment by JoelMarcey** [comment]
So, chatting with @chenglou - his blog post was set up just right to run across this issue. Which is lucky for us because we now know there is an issue. That said, the Docusaurus blog works fine as I imagine most other blogs, so I don't think this is a widespread problem.

However, we should fix this. I am not sure of the best way to go about it though. I like what @endiliey said as a workaround possibility. Will that solve @chenglou's problem? I think so. Will it solve the problem overall? Maybe. @endiliey interested in a PR for your workaround?

@yangshun - any ideas here?

**Comment by endiliey** [comment]
Actually, I did a little bit of investigation. I went for a fresh install 1.1.5, added blog post with that gist, ran `yarn build` & everything works fine. I'm unable to reproduce the bug. Are you able to reproduce it @JoelMarcey ?

I am not sure on how did I got that Unhandled Promise error before, could be because I was messing around with my node_modules before & the code itself for another PR.

I went to see the code and https://docusaurus.io/docs/en/blog.html#rss-feed
The function `utils.extractBlogPostSummary` is only used to generate RSS Feed.

How about this ? Let's not truncate at all the blogPost if there is no `<!--truncate-->` on the markdown ? Since it's only for RSS Feed :)
