### ISSUE TITLE
Readme unclear about templates

### ISSUE THREAD

**Issue by ShalokShalom** [facebook/docusaurus#7201]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Description

See here: 
https://github.com/facebook/docusaurus#installation

Up until this point, **templates** had not been even mentioned once. 
I am expected to know about a topic, that wasn't even mentioned to me before. 

The only thing I am left to do is to blindly accept _classic_ as a somewhat sane default, but by mentioning the different options before the installation part, the user can make an informed decision. 

### Self-service

- [ ] I'd be willing to address this documentation request myself.

**Comment by Josh-Cena** [comment]
Hi! The README is more of a "promotional" text than an "explanatory" text. It's job is to get you up to a site quickly rather than trying to make everything make sense. If you want more explanation, you can check out the docs: https://docusaurus.io/docs/installation#scaffold-project-website

Generally, we have to make a compromise between verboseness and clarity. We don't have much room for clarity in the README. I hope you can understand. It's not very common for big projects to put everything in README.

**Comment by ShalokShalom** [comment]
You give detailed INSTALLATION INSTRUCTIONS. This is not about promotion, this is about technical details. Do it right, or don't do it all.

**Comment by Josh-Cena** [comment]
It does get you a working state, doesn't it? I beg you to define "instructions" and "technical details" because they look very orthogonal to me.

There's a fine line between "instruction" and "explanation". In the instructions, we tell you "do X" where X is something very concrete that you just need to copy. You are not "expected to know about" installation, you are supposed to FOLLOW THE INSTRUCTIONS. That's the point of a getting started guide. Most of the users don't care what a template is, what args/options we accept, or what "classic" exactly means. They may not even know what npm does.

We strive to follow the guideline of [Diátaxis Framework](https://diataxis.fr/). The README, if trying to be explanatory at all, should be a [how-to guide](https://diataxis.fr/how-to-guides/). Very important point:

> An explanation doesn’t show you how to do something - so a how-to guide should not try to explain things. Explanation here will simply get in the way of the action. If explanations are important, link to them.
>
> In how-to guides, practical usability is more helpful than completeness. Whereas a tutorial needs to be a complete, end-to-end guide, a how-to guide does not. It should start and end in some reasonable, meaningful place, and require the reader to join it up to their own work.

If you want to know more about it, it's not like we slap the installation instructions and have literally nothing else in the README. You have the 5-min tutorial. You have the website. And the website tells you probably exactly what you need.

Any reasonably big project does not strive to make the README a self-contained explanation end-to-end because that's simply not feasible. It takes you to a good starting point where you can get your feet wet and start exploring yourself, and then you are invited to read the actual docs for any explanation/tutorial. Thanks for understanding.

**Comment by Josh-Cena** [comment]
Still, I understand how it can be confusing for some. I've sent https://github.com/facebook/docusaurus/pull/7208 which should hopefully make it more like an actual instruction. Thanks for bringing this to our attention @ShalokShalom

**Comment by ShalokShalom** [comment]
I appreciate your time, the distinction between the different kinds of documentation, and for clarifying, that I don't even need to specify a type of template, to get started.

**Comment by Josh-Cena** [comment]
Yeah, I decided to go with the bare minimum in the README so it probably sound less like we are hiding critical information 🤷‍♂️
