### ISSUE TITLE
Google tag manager or before/after body head opens/closes

### ISSUE THREAD

**Issue by cameron-elliott** [facebook/Docusaurus#724]
### Is this a bug report?
Not a bug, but a suggestion

### Have you read the [Contributing Guidelines on issues]?
Multiple times.

### Feedback and suggestion
Okay, please keep in mind, I am a developer, but not a JS developer, and obviously not a React developer too. I don't know the best ways to do stuff in the space, but want to provide some feedback.

First, I really think Docusaurus is very cool! Kudos!

Okay, I have been trying to integrate about four different sets of JS analytics tags into my site, and have come back with some observations and an enhancement suggestion.

Most tag providers generally suggest that you inline their JS and/or HTML snippets in one of four places:
after the &lt;head>, &lt;body> tags, or before the &lt;/head>, &lt;/body> tags.
They don't generally suggest putting these tags in a separate mytagsnippets.js files, from my recent experience.  
While putting these tags in a file such as mytagsnippets.js certainly works, there are differing opinions on whether that could be sub-optimal in a sufficient number of cases due to potential multiple Http requests, etc.   https://stackoverflow.com/questions/3870345/new-google-analytics-code-into-external-file

I don't want to start a discussion about that topic, for sure.
But for those who do think that inlined JS is worth is, and it seems most JS tag suppliers do recommend this method, I do want to ask the question, does the Docusaurus team want to support that more directly?

I did want to follow the recommendations of the SO pundits, and my own HTTP experience and keep the JS inline, even though the file would be cached, etc, etc, etc.

But I found this very difficult to for a couple reasons, 1) it is tough to identify how/where to edit the JS/React to insert HTML, or &lt;Script> stuff at the four locations mentioned earlier. 2) I am currently in blog mode, which makes it even harder (can't hack some JS).
I also didn't want to get into hacking stuff lib/*.js for obvious reasons.

I would suggest these two possibilities for help poor non-front end persons such as myself:

A) Consider allowing straight HTML insertion into the four places I suggested, which would allow the JS and HTML dual combos used by modern analytics platforms such as Facebook and Google.

B) Consider directly supporting Google Tag Manager like how you did with Google Analytics. (No, I don't work for Google.)

Option B) would allow non-web developer like myself to really really easily deal with two or more sets of tag snippets if we are using Google's Tag manager.
Option A) would allow non-web developer like myself to just drop in the HTML & JS in the right place if we felt we should follow the directions of the tag providers to the letter.

Keep in mind some users of Docusaurus may not be able to evaluate the impact between following the suggested method of inlining JS+HTML tags vs dropping it into a JS file to be referenced by the siteConfig/scripts variable. They may not understand it is mostly equivalent, and not too problematic except in a small fractional number of cases.

I ultimately ended up using a feature of Netlify called 'Snippet injection' cause I was really struggling to find good way to do this with Docusaurus.

Thanks again for creating Docusaurus.

Cameron

**Comment by endiliey** [comment]
Thank you @cameron-elliott for the suggestion. To be honest, I found it hard as well when I first started to use & contribute to Docusaurus given that I have not much experience for web development.

In the current state, it is indeed true that it is tough to identify how/where to edit the JS/React to insert HTML, or <Script> stuff. Given that Docusaurus motto is somewhere along the line of "Easy to maintain" and "Easy to use", I believe that maybe we should start looking more and more into this. 

Hoping that more people will give their opinion on this ..
What do you think @JoelMarcey @yangshun ?

**Comment by parvezakkas** [comment]
@endiliey - Would you consider a solution for V1? I manage several docmentation site built with Docusaurus V1 and I need to integrate with Google Tag Manager.

I could probably use an external script to add code snippets provided by Google Tag Manager but I don't think that is helpful. The tag manager should be loaded as soon as possible. The following quick start guide shows that there two places  where scripts needs to be added (one is immediately after opening `<head>` and another is immediately after opening `<body>`).

https://developers.google.com/tag-manager/quickstart

For V1, this could be a simple configuration in `siteConfig.js` which accepts the "tag manager ID". and Docusaurus can generate with the site with the necessary scripts added in the right places.

For V2, I think we will need a plugin like this one with more advanced capability:

https://www.gatsbyjs.org/packages/gatsby-plugin-google-tagmanager/

I'd be happy to open a PR for the V1. I will not be able to migrate to V2 any time soon since it's still in alpha stage and a lot of doc specific feature is not setup yet (i.e. versioning as far as I know). Others may be in similar situation as well. But In the meantime, I need to integrate with Google Tag Manager and I'd prefer having it setup properly instead of hacking around it.

Thoughts?

**Comment by endiliey** [comment]
Sorry but v1 is in maintenance mode now.

**Comment by parvezakkas** [comment]
> Sorry but v1 is in maintenance mode now.

I guess it's your call as the maintainer of Docusaurus but isn't it a bit too early since V2 is still in alpha stage?

Unfortunately the workaround is a little too heavy. My only option (as far as I can think of) is:

- Introduce a custom post-build process that will go through every html files generated and insert the necessary script blocks for google tag manager. This is too much work.
- Use an external script to add google tag manager during runtime when the site is launched. This will delay the setup and can probably skew the results in analytics (i.e. user left the site or browsed to another page before the analytics could be setup)

My suggestion above was to allow us to be able to plugin google tag manager id in the siteconfig similar to google analytics config that is already available. It's not a huge change.

I hope you'll reconsider @endiliey. This would really help out a lot. I can open up a new PR if you agree. Please let me know.

**Comment by endiliey** [comment]
> I guess it's your call as the maintainer of Docusaurus but isn't it a bit too early since V2 is still in alpha stage?

I'll be honest here. The more we add up feature to v1, the more it introduces more work for us to backport it to v2. It's also two completely different codebase. Reviewing takes time. And this is not just a matter of huge change/ not. The moment we accept new feature request, people will keep requesting new feature or sending new feature in. Well, most open source project out there usually can just ignore issues and PRs, but I personally am happier to respond to each of them rather than ignoring it. (that's why docusaurus has < 50 issues open and PRs are generally responded quite fast compared to other project). 

Another reason is because v2 has matured. We have 100+ known public GitHub users right now and 2,6k+ downloads/week for v2 (lot of our user use it for internal setup), and we want to focus on that. Lot of features parity has been matched, and probably what's left for beta is docs versioning and translation. Beta will have full release features.   

I hope you understand. Some recommendation: fork or use https://www.npmjs.com/package/patch-package. It's OSS afterall.

**Comment by parvezakkas** [comment]
I understand. Thanks for all of your time and effort. It's a great tool for getting up and running with Documentation easily.
