### ISSUE TITLE
[Question]: how to swizzle this menu components?

### ISSUE THREAD

**Issue by Chasen-Zhang** [facebook/docusaurus#7332]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Description

![image](https://user-images.githubusercontent.com/15354455/166859550-b1d295cf-0983-4eee-bacc-cc94e669ca01.png)
how to swizzle this menu components?

### Self-service

- [ ] I'd be willing to address this documentation request myself.

**Comment by Josh-Cena** [comment]
Please don't use the issue tracker for questions.

I'm closing this without giving an answer to discourage such action. You've been warned multiple times.

**Comment by Chasen-Zhang** [comment]
If I use the discussion area to ask this question, no one will answer, I can only use the way of the temporary issue to ask, if you know, smoothly say not to go

**Comment by Josh-Cena** [comment]
@slorber and I both answer questions in discussions whenever we have time. Please kindly point me to a question that has not been answered. You can also ask on Discord, where I'm active whenever I'm awake.

The documentation you have in your screenshot also includes at least four steps about how to self-service to find the component. Have you walked through them?

**Comment by Chasen-Zhang** [comment]
You've blocked the way for others to bring up bugs

**Comment by Josh-Cena** [comment]
Sorry—why? The bug tracker is always open.

**Comment by Chasen-Zhang** [comment]
As an open source project, openness and enthusiasm come first

**Comment by Josh-Cena** [comment]
The best way to engage with an open source project is to choose the right channel for the right form of communication.

Open-source does not mean free service—we are not bound to serving you. Quality service and fast iteration, you can only choose one. Maintainers have limited time to manage the issue tracker, and clogging it with unrelated reports that don't even follow the template only hinders us from using our time for more meaningful things.

Please kindly check out our [CONTRIBUTING guide](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md) for how to file issues and what are the other ways to communicate with us (spoiler: GitHub discussions and Discord are very active channels). Issues are a form of serious contribution, not a form of free-form communication for Q&A, because we don't have that much bandwidth.
