### ISSUE TITLE
Add back the information about extra search options for Algolia

### ISSUE THREAD

**Issue by JoelMarcey** [facebook/Docusaurus#743]
### Is this a bug report?

No.

We used to have more info on Search -- See version 1.0.11 docs - https://docusaurus.io/docs/en/1.0.11/search

This commit took a lot of that out - https://github.com/facebook/Docusaurus/commit/5afc0b0a1cd16b46a156276730deab3fcaf5d3ff

But it seems like that information may be useful - see https://github.com/reasonml/reasonml.github.io/issues/388

In that issue, @endiliey said:

> I personally think the extra search option should at least be put back, especially information of
Any occurrences of "VERSION" or "LANGUAGE" will be replaced by the version or language of the current page, respectively is very useful. Because this extra processing is only done via Docusaurus through https://github.com/facebook/Docusaurus/blob/d28b864a59fabeea45add8c090a13de7d0530de5/lib/core/Site.js#L128-L142

So maybe reverting that commit is what we want to do or just write that section again with any improvements?

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/Docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

### Environment

N/A

### Steps to Reproduce

N/A

### Expected Behavior

N/A

### Actual Behavior

N/A

### Reproducible Demo

N/A

**Comment by Kelltimo** [comment]
Hello, 

 I would like to help and contribute on this! Would you recommend I just edit the "guides-search.md" file? 

Thank you

Tim

**Comment by yangshun** [comment]
@Kelltimo Yes, you can look at https://github.com/facebook/Docusaurus/commit/5afc0b0a1cd16b46a156276730deab3fcaf5d3ff and see which changes make sense to be put back. 

I've added an "issue-claimed" label so that others will know not to start work on the issue. If you change your mind about the issue, no worries! Just let me know so that I can remove the label and free it up for someone else to claim.

I'll check in with you periodically so that we can keep the task updated with the progress.
