### ISSUE TITLE
Use url-join to resolve URLs

### ISSUE THREAD

**Issue by JoelMarcey** [facebook/Docusaurus#754]
### Is this a bug report?

No. Enhancement. But could fix unknown or future bugs.

See https://github.com/facebook/Docusaurus/pull/745 for context.

https://github.com/facebook/Docusaurus/blob/master/lib/core/Head.js would be a good place to start with for a PR. instead of concatentating URL fragments with `+`, use the [`url-join` npm package](https://www.npmjs.com/package/url-join) instead.

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/Docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

### Environment

N/A

### Steps to Reproduce

N/A

### Expected Behavior

N/A

### Actual Behavior

N/A

### Reproducible Demo

N/A

**Comment by vaibhavsingh97** [comment]
@JoelMarcey Can I take this issue? I would love to solve this 😄

**Comment by yangshun** [comment]
It's yours!

I've added an "issue-claimed" label so that others will know not to start work on the issue. If you change your mind about the issue, no worries! Just let me know so that I can remove the label and free it up for someone else to claim.

I'll check in with you periodically so that we can keep the task updated with the progress.

**Comment by vaibhavsingh97** [comment]
@JoelMarcey @yangshun Sent PR 😄 https://github.com/facebook/Docusaurus/pull/771

**Comment by endiliey** [comment]
I think we're doing quite good for now and let's not add extra dependency. We are moving to v2 anyway :smile:
