### ISSUE TITLE
onPageNav menu mobile button should not show when user did not enable onPageNav in siteConfig

### ISSUE THREAD

**Issue by yangshun** [facebook/Docusaurus#761]
### Is this a bug report?

Yes

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/Docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

### Environment

Docusaurus 1.2.0

### Steps to Reproduce

(Write your steps here:)

1. Change `siteConfig.onPageNav` to `false` or remove the value.
2. Navigate to a doc page.

### Expected Behavior

The three dots for the mobile onPageNav menu should not appear.

### Actual Behavior

The three dots for the mobile menu should not appear but they still do. Clicking on them does nothing but it's confusing.

### Reproducible Demo

<img width="384" alt="screen shot 2018-06-12 at 12 44 47 am" src="https://user-images.githubusercontent.com/1315101/41276681-d8d8d9ac-6dd9-11e8-82b8-b53fca167ef3.png">

**Comment by Thai56** [comment]
If no one has taken this I would like to give it a stab.

**Comment by endiliey** [comment]
@thai56 it's yours

I've added an "issue-claimed" label so that others will know not to start work on the issue. If you change your mind about the issue, no worries! Just let me know so that I can remove the label and free it up for someone else to claim.

I'll check in with you periodically so that we can keep the task updated with the progress.

**Comment by Thai56** [comment]
#767

**Comment by endiliey** [comment]
Closed by #768
