### ISSUE TITLE
When running the `docusaurus build docs` command, the error `cannot find module tslib` appears

### ISSUE THREAD

**Issue by wangjiaojiao77** [facebook/docusaurus#7623]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Description

For specific errors, please refer to the following figure.

<img width="1728" alt="image" src="https://user-images.githubusercontent.com/24351082/173980558-36a63550-a8e3-4e4f-ae68-0e3f962d1f06.png">

### Self-service

- [X] I'd be willing to address this documentation request myself.

**Comment by Josh-Cena** [comment]
This is either a bug or a question—but not a documentation request at any rate. Using the documentation template means you bypass a lot of critical information needed to help us help you. I'm going to instantly close this because there's not enough information to determine if it's a Docusaurus defect.

Try the following:

1. Remove `node_modules` and re-run `yarn install`
2. If you still can't fix this, provide a public repo link below.
