### ISSUE TITLE
In React pages, imported Markdown does not highlight code blocks

### ISSUE THREAD

**Issue by zzjin** [facebook/docusaurus#7698]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [X] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

when write content in pages using feature `Importing Markdown` with tabs code inside, code is not right highlighted.

### Reproducible demo

https://codesandbox.io/s/priceless-moon-5e2ptf?file=/src/pages/index.js

### Steps to reproduce

import markdown mdx file with `<Tabs>`

### Expected behavior

code blocks render colored rightly.

### Actual behavior

code rendered all white/black without any highlights.

### Your environment

- Public source code:
- Public site URL:
- Docusaurus version used:
- Environment name and version (e.g. Chrome 89, Node.js 16.4):
- Operating system and version (e.g. Ubuntu 20.04.2 LTS):

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by Josh-Cena** [comment]
I can reproduce and can confirm it's not a Prism config thing. The minimum repro is:

````md
<!-- @site/src/components/_test.md -->

```yaml
apiVersion: operator.tigera.io/v1
kind: Installation
  # Configures Calico.
metadata:
  name: default
```
````

```diff
// src/pages/index.tsx
+ import Test from "@site/src/components/_test.mdx";

  export default function Home(): JSX.Element {
    const {siteConfig} = useDocusaurusContext();
    return (
      <Layout
        title={`Hello from ${siteConfig.title}`}
        description="Description will go into a meta tag in <head />">
        <HomepageHeader />
        <main>
+         <Test />
          <HomepageFeatures />
        </main>
      </Layout>
    );
  }
```

This renders a plain text block. The exact same import works in a Markdown page.

**Comment by Josh-Cena** [comment]
Ah, this is because the triple-backtick-to-code-block conversion is done through an `MDXProvider` layer which is currently undocumented. You would need to add the wrapper around imported Markdown yourself.

```jsx
+ import MDXContent from "@theme/MDXContent";
+ import Test from "@site/src/components/_test.mdx";

  export default function Home(): JSX.Element {
    const {siteConfig} = useDocusaurusContext();
    return (
      <Layout
        title={`Hello from ${siteConfig.title}`}
        description="Description will go into a meta tag in <head />">
        <HomepageHeader />
        <main>
+         <MDXContent>
+           <Test />
+         </MDXContent>
          <HomepageFeatures />
        </main>
      </Layout>
    );
  }
```

@slorber Do you think we should do anything about this? It looks working as intended to me and just requires some documentation.

**Comment by slorber** [comment]
> @slorber Do you think we should do anything about this? It looks working as intended to me and just requires some documentation.

Not sure what to do.

We could technically create a global MDX provider at the top of the tree.

At the same time, we probably want to keep and encourage usage of MDXContent as close as possible to the actual MDX content (as it was requested by someone in https://github.com/facebook/docusaurus/pull/6842 + https://github.com/facebook/docusaurus/discussions/5468#discussioncomment-1912419). Not having a default provider helped surface this issue instead of being fail-safe.

So I would probably just add some doc for this specific edge case

**Comment by Josh-Cena** [comment]
Same as what I thought. Would write some docs tonight.
