### ISSUE TITLE
"Important" admonition has "info" as label

### ISSUE THREAD

**Issue by ArtFlag** [facebook/docusaurus#7767]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Description

Hi!

I noticed that with beta.22, the admonition of type `important` is gone. Could we add docs on how to recreate such admonition type and make it available on every docs page by default?

Example:

```
:::important
Something
:::
```

and not

```
:::info Important
Something
:::
```

I'm happy to send a PR if someone knows how to do it! 

### Self-service

- [ ] I'd be willing to address this documentation request myself.

**Comment by Josh-Cena** [comment]
(I'd like to get @slorber's confirmation that it's something worth working on... IIRC the resolution last time was that these things weren't documented in the first place.)

**Comment by slorber** [comment]
So what I understand is that, now when using the undocumented `:::important` then you have the wrong label but the right level/color?

Expected:

<img width="458" alt="CleanShot 2022-07-13 at 15 21 38@2x" src="https://user-images.githubusercontent.com/749374/178743665-f48f8ebd-2f40-41ab-a04f-94927bcb2eb7.png">


Actual:

<img width="547" alt="CleanShot 2022-07-13 at 15 20 56@2x" src="https://user-images.githubusercontent.com/749374/178743590-51c3ef55-2a21-4a03-a193-c4854af80753.png">

---

It would be quite easy to restore the label using swizzle now that the admonitions are mapped to a real theme components. 

But everything is in one file so this requires ejecting a large API surface: we should probably split it to make it more convenient to swizzle.

But I'd also be ok if we added a retro-compatible label to the previously supported (but undocumented) admonition "aliases"

**Comment by societymartingale** [comment]
Is there any documentation on how to swizzle an admonition label or svg?

**Comment by ArtFlag** [comment]
not at the time I opened this issue, but I'd be happy to contribute if someone shows me how to do it 👍

**Comment by Josh-Cena** [comment]
@ArtFlag Our admonition logic is entirely here: https://github.com/facebook/docusaurus/blob/main/packages/docusaurus-theme-classic/src/theme/Admonition/index.tsx

It's a bit tricky, because you still want to keep it as an alias so we don't duplicate the SVG/class name. At the same time, we need to add four new translated labels. For the initial version, you can do it however you want—we can discuss about the actual implementation later.

Remember, you can also do this in userland through ejecting `Admonition`. If you get it to work in your own code, you can make it work in our codebase as well!
