### ISSUE TITLE
images are updated on the server, but docusaurus show the old images

### ISSUE THREAD

**Issue by tesla-cat** [facebook/docusaurus#7785]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [ ] I have tried the `npm run clear` or `yarn clear` command.
- [ ] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [ ] I have tried creating a repro with https://new.docusaurus.io.
- [ ] I have read the console error message carefully (if applicable).

### Description

- images are updated on the server, but docusaurus show the old images
- how can I add something like the following to disable browser cache?

```html
<meta http-equiv='cache-control' content='no-cache'>
<meta http-equiv='expires' content='0'>
<meta http-equiv='pragma' content='no-cache'>
```

### Reproducible demo

na

### Steps to reproduce

na

### Expected behavior

show new image with the same `src` but different content

### Actual behavior

shows the old image

### Your environment

- Public source code:
- Public site URL:
- Docusaurus version used:
- Environment name and version (e.g. Chrome 89, Node.js 16.4):
- Operating system and version (e.g. Ubuntu 20.04.2 LTS):

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by Josh-Cena** [comment]
Cache control is best set on CDN. For example:

https://github.com/facebook/docusaurus/blob/7f40350d6e102fb66a3283c97331699269289530/website/static/_headers#L5-L8

If you want to set meta tags, you can use `metadata`: https://docusaurus.io/docs/seo#global-metadata

Note that it also depends on how the images are included. If you use Markdown image syntax like `![](./img.png)`, we should be able to hash it so that every time it updates, the URL changes as well. But in any case, this is not a Docusaurus defect—we don't control your server behavior or cache control.
