### ISSUE TITLE
Trailing slashes in link causing next/prev buttons to break

### ISSUE THREAD

**Issue by JoelMarcey** [facebook/Docusaurus#780]
### Is this a bug report?

Yes

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/Docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

### Environment

Docusaurus 1.1.5 or 1.2.0

### Steps to Reproduce

https://github.com/babel/website/issues/1693

### Expected Behavior

Links work

### Actual Behavior

Links don't work

### Reproducible Demo

I think Babel fixed the issue by removing the `/` from the links in https://github.com/babel/website/issues/1693

**Comment by endiliey** [comment]
This is actually caused by how relative path in href works.

In `https://babeljs.io/docs/en/babel-plugin-transform-runtime`
href of `babel-register` will translate to `https://babeljs.io/docs/en/babel-register`

In `https://babeljs.io/docs/en/babel-plugin-transform-runtime/`
href of `babel-register` will translate to `https://babeljs.io/docs/en/babel-plugin-transform-runtime/babel-register`
