### ISSUE TITLE
"Edit" button does not respect the version of the doc

### ISSUE THREAD

**Issue by machikoyasuda** [facebook/Docusaurus#794]
### Is this a bug report?

Yes

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/Docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Of course!11

### Environment

(Docusaurus version via `npm outdated docusaurus` or `yarn outdated docusaurus`, OS, Node, npm, yarn)

1.2.1

### Steps to Reproduce

(Write your steps here:)

1. Go to https://docusaurus.io/versions
2. Choose a non-master version, like `1.0.11`
3. Go to a doc, like: https://docusaurus.io/docs/en/1.0.11/commands#docusaurus-start-port-number
4. Click `Edit`

### Expected Behavior

I expect to edit the 1.0.11 version of `api-commands.md`, not master's `api command.md`. I should be taken https://github.com/facebook/Docusaurus/edit/master/website/versioned_docs/version-1.0.11/api-commands.md, not https://github.com/facebook/Docusaurus/edit/master/docs/api-commands.md

### Actual Behavior

Clicking on Edit take me to master: https://github.com/facebook/Docusaurus/edit/master/docs/api-commands.md

### Reproducible Demo

Reproduced on docusaurus.io

**Comment by endiliey** [comment]
I think this might be intended. Changes are only made for `next` docs.

Let's say we are currently at 1.0.13. There is a typo that has occured since version `1.0.11`. 
With the proposed behavior, if we fix the typo of the docs in 1.0.11, the typo will still occurs in 1.0.12 and 1.0.13.

But I do agree that the current behavior is slightly weird as well.
