### ISSUE TITLE
"You are trying to create client-side redirections to paths that do not exist" to folders without trailing slash

### ISSUE THREAD

**Issue by SheetJSDev** [facebook/docusaurus#8016]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [ ] I have tried the `npm run clear` or `yarn clear` command.
- [ ] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [ ] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

For paths to folders without a trailing slash, hosts will typically 302 redirect to the path with the slash

e.g. https://docs.sheetjs.com/docs/getting-started redirects to https://docs.sheetjs.com/docs/getting-started/

`@docusaurus/plugin-client-redirects` does not seem to be aware of this behavior for folders that have subfolders.

This redirect works

```js
        { from: '/docs/installation', to: '/docs/getting-started/' }, // works
```

This redirect elicits the error mentioned in the title:

```js
        { from: '/docs/installation', to: '/docs/getting-started' }, // elicits error
```

The fact that it works for leaf folders that only have `index.html` suggests this is a bug in the redirect scanner:

```js
        { from: '/docs/example', to: '/docs/getting-started/example' }, // this works, even though `example` is a folder
```

### Reproducible demo

https://github.com/SheetJS/docs.sheetjs.com

### Steps to reproduce

```bash
git clone --depth=1 https://github.com/SheetJS/docs.sheetjs.com
cd docs.sheetjs.com/docz
npm i
npm run build ## note: this should work
sed -I '' "s#started/'#started'#g" docusaurus.config.js
npm run build ## this will fail with the aforementioned error
```

If the `sed` command fails, the edit is in `docusaurus.config.js`:

```diff
       redirects: [
         { from: '/docs/example', to: '/docs/getting-started/example' },
-        { from: '/docs/installation', to: '/docs/getting-started/' },
+        { from: '/docs/installation', to: '/docs/getting-started' },
       ]
     }]
```

### Expected behavior

It should create the redirect

### Actual behavior

```
[ERROR] Error: You are trying to create client-side redirections to paths that do not exist:
```

The path in question is not listed in the valid paths

### Self-service

- [X] I'd be willing to fix this bug myself.

**Comment by Josh-Cena** [comment]
Interesting! If you want to investigate this further and share what you found, I'm all ears.

**Comment by SheetJSDev** [comment]
In a structure like:

```
/docs/index.md
/docs/foo/index.md
/docs/foo/bar.md
```

When `trailingSlash` is undefined, the `routesPaths` key exposed to in the postBuild props is:

```
[
  "/docs/",
  "/docs/foo/",
  "/docs/foo/bar"
]
```

Those paths are used in the validation.

One way to resolve the issue without disrupting other plugins is to add both slash variants to the validation.

https://github.com/facebook/docusaurus/blob/4b5a47ba37ffdfbcf46e23790ff0cfe6c4745e14/packages/docusaurus-plugin-client-redirects/src/collectRedirects.ts#L81

```ts
const allowedToPaths = pluginContext.relativeRoutesPaths.flatMap(x => { const y = x.replace(/\/+$/, ""); return [y, y + "/"] });
```

**Comment by Josh-Cena** [comment]
We have a few utility functions to do that normalization I believe. But thanks for the info! It makes sense. I think for `trailingSlash: undefined` only, we should accept both alternatives.

**Comment by slorber** [comment]
> For paths to folders without a trailing slash, hosts will typically 302 redirect to the path with the slash

That's not 100% correct. GitHub Pages does it, not all others, or at least it depends on their configuration.

That would be worth mentioning that you are using GitHub Pages + Cloudflare on top (seen that in request headers).

Note our doc recommends to use an explicit `trailingSlash` setting for GitHub Pages:

https://docusaurus.io/docs/deployment#deploying-to-github-pages

<img width="716" alt="CleanShot 2022-08-31 at 16 27 05@2x" src="https://user-images.githubusercontent.com/749374/187703254-e0a3bd92-77f4-4222-8024-3b3a477f4ef7.png">

In my experience, this is particularly important if you use relative links such as `[xyz](./xyz)` (which we also don't particularly advice) where the link would resolve differently according to the presence/absence of a trailing slash in the current URL.

And you'll notice that you can in practice browse the page with both URLs:
- GitHub pages add a trailing slash on the initial page load: `https://docs.sheetjs.com/docs/getting-started/example/`
- Docusaurus will not add a trailing slash after any SPA navigation: `https://docs.sheetjs.com/docs/getting-started/example`

Really, you'd better to use an explicit setting.

---

> [ERROR] Error: You are trying to create client-side redirections to paths that do not exist:

That would be convenient to paste the full error message instead of just the beginning 😅 

---

> One way to resolve the issue without disrupting other plugins is to add both slash variants to the validation.

> I think for trailingSlash: undefined only, we should accept both alternatives.

👍 seems reasonable

**Comment by SheetJSDev** [comment]
The explanation makes sense and we can send a PR.

@slorber The site started from the default config (`npx create-docusaurus@latest`).  The default site does not include the `trailingSlash` setting.  If it is strongly encouraged to use a default setting, should the default site include some `trailingSlash` setting?

**Comment by slorber** [comment]
Happy to review your PR

> @slorber The site started from the default config (npx create-docusaurus@latest). The default site does not include the trailingSlash setting. If it is strongly encouraged to use a default setting, should the default site include some trailingSlash setting?

We recommend an explicit trailing slash, but only for Github Pages users, not all users.

I wouldn't recommend GitHub pages in the first place, Vercel/Netlify are much better alternatives and you don't always need to use the trailingSlash setting with those.
