### ISSUE TITLE
Inconsistent rendering of sidebar items

### ISSUE THREAD

**Issue by motionsuggests** [facebook/docusaurus#8122]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [X] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

Inline code using back ticks (`) in Headings render in Inconsistently in sidebars, specifically h1's. Left side nav renders the backticks. 

Example:
```md
# Tutorial Intro `code`

Let's discover **Docusaurus in less than 5 minutes**.

## Getting Started `Hello`
```
<img width="1146" alt="Screen Shot 2022-09-21 at 4 17 10 PM" src="https://user-images.githubusercontent.com/181652/191604316-07df4ed9-2257-493e-ab64-bcad99cdafcb.png">

Currently working around this issue by using `sidebar_label` in front matter.

### Reproducible demo

https://stackblitz.com/edit/github-lt39oq?file=docs%2Fintro.md

### Steps to reproduce

1. scaffold new site with `npx create-docusaurus@latest my-website classic`
2. go to `docs/intro.md` and change heading to '# Tutorial Intro \`code\` '
3. see inconsistent rendering

### Expected behavior

I would assume the left nav and breadcrumbs strip markdown syntax or render consistently .

### Actual behavior

Inconsistent rendering.

<img width="1146" alt="Screen Shot 2022-09-21 at 4 17 10 PM" src="https://user-images.githubusercontent.com/181652/191604316-07df4ed9-2257-493e-ab64-bcad99cdafcb.png">

### Your environment

- Public source code: N/A
- Public site URL:N/A
- Docusaurus version used: 2.1.0
- Environment name and version (e.g. Chrome 89, Node.js 16.4): Chrome 104.0.5112.101 
- Operating system and version (e.g. Ubuntu 20.04.2 LTS): Mac OS 12.5.1

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by Josh-Cena** [comment]
This is working as intended. The sidebar title metadata is a simple string, not a JSX element—it's always statically extracted from content via a simple regex before the Markdown is even parsed. In order to render this, we would have to ship an ad-hoc Markdown parser to the client side, which doesn't seem worth it. TOC doesn't suffer from this, because it's generated on-the-spot during Markdown parsing, so it readily benefits from the already-parsed Markdown AST. Please use `sidebar-title: Tutorial intro code` to avoid rendering code at all—in general we don't support using typography in sidebar titles, pagination titles, breadcrumb titles, etc., because it would be a huge undertaking.

**Comment by motionsuggests** [comment]
This makes sense. Thank you for the prompt response.
