### ISSUE TITLE
baseUrl issues with Static Hosting Vercel and Netlify. 

### ISSUE THREAD

**Issue by Mr-spShuvo** [facebook/docusaurus#8138]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [ ] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

Hi, we are trying to build our documentation website with docusaurus. We are closed to launch our product. But we are facing problems with the deployment. We are trying to host the website with vercel. The problem we are stated below. 

We configured Docusaurus baseUrl to `/en/` and deployed to vercel. Locally it builds completely fine. 
But on vercel we are getting 

Your Docusaurus site did not load properly.
A very common reason is a wrong site [baseUrl configuration](https://docusaurus.io/docs/docusaurus.config.js/#baseurl).
Current configured `baseUrl = /en/`
We suggest trying `baseUrl = /`

Also, it looks like when I did go to the `site/en/` vercel is trying to find everything on `build/en/` folder. 
But if I change the build directory to `build/en/`, it looking of `build/en/en/`. 
I tried to search through github issues, tried few things. Nothing worked.
Any help or insights will be appreciated.

Here is my **docusaurus.config.js**

```js
const config = {
  title: 'Agora Documentation',
  tagline:
    'Agora SDKs  is built for Live, interactive voice and video powered by the only global network dedicated to real-time engagement at ease.',
  url: process.env.URL, // https://docs-test-q239acpv9-agora-gdxe.vercel.app/
  baseUrl: process.env.BASE_PATH,  // /en/
  trailingSlash: false,
...
```

Link: https://docs-test-q239acpv9-agora-gdxe.vercel.app/
![image](https://user-images.githubusercontent.com/22437186/192532739-271c055a-bbc9-4ed7-ba25-9c37abfa454a.png)

### Steps to reproduce

-

### Expected behavior

-

### Actual behavior

-

### Your environment

- Public source code:
- Public site URL:
- Docusaurus version used:
- Environment name and version (e.g. Chrome 89, Node.js 16.4):
- Operating system and version (e.g. Ubuntu 20.04.2 LTS):

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by tarjelavik** [comment]
Hi, just to confirm, i have to exact same issue on Vercel. I am trying to create a zone between two apps, but have not managed to get baseUrl to work. 

Deployed with Vercel CLI.

**Comment by slorber** [comment]
Hey,

If you want to use `baseUrl: 'en'` then you should access should deployment on this URL: https://docs-test-q239acpv9-agora-gdxe.vercel.app/en/

You will note the following status code:

- 200 on https://docs-test-q239acpv9-agora-gdxe.vercel.app/
- 404 on https://docs-test-q239acpv9-agora-gdxe.vercel.app/en/

We can also see the problem on the CSS file it tries to load:
- 200: https://docs-test-q239acpv9-agora-gdxe.vercel.app/assets/css/styles.d682a47f.css
- 404: https://docs-test-q239acpv9-agora-gdxe.vercel.app/en/assets/css/styles.d682a47f.css (actually it redirects to our 404.html file 🤪 )

This means that you didn't deploy your site properly under the `/en/` folder but instead deployed the static assets at the root => not good, the `/en/` subfolder is really mandatory to deploy


---

I don't understand how you happen to not deploy the correct folder with the correct path on Vercel, because you neither show your Vercel build command, deploy config nor what running this command locally builds as a Docusaurus tree, so it's really hard to debug.

Have you tried uploading manually the files from your computer to Vercel?

Note: if you build with `yarn build --locale en`, Docusaurus does not output to `build/en` but instead to just `build`: that may be the problem? 🤷‍♂️
