### ISSUE TITLE
Anchor links do not get scrolled to correctly (on production)

### ISSUE THREAD

**Issue by becca-tiessen** [facebook/docusaurus#8171]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [ ] I have tried the `npm run clear` or `yarn clear` command.
- [ ] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [X] I have tried creating a repro with https://new.docusaurus.io.
- [ ] I have read the console error message carefully (if applicable).

### Description

When a URL includes an anchor tag and is pasted into a new tab, the site does not scroll automatically to the anchor tag. I realize this has been [previously reported](https://github.com/facebook/docusaurus/issues/6176), but I think this is a different issue, because I can reproduce it on our production website as well as the Docusaurus demo site (not just a local dev problem).

### Reproducible demo

https://codesandbox.io/s/nameless-frost-nth7gg

### Steps to reproduce

1. Open demo sandbox and open browser in a new window
2. Go to a page and find a heading (e.g. https://nth7gg.sse.codesandbox.io/docs/tutorial-basics/markdown-features#code-blocks)
3. Copy the URL and open a new tab, paste the URL
4. Notice that the page does not scroll to the heading that was specified

(If the sandbox doesn't work for any reason, you could just open a new instance of the playground and reproduce this as well; no changes are required to reproduce)

### Expected behavior

I expected the anchor link to cause the page to be scrolled to the heading that was specified.

### Actual behavior

The page is navigated to, but no scrolling is applied when anchor tags are present in the URL. 

### Your environment

- Public source code: N/A (not public)
- Public site URL: https://developer.boldcommerce.com/default/guides/getting-started/quick-start#create-an-account
- Docusaurus version used: 2.1.0
- Environment name and version (e.g. Chrome 89, Node.js 16.4): Chrome 105.0.5195.125 

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by Josh-Cena** [comment]
> as well as the Docusaurus demo site

Do you mean our deployed site? Do you have a link?

**Comment by becca-tiessen** [comment]
Hmm I forgot about the deployed site actually, I was referencing the playground/sandbox link that I used for the reproducible demo.

But I just checked the official deployed site with a link like this: (https://docusaurus.io/docs/styling-layout#mobile-view) and it does work... Are there significant differences between the deployed site and the playground environment? It looks to me like they're using the same version (2.1.0).

**Comment by slorber** [comment]
@becca-tiessen when I access your url here:

https://developer.boldcommerce.com/default/guides/getting-started/quick-start#create-an-account

There is a "flash" where a banner appears first and then it gets replaced by the real content. The initial content does not contain the hash this is why it doesn't work.

You can debug with JS disabled (there are chrome plugins to easily disable it), this page will show:
https://developer.boldcommerce.com/default/guides/getting-started/quick-start#create-an-account


<img width="1916" alt="CleanShot 2022-10-07 at 16 15 41@2x" src="https://user-images.githubusercontent.com/749374/194574794-555bfe9b-c757-4be1-b72a-ef0d663f76a9.png">

This likely means to me that your host is serving the wrong static file, the one that represents your landing page (`/index.html`) instead of  the file it is supposed to serve `/default/guides/getting-started/quick-start.html`

You either configured your host badly, or you did not upload your Docusaurus static site correctly to that host. That's outside the scope of Docusaurus. Once you fix those hosting issues, the anchor links should work.

**Comment by becca-tiessen** [comment]
Ah ok, I've checked with the rest of my team and we do have a hybrid setup that has caused us some issues in the past, sounds like we'll be adding this problem to the list.

Thanks so much for the explanation and for looking into this; much appreciated. My eyes ignored the flash before but it's obvious now. 👍
