### ISSUE TITLE
Mobile doc nav has a 1px seam

### ISSUE THREAD

**Issue by chenglou** [facebook/Docusaurus#820]
### Is this a bug report?

Yes

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/Docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

### Environment

Docusaurus 1.3.0, iOS 11 mobile safari, iPhone X

### Steps to Reproduce

1. Visit a docusaurus site in mobile browser
2. Scroll down main page
3. See a seam between the header and the nav

### Expected Behavior

No seam

### Actual Behavior

Seam: ![img_fa9168f1a413-1](https://user-images.githubusercontent.com/1909539/42131121-588c5ece-7caf-11e8-94e7-5500af0fd53f.jpeg)

### Reproducible Demo

Visit reasonml.github.io on mobile safari

**Comment by KoenCa** [comment]
Hi! Can I solve this issue?

**Comment by yangshun** [comment]
@KoenCa it's yours!

We've added an "issue: claimed" label so that others will know not to start work on the issue. If you change your mind about the issue, no worries! Just let me know so that I can remove the label and free it up for someone else to claim.

I'll check in with you periodically so that we can keep the task updated with the progress.

**Comment by endiliey** [comment]
@wszgxa feel free to send a PR.

**Comment by yangshun** [comment]
@wszgxa Just a heads up, this issue may not be worth fixing because it's quite a small issue (had trouble reproducing the issue reliably), doesn't affect too many users, and a solution may involve dirty hacks.

**Comment by endiliey** [comment]
#1152
