### ISSUE TITLE
can we add a new function: read summary.md as sidebar

### ISSUE THREAD

**Issue by linkdao** [facebook/docusaurus#8223]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Description

there are too many document base gitbook or othes solution press，if we develop a new function make it easy to migrate. the roblems I encountered during the migration process is rearrange navigation ,the sidebar.js file  requires patience and careful verification . so if we have this function can simplifies the migration process and increases welcome. my requirement is：read directly summary.md file as sidebar thanks.

### Motivation

Improve user experience

### Self-service

- [X] I'd be willing to contribute this feature to Docusaurus myself.

**Comment by Josh-Cena** [comment]
This issue is too underdeveloped to be actionable. Without a detailed API design and/or motivation/field research, please send it as a [Canny request](https://docusaurus.canny.io/) first, as the issue chooser has asked. Autogenerated should suffice in almost all cases and results in you writing nothing at all.

**Comment by slorber** [comment]
It's hard to understand what this issue is about. 

But... I'll still try to be helpful:
- we support `index.md` and `readme.md` for autogenerated category index, not `summary.md`
- this naming convention can be customized, so you can implement support for `summary.md` yourself

https://docusaurus.io/docs/sidebar/autogenerated#category-index-convention
