### ISSUE TITLE
Local dev environment shows correct file structure, but prod has a duplicate

### ISSUE THREAD

**Issue by debbly** [facebook/docusaurus#8232]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [X] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

Duplicate folder showing on nav on left hand side on production. This does not show within the local dev environment. 

What we've tried: clearing the cache and redeploying, but still same error.

Dev environment
<img width="325" alt="Screen Shot 2022-10-19 at 9 51 58 AM" src="https://user-images.githubusercontent.com/5404516/197028100-1991019e-ebdc-43b5-b6b9-3aed163fadff.png">

On netlify/docasaurus
<img width="304" alt="Screen Shot 2022-10-19 at 9 52 06 AM" src="https://user-images.githubusercontent.com/5404516/197028143-693a0415-95f1-4abb-a821-0c3c8236b097.png">

### Reproducible demo

https://github.com/LIT-Protocol/docs

### Steps to reproduce

1. Pull repo and do a fresh install
2. `yarn; yarn start; yarn build` -> check localhost:3000, dev build shows the correct format
3. If you open a pull requests on the Lit docs, the netlify preview will show the incorrect format on the left hand side

### Expected behavior

Expectation:
<img width="325" alt="Screen Shot 2022-10-19 at 9 51 58 AM" src="https://user-images.githubusercontent.com/5404516/197028498-565154f9-6220-462c-82fb-6a03f7f4a4cb.png">

### Actual behavior

Actual behavior
<img width="304" alt="Screen Shot 2022-10-19 at 9 52 06 AM" src="https://user-images.githubusercontent.com/5404516/197028541-cbf7050c-d3eb-43f2-96d0-c1e7dbe87035.png">

### Your environment

- Public source code: https://github.com/LIT-Protocol/docs
- Public site URL: https://developer.litprotocol.com/
- Docusaurus version used: @docusaurus/core@2.1.0
- Environment name and version (e.g. Chrome 89, Node.js 16.4): Chrome 
- Operating system and version (e.g. Ubuntu 20.04.2 LTS): macOS Big Sur

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by Josh-Cena** [comment]
Hi! Your [docs folder](https://github.com/LIT-Protocol/docs/tree/main/docs) have two `Ecosystem` folders:  `docs/Ecosystem` and `docs/ecosystem`. Whether they are treated as the same directory is system-dependent. Linux is case-sensitive, so these become two distinct categories on your CI environment. However, locally, Windows and macOS both see them as the same directory because these file systems are case-insensitive. Therefore when we query the FS API, we get the information that only one folder called `Ecosystem` exists, and there's no way for us to align the behavior here. See also: https://github.com/facebook/docusaurus/issues/7896
