### ISSUE TITLE
change-icon-for-page-previews

### ISSUE THREAD

**Issue by jcstein** [facebook/docusaurus#8304]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Description

I'd like to change the icon in the pink box in the screenshot attached, but I can't find guidance on how to do this in the docs. Is this possible?

<img width="319" alt="Screenshot 2022-11-08 at 4 31 33 PM" src="https://user-images.githubusercontent.com/46639943/200680758-a8311665-4988-4180-8f9a-274a955bdde4.png">

### Motivation

Looking to add variation on pages with multiple link card previews.

### Self-service

- [x] I'd be willing to contribute this feature to Docusaurus myself.

**Comment by slorber** [comment]
We don't have an API for that apart using [swizzle](https://docusaurus.io/docs/swizzling) on the `DocCard` component.

It's unlikely we implement anything like this in the future because there are tons of way to provide an icon (React, emoji, font icon, SVG, SVGR...) and we wouldn't be able to find a good API that satisfies all usages. Swizzle remains the most flexible option for such use-cases.

**Comment by jcstein** [comment]
thank you @slorber - can you point me to more information on the `DocCard` component?

**Comment by slorber** [comment]
> thank you @slorber - can you point me to more information on the `DocCard` component?

I'm not sure what information you want exactly. 

Have you read the doc and tried to swizzle? I won't write you a step by step tutorial so please read the doc and report what exactly is unclear. We'll improve the doc for all instead of helping a single user.
