### ISSUE TITLE
Redirect not work with relative path

### ISSUE THREAD

**Issue by tisonkun** [facebook/docusaurus#8317]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Prerequisites

- [ ] I'm using the latest version of Docusaurus.
- [ ] I have tried the `npm run clear` or `yarn clear` command.
- [ ] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [ ] I have tried creating a repro with https://new.docusaurus.io.
- [ ] I have read the console error message carefully (if applicable).

### Description

Well, I'm using the 2.0.1 version.

If you open https://pulsar.apache.org/docs/standalone, although its source content is:

`````mdx
---
id: standalone
title: Set up a standalone Pulsar locally
sidebar_label: "Run Pulsar locally"
---

````mdx-code-block
import {Redirect} from '@docusaurus/router';

<Redirect to="getting-started-standalone" />
````

`````

It's redirected to https://pulsar.apache.org/docs/standalone/getting-started-standalone instead of https://pulsar.apache.org/docs/getting-started-standalone.

Moreover, it works well when previewing locally.

### Steps to reproduce

As described above.

### Expected behavior

Correctly redirected to https://pulsar.apache.org/docs/getting-started-standalone.

### Actual behavior

Wrongly redirected to https://pulsar.apache.org/docs/standalone/getting-started-standalone.

### Your environment

- Public source code: https://github.com/apache/pulsar-site/tree/main/site2/website-next
- Public site URL: https://pulsar.apache.org/docs/standalone
- Docusaurus version used: 2.0.1
- Environment name and version (e.g. Chrome 89, Node.js 16.4):
- Operating system and version (e.g. Ubuntu 20.04.2 LTS):

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by slorber** [comment]
This is due to your host doing a server-side redirect to `standalone/` so the relative link is resolved client-side in a different way

<img width="1092" alt="CleanShot 2022-11-10 at 12 30 28@2x" src="https://user-images.githubusercontent.com/749374/201079993-b88f97e9-0946-46b9-b125-92188afd0235.png">

You may have configured `trailingSlash` incorrectly for your specific host, leading to issues. Make sure all URLs are always served with/without a trailing slash consistently, and adjust your relative links accordingly

**Comment by tisonkun** [comment]
Thank you!
