### ISSUE TITLE
Improve the docs or error message for blog has no active contents

### ISSUE THREAD

**Issue by tomohirohiratsuka** [facebook/docusaurus#8331]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Description

It would be great if we can get what is going wrong on our codes specifically from error messages.

For now, if the `/blog` dir doesn't have any contents or every contents have draft=true flag in front matter, docusaurus build will be failed with showing error that `Error: Docusaurus found broken links! -> linking to /blog.`

It's very helpful for everyone if the error also show some hints for reasons like "You may have no active contents in your /blog. To pass build you should have at least an active content in your /blog directory."

I know this only may affect for beginners so improving documentation may be enough for this.

### Self-service

- [X] I'd be willing to address this documentation request myself.

**Comment by slorber** [comment]
Hey

Docusaurus can build even if there's no content in your blog.

This error message is accurate to me: you have a link somewhere that points to `/blog`, but this URL doesn't exist on your site, and the generic broken link checker of Docusaurus simple reports it to you to prevent deploying a site with broken links.

This broken link checker is a last-resort check. It is unopinionated and doesn't know what a blog post even is. It is unlikely to ever print clever hints like "you have all your blog posts with the draft frontmatter" because it would mean coupling our core logic to a specific plugin.

---

Unfortunately, I'm not sure how to improve the DX.

If you have all your blog posts as draft, it makes sense that they are all displayed in dev, but not displayed at all in prod.

If your navbar/footer contains a link to `/blog`, this only makes sense in dev, and not in prod, but how can we explain this? Remember we have a plugin/theme decoupled architecture. The blog plugin doesn't know what a theme navbar is, and some themes might use the blog plugin without any navbar navigation in the future.

**Comment by slorber** [comment]
Going to close because I don't see a clear solution to improve the DX considering our modular architecture.

If you have any suggestion that is technically possible to implement, I'm still open to hear it.
