### ISSUE TITLE
Optional Header & Footer disable (display content only) for embedded environments with query params

### ISSUE THREAD

**Issue by softmarshmallow** [facebook/docusaurus#8332]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Motivation

<img width="1680" alt="Screen Shot 2022-11-13 at 6 50 15 PM" src="https://user-images.githubusercontent.com/16307013/201515832-04fed540-f9d7-4627-b4cc-4dd163d4b7bf.png">

I'm planning to use my docs site for other app's help panel with iframe embed. The problem is that it show the docs site as-is, not optimized for panel embedding.

These are the things I want to configure with extra query params provided

- ?theme=dark
- ?header=0
- ?footer=0

So for example, the final url for the embedding would be , e.g., https://grida.co/docs/with-figma/guides/how-to-get-personal-access-token?theme=dark&header=0&footer0

### Self-service

- [ ] I'd be willing to do some initial work on this proposal myself.

**Comment by slorber** [comment]
Hi

Docusaurus outputs static files, for which the header/footer is always present.

It is not possible to use a query string to dynamically create a different HTML output without the layout elements.

However it should be technically possible to read the query string on page load, and immediately hide the layout elements using JS + CSS through a Docusaurus client module with code like this:

```tsx
import ExecutionEnvironment from '@docusaurus/ExecutionEnvironment';

if (ExecutionEnvironment.canUseDOM) {
  const queryString = new URLSearchParams(window.location.search);
  if (queryString.get('navbar') === '0') {
    const navbar = document.getElementsByTagName('nav')[0]!;
    navbar.style.display = 'none';
  }
}
```

Note this is pseudo code and you'll have to figure out the details if you want to use this solution.

---

But it doesn't take into consideration multiple things, including the fact that you have to define the behavior you want when you navigate through a link inside your document:
- should it navigate the iframe directly
- and how will that qiuerystring be preserved on the target URL?
- should it open the link in a new tab? 
- should it send a postMessage to parent so that it can act on it? 

For all these reasons I believe we need a proper solution for embedding documents in an iframe, that is flexible enough to allow you to define exactly the behavior you want here.

My idea for a proper official solution would be to have a "document variant" API where you can create alternative HTML static outputs for the same file.

So I'm closing this issue in favor of https://github.com/facebook/docusaurus/issues/7480
