### ISSUE TITLE
Mermaid incorrect "Syntax error in graph"

### ISSUE THREAD

**Issue by wenerme** [facebook/docusaurus#8333]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [ ] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

Source https://github.com/wenerme/wener/blob/master/notes/languages/diagram/mermaid.md
Output https://wener.me/notes/languages/diagram/mermaid
Build log https://github.com/wenerme/wener/actions/runs/3454557726/jobs/5765939898#step:8:295

<img width="480" alt="image" src="https://user-images.githubusercontent.com/1777211/201517698-a766f7a8-6369-47f8-b892-1fe97a900ad0.png">

### Reproducible demo

https://github.com/wenerme/wener

### Steps to reproduce

```bash
git clone git@github.com:wenerme/wener.git
cd wener/site

pnpm install
make build
```

### Expected behavior

Mermaid works as expected

### Actual behavior

Syntax error in graph

### Your environment

- Public source code: https://github.com/wenerme/wener
- Public site URL: https://wener.me
- Docusaurus version used: 2.2
- Environment name and version (e.g. Chrome 89, Node.js 16.4):
- Operating system and version (e.g. Ubuntu 20.04.2 LTS):

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by wenerme** [comment]
@slorber The error is not caused by Mermaid.js, use the newer syntax, 

````
```mermaid
graph TD;
    A-->B
    A-->C
    B-->D
    C-->D
```
````

with the config

```js
{
  markdown: {
    mermaid: true,
  },
  themes: [
    '@docusaurus/theme-live-codeblock',
    '@docusaurus/theme-mermaid',
  ],
}
```

https://github.com/wenerme/wener/blob/bc57f0d06ae1f98eb0bc42dab9a9d54ba88db406/site/docusaurus.config.js#L288-L294

**Comment by slorber** [comment]
🤷‍♂️ please create a smaller repo, and test your integration on that smaller repro. Otherwise I won't try to help.

Your issue is unclear (what does not work exactly? You don't really tell and I can only guess) and your repro is too big and your theme component overrides the default mermaid behavior.

**Comment by wenerme** [comment]
Thank for your time, I will look deeper, another next+mdx project has the same problem, seems not related to docusaurus.

**Comment by slorber** [comment]
`theme/Mermaid` is the theme component name we use now. If you need 2 different Mermaid systems to co-exist in parallel for whatever reason, you'll have to rename the older `theme/Mermaid` component otherwise it overrides the official one with very different behavior.

I can't guarantee that 2 distinct mermaid systems can coexist on the same Docuaurus site nicely. If you want to have that, you'll have to figure out the details

**Comment by wenerme** [comment]
Thanks, I don't know 2.2 use Mermaid as theme component, will rename this to another name.
