### ISSUE TITLE
Internationalization with multiple docs plugins

### ISSUE THREAD

**Issue by tyzion** [facebook/docusaurus#8367]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [X] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

Hi, I'm trying to translate a multi-docs website.

Since I've changed my docusaurus.config.js for the multi-docs configuration, I couldn't translate my website anymore.

I've created a repository on github with 2 docusaurus.config file. The first one is for the multi-docs, the second one is for a single doc plugin.

Could you please tell me what I'm doing wrong?

P.s. I noticed that using multiple-docs plugin, it will translate .md files in the /docs folder (those will appear only in the default docs).

### Reproducible demo

https://github.com/tyzion/docusaurus

### Steps to reproduce

1. Start the project with --locale it
2. Make changes in files inside the i18n folder

### Expected behavior

Files rendered should be those inside i18n/ folder

### Actual behavior

Docusaurus is reading files from docs/ folder

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by slorber** [comment]
Hi

This is more a question / support request than a bug, so I'm closing. 
You can ask on Discord for support, and if nothing help open a github discussion instead of an issue.

In your case you have 2 plugin instances so you have to have 2 i18n folders for docs, as documented here:

https://docusaurus.io/docs/api/plugins/@docusaurus/plugin-content-docs#translation-files-location

Multi-instance path: `website/i18n/[locale]/docusaurus-plugin-content-docs-[pluginId]`

We can see on your site that you only have 1 folder. You should split this folder in 2, one for legal, one for tutorial.
https://github.com/tyzion/docusaurus/tree/main/i18n/it/docusaurus-plugin-content-docs

- `i18n/it/docusaurus-plugin-content-docs/current` for tutorial docs
- `i18n/it/docusaurus-plugin-content-docs-legal/current` for legal docs

I can understand how it is confusing. Hopefully I'll add soon the ability to just do something like `tutorial.md` + `tutorial.it.md` which will make it simpler for git-based translations

**Comment by tyzion** [comment]
Hi @slorber,

Sorry to have opened an issue, didin't know the existance of discussions.
I've tried on Discord too, but no one answered me.

Anyway thank you so much! I just made it work.
I totally misunderstood the `website/i18n/[locale]/docusaurus-plugin-content-docs-[pluginId]` part, sorry!

It would be an awesome way to translate the website!
All the best and thanks again!
