### ISSUE TITLE
Documentation about versioning across branches rather than a single directory

### ISSUE THREAD

**Issue by hasezoey** [facebook/docusaurus#8373]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Description

I have noticed that docusaurus lacks documentation about versioning across different branches rather than a single branch with a versioned directory, even if it is just a note about not being supported.

---

I wanted to set-up versioning for my project which uses separate branches for older versions (like `master` for current version, `old/vX` for older versions) and i have read that docusaurus supports versioning across branches, but i cannot find any documentation (even outside of the official documentation) regarding setting this up.
The only vaguely similar things i found are basically `setup a reverse proxy` or `depend on immutability from your provider`, which is not really great for `github pages` or other static-only providers.

### Self-service

- [ ] I'd be willing to address this documentation request myself.

**Comment by slorber** [comment]
Hey

We don't document this because somehow it's a bit outside the scope of Docusaurus. 

If you have versioned git branches; and put docs inside them, then you implicitly have versioned documentation too, and you are able to build a different Docusaurus site for each of those.

So basically you have multiple single-version Docusaurus sites (one per git Branch). And a single-version/unversioned Docusaurus site is actually documented.

It is now your responsibility to deploy/link these different sites together the way you want. There are many ways to do that, including a hybrid mode (like we do on our own website) where very old versions are archived and newer versions are in the `main` branch. You can decide to deploy older versions on immutable deployments, on a subdomain, on a subpath of your main domain... it's really up to you.

> The only vaguely similar things if found are basically setup a reverse proxy or depend on immutability from your provider, which is not really great for github pages or other static-only providers.

As far as I know GitHub pages can only deploy one Git branch `gh-pages` so if you want to publish multiple versions on GitHub pages you have to assembly a single static deployment containing all the versions. That's easier if you build one multi-version Docusaurus site, but it is indeed possible to create such static deployment using multiple unversioned docusaurus sites found on multiple versioned git branches. 

But really, this complicates thing and we won't document this. If you want to use one deployment per git version, I suggest you should know what you are doing if you want to use GitHub pages, or you should simply upgrade to a better host that will enable you to do that in a much simpler way.

---

In general I'm ok to document this use-case better but keep in mind everything related to deployment is kind of out of the scope of Docusaurus, and we can't really be exhaustive in terms of options and recommendations.

What do you suggest exactly? Are you willing to write this doc?

**Comment by hasezoey** [comment]
> It is now your responsibility to deploy/link these different sites together the way you want. There are many ways to do that, including a hybrid mode (like we do on our own website) where very old versions are archived and newer versions are in the main branch. You can decide to deploy older versions on immutable deployments, on a subdomain, on a subpath of your main domain... it's really up to you.

it seems like you know a bit about this, could you maybe explain or give me a example on how to manually set-up docusaurus to use a manually deployed version (which settings / paths to use), or do i just have to use the `external version link` system? (from what i know all `external version link`'s will show up as "archived version", is this correct, if yes can this be changed?)

**Comment by slorber** [comment]
That's pretty simple and not sure what to explain

- Git branch `v1`: you configure your hosting solution to pull Docusaurus from that branch instead of `main`, and configure subdomain `v1.myproject.com`
- Git branch `v2`: you configure your hosting solution to pull Docusaurus from that branch instead of `main`, and configure subdomain `v2.myproject.com`
- Git branch `main` for current/live v3 version: you configure your hosting solution to pull Docusaurus from `main`, and configure main domain `myproject.com`. You can also use a subdomain if you want to.

You end up with one (sub)domain per git branch. 

Each docusaurus site is independent from each other, does not need to use the docs versioning feature (ie there's only version "current" which is the name of your git branch). There's no particular setting to use, just use the base docusaurus init site on 3 separate branches. It is your responsibility to backport/cherry-pick docs from one version to another if it makes sense (it doesn't always make sense, depends on the project).

Docusaurus does not have any concept of "external version link" or "archived version", that's your responsibility to implement whatever page of this kind you want, on the 3 different Git branches deployed to those 3 different domains.  What we do on our own website is only one solution among many others.

---

Again, all this is outside the scope of Docusaurus. For example, you could even have v1 using Jekyll, v2 using MkDocs, and v3 using Docusaurus: which of those 3 frameworks according to you should document this multi-branch setup? None of them, because that's a git/organizational/deployment concern, not a framework concern. The answer would be the same for all 3 frameworks.

I'm open to adding a small section to our doc. Please open a PR directly if you have ideas on how to explain all that in a very simple and concise way.

**Comment by hasezoey** [comment]
> You end up with one (sub)domain per git branch, and one app per git branch. There's a 1-1 mapping.

this is what i meant with "not really possible with github pages", is it also possible to use different paths (like `/project/docs` for main and `/project/v1/docs` or older) like built-in versioning in the same github-pages branch without each deploy interfering with each other?

> Docusaurus does not have any concept of "external version link" or "archived version", that's your responsibility to implement whatever page of this kind you want, on the 3 different Git branches deployed to those 3 different domains. What we do on our own website is only one solution among many others.

from what i know docusaurus has this, i was (and still am) not sure about the proper terminology, quote from the docs:

> archive older versions
> If you deploy your site on a Jamstack provider (e.g. [Netlify](https://docusaurus.io/docs/deployment)), the provider will save each production build as a snapshot under an immutable URL. You can include archived versions that will never be rebuilt as external links to these immutable URLs. The Jest website and the Docusaurus website both use such pattern to keep the number of actively built versions low.

[from versioning](https://docusaurus.io/docs/versioning#keep-the-number-of-versions-small)

i just meant to adapt this "link to immutable" to just point to a different path from the same github-pages branch or if there is some way to tell docusaurus to build for a specific version and deploy this into a already existing one (like the built-in versioning).

**Comment by slorber** [comment]
> this is what i meant with "not really possible with github pages", is it also possible to use different paths (like /project/docs for main and /project/v1/docs or older) like built-in versioning in the same github-pages branch without each deploy interfering with each other?

If you want multiple domains with GitHub pages, you will have to use multiple deployment repositories. Again this complicates things and you'd rather use a better host instead.

You can have subpaths on a single GHP deployment, and it's also outside the scope of Docusaurus (only `baseUrl` is part of the Docusaurus scope. 

Taking the 3 distinct framework examples, you can have Jekyll on `/v1`, MkDocs on `/v2`, and Docusaurus on `/` or `/v3`. 

Static deployments are just static files, you can just merge 3 static folders into one if you want, and push all the files to the `gh-pages` branch of your repo. That's a complex setup and it's your responsibility to figure out details on how to assemble just deployment. That's DevOps, not Docusaurus.

---

> from what i know docusaurus has this, i was (and still am) not sure about the proper terminology, quote from the docs:

This is not a Docusaurus feature, just an opinionated suggestion. We don't have any code to handle this, and it's up to you to follow our suggestion or not. In the same way the doc you are asking to write here is not involving any code change or Docusaurus feature, and would just be here to guide users and give some ideas.

---

> i just meant to adapt this "link to immutable" to just point to a different path from the same github-pages branch or if there is some way to tell docusaurus to build for a specific version and deploy this into a already existing one (like the built-in versioning).

Docusaurus has navbar links and navbar dropdowns. You can link to whatever you want here. 
- If you have v1 on a subpath, link to that subpath (eventually with the `pathname://` protocol or an absolute URL). 
- If you have v1 on a subdomain, link to that subdomain
- If you have v1 on an immutable deployment, link to that immutable deployment

These things are just regular links. There's no Docusaurus code involved, at all.


At best this is just a bit of Node.js in the config:
- https://github.com/facebook/docusaurus/blob/main/website/versionsArchived.json
- https://github.com/facebook/docusaurus/blob/main/website/docusaurus.config.js#L479

**Comment by hasezoey** [comment]
> You can have subpaths on a single GHP deployment, and it's also outside the scope of Docusaurus (only baseUrl is part of the Docusaurus scope.
> 
> Taking the 3 distinct framework examples, you can have Jekyll on /v1, MkDocs on /v2, and Docusaurus on / or /v3.
> 
> Static deployments are just static files, you can just merge 3 static folders into one if you want, and push all the files to the gh-pages branch of your repo. That's a complex setup and it's your responsibility to figure out details on how to assemble just deployment. That's DevOps, not Docusaurus.

thanks for the feedback, i just wanted to ask if there would be any problems with doing a nested (which it would be) docusaurus deployment to a sub-folder, while still having the main docusaurus up on the root in github-pages

**Comment by slorber** [comment]
np 👍 

No problem, you just need to build the 2 docusaurus sites (one with `baseUrl: '/'` and one with `baseUrl: '/v1'`) and merge the 2 static outputs as a single static site. Replace Docusaurus by any other SSG and the answer remains true: that's not specific to Docusaurus but is just how static files and folders work 😄 

The only thing that matters is that you have both `./index.html` and `./v1/index.html` in your deployment.

**Comment by karl-cardenas-coding** [comment]
@slorber, my team and leveage git branches for our versioning content in our [documentation repository](https://github.com/spectrocloud/librarium).  I'm thinking of writing a blog about how and why we did it. I'd be happy to share the link to the blog if you think there would be value in sharing.

**Comment by kopparam** [comment]
> For those who come across this issue. Feel free to check out the [blog post](https://www.spectrocloud.com/blog/when-docs-and-a-dinosaur-git-along-enabling-versioning-in-docusaurus) we published that explains how you can enable content versioning with Docusaurus and git. We also include an [example repository](https://github.com/spectrocloud/docusarus-versioning-template), so you can experiment with our pattern.

Thank you so much. Very helpful.
