### ISSUE TITLE
Sidebar not escaping characters

### ISSUE THREAD

**Issue by oneElectron** [facebook/docusaurus#8386]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [ ] I have tried creating a repro with https://new.docusaurus.io.
- [ ] I have read the console error message carefully (if applicable).

### Description

Reproducible demo: [https://github.com/oneElectron/sidebar-escaping](url)
```
  npm start
```
open the page in your web browser and click Tutorial on the top bar

When setting the title of a markdown page, it also sets the name of the file in the sidebar. For example the file intro.md:
```
# Welcome
This is the intro.md file
```
Would appear in the sidebar as Welcome.

This leads to an issue where having the title with a character that requires escaping e.g. \>, causes the title of the markdown file to be correct, but the name of the file in the sidebar is incorrect. For example the file iostream.md:

```
# <iostream\>
This file talks about iostream.
```

the sidebar will include the \ in the file name

### Reproducible demo

https://github.com/oneElectron/sidebar-escaping

### Steps to reproduce

1. Give a markdown file a title with a character that needs to be escaped, for example \>
2. start the Webserver and look for said file, it should have an escape sequence in the name.

### Expected behavior

I would expect that the character would be properly escaped, leaving only the escaped character, not the escape sequence

### Actual behavior

The escape sequence was displayed

### Your environment

- Public source code: [https://github.com/oneElectron/sidebar-escaping](url)
- Public site URL: N/a
- Docusaurus version used: latest
- Environment name and version (e.g. Chrome 89, Node.js 16.4): Browsers tested: safari, Firefox. npm version: 8.15.0
- Operating system and version (e.g. Ubuntu 20.04.2 LTS): MacOS 13.0.1

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by Josh-Cena** [comment]
This is tricky to get right. The sidebar title does _not_ attempt any kind of Markdown parsing—backticks are not stripped, nor are underlines and asterisks. Escaping is also part of Markdown parsing—while I agree it's necessary and fits user expectation, I don't know what's a good algorithm for that. In the meantime, you can always use `sidebar_title` and/or the `title` front matter instead of relying on H1 titles.

**Comment by oneElectron** [comment]
Would it be possible to ignore certain characters if the file type is markdown?
The only issue I see with this is if the user wanted to include a backslash.

**Comment by Josh-Cena** [comment]
For example, if the title is ``# The `\n` escape sequence``, we definitely cannot remove the `\` character there. This eventually means we have to make an ad hoc Markdown parser ourselves, which we are trying to avoid.

**Comment by oneElectron** [comment]
If you could ignore the first backslash but not the second this would solve the issue.
This also mimics the behaviour of markdown where two backslashes render out to one:
\\ (two backslashes)

**Comment by Josh-Cena** [comment]
@oneElectron The issue is that text within backticks should never be interpolated, which means we are inclined to ship a parser that at least parses two things: escape sequences and inline code. Neither is trivial enough to be implemented without bugs.

IMO, `_italic_`, `` `code` ``, and `\escape` should all be considered "Markdown syntax". If we don't interpolate/sanitize the previous two, neither should we translate the escape sequences. Do you think it would be a good solution if you simply use the `title` front matter key instead? That's the "real way" anyway, and the `#` h1 heading is only a syntax sugar.

**Comment by oneElectron** [comment]
Considering the work required for a bug that is easy to get around, I am fine with it.
