### ISSUE TITLE
Algolia + Client-side redirections cannot serve properly search results

### ISSUE THREAD

**Issue by tisonkun** [facebook/docusaurus#8413]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [ ] I have tried the `npm run clear` or `yarn clear` command.
- [ ] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [ ] I have tried creating a repro with https://new.docusaurus.io.
- [ ] I have read the console error message carefully (if applicable).

### Description

After setting up client-side redirections from `/docs/` to `/docs/2.10.x/`, when searching under `/docs/2.10.x/`, the result is under `/docs/`. And when I click the search result, it jumps to a 404 page which jump back to the correct page with a manual reload:

https://user-images.githubusercontent.com/18818196/205787832-b2bdcd0b-204c-42c8-b99a-2966c168757c.mov

### Steps to reproduce

See the audio above.

### Expected behavior

After click the search result, jump to the page and successfully load.

### Actual behavior

Fail to load. 404.

### Your environment

- Public source code: https://github.com/apache/pulsar-site/tree/main/site2/website-next
- Public site URL: https://pulsar.apache.org/
- Docusaurus version used: 2.2.0
- Environment name and version (e.g. Chrome 89, Node.js 16.4):
- Operating system and version (e.g. Ubuntu 20.04.2 LTS):

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by tisonkun** [comment]
It seems regenerating Algolia index solves the problem.

But I still wonder why the page doesn't reload on the previous case.

**Comment by slorber** [comment]
Hi

The client redirect plugin is only used on the first-page load as a best-effort to help you redirect to the correct page.

Once React + React-Router kick in, navigating to `/docs/administration-geo/#migrate-data-between-clusters-using-geo-replication` (like it happened by clicking a search result) will lead to a 404 because your browser won't load the HTML redirect file from the server but will try to find an existing client-side SPA route to navigate to. This route doesn't exist anymore so it will serve the 404.

So, these results are expected and should be fixed with an up-to-date Algolia index.

If you want `/docs/administration-geo/` to exist boh as a static redirect file AND a client-side route, you'll have to implement this yourself for example using a React-Router `<Redirect>` component in a `page/docs/administration-geo/index.md` page. I don't particularly recommend doing this, it's just a possibility.

I strongly suggest to use server-side redirects instead. The client-side redirect plugin is only a best effort and is not the best practice in terms of redirects.

**Comment by tisonkun** [comment]
@slorber I'm trying server-side redirection. But if the routing logic is handled in the client-side SPA route, will it try to apply server-side redirect?

**Comment by slorber** [comment]
Server redirects are always applied before anything client-side.

We do use Netlify server redirects on our own website and it works fine:
https://github.com/facebook/docusaurus/blob/main/website/static/_redirects
