### ISSUE TITLE
Renaming docs breaks links in old versions

### ISSUE THREAD

**Issue by microbouji** [facebook/docusaurus#845]
## 🐛 Bug Report

Renaming a doc file in the `docs` folder seems to break links of the form `[inner link](doc.md)` in the `versioned_docs` folder.

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/Docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes.

## To Reproduce

1. `npx docusaurus-init`
1. Cut a new version.
    ```
    yarn examples versions
    yarn run version 1.0.0
    ```
1. The sample `doc2.md` has a link to `doc3.md`. So we can rename `doc3.md` to something else and update the link in `doc2.md`. Start docusaurus now and you'll find that in the "next" version:
http://localhost:3000/docs/next/doc2.html
the link works correctly, but in the current one:
http://localhost:3000/docs/doc2.html
it does not.

## Expected behavior

I think renaming doc files should be supported.

## Actual Behavior

Next version page (`"another document"` correctly points to `renamed-doc3.html`):
![next](https://user-images.githubusercontent.com/2972085/42526127-424086ea-8475-11e8-8455-a00a99da9ff8.png)

Current version page (link points to `doc3.md`):
![current](https://user-images.githubusercontent.com/2972085/42526145-4f43c7ee-8475-11e8-9c22-25b900444fa7.png)

Notice the "NEXT" button also failing to get `doc3.md`'s title.

## Reproducible Demo

This is currently happening at the babel website where we've renamed some plugin docs to remove es2015 from the name. So the links under ES2015 here in the "current" 6.x version are broken:
https://babeljs.io/docs/en/plugins#es2015

but they're working in the "next" version:
https://babeljs.io/docs/en/next/plugins#es2015

Taking the arrow functions document as an example. The doc name in the [versioned_docs/version-6.x](https://github.com/babel/website/tree/master/website/versioned_docs/version-6.x) folder is `plugin-transform-es2015-arrow-functions.md` whereas in the [docs](https://github.com/babel/website/tree/master/docs) folder it's `plugin-transform-arrow-functions.md`

**Comment by endiliey** [comment]
I just tried this out & have found the cause. I think the fix implementation is not trivial (lot of changes & might break other places) so might need some time to properly test & implement this.

Looking at:
https://github.com/facebook/Docusaurus/blob/a7a214fb3a36b3627e4346c2ddbcc4d01e3bf3a1/lib/server/server.js#L251-L272

This is where we change the [docs/plugin-transform-es2015-arrow-functions.md](docs/plugin-transform-es2015-arrow-functions.md) to [/docs/en/next/plugin-transform-es2015-arrow-functions.html](/docs/en/next/plugin-transform-es2015-arrow-functions.html)

The bug occurs because there is no `plugin-transform-es2015-arrow-functions.md` key in mdToHtml object. Causing all occurences of `plugin-transform-es2015-arrow-functions.md` not being replaced to the html link. This is because when we build the key for `mdToHtml`, we only consider the latest docs source and try to cleverly change `VERSION` to the correct version later on
https://github.com/facebook/Docusaurus/blob/a7a214fb3a36b3627e4346c2ddbcc4d01e3bf3a1/lib/server/server.js#L198-L212

Meanwhile,
A quick fix for babel right now is to rename all (the docs name & even the linking) of `plugin-transform-es2015-arrow-functions.md` in versioned_docs to `plugin-transform-arrow-functions.md`

**Comment by microbouji** [comment]
Thanks @endiliey for looking into this and for the suggested workaround!

**Comment by parthpp** [comment]
@endiliey Continuing our discussion from https://github.com/facebook/Docusaurus/issues/1282.
This bug is might be a very time consuming problem for us since we might have many instances where document files are added, deleted or renamed between versions. A manual work around to hunt down all the links and convert them might not be feasible. Can you suggest an automated solution? If not, will you accept the PR if I make a change to fix this issue in Docusaurus version 1? 
I understand that version 2 might fix this problem, but we do not know when it will be ready.

**Comment by endiliey** [comment]
> A manual work around to hunt down all the links and convert them might not be feasible.
Docusaurus by default warn users for any unresolved link file.

> If not, will you accept the PR if I make a change to fix this issue in Docusaurus version 1?

@parthpp If there is a PR, will be happy to accept & review it.

**Comment by parthpp** [comment]
@endiliey Thanks! Can you also shed some light on where are we with versioning topic in Docusaurus version 2 and when will version 2 of Docusaurus be released?

**Comment by slorber** [comment]
The Docusaurus team is actively working on Docusaurus v2.

After a very long alpha, Docusaurus v2 is [now in beta](https://docusaurus.io/blog/2021/05/12/announcing-docusaurus-two-beta).
We believe that the v2 beta is already better than v1, and v2 is ready for maintstream adoption.

Apart from critical issues and security fixes, we don't plan to invest much time on Docusaurus v1 anymore.

We are all closing v1 issues. 
Maybe the current issue is already fixed in Docusaurus v2.
Please try to upgrade, and if the issue is still there on Docusaurus v2, open a new issue.
