### ISSUE TITLE
unexpected broken links in production, but not locally

### ISSUE THREAD

**Issue by jcstein** [facebook/docusaurus#8499]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [ ] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

1. Above this heading (https://docs.celestia.org/nodes/light-node#keys-and-wallets) there is a link to RPC endpoints: "you can check from the list [here](https://docs.celestia.org/nodes/arabica-devnet)"
- however, the link does not work as expected, although when testing locally and reviewing the code (https://github.com/celestiaorg/docs/blob/d7190ea8c3efafd67fab0b4e0a8a32c773874282/docs/nodes/light-node.mdx?plain=1#L741 & https://github.com/celestiaorg/docs/blob/d7190ea8c3efafd67fab0b4e0a8a32c773874282/docs/nodes/light-node.mdx?plain=1#L752) it appears to be in the proper format.
- this was documented in this issue: https://github.com/celestiaorg/docs/issues/342
2. This issue also appears in other places on our site, documented here: https://github.com/celestiaorg/docs/issues/386

### Reproducible demo

https://github.com/celestiaorg/docs

### Steps to reproduce

1. Review comments above, and test the live site at https://docs.celestia.org/nodes/light-node and at https://docs.celestia.org/developers/full-stack-modular-development-guide#deploying-to-the-ethermint-sovereign-rollup
2. Clone repo and build locally, testing the same links. They will work locally, but not on our live site. 

### Expected behavior

The links should work as expected, and as they do when developing locally.

### Actual behavior

"Page Not Found"

### Your environment

- Public source code: https://github.com/celestiaorg/docs
- Public site URL: https://docs.celestia.org
- Docusaurus version used: 2.2
- Environment name and version (e.g. Chrome 89, Node.js 16.4): Chromium 108, Node.js 19.2
- Operating system and version (e.g. Ubuntu 20.04.2 LTS): Mac OSX Ventura 13

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by slorber** [comment]
You probably did not configre the `trailingSlash` Docusaurus config properly.

Your host is adding a trailing slash to URLs (it's out of Docusaurus control)

```
Access: https://docs.celestia.org/nodes/light-node
Redirected to: https://docs.celestia.org/nodes/light-node/
```

And you use relative links.

> If you need a list of RPC endpoints to connect to, you can check from the list [here](./mocha-testnet#rpc-endpoints)

Depending on the presence of the trailing slash, such relative link target will be resolved differently:

```
/nodes/light-node => https://docs.celestia.org/nodes/light-node
/nodes/light-node/ => https://docs.celestia.org/nodes/light-node/mocha-testnet
```

(this is not something from Docusaurus, this is how the web works)


---

We advise to not use relative links [here](https://docusaurus.io/docs/markdown-features/links) for these exact reasons: relative links are rendered as-is by Docusaurus, and can break if your host add/remove a trailing slash.

We also advise to [configure the `trailingSlash` config properly](https://docusaurus.io/docs/deployment) for your host so that URL is consistently with or without a trailing slash. Not having server-side-redirect on page load is also better for perf and SEO.

**Comment by jcstein** [comment]
thank you @slorber!
