### ISSUE TITLE
Access ColorModeContext in Root

### ISSUE THREAD

**Issue by pelikhan** [facebook/docusaurus#8566]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Description

A Root  component is a not able to determine the light/dark mode because the ColorModeContext is not yet mounted.

### Motivation

I have a plugin that displays a side editor on demand. It is implemented as a wrapper around Root. The side editor needs to know the current color mode to match it's internal color mode as well.

### API design

no api change, but useColorMode() would be available to Root.

### Have you tried building it?

no

### Self-service

- [X] I'd be willing to contribute this feature to Docusaurus myself.

**Comment by Josh-Cena** [comment]
It is not undoable through some tweaks to our architecture, but we very much actively decline such changes because it blurs the line between "core" and "theme". The color mode is a theme concern and it's very possible that different themes come up with different abstractions of the color mode or do not have modes at all. `<Root>` is the root of the entire React app—it's maintained by the core and is above all contexts. This means it's very much by design that the root is agnostic about any contexts—it never re-renders and never unmounts, which allows you to easily manage global data. See [docs](https://docusaurus.io/docs/swizzling#wrapper-your-site-with-root):

> The `<Root>` component is rendered at the very top of the React tree, above the theme `<Layout>`, and never unmounts. It is the perfect place to add stateful logic that should not be re-initialized across navigations (user authentication status, shopping card state...).

Color mode comes from `<Layout>`—specifically `<ColorModeProvider>`. If you want to render something at the top that depends on the color mode, wrap `<Layout>` instead:

```js
import Layout from "@theme-original/Layout";

export default function L({ children, ...props }) {
  return (
    <Layout {...props}>
      <YourComponent>{props.children}</YourComponent>
    </Layout>
  );
}
```

...Something like that. It's hard to give exact advice without knowing the implementation details, but the verdict is no—we would not allow accessing color mode from the root.

**Comment by pelikhan** [comment]
In the details, I'm creating a wrapping the Docusaurus children passed to root into a 2 column split pane component. The second pane loads an iframe which runs an editor. I'll see about wrapping Layout instead.

**Comment by Josh-Cena** [comment]
If "never unmount between route transitions" is also a design goal, you may also find it convenient to simply read the color mode from the `html` element's `data-theme`.

**Comment by pelikhan** [comment]
With iframe's, it's definitely part of the design goal to avoid unmounting.. html.data.theme sounds like a good tradeof here. Thanks for the speedy answer.

**Comment by slorber** [comment]
To avoid flashes of dark/light mode on page hydration, it's preferable that you use themed CSS queries.

```css
[data-theme='light'] .sideEditor {
  background-color: white;
}
[data-theme='dark'] .sideEditor {
  background-color: black;
}
```

Using the colorMode value retrieved from a hook or component props should be used as a last resort because on the first render it will always give you a static value: the default one we use for the server-side rendering phase (where it's not possible to read localstorage). 

Now for setting the theme of an iframe it could be fine as the iframe will probably only load after React hydrates. You might need to use some tricks so that the iframe placeholder background matches your theme on first render. You can read `data-theme` from the `<html>` element for example, as we set this attribute as soon as possible with inlined JS on page load.

**Comment by pelikhan** [comment]
I ended up querying html.data-theme and ignore in the hook. In my scenario, the iframe is loaded llloooonnnngg after the renders so the flashing is not realy an issue.
