### ISSUE TITLE
Admonitions: hide header (icon and title)

### ISSUE THREAD

**Issue by baur** [facebook/docusaurus#8568]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

Hide header (icon and title) 

![image](https://user-images.githubusercontent.com/2898361/213957874-82e06abb-4121-48ae-bb23-a5a52326b9cd.png)

### Motivation

I can pass empty icon and title, but header height not changes. I'd like to full hide header

Like this:

<img alt="image" src="https://user-images.githubusercontent.com/749374/126460989-47d41516-0f1d-40f5-8ce0-970bf8745a0c.png">

**Comment by Josh-Cena** [comment]
Related to: https://github.com/facebook/docusaurus/discussions/8458

**Comment by baur** [comment]
ok, thanks!

**Comment by Josh-Cena** [comment]
I do think it's fair as feature request though, just we need more design for it to be actionable.

**Comment by slorber** [comment]
Definitively something I'd like to add.

In the meantime you can probably do something like

```
:::tip NO_ICON

my tip

:::
```

And swizzle the component to not render the icon/heading if title === "NO_ICON"

**Comment by kalsky** [comment]
I think keeping the icon makes sense, otherwise, the only differentiation is the background color.
But I do want to be able to set it as a one-liner admonition with/without the title and with/without the icon.
Right now, when I don't need the title, I just do something like:
:::note &nbsp;
something
:::

**Comment by slorber** [comment]
I'm not here to judge if having an icon makes sense. Users should be able to decide for themselves if they want one.

We should rather use the [Markdown directive](https://talk.commonmark.org/t/generic-directives-plugins-syntax/444/28) syntax, since we already use [remark-directive](https://github.com/remarkjs/remark-directive) anyway.


```md
:::note{icon=false}

content

:::
```

Whatever is in `{}` (directive attributes) should rather become available to the underlying component we use for rendering, as props. This would be generic and flexible for users to implement other use cases as well thanks to swizzle. 

A little annoying thing is that directives do not seem to be typed, here we get `"false"` instead of `false`

![CleanShot 2024-04-25 at 11 54 14](https://github.com/facebook/docusaurus/assets/749374/aff7ef28-e143-49d8-a6db-ce5873754b69)

Our remark admonition plugin is also not in an ideal form so I'll refactor all this some day when I have time.

**Comment by slorber** [comment]
Regarding this specific issue, I can reproduce when using admonitions through JSX nodes.

```jsx
import Admonition from '@theme/Admonition';

<Admonition type="info" title={null} icon={null}>
  <p>Some information</p>
</Admonition>
```
![CleanShot 2024-04-25 at 12 01 18](https://github.com/facebook/docusaurus/assets/749374/f6196609-16ae-48bb-b6ee-ec104b30de29)


https://stackblitz.com/edit/github-jit8sw?file=docs%2Fintro.md



This is probably just a little conditional rendering issue in our `AdmonitionLayout` component:

```diff
 <AdmonitionContainer type={type} className={className}>
-  <AdmonitionHeading title={title} icon={icon} />
+  {(title || icon) ? <AdmonitionHeading title={title} icon={icon} /> : null}
   <AdmonitionContent>{children}</AdmonitionContent>
 </AdmonitionContainer>
```

If someone wants to submit a PR for this, it should be relatively easy.

Please add a test case in this page so that we can see it working in the deploy preview:

https://docusaurus.io/tests/pages/markdown-tests-mdx#admonitions

**Comment by andrmaz** [comment]
@slorber I'll deal with this
