### ISSUE TITLE
False positive markdown link couldn't be resolved

### ISSUE THREAD

**Issue by tisonkun** [facebook/docusaurus#8632]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [ ] I have tried the `npm run clear` or `yarn clear` command.
- [ ] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [ ] I have tried creating a repro with https://new.docusaurus.io.
- [ ] I have read the console error message carefully (if applicable).

### Description

Markdown links in code block are not effective links, but the detector complains.

### Steps to reproduce

```shell
git clone https://github.com/apache/pulsar-site.git
cd pulsar-site
yarn install
./preview.sh 2.11.x
```

### Expected behavior

Markdown links in code block should not be checked.

### Actual behavior

```
[WARNING] Docs markdown link couldn't be resolved: (function-overview.md) in "/home/tison/Brittani/pulsar-site/contribute/document-syntax.md" for version current
[WARNING] Docs markdown link couldn't be resolved: (../../function-overview.md) in "/home/tison/Brittani/pulsar-site/contribute/document-syntax.md" for version current
```

### Your environment

- Public source code: 

https://github.com/apache/pulsar-site/blob/38ca8e2457c3b154f2687e97c57a6c7f4f7e28e0/contribute/document-syntax.md?plain=1#L254-L257

- Public site URL: https://pulsar.apache.org/contribute/document-syntax/
- Docusaurus version used: 2.2.0
- Environment name and version (e.g. Chrome 89, Node.js 16.4):
- Operating system and version (e.g. Ubuntu 20.04.2 LTS):

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by Josh-Cena** [comment]
It's a known issue that the Markdown link resolver disregards any Markdown syntax, and it's a particularly hard issue to fix. The priority is low as well, because the only use case we can envision is meta-docs about how to author Markdown, as is the case here. We'll track this in https://github.com/facebook/docusaurus/issues/5659. For now, you can simply ignore the warning.

(BTW, the syntax does not work—you can't use backticks in JSX. You have to use all JSX syntax, like `<li><code>foo</code></li>`.)
