### ISSUE TITLE
Show sidebar when acessing a doc that is not listed in sidebars.json

### ISSUE THREAD

**Issue by DiegoFelipe** [facebook/Docusaurus#865]
## ❓ Questions and Help

I noticed that when I access a doc that is not inside sidebars.json, the left sidebar doesn't shows up, but if I add this doc do the JSON is shows, I want the left sidebar to be visible, even id the doc that I'm accessing is not listed in this JSON file

**Comment by endiliey** [comment]
### Please note that this issue tracker is not a help form and this issue will be closed.

Please contact us instead. We have a few channels:
- [Stack Overflow](https://stackoverflow.com/questions/tagged/docusaurus)
- [Twitter](https://twitter.com/docusaurus)
- [Discord](https://discord.gg/docusaurus)

Otherwise, please open a feature request issue for this
