### ISSUE TITLE
process.env.DOCUSAURUS_CURRENT_LOCALE is undefined in serve

### ISSUE THREAD

**Issue by Josh-Cena** [facebook/docusaurus#8849]
### Discussed in https://github.com/facebook/docusaurus/discussions/8848

<div type='discussions-op-text'>

<sup>Originally posted by **laojun** March 30, 2023</sup>
Hi:
First of all, Thanks for the v2.4。

I use `process.env.DOCUSAURUS_CURRENT_LOCALE`  to solve my problem in https://github.com/facebook/docusaurus/discussions/8745。

Here is my docusaurus.config.js
```
baseUrl: `/${process.env.DOCUSAURUS_CURRENT_LOCALE}/`
```

Seems right when i run build
![image](https://user-images.githubusercontent.com/15364706/228841951-1cc283a1-473e-4196-b920-9637f9b14eb9.png)

But error when i run server
![image](https://user-images.githubusercontent.com/15364706/228842944-d4ae8c65-7c3e-4201-8f53-fb064f14b5e3.png)

How can i make it right when i run server?

Thanks

</div>

**Comment by tarunrajput** [comment]
@Josh-Cena , DOCUSAURUS_CURRENT_LOCALE was not added to the serve command. It is only available in build and start with --locale flag.
cc: @slorber

**Comment by slorber** [comment]
@laojun according to you, which value `process.env.DOCUSAURUS_CURRENT_LOCALE` should have when running the serve command? 


The original PR (https://github.com/facebook/docusaurus/pull/8677
) mentions that this env variable is a temporary workaround until we figure out a better API

And it is also explained that you have to program defensively against the value being potentially undefined. 

`docusaurus serve` belongs to the commands we documented with an undefined current locale env variable.

My suggestion, try something like this:

```js
baseUrl: process.env.DOCUSAURUS_CURRENT_LOCALE
  ? `/${process.env.DOCUSAURUS_CURRENT_LOCALE}/`
  : "/"; // or "/zh-cn/" ???
```

---

Going to close because for me it's not a bug, it's a documented limitation of the current implementation. 

Even if we had a better API, I have no idea which locale we should define as the "current one" when running `docusaurus serve`. I'm not sure we could generalize a good solution here. Open to discussing this more but please explain me your expectations when running this command.

**Comment by Josh-Cena** [comment]
Yeah, that makes sense :/ Multiple locales are served at once so it's hard to tell

**Comment by laojun** [comment]
> @laojun according to you, which value `process.env.DOCUSAURUS_CURRENT_LOCALE` should have when running the serve command?
> 
> The original PR (#8677) mentions that this env variable is a temporary workaround until we figure out a better API
> 
> And it is also explained that you have to program defensively against the value being potentially undefined.
> 
> `docusaurus serve` belongs to the commands we documented as having an undefined current locale env variable.
> 
> My suggestion, try something like this:
> 
> ```js
> baseUrl: process.env.DOCUSAURUS_CURRENT_LOCALE
>   ? `/${process.env.DOCUSAURUS_CURRENT_LOCALE}/`
>   : "/"; // or "/zh-cn/" ???
> ```
> 
> Going to close because for me it's not a bug, it's a documented limitation of the current implementation.
> 
> Even if we had a better API, I have no idea which locale we should define as the "current one" when running `docusaurus serve`. I'm not sure we could generalize a good solution here. There are many cases to consider when serving a build output depending on what has been built (single localized site vs site with multiple locales built one after the other)
> 
> Open to discussing this more but please explain me your expectations when running this command.

Thanks for the reply。

I try it like this
```
baseUrl: process.env.DOCUSAURUS_CURRENT_LOCALE ? `/${process.env.DOCUSAURUS_CURRENT_LOCALE}/` : '/zh-cn/',
```
It goes well when i choose locale `zh-cn`, And the url goes to `/zh-cn/en-us` when i chose `en-us`.

**Comment by Josh-Cena** [comment]
This is the same issue as https://github.com/facebook/docusaurus/issues/8652 I believe

**Comment by slorber** [comment]
I think we could fix this behavior as part of https://github.com/facebook/docusaurus/pull/6731

This means you could keep `/` for your site baseUrl, but make it use a `/zh-cn/` for Chinese.

`/` + `/zh-cn/` = `/zh-cn/`

Does it make sense?
