### ISSUE TITLE
There's no way to remove the trailing slash from baseUrl

### ISSUE THREAD

**Issue by vahnag** [facebook/docusaurus#8868]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [X] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

I'm trying to normalize all urls and remove all trailing slashes from links. 

I have a custom baseUrl set in the config with the value of `/docs`.

I'm using the `trailingSlash: false` which works as expected and removes all trailing slashes from all links except for the ones directly linking to the base URL.

So whenever I'm trying to link to the root of the docs, which I expect to be linked as `/docs`, it's instead being linked as `/docs/`.

I tracked it back to these lines of code, which always add the trailing slash to the base url:

https://github.com/facebook/docusaurus/blob/be0ac6c2cd6515f7b0cf5158fdf68dbcdf45133c/packages/docusaurus/src/client/exports/useBaseUrl.ts#L29-L33

I think this makes sense to do when the baseUrl is the root of the domain, but don't see why it's being done for all links linking to the root.

### Reproducible demo

https://github.com/dragonflydb/documentation/blob/main/docusaurus.config.js

### Steps to reproduce

1. Add `trailingSlash: false` and `baseUrl: "/docs"` to the docusaurus config.
2. Create a doc with slug of `/`.
3. Link to that doc anywhere, either in Sidebar or Nav.

### Expected behavior

The generated link should be `/docs` (note missing trailing slash)

### Actual behavior

It's ending up being `/docs/` (note the trailing slash)

### Your environment

- Public source code: https://github.com/dragonflydb/documentation
- Public site URL: https://dragonflydb.io/docs
- Docusaurus version used: 2.3.1
- Environment name and version (e.g. Chrome 89, Node.js 16.4): n/a
- Operating system and version (e.g. Ubuntu 20.04.2 LTS): n/a

### Self-service

- [X] I'd be willing to fix this bug myself.

**Comment by slorber** [comment]
Not sure I can qualify this as a bug but rather a limitation of what we consider a baseUrl.

Even if you provide `baseUrl: "/docs"` we normalize it as `baseUrl: "/docs/"`

At the end of the day, we have to emit files inside the `./build` folder. 

The homepage is `./build/index.html`.

If `baseUrl: "/docs"` with no trailing slash was possible this means the homepage would need to be outputted at `./index.html` (outside the `./build` folder). 

How would you deploy your site then? 

I'm open to discussions but I don't see how we could fix it considering we need to output all the static deployment in a single folder.

**Comment by vahnag** [comment]
@slorber thanks for taking a look!

I'm not exactly sure what's holding us back from linking to the `./build/index.html` as `/docs`.

We have this other route in the project that's just a single level deep with the link of `/docs/getting-started`. The build output for that route is in `./build/getting-started/index.html`. And it works fine linked as `/docs/getting-started`.

Do I get it right that you would expect the build file to be `./build/getting-started.html` in this case? Because it isn't.

I understand that if the base URL is just the root of the page we can't link to it without the slash, but don't see how is that a limitation in my case.

**Comment by slorber** [comment]
> I'm not exactly sure what's holding us back from linking to the ./build/index.html as /docs


Do we agree that we can't output `./docs.html` outside the build folder right?
Your index is at `./buid/index.html` right? 


Many hosts will not serve from `/docs` the file and will usually redirect to `/docs/`. Technically we could probably allow linking to the URL without trailing slash, but it means the linked URL will be a redirect and not the canonical URL. It is better to link to the canonical URL directly. What's the advantage of linking to the URL without a trailing slash anyway?

If you host Docusaurus on Github, `https://slorber.github.io/trailing-slash-guide/folder` will be redirected to `https://slorber.github.io/trailing-slash-guide/folder/` and you have no option to turn it off. 

What's the point of linking to `/docs` if on refresh the host redirects you to `/docs/` anyway? 🤷‍♂️ 

See my repo to inspect major CDN behaviors: https://github.com/slorber/trailing-slash-guide

By chance, all the major CDNs that we documented here will perform a server redirect:

![CleanShot 2023-04-06 at 11 34 40@2x](https://user-images.githubusercontent.com/749374/230337195-39ee0373-9fac-4fa3-8f6e-fa6e5cde7c55.png)

But what if some hosts are unable to server `./build/index.html` from `/docs` pathname? I've seen such cases with other hosts where it's not a redirect but a 404.

If we made it so that a link to `/` would be transformed as `/docs` instead of `/docs/`, sites with `trailingSlash: false` + some specific hosts would be unable to access the homepage from `/docs` but would from `/docs/` => this opens the door to lots of complaints difficult to debug for us.


---


> We have this other route in the project that's just a single level deep with the link of /docs/getting-started. The build output for that route is in ./build/getting-started/index.html. And it works fine linked as /docs/getting-started.

It works fine for you, with your specific host config, but can we generalize for all hosts and assume this linking will be generally safe everywhere? No

> Do I get it right that you would expect the build file to be ./build/getting-started.html in this case? Because it isn't.

Yes it should be the case if you have trailingSlash: false and routeBaseUrl: "/" for docs (both are not the default values). Show me a repro if that's not the case.


---

Hope you understand why what you ask for can't really be the default behavior, and why I think it's not a good idea in the first place.

Now if you provide a good reason to avoid the trailing slash, I'm open to provide you primitives to override our default linking behavior and implement the risky things on your own.

This means for example the ability to swizzle the Link component to implement custom behavior.

Technically you can probably already create a plugin that provides a Webpack alias to override our existing alias `@docusaurus/Link` and write your own Link component

**Comment by vahnag** [comment]
Oh, I might have been looking at that wrong. For some reason yesterday I was sure that the index files were being generated inside the folders, but now that I checked I see what you mean.

So my problem right now is that I'm using Vercel with `trailingSlash: false`.

To make all the links consistent throughout the website I added the same config to Docusaurus config to remove all trailing slashes.

Everything is working as expected, except for that single path (/docs/) which, when visited is resulting in a redirect by Vercel, which is something that Google's indexing doesn't like and would be good to fix.

By the way, this is a completely separate issue, but I had to enable `cleanUrls: true` on Vercel to get it to work with `trailingSlash: false`'s output, as shown in your screenshot.

--- 

I would like to suggest two solutions for this:

* Have separate options for configuring the build output and the trailing slashes in the URLs.
   
   * If there were the option to have the same buld output as with `trailingSlash: true` (nested index.html files inside folders), but with the trailing slashes removed from the URLs I would choose that in my case, to not have to rely on Vercel's `cleanUrls: true` option.

* At least allow swizzling the Link component or useBaseUrl hook.

---

Thanks for the hint for doing this with a custom Webpack plugin, but I'd really like this implemented in the framework itself, as I don't feel like I'm the only one who would need this in the future.

**Comment by slorber** [comment]
> So my problem right now is that I'm using Vercel with trailingSlash: false.

Is this a requirement? Why did you choose this setting?

> Everything is working as expected, except for that single path (/docs/) which, when visited is resulting in a redirect by Vercel, which is something that Google's indexing doesn't like and would be good to fix.

If that's the only problematic case you can probably handle this exception with a Vercel rewrite so that `/docs/index.html` is served from `/docs/` as well. 


> By the way, this is a completely separate issue, but I had to enable cleanUrls: true on Vercel to get it to work with trailingSlash: false's output, as shown in your screenshot.

Docusaurus is only able to build static files and unfortunately all hosts behave differently to serve them. We only control the output.

> Have separate options for configuring the build output and the trailing slashes in the URLs.

Both are related.

That may be useful but this opens the door to incompatible configs for specific hosts, such as `output: 'folder' + trailingSlash: false`: this complicated life for all users to figure out the appropriate combination for their host.

> If there were the option to have the same buld output as with trailingSlash: true (nested index.html files inside folders), but with the trailing slashes removed from the URLs I would choose that in my case, to not have to rely on Vercel's cleanUrls: true option.

`trailingSlash: undefined` allow to output files in folders, and does not force adding a trailing slash to links. This is the default in Docusaurus. Note the root of your site always has a trailing slash (`/docs/`)


<img width="1010" alt="CleanShot 2023-04-06 at 18 44 36@2x" src="https://user-images.githubusercontent.com/749374/230443280-62d7fe6d-59c8-4044-9683-d3f5b2377a20.png">


See https://github.com/slorber/trailing-slash-guide

> At least allow swizzling the Link component or useBaseUrl hook.

We can do that and give you easier options to customize the linking behavior

**Comment by Zenahr** [comment]
@slorber Our use-case for using the hash router is to provide a zip for customers who won't always have internet access when needing to read our docs (e.g., underground car park).

I tried to get it working but when building the site I receive:

```js
[ERROR] Error: Unable to build website for locale en.
    at tryToBuildLocale (/home/zenahr/DOCS_NEW/product-docs/node_modules/@docusaurus/core/lib/commands/build.js:54:19)
    at async /home/zenahr/DOCS_NEW/product-docs/node_modules/@docusaurus/core/lib/commands/build.js:65:9
    at async mapAsyncSequential (/home/zenahr/DOCS_NEW/product-docs/node_modules/@docusaurus/utils/lib/jsUtils.js:21:24)
    at async Command.build (/home/zenahr/DOCS_NEW/product-docs/node_modules/@docusaurus/core/lib/commands/build.js:63:5) {
  [cause]: [Error: ENOENT: no such file or directory, open '/home/zenahr/DOCS_NEW/product-docs/build/Home/index.html'] {
    errno: -2,
    code: 'ENOENT',
    syscall: 'open',
    path: '/home/zenahr/DOCS_NEW/product-docs/build/Home/index.html'
  }
}
[INFO] Docusaurus version: 3.5.2
Node version: v20.14.0
```

We run 3 docs-plugin instances, out of which the default is `Home`. The folder for Home looks like this:

/Home/index.md (empty)
/Home/sidebars.js:
```js
// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
    sidebar: [{type: 'autogenerated', dirName: '.'}],
  };

  module.exports = sidebars;
```

The site builds fine when using the regular router, but fails with the error shown above when using the hash router but I can't yet get behind why that is.

**Comment by slorber** [comment]
Sorry @Zenahr but I can't troubleshoot a problem like this without a minimal repro. Try forking your site and removing all useless/sensitive content until you have one
