### ISSUE TITLE
Remove distinction between docs and blog

### ISSUE THREAD

**Issue by dionjwa** [facebook/docusaurus#8885]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Motivation

I want blog features in docs, and docs feature in blogs, and I encounter many issues where others want similar things, and the distinction between them is unclear.

- they both show "pages"
- authors can be shown in blog posts, and it's desired to show them in docs
- desired similar controls for sidebars, navigation, etc, but some things like disabling the right navigation, is possible in docs, but not blogs

You get the idea. These could be the same thing, just configured slightly differently

### Self-service

- [ ] I'd be willing to do some initial work on this proposal myself.

**Comment by Josh-Cena** [comment]
These things should be proposed one-by-one: saying "they should support the same things" isn't very actionable, because they are distinct sets of features with different goals of UX and content management. For example, the primary organization of docs would always by sidebar, while for blog it's always in linear chronology. We don't expect this fundamental concept to change.

> they both show "pages"

Not sure what this means

> authors can be shown in blog posts, and it's desired to show them in docs

Showing authors for docs is proposed in https://github.com/facebook/docusaurus/issues/6218. It's more complex than blog, because docs are constantly updated and re-written, so there does not exist one clear "author" of a page, and we can only display a list of contributors.

> some things like disabling the right navigation, is possible in docs, but not blogs

`hide_table_of_contents` is a front matter present in both docs and blog: https://docusaurus.io/docs/api/plugins/@docusaurus/plugin-content-blog#hide_table_of_contents

Are there others you'd like to propose? Otherwise I will close this as unactionable.

**Comment by slorber** [comment]
There is a distinction between docs and blogs because those are different plugins run by different codes that are decoupled.

The best we can do is to try to make the API and behavior of both plugins consistent with each others so that they are more intuitive to use.

If you notice a consistency problem that we should aim to fix to improve the DX, please open a dedicated issue **per subject** so that we can discuss each subject independently, instead of creating one issue for everything.
