### ISSUE TITLE
Google SEO Blocker: No unique URL handling

### ISSUE THREAD

**Issue by deleonio** [facebook/docusaurus#8969]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [X] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

Where can we fix the unique URL handling - Google does not indicied our website - we have a lot of issues in the google search console.

Example:
- https://docusaurus.io/docs/docusaurus-core/
- https://docusaurus.io/docs/docusaurus-core

Both works - without Slash over the navigation

### Steps to reproduce

1. Open https://docusaurus.io/docs/docusaurus-core/
2. Look at the browser url line `https://docusaurus.io/docs/docusaurus-core/`
3. Click in the nav left on "Client API"
4. Look at the browser url line `https://docusaurus.io/docs/docusaurus-core`

### Expected behavior

Only one `https://docusaurus.io/docs/docusaurus-core/`- maybe with Slash at the end.

### Actual behavior

Both URLs works
- `https://docusaurus.io/docs/docusaurus-core/`
- `https://docusaurus.io/docs/docusaurus-core`

### Your environment

- Public source code: https://github.com/public-ui
- Public site URL: https://public-ui.github.io/docs/willkommen
- Docusaurus version used: ^2
- Environment name and version (e.g. Chrome 89, Node.js 16.4): all
- Operating system and version (e.g. Ubuntu 20.04.2 LTS): all

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by slorber** [comment]
Both URLs work yes, but why exactly is this a problem?

Both URLs set the same canonical URL, and Google/Search engines use this to deduplicate content:

```
<link data-rh="true" rel="canonical" href="https://docusaurus.io/docs/docusaurus-core">
```

Docusaurus is only responsible for building a folder full of static files (`./build`) and is not providing any behavior on how those files are served. 


---

If you really want a single URL to serve a single page (which I think is useless IMHO), this is outside the scope of Docusaurus and should be configured on your host directly.

The only thing Docusaurus offers is control over the static file names through the `trailingSlash` config: 
- https://docusaurus.io/docs/deployment#trailing-slashes
- https://docusaurus.io/docs/api/docusaurus-config#trailingSlash

And here's a non-exhaustive guide on how popular hosting solutions serve the static files built by Docusaurus: https://github.com/slorber/trailing-slash-guide

Closing because there's nothing we can do in Docusaurus to solve your problem.
