### ISSUE TITLE
Table `|` character error

### ISSUE THREAD

**Issue by SuperManito** [facebook/docusaurus#9008]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [X] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

When using code tags in tables. If the content contains a '|' character, it will be recognized as a list separator

### Reproducible demo

https://githubbzjyie-l5a2--3000--fc9e1a28.local-corp.webcontainer.io/docs/intro

### Steps to reproduce

```
|  name   | desc |
| :-----: | ---- | ---- |
| `--help | -h`  | Help |

or

|      name      | desc |
| :------------: | ---- |
| `--help \| -h` | Help |
```

### Expected behavior

Will not be parsed. At least the problem doesn't appear on other documentation engines

### Actual behavior

.

### Your environment

- Public source code:
- Public site URL:
- Docusaurus version used:
- Environment name and version (e.g. Chrome 89, Node.js 16.4):
- Operating system and version (e.g. Ubuntu 20.04.2 LTS):

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by Josh-Cena** [comment]
Hi, I'm not sure what "other documentation engines" you are referring to, but this is the exact behavior of GitHub, which is that you need to escape the pipe to avoid it becoming a column separator:

```md
|      name     | desc |
| :-----------: | ---- |
| `--help | -h` | Help |

|      name      | desc |
| :------------: | ---- |
| `--help \| -h` | Help |
```

|      name     | desc |
| :-----------: | ---- |
| `--help | -h` | Help |

|      name      | desc |
| :------------: | ---- |
| `--help \| -h` | Help |

We are using MDX, so any behavior is inherited from this parser and we have no control over it. Because Markdown tables is a GitHub Markdown extension syntax anyway, I think it's best for us to align behavior with GitHub.
