### ISSUE TITLE
Provide documentation on configuring .jsonld files to be loaded as script

### ISSUE THREAD

**Issue by thadguidry** [facebook/docusaurus#9052]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Description

We currently do OK by mentioning that scripts can be loaded.
https://docusaurus.io/docs/api/docusaurus-config#scripts
Great!

However, we should provide an example to also be linkable to our SEO section for https://docusaurus.io/docs/seo#structured-content.

For example, it's unclear what or where the best convention is (so we should provide a paragraph on guidelines under structured-content and also under the API reference for docusaurus-config#scripts) when a user has created their `.jsonld` file for Schema.org context to be loaded.  Where to place the `.jsonld` file in Docusaurus file hierarchy is a bit unclear as a best practice.  Should it go under `/src`?  Or `/static`? or `/assets`? somewhere else?

where in Docusaurus file heirarchy do I place my `seo_homepage.jsonld` file to be properly loaded in this example?
```js
module.exports = {
  scripts: [
  { src: 'https://plausible.io/js/script.js',
    'data-domain': 'homihq.com',
    defer: true,
    async: false,
  },
  { src: 'seo_homepage.jsonld',
    type: 'application/ld+json',
    defer: true,
    async: true,
  },
  ],
  ```

### Self-service

- [X] I'd be willing to address this documentation request myself.

**Comment by slorber** [comment]
cc @johnnyreilly maybe you have an opinion on how we could lightly document how to use microdata/jsonld/structured data?

We probably don't want to copy/paste authority sites best practices but we could add some external links and mention various possibilities.

**Comment by thadguidry** [comment]
I've tried many different things to get my local `.jsonld` file content to be added either into the `<script>` tag which does get created successfully.
Here's the tag snippet that does indeed get created:
```html
<script src="seo_homepage.jsonld" type="application/ld+json" defer="" async=""></script>
```
I didn't see the jsonld file being copied into sources?
LINE 14:
![image](https://github.com/facebook/docusaurus/assets/986438/e40b815f-8d46-4a2c-8148-3744d5dd8889)

But notice the content itself does not show up in between the `<script>` tags?
```jsonld
FILE: seo_homepage.jsonld

{
    "@context": "https://schema.org",
    "@type": "Organization",
        "name": "Homi",
        "url": "https://homihq.com",
        "logo": "https://homihq.com/img/logo-black.png"
}
```

Maybe the issue is how I'm trying to read from `src: ` ? or the pathing? or maybe I need to `resolve()` specially?  So I thought that we could slightly improve the docs, as well as figure out why something that did seem documented well enough and simple, doesn't seem to be working as I expected.

**Comment by thadguidry** [comment]
I'm happy to push this over to the docusaurus.community site, but I thought a brief mention of `jsonld` handling could benefit everyone with a small paragraph explaining how you might accomplish something like what I am trying to do.

**Comment by slorber** [comment]
> I didn't see the jsonld file being copied into sources anywhere in the left panel?


Adding `scripts` to config does not magically make those scripts part of your deployment.

Any `/static` file is supposed to be copied to `/build` and become part of your Docusaurus deployment. If that's not the case you can open an issue with a repro.  

> But more importantly, notice the content of the jsonld file itself does not show up in between the <script> tags?

I don't understand what you mean by "the content of the jsonld file itself does not show up in between the <script> tags"

Docusaurus does no magic here, if you add a script tag, it will add the script page to the html page as is, that's all it does. Don't expect Docusaurus to fetch the content of it and insert it as a string in the static page. 

Having the script tag added this way to your page is definitively the expected behavior:

```html
<script src="seo_homepage.jsonld" type="application/ld+json" defer="" async=""></script>
```

> Maybe the issue is how I'm trying to read from src:  ? or the pathing as in my original comment above? or maybe I need to resolve() specially? 

I have no idea what you mean by "trying to read from src". `scripts ` are added as is, unmodified. It is your responsibility to make sure the URL or relative/absolute path you reference in the script exists, and there's not a single way to do that.

> So I thought that we could slightly improve the docs, as well as figure out why something that did seem documented well enough and simple, doesn't seem to be working as I expected.

My intuition is that you try to put `src/seo_homepage.jsonld` and then use a script with src `seo_homepage.jsonld`. Where do you see it documented anywhere that it's something you should do?

Eventually you should do `static/seo_homepage.jsonld` and use a script with `/seo_homepage.jsonld`

Again, Docusaurus does absolutely 0 magic here, it just adds a script tag as is. There's no "processing" or whatever, it is just how html works.

If all your pages contain a script with src `seo_homepage.jsonld` (no leading slash), then your browser will consider it as a relative pathname and resolve against the current page, which is likely not what you want. For example it will try to load `/docs/myCategory/seo_homepage.jsonld` while you are on page `/docs/myCategory/myDoc`, because that's how the web simply works.

**Comment by thadguidry** [comment]
@slorber Firstly, thanks for your patience!  I was frantically trying to find the easiest route to add this to only the homepage:

```html
<script src="seo_homepage.jsonld" type="application/ld+json" defer="" async="">
{
    "@context": "https://schema.org",
    "@type": "Organization",
        "name": "Homi",
        "url": "https://homihq.com",
        "logo": "https://homihq.com/img/logo-black.png"
}
</script>
```

But I think I have my answer after spending a few hours all over the docs... which is unfortunate and where I think that structured-content section could improve.

After those few hours spent by me, I think what is likely the missing piece of documentation under the https://docusaurus.io/docs/seo#structured-content would be a light mention something along the lines of:

> Sometimes you want to apply SEO changes only to the homepage or landing page.  You can add additional custom `<script>`, `<meta>`, `<link>`, etc. tags to only the homepage by modifying `/src/pages/index.js` and using the `<Head>` API https://docusaurus.io/docs/docusaurus-core#head as its examples show.

What do you think of the above quote or similar going into that [structured-content](https://docusaurus.io/docs/seo#structured-content) section in a PR by me?

**Comment by thadguidry** [comment]
THIS finally:

```jsx
import Head from '@docusaurus/Head';
import MySEO from '@site/static/seo_homepage.json';

function CustomSEO() {
  return (
    <Head>
      <script src="" type="application/ld+json" defer="" async="">
        {JSON.stringify(MySEO)}
      </script>
    </Head>
  );
}

export default function Home() {
  const {siteConfig} = useDocusaurusContext();
  return (
    <Layout
      title={`${siteConfig.title}`}
      description="Low code API Development. <head />">

//  ---- USE IT HERE ?
        <CustomSEO />
// ----
      <HomepageHeader />
      <main>
        <HomepageFeatures />
      </main>
    </Layout>
  );
}
```

But then I get what seems to be many duplicated elements inside `<head>` in the HTML?
So I'm liking overloading something where I should not be?

**Comment by thadguidry** [comment]
You might be well right.  So let's close this issue.

**Comment by slorber** [comment]
Great

Will still add a few other metadata in the example, this might help users to understand

**Comment by slorber** [comment]
Please review this PR and let me know if it makes things clearer: https://github.com/facebook/docusaurus/pull/9071
