### ISSUE TITLE
Custom magic comments for CodeBlock with raw-loader not working

### ISSUE THREAD

**Issue by felipecrs** [facebook/docusaurus#9129]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [X] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

I think the title says everything. Custom magic comments are working on plain markdown code blocks but not on MDX CodeBlock with raw-loader.

myfile.yaml contents:

```
# hide-next-line
docsTitle: My File
# hide-start
docsDescription: |
    My File description
# hide-end
this: should-show
```

### Reproducible demo

https://github.com/felipecrs/shiki-docusaurus-test/commit/49e3e8af2021f86df74a122b35c13908b16459c0

### Steps to reproduce

Described above.

### Expected behavior

To work as it works for plain md code blocks.

### Actual behavior

![image](https://github.com/facebook/docusaurus/assets/29582865/a9be92ca-6e85-40e7-9383-a94c77e0c52b)

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by felipecrs** [comment]
PS: I'm opening this as a bug because documentation doesn't mention anything about custom magic comments being unsupported in CodeBlocks with raw-loader. In fact the default magic comment works (highlight-next-line for example).

**Comment by Josh-Cena** [comment]
If the default magic comments work but not custom ones, it should probably be a bug. Otherwise I was not so sure ^^

**Comment by slorber** [comment]
You are using a shiki preset that is overriding our default code block

This shiki preset does not implement magic comments:
https://github.com/shikijs/twoslash/blob/main/packages/docusaurus-preset-shiki-twoslash/docusaurus-theme-shiki-twoslash/theme/CodeBlock/index.js

Please open a new repro without using any third-party plugin/preset, otherwise it can't be considered as a bug in docusaurus core

**Comment by felipecrs** [comment]
@slorber I'm not using the shiki preset for reproducing this issue. The branch I referred to in the example doesn't contain shiki stuff although the repo name.

**Comment by felipecrs** [comment]
I also noticed this issue first in my production website (internal), which doesn't use Shiki, and only after that I created the reproduction repo.

**Comment by slorber** [comment]
I can reproduce, minimal repro: https://stackblitz.com/edit/github-ebe6eo-zlw6c8?file=src%2Fpages%2Findex.md

It seems related to the `showLineNumbers` props:

![CleanShot 2023-07-20 at 17 06 54@2x](https://github.com/facebook/docusaurus/assets/749374/239ba0dd-0c15-4273-a1d8-42e5e20d8066)

This prop overrides the `display: none;` CSS you set:

<img width="341" alt="CleanShot 2023-07-20 at 17 09 22@2x" src="https://github.com/facebook/docusaurus/assets/749374/a61ad99d-1070-487e-8061-84bfcdbec487">

I think it's working as intended: the CSS className is added properly to the line, it's just "ignored" due to styling conflicts. So it's not a magic comments bug but rather a conflict between our theme CSS and your custom CSS, which is hard to avoid, unfortunately.

I'd like your custom CSS to automatically override our theme by default: but that belongs to a more general issue about CSS insertion order: https://github.com/facebook/docusaurus/issues/3678

---

The workaround is simply to use `!important`:

```css
.code-block-hide-line {
  display: none !important;
}
```

<img width="294" alt="CleanShot 2023-07-20 at 17 12 43@2x" src="https://github.com/facebook/docusaurus/assets/749374/968cc0d9-a564-4ec0-8ce0-c86f7680f79d">
