### ISSUE TITLE
React hydration issue on Docusaurus v2

### ISSUE THREAD

**Issue by RoiArthurB** [facebook/docusaurus#9208]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [X] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

While, on long documentation page (~ 3k MD lines), opening an anchor link (from the same page or another one) in the current tab works fine. However, if this same link is opened in a new tab, the anchor link is broken in the page.

### Reproducible demo

https://stackblitz.com/edit/github-rr9wit-wtoyyd?file=docs%2FOperatorsSZ.md

### Steps to reproduce

1. Create a new Docusaurus project
2. Add some long MD files in the folder docs/
3. Go on one new documentation page (in stackblitz example, open docs/OperatorsSZ#color-related-operators )
4. Pick a link to another page ( link `gradient`)
  1. If opening in same tab, see everything good
  2. If opening in new tab, see anchor attached to another h3 tag below in the page

### Expected behavior

Having the same behavior while opening in a link in the current tab and in another tab.

### Actual behavior

Opening link to a new tab create a wrong page with anchor linked to another tag on the page.

![image](https://github.com/facebook/docusaurus/assets/16764085/e72c2631-4b37-4f45-90e7-758159bc4d7e)

![image](https://github.com/facebook/docusaurus/assets/16764085/eda808a0-d71a-45ea-8d30-2a0bf2cf8a75)

### Your environment

- Public source code: https://github.com/gama-platform/gama-platform.github.io/
- Public site URL: https://gama-platform.org/
- Docusaurus version used: latest
- Environment name and version (e.g. Chrome 89, Node.js 16.4): Any
- Operating system and version (e.g. Ubuntu 20.04.2 LTS): Any

- Original issue : https://github.com/gama-platform/gama-platform.github.io/issues/179

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by Josh-Cena** [comment]
I can reproduce this, and 99% of the time when this happens, it's a hydration mismatch. Do you have any dynamic content generation on these pages?

**Comment by RoiArthurB** [comment]
@Josh-Cena nothing. It's just some raw long markdown files listing some langage keywords with some text explaination and code block. No images, no dynamic stuff, simpliest files possible imported from Github Wiki ( https://github.com/gama-platform/gama/wiki/OperatorsSZ.md )

**Comment by slorber** [comment]
It is annoying but a bit expected that the problem can be reproduced in StackBlitz in dev mode, because the target page is not static. 

However it should work in production mode, or if you run `yarn build && yarn serve` on the StackBlitz terminal.

I am able to open `https://<localprefix>.webcontainer.io/docs/OperatorsDH#harmonic_mean` and the page scrolls to the correct location in prod mode:

<img width="1893" alt="CleanShot 2023-08-10 at 17 59 47@2x" src="https://github.com/facebook/docusaurus/assets/749374/e8e18d9f-bed2-4a03-8318-2621ee447a52">




---

> I can reproduce this, and 99% of the time when this happens, it's a hydration mismatch. Do you have any dynamic content generation on these pages? (By that I mean content generated on-the-fly during rendering, not build phase)

Hydration issues can happen also due to our theme. I fixed some issues for Docusaurus v3, but v2 users can still occasionally get weird behaviors on regular docs content, although it should be quite rare. I don't think it's the problem here.

**Comment by slorber** [comment]
Hey, @Josh-Cena indeed it looks like an hydration issue:

With JS disabled:

<img width="422" alt="CleanShot 2023-08-10 at 18 12 46@2x" src="https://github.com/facebook/docusaurus/assets/749374/7bc1acd2-7066-4676-8919-9420174f057a">


With JS enabled (after React hydration):

<img width="388" alt="CleanShot 2023-08-10 at 18 13 31@2x" src="https://github.com/facebook/docusaurus/assets/749374/2f84b5ca-6296-441e-a372-dc2504f489ca">

**Comment by slorber** [comment]
For Docusaurus v3 we upgraded to React 18, which now emits error messages when there's any non-critical hydration mismatch (ie it's not good, but React can recover). This allowed me to fix SSR/CSR mismatches in our theme that could cause this kind of issues quite randomly on some docs. Although it happens rarely, this can be annoying and cause more troubles than just a bad anchor link.

---

I upgraded your repro to v3 canary, did the necessary docs changes (replacing `<` and `{` chars that now cause problems with MDX 2), and now the problem is gone, there's no more React hydration issue on that `#gradient` anchor on a production build.

https://stackblitz.com/edit/github-rr9wit-xvu9qc?file=docusaurus.config.js,docs%2FOperatorsDH.md

**Comment by RoiArthurB** [comment]
Hi @slorber 

So the issue seems to come from the old version of React used by Docusaurus 2 and not much fix can be provided else than moving to newest Docusaurus 3 and it's upgraded React version, right ?

I will give it a try on local build, but I can't take the risk of using the very first alpha release for the documentation website. All of it has to be stable (not much tech nor time for maintaining this part of our open-source software) and even your stackblitz is failing on some package install rn...

```
❯ yarn install && npm start
yarn install v1.22.19
warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
[1/5] 🔍  Validating package.json...
[2/5] 🔍  Resolving packages...
[3/5] 🚚  Fetching packages...
error An unexpected error occurred: "Failed to fetch dependencies:
- @types/gtag.js@0.0.12".
info If you think this is a bug, please open a bug report with the information provided in "/home/projects/github-rr9wit-xvu9qc/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

Anyway, if the only solution is D3, I'll wait for you guys to have more stable release and a documented migration path :)

**Comment by slorber** [comment]
> So the issue seems to come from the old version of React used by Docusaurus 2 and not much fix can be provided else than moving to newest Docusaurus 3 and it's upgraded React version, right ?

It's not related to the React version. 

Technically I could take time to backport a few changes I did for Docusaurus v3 to v2, but it is time I currently don't have, it requires some work, the process would is error prone and with no guarantee of success, for only helping one user that currently has this problem on a single page. So if I do this I'd do this after v3 becomes stable anyway because I want to focus on that.

---

Generally, when this kind of issue happens, adding some html tags or changing a bit the content around the problematic doc fragment can fix it. I can't tell the exact steps but there should be a way to fix it this way. Often this is a good-enough workaround.

---

FYI for me D3 is stable enough to use in production. The StackBlitz is a quick hacky edit of yours, it's not a proper setup: you have to choose between yarn or npm for example.

The reason D3 is still alpha is:
- I will pass it in beta once RN and Jest websites use it in production (working on it right now) and once I have better upgrade docs (currently spread into multiple PRs)
- I will pass it in RC/GA once the community report the remaining bugs (ie: I need you to try it)

**Comment by RoiArthurB** [comment]
> Technically I could take time to backport a few changes I did for Docusaurus v3 to v2, but it is time I currently don't have, it requires some work, the process would is error prone and with no guarantee of success, for only helping one user that currently has this problem on a single page. So if I do this I'd do this after v3 becomes stable anyway because I want to focus on that.

I understand.

> Also even if I backport an attempt to fix it in v2, there's no guarantee that this specific problem is not caused by code on your own site. I'm not sure to understand where your site code it so can't inspect it, you look to have a fancy setup based on data stored in GitHub Wiki? thinking interesting.

As you said, all the website's documentation source is hosted on the Github's wiki part of the main software's repository. This is because I use Docusaurus (since v1) as an almost drop-in framework to build static website for this markdown documentation. The problematic pages (OperationXX.md) are generated from the Javadoc in the source code, pushed in the wiki and, later on, built in Docusaurus.



> Generally, when this kind of issue happens (we have like one report every 6 months), adding some html tags or changing a bit the content around the problematic doc fragment can fix it. I can't tell the exact steps but there should be a way to fix it this way. Often this is a good-enough workaround. Sometimes just adding MDX random tags like `<br/>`, `<div>` or `<span>` can fix it.

I already tried to change tags for those pages (as they are generated) but nothing is working. Also, I pointed in my issue only a single tag having this issue, but it appears on most of links past a certain point on the web page. I really can't diagnose much as my knowledges on react are very limited...

For instance, clicking on the tag [`has_belief_with_name_op`](https://gama-platform.org/wiki/OperatorsDH#has_belief_with_name_op) from this section https://gama-platform.org/wiki/OperatorsAA#bdi will lead to the good part, but will create a little scroll down and the link on the page itself isn't correct. 


> FYI for me D3 is stable enough to use in production. The StackBlitz is a quick hacky edit of yours, it's not a proper setup: you have to choose between yarn or npm for example.
> 
> The reason D3 is still alpha is:
> 
>     * I will pass it in beta once RN and Jest websites use it in production (working on it right now) and once I have better upgrade docs (currently spread into multiple PRs)
> 
>     * I will pass it in RC/GA once the community report the remaining bugs (ie: I need you to try it)

Nice to hear. I would be glad to try it, but I'll really need a little migration doc to follow as I don't have nor the time/knowledges to dive in every PR trying to understand every modifications... I'll wait at least for a little bullet point of points to follow and modifications before trying this new alpha release as a way to contribute to this great documentation project #8968

**Comment by RoiArthurB** [comment]
Hi @slorber 

I tried to add my big Operator pages in a fresh Docusaurus 3 project and this issue remains :/ 

Step to reproduce : 
- Create new Docusaurus project : `npx create-docusaurus@next website classic`
- Copy and paste Operators_XX_ pages (can be found [here](https://github.com/gama-platform/gama-platform.github.io/tree/sources/website/versioned_docs/version-1.9.2)) in `docs` subfolder
- Open website and follow original steps 
- See hydration issue

**Comment by slorber** [comment]
@RoiArthurB please create a repro using docusaurus.new running on Docusaurus v3 and tell me exactly which page / heading I should look at. 

There are many operator pages and many headings, and having a clear way to reproduce your problem on v3 will save time

**Comment by slorber** [comment]
> Hi @slorber
> 
> I tried to add my big Operator pages in a fresh Docusaurus 3 project and this issue remains :/
> 
> Step to reproduce :
> 
> * Create new Docusaurus project : `npx create-docusaurus@next website classic`
> * Copy and paste Operators_XX_ pages (can be found [here](https://github.com/gama-platform/gama-platform.github.io/tree/sources/website/versioned_docs/version-1.9.2?rgh-link-date=2023-09-27T05%3A19%3A59Z)) in `docs` subfolder
> * Open website and follow original steps
> * See hydration issue

I spent some time on it and it seems your doc set does not compile under MDX v2 / Docusaurus v3 and need some adaptation. 

For example `[<](OperatorsAA#<)` can't compile, you now need to escape it: `[\<](OperatorsAA#<)`

I find it a bit odd that you give me repro instructions that you clearly couldn't even run yourself 😅 

That's why we ask for a docusaurus.new sandbox running on v3: to be sure that we talk about the same thing and can reproduce the bug consistently. Otherwise we are all losing our time.

**Comment by RoiArthurB** [comment]
Hi @slorber 

I know this didn't work, I forgot to paste you this link on a new repo with the MD cleaned to compile with MDX 2 : https://roiarthurb.github.io/docusaurus-hydration-issue9208 / https://github.com/RoiArthurB/docusaurus-hydration-issue9208

And, I just dug it a bit longer and I did probably confuse between the 2 versions as this issue is solved on Docusaurus 3 :) Which might mean that I _only_ need to turn my documentation MDX 2 compliant to be able to migrate the website :D

**Comment by RoiArthurB** [comment]
I did migrate the documentation on Docusaurus 3 and the issue is totally fixed now. Thanks for this great work !

**Comment by slorber** [comment]
Great to know thanks 👍
