### ISSUE TITLE
Expose frontmatter in plugin-content-docs client hooks

### ISSUE THREAD

**Issue by imp-dance** [facebook/docusaurus#9263]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Description

Currently, the only properties available are 

* **`id`**
* **`path`**
* **`sidebar`**

...when accessing the data through one of Docusaurus' client hooks (ex: `useGlobalData` or `useDocusaurusContext`). It would be great if we could get some more metadata in these objects. Some properties that could be included could be:

* **`frontmatter`** - A record that contains frontmatter data for the relevant document
* **`markdown`** - A string that contains the markdown content

I realise that exposing the markdown could be a challenge, especially considering the fact that pages can be written in MDX. Maybe that wouldn't be necessary for my specific use case.

### Motivation

I want to create a "internal link preview" component that when hovered, shows a popover that contains a small preview of the document that the user is linking to.

I'm currently able to "find" the document, but I'm not getting enough relevant information to render a preview of the document. If I receive the frontmatter, atleast I can show a title and description.

### API design

Currently, `docusaurus-plugin-content-docs` exposes this data to the client hooks:

```typescript
type PluginContentDocsData = Record<string, {
   breadcrumbs: boolean;
   path: string;
   versions: Array<{
      docs: Array<{
         id: string;
         path: string;
         sidebar: string;
      }>;
      // ...rest
   }>;
}>;
```

But if the frontmatter is available, it would be great to also get that in the doc-object:

```typescript
type PluginContentDocsData = Record<string, {
   breadcrumbs: boolean;
   path: string;
   versions: Array<{
      docs: Array<{
         id: string;
         path: string;
         sidebar: string;
         frontmatter: Record<string, string | string[]>;
      }>;
      // ...rest
   }>;
}>;
```

### Have you tried building it?

Yes I've tried looking into every client API available to see if it was possible to render a document preview from a React component, but alas it seems to not be possible given the current API of `docusaurus-plugin-content-docs` (since it doesn't expose enough information about the documents).

### Self-service

- [ ] I'd be willing to contribute this feature to Docusaurus myself.

**Comment by slorber** [comment]
Hi

I understand your use-case, but unfortunately the global data is kept minimal for a good reason. If we add lots of content there, then loading any of your site's page would be much more heavy in terms of JS/JSON data to load. Even if a page does not use that data, it will still have to be loaded because everything ends up in the same file.


In https://github.com/facebook/docusaurus/issues/6923 I propose to introduce this so that you can register yourself extra global data, but keep in mind that data should rather be kept minimal in any case:

```md
global_custom_props: 
  a: b
  c: d
  e: ["f"]
```

In the future, React Server Components (track https://github.com/facebook/docusaurus/issues/9089) are going to provide good flexibility to implement your hover preview use case, without the need for global data. It's possible that we'll even deprecate the global data API in favor of RSCs.
