### ISSUE TITLE
When there are some special characters, compilation fails

### ISSUE THREAD

**Issue by zonewancheng** [facebook/docusaurus#9287]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [ ] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

Module build failed (from ./node_modules/@docusaurus/plugin-content-docs/node_modules/@docusaurus/mdx-loader/lib/index.js):

### Steps to reproduce

Error example 1:
module.md
```
# TypeScript 模块
## import type 语句

import 在一条语句中，可以同时输入类型和正常接口。
```
Result 1:
```
SyntaxError: /module.md: Unexpected character '，'. (1:13)
> 1 | import 在一条语句中，可以同时输入类型和正常接口。
    |              ^
    at parser.next (<anonymous>)
```

Error example 2:
index.md
```
<table>
<tr>
  <td class="xl65" width="392" style="border-top:none;border-left:none;width:294pt">{"status":"upgrade complete","result": {"sourceVersion":"redioxy-v1.6.0.zip","targetVersion":"redioxy-v1.4.4","upgrade": true,"takeover":true,"takeoverSessionCount": 0,"executeTime":2093,"startTime": "2023-04-1114:09:17"},"UpgradePids": [{"upgrade":true,"takeover": true,"sourcePid":29724,"targetPid": 31669,"SessionCount":0,"errorReason": "","executeTime": 620}]}</td>
</tr>
</table>
```
Result 2:
```
SyntaxError: index.md: Unexpected token, expected "}"
```

### Expected behavior

Interpreting the error location as text rather than parsing it based on code

### Actual behavior

```
✖ Client
  Compiled with some errors in 399.64ms



SyntaxError: /module.md: Unexpected character '，'. (1:13)
> 1 | import 在一条语句中，可以同时输入类型和正常接口。
    |              ^
    at parser.next (<anonymous>)
    at normalizeFile.next (<anonymous>)
    at run.next (<anonymous>)
    at transform.next (<anonymous>)
    at new Promise (<anonymous>)
SyntaxError: /index.md: Unexpected token, expected "}" (106:93)
  > 106 |   <td class="xl65" width="392" style="border-top:none;border-left:none;width:294pt">{"status":"upgrade complete","result": {"sourceVersion":"redioxy-v1.6.0.zip","targetVersion":"redioxy-v1.4.4","upgrade": true,"takeover":true,"takeoverSessionCount": 0,"executeTime":2093,"startTime": "2023-04-1114:09:17"},"UpgradePids": [{"upgrade":true,"takeover": true,"sourcePid":29724,"targetPid": 31669,"SessionCount":0,"errorReason": "","executeTime": 620}]}</td>
      |                                                                                              ^
  client (webpack 5.88.2) compiled with 2 errors

✖ Client
  Compiled with some errors in 187.19ms

```

### Your environment

- Public source code: Please refer to the steps above for the instructions
- Public site URL: null
- Docusaurus version used: 2.4.1
- Environment name and version (e.g. Chrome 89, Node.js 16.4): Node:16.16
- Operating system and version (e.g. Ubuntu 20.04.2 LTS): macos 13.5 (22G74),Apple M1 pro

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by slorber** [comment]
Docusaurus is using MDX:
https://docusaurus.io/docs/markdown-features/react

`import 在一条语句中，可以同时输入类型和正常接口。` gets interpreted as an ES import, that's why it fails.

The 2nd case: you are trying to embed HTML in Markdown. With MDX you need to use JSX instead, it's not exactly the same syntax.

Use the MDX v1 playground: https://mdx-git-renovate-babel-monorepo-mdx.vercel.app/playground/

---

Note: in Docusaurus v3 (using MDX v2), you will be able to opt-out of MDX/React usage, and opt-in instead for using a std commonmark compatible parser (use frontmatter `format: md`). 

Those things will be supported:

![CleanShot 2023-09-07 at 12 37 03](https://github.com/facebook/docusaurus/assets/749374/62f651e1-0407-49c2-bc21-815bf9b206f6)

Playground: https://mdxjs.com/playground/

Need to turn these 2 options on: 

![CleanShot 2023-09-07 at 12 37 45](https://github.com/facebook/docusaurus/assets/749374/dd11c2a4-2819-46e3-9156-aa6ef4539159)

Docusaurus v3 is in alpha and will move to beta/RC/GA very soon. A good time to give it a try.
https://github.com/facebook/docusaurus/releases/tag/v3.0.0-alpha.0
