### ISSUE TITLE
Million.js Implementation with Docusaurus

### ISSUE THREAD

**Issue by anaclumos** [facebook/docusaurus#9289]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Motivation

Million.js is a Virtual DOM Replacement for React. It claims to make React 70% faster. However, it requires some [Webpack setup](https://million.dev/docs/install#ignoring-components), and I would like to learn how to do it. [Docusaurus Support · Issue #566 · aidenybai/million](https://github.com/aidenybai/million/issues/566)

### Self-service

- [X] I'd be willing to do some initial work on this proposal myself.

**Comment by slorber** [comment]
Curious: what's the outcome you expect in your app by installing Million?
https://million.dev/blog/virtual-dom#lots-of-static-content-with-little-dynamic-content

It looks for for quite static content, but on Docusaurus we don't do many React re-renders anyway because the whole site is quite stateless.

Does it have the possibility to reduce hydration time?

Does it have the possibility to reduce page transition time?

Also we are going to start using React Server Components in the future (https://github.com/facebook/docusaurus/issues/9089). Once most of the React code of our theme is RSC running at build time, is Million still worth using?

cc @aidenybai @tobySolutions

---


If the Webpack setup is that simple, you could just create a Docusaurus plugin and use the `configureWebpack` hook, to install the Millions webpack plugin: https://docusaurus.io/docs/api/plugin-methods/lifecycle-apis#configureWebpack

But is it enough to make it work? Will it also compile our theme code too, that is inside a library and is not first-party site code?

**Comment by anaclumos** [comment]
I didn't know about Docusaurus moving to RSC! If then, there wouldn't be much incentive to implement it.

**Comment by aidenybai** [comment]
hydration currently is a WIP. we can revisit this in the future
