### ISSUE TITLE
Providing properties for wrapping Admonition

### ISSUE THREAD

**Issue by GasimGasimzada** [facebook/docusaurus#9300]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Motivation

This is part of a bigger effort that I want to invest some time in if anyone here is interested in this direction. I want to incrementally make more of the `theme-classic` components safe for wrapping. As a first step, I decided to look into Admonition and wanted to share my thoughts.

My main motivation here is to provide a a way to use tailwind css for all styles while still using the Admonition components and logic provided by the docusaurus.

**Proposal:**

Currently, when I create wrappable version of Admonition, I get the following:

```tsx
import React from 'react';
import Admonition from '@theme-original/Admonition';

export default function AdmonitionWrapper(props) {
  return (
    <>
      <Admonition {...props} />
    </>
  );
}
```

We can provide a `className` prop here but this prop does not replace the infima class names that are stored in the class. So, my suggestion here is to provide a method or an object that maps to different class names:

```tsx
<Admonition {...props} classMap={{
  note: "bg-white-200",
  tip: "bg-yellow-200",
  info: "bg-blue-200",
  caution: "bg-orange-200",
  danger: "bg-red-200"
}} />
```

### Self-service

- [X] I'd be willing to do some initial work on this proposal myself.

**Comment by slorber** [comment]
If we go into this direction, then we could also pass the icon and label as a map, and entirely get rid of the sub components.

That somehow assumes that all admonitions are normalized to a std layout, which in practice may not always be the case considering users can implement their own admonitions.

---

The root `<Admonition/>` component is just the entry point that has the responsibility to redispatch props to the appropriate underlying admonition component. Those components should be able to stand alone and be self-contained.

If you want to use Tailwind instead of Infima, you should eject instead of wrap, and change the implementation details you don't like (ie usage of Infima). Wrapping is for "enhancing", not "overriding" internal impl details. `<AdmonitionTypeNote/>` should be able to render correctly alone, even when not used through the root `<Admonition>` component, so it should contain the Infima class.
