### ISSUE TITLE
Create whole card clickable to redirect to website on /showcase route's card 

### ISSUE THREAD

**Issue by noobtuber20103152** [facebook/docusaurus#9364]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Description

It will be better user experience to make whole card clickable to redirect there website.

### Motivation

Want to improve user experince of the website.

### Self-service

- [X] I'd be willing to contribute this feature to Docusaurus myself.

**Comment by AnishTiwari16** [comment]
please assign this to me

**Comment by Josh-Cena** [comment]
Hi, we don't do this because there are already many interactable parts in each card: the pills have hivernale tooltips and the source link is clickable. It's better not to stack interactivity because it becomes hard to tell whether each region will have a different action—if I hover over a pill and see the pointer become a little hand and a tooltip pops up, should I expect clicking it to take me to a page about that pill (for example about "design" or "i18n")?
