### ISSUE TITLE
@docusaurus/plugin-client-redirects does not work with GitHub Pages

### ISSUE THREAD

**Issue by miguelmartin75** [facebook/docusaurus#9412]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [ ] I have tried the `npm run clear` or `yarn clear` command.
- [ ] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [ ] I have tried creating a repro with https://new.docusaurus.io.
- [ ] I have read the console error message carefully (if applicable).

### Description

I am attempting to redirect `/docs/X` to `/docs/ego4d/X` if the page `X` does not exist as I have recently added mutliple instanced docs to the documentation site. The site I am hosting is hosted on github pages on this repo: https://github.com/EGO4D/docs

I have tried doing so via:

1. `@docusaurus/plugin-client-redirects` (this does not work locally or in production)
2. Using `Redirect`, `useLocation()` and `useIsBrowser()` by swizzling the NotFound component (both by wrapping and overriding it)

(2) does not work as I am unable to build a static site due to the use of Redirect, useLocation and useIsBrowser. I have tried useEffect in react, but this does not work as it states I am not in a react component.

It is unclear to me how to redirect subpages. Any help would be appreciated on this issue.

### Steps to reproduce

1. On development environment, goto localhost:3000/docs/abc
2. Observe that this redirects to localhost:3000/docs/ego4d/abc 
  - For (1) this does not work, but will according to the docs and other issues referencing this, i.e. #8691 
3. `yarn deploy`
4. Observe in production the above does not happen

### Expected behavior

Redirect according to my description

### Actual behavior

No redirect occurs

### Your environment

- Public source code: https://github.com/EGO4D/docs
- Public site URL: https://ego4d-data.org/docs/
- Docusaurus version used: 2.4.3
- Environment name and version (e.g. Chrome 89, Node.js 16.4): stable v20.4.0 & Chrome 118.0.5993.70 (arm64)
- Operating system and version (e.g. Ubuntu 20.04.2 LTS): MacOS Ventura 13.5.2

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by Josh-Cena** [comment]
Are you trying to redirect a fixed set of pages, or a wildcard redirect? Client-redirects works by emitting extra HTML files, so you cannot possibly achieve the latter.

**Comment by slorber** [comment]
If you think there is a bug, please report it correctly. You can't throw us a bunch of unclear attempts like that.


"does not work" is unclear, tell us exactly what happens, don't expect us to try to guess.

> I am attempting to redirect /docs/X to /docs/ego4d/X if the page X does not exist as I have recently added mutliple instanced docs to the documentation site. 

I would do:

```js
export default {
  plugins: [
    [
      '@docusaurus/plugin-client-redirects',
      {
        createRedirects(existingPath) {
          if (existingPath.includes('/docs/ego4d')) {
            // Redirect from /docs/X to /docs/ego4d/X
            return [
              existingPath.replace('/docs/ego4d', '/docs'),
            ];
          }
          return undefined; // Return a falsy value: no redirect created
        },
      },
    ],
  ],
};
```

While your current code is:

```js
 [
      '@docusaurus/plugin-client-redirects',
      {
        createRedirects(existingPath) {
          if(!existingPath.includes("ego4d") && !existingPath.includes("egoexo") && existingPath.includes("/docs/")) {
            return [
              existingPath.replace("/docs/", "/docs/ego4d/")
            ];
          }
          return undefined; // Return a falsy value: no redirect created
        },
      }
    ]
```

Your current code looks wrong to me, the "existing path" is the path of a real document (`/docs/ego4d/X`), not the path of the redirect you plan to create (`/docs/X`). 
You want to redirect from `/docs/X` to `/docs/ego4d/X`, but your code seems to try to do the opposite (redirect from `/docs/ego4d/X` to `/docs/X`)

---

To help you debug this, maybe start first by using a static hardcoded list of redirects, before attempting to create them dynamically.

---

`@docusaurus/plugin-client-redirects (this does not work locally or in production)`

We mention that this only works in production build in the docs, so don't expect it to even work locally, unless you build in production mode locally.

If you want to redirect from `/docs/ego4d/X`, and you can debug your own plugin usage because one of those 2 redirect files must exist after a production build:
- `/docs/ego4d/X/index.html` (with `trailingSlash: true` that you use)
- `/docs/ego4d/X.html`

If this file does not exist locally after your build then you did something wrong in your `createRedirects` logic.

---
 
> Using Redirect, useLocation() and useIsBrowser() by swizzling the NotFound component (both by wrapping and overriding it)

If you choose to use React or React-Router to do a redirect, that's a bit out of the scope of Docusaurus. If "it doesn't work" then you can open an issue to React-Router

> (2) does not work as I am unable to build a static site due to the use of Redirect, useLocation and useIsBrowser. I have tried useEffect in react, but this does not work as it states I am not in a react component.

If React complains then it's because you used it badly. Again we can't teach you how to use React here, it's out of the scope of Docusaurus. We don't even see your bad code to be able to help you 🤷‍♂️ 

---

If you want help, please help us help you. If you try multiple attempts, then create one branch per attempt, and describe each attempt clearly/independently with code used, screenshots, expectations and unexpected result. "doesn't work" is not helpful. Also if you look for support, please don't open bug reports. 

Also, unless a very clear minimal repro is provided, this is not a bug but a support request, for which Discord or GitHub discussions are a better place.

**Comment by miguelmartin75** [comment]
I see, it appears I was using `createRedirects` incorrectly, as I was thinking it input a path that the user would request. Instead it provides a mapping from existing documents to the set of redirects to be constructed.

Thanks.
