### ISSUE TITLE
Document how to integrate with Doxygen

### ISSUE THREAD

**Issue by JoelMarcey** [facebook/docusaurus#943]
## 📚 Documentation

Clear and explicit documentation on how to integrate Doxygen-generated APIs.

## Have you read the [Contributing Guidelines on issues](https://github.com/facebook/Docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## Motivation

https://github.com/facebook/Docusaurus/issues/942

## Pitch

For those that build Doxygen based API docs so that the resulting HTML can be used with Docusaurus should know where to put the files (e.g., `static/api`) and that you may want to use the `separateCSS` site config option so that any CSS with the documentation gets copied directly over on build, instead of concatenated.

> `separateCss` - Directories inside which any css files will not be processed and concatenated to Docusaurus' styles. This is to support static html pages that may be separate from Docusaurus with completely separate styles.

**Comment by nathfreder** [comment]
Can you give more information, I'm interested!

**Comment by tianhaoz95** [comment]
I am facing the same issue with jsdoc, i put 'static/api' inside separateCSS, but not working, the `css` files are still missing. any more information on this?

**Comment by yangshun** [comment]
@tianhaoz95 I think it should be `separateCss` (lower case ss). Try that?

**Comment by slorber** [comment]
This is initially a v1 issue

v2 has different ways, to integrate:
- Put things in /static
- Use MDX and add an iframe to some doc page
- Build a plugin

Doxygen is one solution to generate HTML files from APIs, and there are many. I don't think we should document Doxygen in particular, or be exhaustive about all the solutions that can be integrated with Docusaurus.

Similar issue on how to integrate openapi/swagger for REST apis: https://github.com/facebook/docusaurus/issues/638

**Comment by slorber** [comment]
The Docusaurus team is actively working on Docusaurus v2.

After a very long alpha, Docusaurus v2 is [now in beta](https://docusaurus.io/blog/2021/05/12/announcing-docusaurus-two-beta).
We believe that the v2 beta is already better than v1, and v2 is ready for maintstream adoption.

Apart from critical issues and security fixes, we don't plan to invest much time on Docusaurus v1 anymore.

We are all closing v1 issues. 
Maybe the current issue is already fixed in Docusaurus v2.
Please try to upgrade, and if the issue is still there on Docusaurus v2, open a new issue.
