### ISSUE TITLE
DOM elements from home page appearing in Markdown docs page

### ISSUE THREAD

**Issue by rdmeal** [facebook/docusaurus#9444]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [X] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

When hosting a static Docusaurus site (so when no SSR occurs), navigating directly to a docs page that has been created using Markdown uses the DOM element from the home page's React Component, including any styling for that element. This does not occur when you navigate to the docs page via a link within the Docusaurus site.

e.g. Navigating via an internal link, the page looks as expected:

![navigate-via-link](https://github.com/facebook/docusaurus/assets/6094762/9c4a713a-14a7-4abf-82c0-88a528dfe91b)

However, navigating directly to the docs page retains the DOM element from the main page - including the associated styling:

![navigate-direct](https://github.com/facebook/docusaurus/assets/6094762/d732e701-fad3-4cd4-a6cc-52b676a4961e)

### Reproducible demo

https://stackblitz.com/edit/github-dzhl4y?file=src%2Fpages%2Findex.tsx

### Steps to reproduce

1. Add a Markdown docs page
2. Create React component for the Home Page, in `Pages/index.tsx` . It is the direct child element of the `Layout` element that seems to persist:
```
    <Layout>
      <div id="this-is-the-element-that-persists" >
        ...
      </div>
    </Layout>
```
In my example I have added styling (e.g. background-color) to that div to show clearly when it persists
3. Build using `docusaurus build`
4. Serve the `./build` directory using a static webserver that does not do Server-Side rendering, e.g. [serve](https://www.npmjs.com/package/serve) (note: the bug does not occur when using `docusaurus start` or `docusaurus serve`)
5. Navigate directly to `/docs/intro` (the URL of the markdown page added in step 1.) via the browser, so the website is loaded afresh (note: the bug does not occur if you use internal links from the website to navigate to the docs page)

### Expected behavior

The docs page should have no styling from the home page

### Actual behavior

A DOM element from the home page is retained in the DOM on the docs page.

Screenshot of DOM on _docs_ page (e.g. `/docs/intro`), note the `div` with the ID `home-page-container`:
![image](https://github.com/facebook/docusaurus/assets/6094762/9fe22626-9f3c-4771-a8e1-41e73a783dfb)

That ID is created in the Home Page React Component in my example:
 
![image](https://github.com/facebook/docusaurus/assets/6094762/d5633625-8dd0-4179-ada8-56156e91bb4b)

This causes all the associated styles of that DOM element to be applied, in my example that is a hotpink background colour:
![image](https://github.com/facebook/docusaurus/assets/6094762/12f27bf6-43a7-4c17-bc4e-83e1c62d0e3b)

Note: For comparison, if you navigate to the docs page via a link within the Docusaurs site, the DOM behaves correctly and looks like:
![image](https://github.com/facebook/docusaurus/assets/6094762/126e8393-d897-4d04-aea4-f70b796769b4)

### Your environment

- Public source code:
- Public site URL:
- Docusaurus version used: 2.4.3
- Environment name and version (e.g. Chrome 89, Node.js 16.4): Chrome 118, Node 16
- Operating system and version (e.g. Ubuntu 20.04.2 LTS): Windows 10

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by slorber** [comment]
> 4. Serve the ./build directory using a static web[serve](https://www.npmjs.com/package/serve)r that does not do Server-Side rendering, e.g. serve (note: the bug does not occur when using docusaurus start or docusaurus serve)

A static webserver that "does not do Server-Side rendering" does not mean anything to me. Docusaurus does not do SSR, it only does SSG (which technically is SSR at build time)

`vercel/serve` is what Docusaurus uses, but your Stackblitz is using `express/serve-static`, a totally different package. We can only support you using the official package through the Docusaurus integration, and if you choose to use something else, you are responsible to configure it appropriately to make it work for Docusaurus.

In any case, both do not do SSR and they juste serve static files found in the build folder.

---

So, what happens is:

```
"start": "npm run build && npm run serve-static",
```

On initial page load of `/docs/intro`, your web server will send the page at `build/index.html` instead of the page at `build/docs/intro/index.html`: that's a problem and a configuration issue in your web server that you need to fix if you absolutely want to use it with Docusaurus (or any static html deployment). This can be seen in stackblitz more easily if you use low 3g network throttling: it first shows your homepage, and then the weird intro doc.

The weird issues you see are related to React hydration mismatches between initial HTML, and what the SPA tries to hydrate. In Docusaurus v3 you would get a lot of errors in the console due to that problem, but in v2, React 17 doesn't emit any error.

So, this is not a bug, this is a bad usage/configuration of `express/serve-static`. I don't know this web server and can't tell you how to configure it appropriately, but if you remove the `-s` option the problem doesn't appear anymore.

> -s, --single                        Rewrite all not-found requests to `index.html`


Note some npm packages are not as good as others. I'm not sure I would recommend this one based on first impression considering it's old and `-s` seems to be a legit option to use, but apparently doesn't work as expected 🤷‍♂️ 


And reirecting to `index.html` is not even good: we want to serve `build/404.html` for these cases, with an appropriate code, which is a convention most static CDNs (Vercel, Netlify, GitHub Pages, Cloudflare Pages...) understand by default.

**Comment by rdmeal** [comment]
I maybe should have put this in the original bug report, but using `express/serve-static` was just coming up with a repro which can be done using the tools that are provided by `https://new.docusaurus.io/.` . In our actual environment we are hosting the built website with NGINX and that gives the same problem.

This still feels either like a bug or a possibility for a DX improvement - it's failing in a non-obvious way without any clear explanation to the developer around what the problem is. It should fail fast and fail loud.

**Comment by slorber** [comment]
> In our actual environment we are hosting the built website with NGINX and that gives the same problem.

This is because your NGINX is not configured properly to serve a static deployment. We at Docusaurus are not expert at NGINX. I have never used it in my life and don't really plan to, considering using a CDN is always going to be a better option.

If your company impose you the usage of NGINX, then your company must have NGINX experts that can configure it properly to host a static deployment.

The base requirement is that your NGING is configured so that `/docs/intro` serves either `/docs/intro.html` or `/docs/intro/index.html`, like any decent static host does for you out of the box.

If you want to see how CDNs serve static files out of the box, here's a nice host-by-host comparison: https://github.com/slorber/trailing-slash-guide. You will have to try to mimic those using your NGINX config.


> This still feels either like a bug or a possibility for a DX improvement

Docusaurus is only responsible for building a static deployment. Once this is done, you have the responsibility to host it properly. There's an infinite and ever-growing set of options to host a static deployment, each coming with its own configuration options. 

We can't document all this exhaustively so if you don't use any option we recommend, you have to figure this yourself reading the documentation of your host. 

You can easily google this and find a solution:
- https://jvns.ca/blog/2022/01/24/hosting-my-static-sites-with-nginx/
- https://tutorials.tinkink.net/en/nginx/nginx-static-file-server.html

> it's failing in a non-obvious way without any clear explanation to the developer around what the problem is. It should fail fast and fail loud.


It's not possible for us to "fail fast" because... Docusaurus actually works, and succeeded to build the static `./build` folder. It's not us that failed, it's you, when deploying the site.

Docusaurus v3 will be using React 18, which now lets us log React hydration errors to the console thanks to its new `onRecoverableError` callback.

I understand why you'd want this error to be "louder", but the truth is we can't really make it louder. React emits "recoverable" errors because most of the time these errors do not lead to significant problems (unlike in this case). Also such errors can be caused by third-party browser plugins altering the DOM, google Chrome autotranslate and other things like that. If we added a big `alert('it doesn't work')` then some users might be affected by it while in practice the problem does not lead to any significant problem.

So, I do agree about fail-fast, fail-loud, but in practice I don't have any technical solution to deploy this.

If you want to fail-fast, you'd have to do this on your own: deploy some bot that checks your website and tell you if there's any console error or UI bug.

**Comment by rdmeal** [comment]
Thanks for the responses.

We solved this by setting `trailingSlash:true` in `docusaurus.config.js`: https://docusaurus.io/docs/api/docusaurus-config#trailingSlash
