### ISSUE TITLE
Document the minimum disk space storage needed for a regular install

### ISSUE THREAD

**Issue by thadguidry** [facebook/docusaurus#9488]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Description

I wanted to test a few things of Docusaurus across various cloud providers with varying storage levels of containers.
One of the things I wanted to quickly find out was the minimum installation size of a Docusaurus default install.
I could not find a mention in docs or past issues.  And not where I expected it here: `/docs/installation#requirements`

Preferably we should state something along the lines of:

>The approximate minimum disk space storage needed for a default install of Docusaurus is < 2GB.  Further plugins or features will increase the storage needed.

### Self-service

- [X] I'd be willing to address this documentation request myself.

**Comment by Josh-Cena** [comment]
Install size does not depend on Docusaurus, though. It also depends on your package manager and the transitive dependencies. For example, if package A suddenly depends on a very big package B, our docs would need to be updated. If your package manager is not as good at hoisting dependencies, you may end up with multiple copies of the same version of a dependency. Yarn PnP installs packages as ZIP rather than folders. pnpm uses a global cache. All these impact the size of your node_modules. On top of that, node_modules is only a fraction of the disk space required; there's also the source files and build output, and those are uncontrollable. In all I don't think the utility of such documentation would be high and it's best if you try yourself what works best for you.

**Comment by thadguidry** [comment]
@Josh-Cena the need is not to be 100% accurate.  Instead, it is just to get a general idea of a typical install size so that those in constrained VMs or Containers can have a sense of storage taken to know if it will fit.  I appreciate your in-depth explanation, but I was well aware of that.  This is just a need to document the space likely needed.

**Comment by Josh-Cena** [comment]
Documentation we provide will necessarily be a lower bound because a site can always grow unboundedly, but you want a strict upper bound, so not sure how helpful it will be in helping you figure out space to allocate.
