### ISSUE TITLE
Hover on anchors leveraging dynamic values in a span are bad

### ISSUE THREAD

**Issue by thejcannon** [facebook/docusaurus#9497]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [X] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

I have a "helper" MDX file:

```mdx
### <span className="...">{props.title}</span>

...
```

When this is rendered, the HTML looks like:

```html
<a href="#propstitle" class="hash-link" aria-label="Direct link to propstitle" title="Direct link to propstitle">​</a>
```

### Reproducible demo

https://stackblitz.com/edit/github-pqvkar?file=docs%2F_helper.mdx

### Steps to reproduce

(See description)

### Expected behavior

My title looking like the displayed value

### Actual behavior

Tooltip uses the expression

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by slorber** [comment]
> I have a "helper" MDX file:
> 
> ```mdx
> ### <span className="...">{props.title}</span>
> 
> ...
> ```
> 
> When this is rendered, the HTML looks like:
> 
> ```
> <a href="#propstitle" class="hash-link" aria-label="Direct link to propstitle" title="Direct link to propstitle">​</a>
> ```


Not really, this is rendered as:

```html
<h3 class="anchor anchorWithStickyNavbar_node_modules-@docusaurus-theme-classic-lib-theme-Heading-styles-module" id="propstitle"><span>foo</span><a href="#propstitle" class="hash-link" aria-label="Direct link to propstitle" title="Direct link to propstitle">​</a></h3>
```

Which is the intended behavior

I understand "propstitle" does not look like a good looking value, but it is the only reasonable default we can infer here, because we must be able to compute the anchor without executing the underlying MDX/React code.

If you want another value, you can use the heading `{#headingId}` syntax instead to override the default value that we infer.

```html
<a href="#headingId" class="hash-link" aria-label="Direct link to headingId" title="Direct link to headingId">​</a>
```

For the same reason, this value can't be dynamic.


---

If you want to use a helper for headings, maybe this would work better?

```mdx
## <Helper title="foo" /> {#foo}
```

You can also provide your own custom `h2/h3/hx` component to the MDX provider map: https://docusaurus.io/docs/markdown-features/react#mdx-component-scope
