### ISSUE TITLE
Regression in v3: admonitions in nested lists are not recognized as markup elements

### ISSUE THREAD

**Issue by hrumhurum** [facebook/docusaurus#9507]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [X] I have tried creating a repro with https://new.docusaurus.io.
- [x] I have read the console error message carefully (if applicable).

### Description

Docusaurus v3.0.0 has a regression in admonitions handling when they are placed inside a list. They are not treated as markup elements while admonitions placed outside of the list are treated correctly.

### Reproducible demo

https://stackblitz.com/edit/github-42617b?file=docs%2Fintro.md

### Steps to reproduce

```
1. Item 1

2. Item 2

   :::info Important Considerations
   For better experience, try to keep the upgrade experience smooth.
   :::

:::info Important Considerations
For better experience, try to keep the upgrade experience smooth.
:::
```

### Expected behavior

Both admonitions should be rendered as admonitions.

### Actual behavior

1. The admonition inside the list is not treated as markup element and rendered as a raw text instead of an admonition element
2. The admonition outside of the list is rendered correctly

### Your environment

- Docusaurus version used: 3.0.0
- Environment name and version (e.g. Chrome 89, Node.js 16.4): Chrome 119, Node.js v18.16.0
- Operating system and version (e.g. Ubuntu 20.04.2 LTS): Windows 11

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by AnthonyTsu1984** [comment]
Same issue here.

The following indented admonition can be displayed correctly.

```
1. In the **Create New Cluster** section, choose the **Starter** plan and fill in the required parameters. 
    :::info Notes    
    
    Each user is permitted one free serverless cluster. For additional clusters, opt for the Standard or Enterprise plans.

    :::
```

![image](https://github.com/facebook/docusaurus/assets/115786031/1cdfee55-9299-4b65-a1ed-5675db4f15cb)


The following blocks do not

```
- **Scale-up cluster**
    :::caution Warning    
    
    Scaling up a cluster may cause several minutes of downtime. Please exercise caution.

    :::
```

![image](https://github.com/facebook/docusaurus/assets/115786031/e34b3814-ca53-43d6-88e3-80d6935520d4)

**Comment by slorber** [comment]
Hey

Admonitions in Docusaurus v3 are now using the Markdown directive syntax, and the way to specify a title is different now.

https://docusaurus.io/docs/markdown-features/admonitions#specifying-title

<img width="903" alt="CleanShot 2023-11-11 at 18 34 58@2x" src="https://github.com/facebook/docusaurus/assets/749374/d82ffa1a-5963-40aa-9169-f300c15f4e3f">

---

In the v3 migration guide, it is explained that we provide retrocompatibility with v2 syntax thanks to a compatibility option

https://docusaurus.io/docs/migration/v3#admonitions-option

<img width="887" alt="CleanShot 2023-11-11 at 18 36 30@2x" src="https://github.com/facebook/docusaurus/assets/749374/6cfb1614-7d1e-4cf9-a6ba-4e9eaaa5d1b5">

So, we can consider it a bug in our v2 compatibility layer: apparently we don't process admonitions properly when they are nested and line starts with space/indentation.

---

Note: this only happens with admonitions using the v2 title syntax (that we'll deprecate), because MDX is able to parse admonitions without titles and admonitions with markdown directive title syntax, cf playground:

![CleanShot 2023-11-11 at 18 38 58@2x](https://github.com/facebook/docusaurus/assets/749374/478b8760-bac5-4fe0-98ad-dbcec9e9260b)

So, we can fix it, but I'd recommend to fix it yourself by using the markdown directive label syntax.
