### ISSUE TITLE
Can't find how to install on the root of in an existing repo

### ISSUE THREAD

**Issue by olivierlambert** [facebook/docusaurus#9511]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Description

Sorry for this issue if I overlooked something, but I spend few hours to try to figure how to install Docusaurus v3 in an existing Git repo, at the root level. In short, I already have a project, and I'd like to migrate from VuePress to Docusaurus. So I'm removing all the irrelevant files (packages.json and so on), to only keep the .md files and the assets.

From there, I'd like to tell Docusaurus to scaffold at the root of this repo, but it's impossible, I always have the "Directory already exists". I know it exists, but I'd like to scaffold anyway. I don't want to have the README and the doc into a first dir while it should be on the root.

Is there any workaround? I don't want to recreate a git repo from scratch just for Docusaurus, it doesn't make sense to me.

I hope I was clear enough, let me know if I wasn't. Happy to contribute to the documentation if something is missing, and if it's not, I'll be happy to see what I missed!

### Self-service

- [X] I'd be willing to address this documentation request myself.

**Comment by Josh-Cena** [comment]
You either scaffold a new Docusaurus project and copy the relevant files back into your project, or you set up a new git repo and make it track the same upstream repo as your original one so you can directly push the new files. We don't plan to make this use case any more specialized because it's too niche. The CLI cannot "scaffold in an existing project" because then we have to decide whether each clashing file is "useful", and whether we override or merge the content—and if you have no clashing anyway, you might as well just copy en masse the generated files, which sounds trivial.

**Comment by olivierlambert** [comment]
Understood, thanks for your answer. The workaround used in the end was to move the files from the folder created to the root.
