### ISSUE TITLE
Unable to link to a *.{md,mdx} file in Markdown as static asset

### ISSUE THREAD

**Issue by dustyhorizon** [facebook/docusaurus#9526]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [X] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

Following [these](https://docusaurus.io/docs/markdown-features/assets) instructions, I am trying to "colocate" downloadable .{md,mdx} files for users to download. To prevent them from being rendered, I placed them within a `_prefixed/` folder. 

Understandably, the `static/` folder at the project root will work but I am working on a monorepo where it is preferred that such asset live closer to the documentation specific to each of these folders.

An alternative workaround is to use an arbitrary extension for these files so that the file-loader can process the properly.

Specifically to this issue, should the file loader be able to pick up these files in the first place (without using an arbitary extension)?

### Steps to reproduce

1. Create `_prefixed_directory/`
2. Create any {md,mdx} document inside said directory and name it appropriately (test.md, test.mdx)
3. Reference this file within the {md,mdx} document i.e. `[Link](./_prefixed_directory/test.{md,mdx}`
4. Notice that console warns `Docs markdown link couldn't be resolved: (./_prefixed_directory/test.mdx) in "/path/to/my/docs/20-page.mdx" for version current`

### Expected behavior

I expected that links will be created just like if it was any other file, the example in (here)[https://docusaurus.io/docs/markdown-features/assets] works.

### Actual behavior

Console throws `Docs markdown link couldn't be resolved: (./_prefixed_directory/test.mdx) in "/path/to/my/docs/20-page.mdx" for version current` and the link shown in the docs are not processed.

### Your environment

- Public source code:
- Public site URL:
- Docusaurus version used: 3.0.0
- Environment name and version (e.g. Chrome 89, Node.js 16.4): Node.js 18.18.2
- Operating system and version (e.g. Ubuntu 20.04.2 LTS): Manjaro

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by slorber** [comment]
When linking to a .md or .mdx file, Docusaurus resolves those file references to actual links.
That's a behavior documented [here](https://docusaurus.io/docs/markdown-features/links) and is considered a feature, not a bug.

---

It's unexpected that Docusaurus reports broken links. Are you even sure your steps are correct? Please provide a repro instead of steps, this makes sure that we can inspect the behavior if needed.


---

If you want to link to md/mdx files as downloadable assets instead of links, you can try to use a [Webpack inline file loader](https://webpack.js.org/concepts/loaders/#inline) but that's not a Docusaurus supported feature.

**Comment by dustyhorizon** [comment]
@slorber repro repo (here)[https://stackblitz.com/edit/github-g3ak8s?file=docs%2Flinktest.md]

**Comment by slorber** [comment]
> Console throws `Docs markdown link couldn't be resolved: (./_prefixed_directory/test.mdx) in "/path/to/my/docs/20-page.mdx" for version current` and the link shown in the docs are not processed.

This happens because the linked file is in a folder prefixed with `_`, so it does not lead to a page being created, and it's not possible to resolve the final url because there's no url for this page.

> @slorber repro repo [here](https://stackblitz.com/edit/github-g3ak8s?file=docs%2Flinktest.md)
> 
> Attached is a screenshot of the problem in terminal as well
> 
> ![image](https://user-images.githubusercontent.com/4987132/282053806-3dc40503-6c50-41ef-9aae-3e44f4e8aa14.png)

Thanks but as explained above, this is the intended behavior. If you want to allow downloading md files then you can use proprietary webpack inline file loader syntax.
