### ISSUE TITLE
Docusaurus server-side rendering could not render static page

### ISSUE THREAD

**Issue by Arhell** [facebook/docusaurus#9550]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [ ] I have tried the `npm run clear` or `yarn clear` command.
- [ ] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [ ] I have tried creating a repro with https://new.docusaurus.io.
- [ ] I have read the console error message carefully (if applicable).

### Description

Docusaurus server-side rendering could not render static page
a lot of words prevent a normal project build

name is not defined
namespace is not defined

### Steps to reproduce

1. npm run build

### Expected behavior

https://app.netlify.com/sites/karmada/deploys/65542056107b700008b60d9d
https://github.com/karmada-io/website/pull/510

example
Docusaurus server-side rendering could not render static page with path /docs/next/reference/karmada-api/networking-resources/multi-cluster-ingress-v1alpha1 because of error: namespace is not defined

https://github.com/karmada-io/website/blob/main/docs/reference/karmada-api/networking-resources/multi-cluster-ingress-v1alpha1.md

### Actual behavior

https://github.com/karmada-io/website/pull/510

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by Josh-Cena** [comment]
Please read https://docusaurus.io/blog/preparing-your-site-for-docusaurus-v3#bad-usage-of-. For example, `namespace is not defined` is because in this file: https://raw.githubusercontent.com/karmada-io/website/main/docs/reference/karmada-api/auto-scaling-resources/cron-federated-hpa-v1alpha1.md there's a `{namespace}` that's not wrapped in code.

If you have too many of these, consider trying https://docusaurus.io/docs/markdown-features#mdx-vs-commonmark.

Please don't use the bug template unless you can prove it's a bug—better to ask in discussions first.
