### ISSUE TITLE
Admin side with no sql or sqlite

### ISSUE THREAD

**Issue by gazi786** [facebook/docusaurus#9561]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Description

Cant we develop an admin portal to manage content and add content using an editor. 

### Motivation

It provides non-technical users and semi technical writers to easily navigate and maintain the content.

### Self-service

- [ ] I'd be willing to contribute this feature to Docusaurus myself.

**Comment by slorber** [comment]
I don't know what you mean by "with no sql or sqlite"

If you want a user-friendly interface to Docusaurus, that's a bit outside the scope of Docusaurus itself since its scope is to generate a static site from markdown/mdx files, and it doesn't care how you choose to provide those files (including how you edit them).

There are many ways to do that, each with tradeoffs to consider on a case-by-case basis. We don't plan to implement this in Docusaurus for now.

Notably:
- You can use a CMS and download markdown files from it as a pre-build step
- You can use a Git-based CMS (TinaCMS, NetlifyCMS...) to provide an interface on top of Markdown files stored in Git
- You can use sandbox tools like Stackblitz Codeflow or Codesandbox to make it easy to edit/commit files on Git with a real preview, not requiring users to setup nodejs/docusaurus locally

---

TinaCMS has documentation for Docusaurus: https://tina.io/blog/tinasaurus-docusaurus-starter/
