### ISSUE TITLE
Blog sidebar like in Docs

### ISSUE THREAD

**Issue by FerdinandSukhoi** [facebook/docusaurus#9593]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Description

Hello, I was very dissatisfied with the default layout of the blog before because it would leave a lot of blank space on the maximized page, and the side navigation bar could not be folded. 

After learning about Swizzle, I tried to customize my BlogLayout component and made the sidebar in blog pages look like the ones in Docs pages. I do think it looks much better now ([my blog](https://ferdinandsukhoi.github.io/blog) is using it. Sorry but it is in Chinese). 
![image](https://github.com/facebook/docusaurus/assets/54871796/30c49a4f-cd1b-4211-ac3d-2685e660ba60)

However, I am unsure if submitting a PR to you is necessary to achieve this effect, as the maintainer seems to have little interest in optimizing the display effect of the blog page (as replied in Canny). 

In addition, I'm a react newbie.

### Has this been requested on Canny?

https://docusaurus.io/feature-requests/p/blog-sidebar-like-in-docs

### Motivation

I was very dissatisfied with the default layout of the blog before because it would leave a lot of blank space on the maximized page, and the side navigation bar could not be folded. 

### Have you tried building it?

It seems to work quite well in[my blog](https://ferdinandsukhoi.github.io/blog). 

### Self-service

- [X] I'd be willing to contribute this feature to Docusaurus myself.

**Comment by FerdinandSukhoi** [comment]
In addition, I also plan to implement a nestable sidebar suitable for the blog plugin, so that blog posts can be classified and folded by time (year and month) or tags.

**Comment by slorber** [comment]
Hey

That's great that you were able to implement the design you like.

However it's not because you prefer something that the majority of users would prefer it to. 

For example I personally don't like your design, and implementing it would be disruptive for many existing sites, so I wouldn't accept such PR sorry. White spaces are here for a reason and taking the full screen width is not a good practice for readability.

I acknowledge Docusaurus doesn't have the most beautiful theme, and things are not perfect, but we need to take a coherent and uniform approach instead of accepting contribution from many external contributors having different opinions.

The good thing is that swizzle is here for that: if you don't like the defaults you can override them.

**Comment by FerdinandSukhoi** [comment]
@slorber I see, thanks for your kind interpretation.

Docusaurus is a great framework. Thanks to Swizzle, people with different opinions could have more options. Later, I will post my swizzling method here to help others who prefer a full-screen view.

Best wishes to you and Docusaurus, have a nice day!😀
