### ISSUE TITLE
SEO: blog pagination and tags pages after page 1 should be marked as "noindex" to avoid "duplicate content" penalisation

### ISSUE THREAD

**Issue by johnnyreilly** [facebook/docusaurus#9657]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Description

I've been experiencing issues with my SEO and working through it over the last year.  One of the issues is around being penalised for duplicating content.  What follows is an [tweaked excerpt from my post on the topic](https://johnnyreilly.com/how-we-fixed-my-seo#1-remove-or-noindex-unnecessary-pages). 

> The report suggests there was a good amount of duplicate content on my site. This was because Docusaurus generates "pagination" pages which allow you to navigate click by click through the whole history of a blog, and surface the blog content along the way.
>
> Also Docusaurus creates "tag" (or category) pages that reproduce blog posts under tags that have been used to categorise the posts

I've been able to solve this issue on my own site using headers. But we could move this behaviour into Docusaurus, so every gets the benefit of better behaviour by default by adding this meta tag to the relevant pages:

```jsx
<meta name="robots" content="noindex" />
```

### Has this been requested on Canny?

No

### Motivation

To improve the default behaviour of Docusaurus with regards to SEO

### API design

No API required

### Have you tried building it?

Yes - PR here: https://github.com/facebook/docusaurus/pull/9658

### Self-service

- [X] I'd be willing to contribute this feature to Docusaurus myself.

**Comment by slorber** [comment]
Your blog post is super long, I'll have to study all that 😅 can you TLDR a bit please?

---

Are you suggesting that we should totally unindex your homepage https://johnnyreilly.com/ ? 🤔 and that this should also be fine for all Docusaurus users that have a blog-only setup?

This also means that all your backlinks targeting your home will likely be "ignored" and you'll loose a good amount of SEO juice. Your Azure config does not unindex your homepage, but your PR does.

Isn't Google supposed to understand the structured data we added to paginated pages, and figure out what is duplicate content or not?

---

Where does this report comes from? 
Can we trust the tool generating it?
Is it from Google, or from an SEO tool that may not support structured data?


![image](https://github.com/facebook/docusaurus/assets/749374/60f5df18-d540-4c30-a138-8f69d9199770)

> In my case, some of these pagination or tags pages were being prioritised over the original blog posts. This felt quite strange from a readers point of view. We took a number of steps to address this.

Examples to show?

That would be helpful to figure out why it happens using official recommendations from a trusted authority like Google, and not third-party SEO tools. Isn't there a metadata we miss to fix the problem?

---

I don't take those changes lightly, and might consider them as breaking change considering the impact they can have on our community's sites SEO. 

If I merged your PR as is and released, many sites upgrading would likely significantly degrade their SEO, so we'll only merge if we are 100% sure of what we are doing. SEO does not forgive mistakes so it's important to be extra careful.

**Comment by johnnyreilly** [comment]
> Are you suggesting that we should totally unindex your homepage https://johnnyreilly.com/ ? 🤔

You have a very good point here! Yeah the root page of the blog should not have this applied - glad you spotted that!

**Comment by johnnyreilly** [comment]
> In the current state at best I could be ok to noindex page >= 2, but probably not the first page of each paginated list.

I have amended the [linked PR](https://github.com/facebook/docusaurus/pull/9658) to this behaviour.  Good catch!

**Comment by slorber** [comment]
> > Examples to show?
>
> I've remedied the issue now. It took a while; SEO fixes are slow to be picked up. Working with Growtika and following best practices got it resolved in the end. Happily!

If this is a Docusaurus problem, maybe you can illustrate it with a live example found in any Docusaurus site of our showcase? 
Not necessarily yours, but it's helpful to try to solve a problem we fully understand and having some way to eventually measure if things improved. 

I tried on our own site and even though tags and pagination gets indexed, I couldn't find any example where the paginated url would rank higher than the original content. I'd like to see this problem in action at least once before attempting to solve it. Otherwise, I have to blindly believe you that we have a problem and it's worth shipping an impactful and risky fix for the whole Docusaurus user base 😅 

<img width="921" alt="CleanShot 2023-12-22 at 11 32 50@2x" src="https://github.com/facebook/docusaurus/assets/749374/45f14db2-88b6-4c29-8697-e83f206212d5">

---

> Having multiple URLs can dilute link popularity. For example, in the diagram above, rather than 50 links to your intended display URL, the 50 links may be divided three ways among the three distinct URLs.

I doubt your readers will ever backlink backlink to `/page/2` of your blog. Devs know that the blog canonical url is the one they should link to. For me, this is a non-problem, or if it is one, show me your site backlinking profile showing backlinks to paginated pages.

> Search results may display user-unfriendly URLs (long URLs with tracking IDs, session IDs)
Decreases chances of user selecting the listing
Offsets branding efforts

Not sure how this is relevant 😅 

> Can we trust the tool generating it? I believe so, it's a widely trusted tool; 

I've seen widely used tools such as Ahrefs reporting false positives on things such as `hreflang` meta in the past, while the official Google tool did not report those. I remain sceptic unless it's from Google.

---

The official/current Google doc regarding pagination is https://developers.google.com/search/docs/specialty/ecommerce/pagination-and-incremental-page-loading?hl=en

> Give each page a unique URL. For example, include a ?page=n query parameter, as URLs in a paginated sequence are treated as separate pages by Google.

We do

> Don't use the first page of a paginated sequence as the canonical page. Instead, give each page in its own [canonical URL](https://developers.google.com/search/docs/crawling-indexing/consolidate-duplicate-urls).

We don't, each paginated page has its own canonical url

---

I can't find anywhere google mentioning to use `noindex` on paginated pages, although it could make sense to me.

Note that neither Semrush (the tool reporting you duplicate content 🤪 ) nor Ahrefs have "noindex" on their paginated pages.

- https://www.semrush.com/blog/?page=2
- https://ahrefs.com/blog/archive/page/2/
- https://moz.com/blog/p2
- https://yoast.com/seo-blog/page/2/

If people that are clever than us regarding SEO don't do this, why would we do something different?

All the "popular sites" I looked at also don't have noindex on paginated pages:

- https://webkit.org/blog/category/news/page/2/
- https://stackoverflow.com/questions/tagged/reactjs?tab=newest&page=2&pagesize=50


If Docusaurus sites have duplicate content issues (remains to be proved), and not those sites do not, then maybe the solution to implement is something different? 

How did these sites do to avoid duplicate content?

Why SEMRush reports duplicate content and the fix would be to use something SEMRush does not even use on their own blog 😅 

So far the only site implementing your solution I could find was this one: 
https://blog.mozilla.org/en/category/products/firefox/page/2/

**Comment by johnnyreilly** [comment]
> I'd like to see this problem in action at least once before attempting to solve it. Otherwise, I have to blindly believe you that we have a problem and it's worth shipping an impactful and risky fix for the whole Docusaurus user base 😅

Unfortunately having fixed the issue on my own site, I'm now unable to demo it! I've just been digging back through my messages as I'm pretty sure I had some screenshots of Google search results illustrating the issue but I can't spot it.

> each paginated page has its own canonical url

This is actually not that helpful :smile: By adding a canonical URL to a page which points to itself and duplicates content, you're signalling to search engines "this is a page you consider as a significant source of content". This is not the message you want to send with pagination pages as you're signalling that they are as important as the original blog posts.

> It may be a good solution to add noindex according to a few docs I read, but this solution has never been suggested by Google as far as I can see.

I took the implementation from this Google doc: https://developers.google.com/search/docs/crawling-indexing/block-indexing

> Overall I'm not against the change, but my intuition after reading a few "SEO pagination best practices" docs is that it's a tradeoff. You could make the paginated urls disappear from search results with noindex, but you'd eventually lose some SEO juice in the process.

My understanding is more that it's the other way around; duplicate content tends to mean you add more SEO juice to the original content, and don't get diluted by the pagination pages ranking.  

---

> Note that neither Semrush (the tool reporting you duplicate content 🤪 ) nor Ahrefs have "noindex" on their paginated pages.
>
> https://www.semrush.com/blog/?page=2
> https://ahrefs.com/blog/archive/page/2/
> https://moz.com/blog/p2
> https://yoast.com/seo-blog/page/2/
> 
> If people that are clever than us regarding SEO don't do this, why would we do something different?

So these sites *are* doing something different than Docusaurus does by default.

I go on to mention this [later in my blog post](https://johnnyreilly.com/how-we-fixed-my-seo#2-docusaurus-truncate) but essentially what those posts are doing is *not* repeating the full content in their pagination pages. Repeating the full content is the default behaviour of Docusaurus unless you've opted into using the [`truncate`](https://docusaurus.io/docs/next/blog#blog-list) marker on each blog post.

I've done that now manually, and that helps reduce the duplicate content signal significantly.

It would actually be useful if Docusaurus did these things by default:
1. In the absence of a `truncate` marker, automatically truncate after the first paragraph to reduce duplicate content
2. Didn't surface a canonical pointing to itself on the list page.

No worries if you'd rather this didn't ship - if you'd rather close this issue as "not desired" that's okay with me.

**Comment by slorber** [comment]
> This is actually not that helpful 😄 [From Google:](https://developers.google.com/search/docs/crawling-indexing/canonicalization)
> 
> > Canonicalization is the process of selecting the representative –canonical– URL of a piece of content. Consequently, a canonical URL is the URL of a page that Google chose as the most representative from a set of duplicate pages. Often called deduplication, this process helps Google show only one version of the otherwise duplicate content in its search results.
> 
> By adding a canonical URL to a page which points to itself and duplicates content, you're signalling to search engines "this is a page you consider as a significant source of content". This is not the message you want to send with pagination pages as you're signalling that they are as important as the original blog posts.

Yet you will find Google say clearly that each page should have a canonical url. Considering using canonical url and noindex the same time is a contradictory signal and a known SEO bad practice, this also implicitly means that those pages should not have noindex.

---

> My understanding is more that it's the other way around; dealing with duplicate content tends to mean you add more SEO juice to the original content, and don't get diluted by the pagination pages ranking.

If you have 3 backlinks to `/blog/xyz` and 1 backlink to `/page/2` (unlikely I admit), and you noindex the later, you now have 3 backlinks instead of 4, and your domain ranking decrease. 

IMHO keeping `/page/2` indexed does not derank `/blog/xyz`, it only adds a new candidate for ranking, hence the dilution. 

> Pagination pages didn't surface a canonical pointing to themselves.

Many SEO pagination articles clearly show


---


> In the absence of a truncate marker, automatically truncate each blog post after the first paragraph to reduce duplicate content

I guess we could use the blog description by default for paginated lists when no truncate marker is specified.

That would be a breaking change, with an opt-out option we could ship in v4.

Maybe that was the problem in the first place, and solving this alone without adding noindex would fix the duplicate content issue?


---

This article agrees with your PR:

https://seranking.com/blog/pagination/#:~:text=affect%20its%20speed.-,Prevent%20paginated%20content%20from%20being%20indexed%20by%20search%20engines,-A%20classic%20method

<img width="832" alt="CleanShot 2023-12-22 at 18 18 34@2x" src="https://github.com/facebook/docusaurus/assets/749374/103e082e-12e7-4f3e-87fd-b6dbb2f663a9">

---

This article also mentions your solution, and say the Google official recommandations shouldn't always be strictly followed: https://www.searchenginejournal.com/technical-seo/pagination/

It does mention a caveat though:

> However, the larger issue with this method is that a long-term noindex on a page will eventually [lead Google to nofollow the links](https://www.seroundtable.com/google-long-term-noindex-follow-24990.html) on that page.
> This could cause content linked from the paginated pages to be removed from the index.

Not sure how we could be affected by it considering we have an archive page and a sitemap, but still worth studying what kind of impact it could lead to.


---

Maybe we could add plugin options to enable these behaviors?

---

In general I'd prefer if we don't do all these changes bindly for all Docusaurus users.

Maybe you can apply them to your site first, and then show us with SEO metrics that there is an improvement? Doing this for all Docusaurus sites at once without measuring anything feels a bit scary.

**Comment by johnnyreilly** [comment]
> Maybe you can apply them to your site first, and then show us with SEO metrics that there is an improvement? Doing this for all Docusaurus sites at once without measuring anything feels a bit scary.

So effectively I have - I just used response headers instead of  `<meta name="robots" content="noindex" />` to achieve the same goal [as suggested by Google here](https://developers.google.com/search/docs/crawling-indexing/block-indexing#implementing-noindex):

> There are two ways to implement `noindex`: as a `<meta>` tag and as an HTTP response header. They have the same effect 

My blog is hosted on Azure Static Web Apps. Here's an excerpt from my `staticwebapp.config.json` related to pages:

```json
{
  "route": "/page/*",
  "headers": {
    "X-Robots-Tag": "noindex"
  }
}
```

This takes URLs of the pattern `/page/[page_number]` and serves up a `X-Robots-Tag: noindex` response header, as demonstrated in Chrome devtools below:

![image](https://github.com/facebook/docusaurus/assets/1010525/16416ca2-09dc-4ffe-9bd3-2521add683a2)

I can demonstrate that my SEO was in a terrible state and recovered after this change:

![image](https://github.com/facebook/docusaurus/assets/1010525/22a886d4-1489-425f-8df4-9f71042a323e)

However, this is only one of the things that I did to help it recover.  Unfortunately I can't say conclusively how much of a difference this made, I suspect it only contributed a small amount.

---

I'm going to go out on a limb and say I think you're uncomfortable with this change and you'd probably rather it didn't go ahead :smile:  That's fine; I think this would improve things but not a great deal. In the end, I'd rather you didn't lose sleep.

Unless you feel strongly otherwise, I'm going to suggest I close this issue and related PR and leave things as they are.  Sound good?

**Comment by slorber** [comment]
As you said we don't know for sure which change you did that fixed your SEO. IMHO it's the truncate marker that had the most significant impact.

What I'm not comfortable with is to not have a clear methodology to measure the impact of our changes, and to ship things that could affect negatively our users in the long term.

What about swizzling our own website first with these changes, and look at our SEO in a few months? I have Google search console and Ahrefs plugged in. If we don't see any issue in 2 or 3 months and things even improve, we can conclude it's safe to ship?

I don't mind affecting our own SEO because at some point a site has to take the risk, as long as we don't impose that risk to all users at once.

**Comment by johnnyreilly** [comment]
> What about swizzling our own website first with these changes, and look at our SEO in a few months?

Yeah that sounds like a good idea - leave it with me and I'll put up a PR in a while

**Comment by johnnyreilly** [comment]
> > In the absence of a truncate marker, automatically truncate each blog post after the first paragraph to reduce duplicate content
>
> I guess we could use the blog description by default for paginated lists when no truncate marker is specified.
>
> That would be a breaking change, with an opt-out option we could ship in v4.
>
> Maybe that was the problem in the first place, and solving this alone without adding noindex would fix the duplicate content issue?

I feel like this could be a good idea - and yeah I think the truncate marker is much more likely to have had an impact on the duplicate content issue.

**Comment by johnnyreilly** [comment]
The thoughts around truncation feel like the most valuable output of this thread: 

> IMHO it's the truncate marker that had the most significant impact.

...

> > In the absence of a truncate marker, automatically truncate each blog post after the first paragraph to reduce duplicate content
>
> I guess we could use the blog description by default for paginated lists when no truncate marker is specified.
