### ISSUE TITLE
Error: Unable to build website for locale en.

### ISSUE THREAD

**Issue by flixyudh** [facebook/docusaurus#9667]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [ ] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [ ] I have tried creating a repro with https://new.docusaurus.io.
- [ ] I have read the console error message carefully (if applicable).

### Description

I just create new docusaurus project using `npx create-docusaurus@latest doc classic` yesterday, and after finishing my website documentation using `yarn doc start`, i want to deploy it into my github pages, but i got an error when build using `yarn doc build` like so:

```bash
> yarn doc build
📁 docusaurus.config.js:11 📁 | 🧭 __dirname 🧭 | 🔀 /Users/administrator_1/Documents/Flix/react-native-flix-snackbar/doc
[INFO] [en] Creating an optimized production build...
📁 docusaurus.config.js:11 📁 | 🧭 __dirname 🧭 | 🔀 /Users/administrator_1/Documents/Flix/react-native-flix-snackbar/doc

✔ Client
  

✖ Server
  Compiled with some errors in 25.86s


Error: Unable to build website for locale en.
    at tryToBuildLocale (/Users/administrator_1/Documents/Flix/react-native-flix-snackbar/doc/node_modules/@docusaurus/core/lib/commands/build.js:55:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async mapAsyncSequential (/Users/administrator_1/Documents/Flix/react-native-flix-snackbar/doc/node_modules/@docusaurus/utils/lib/jsUtils.js:44:24)
    at async Command.build (/Users/administrator_1/Documents/Flix/react-native-flix-snackbar/doc/node_modules/@docusaurus/core/lib/commands/build.js:82:21) {
  [cause]: Error: Failed to compile due to Webpack errors.
  TypeError: Cannot read properties of undefined (reading 'match')
      at /Users/administrator_1/Documents/Flix/react-native-flix-snackbar/doc/node_modules/@docusaurus/core/lib/webpack/utils.js:207:24
      at /Users/administrator_1/Documents/Flix/react-native-flix-snackbar/doc/node_modules/webpack/lib/MultiCompiler.js:554:14
      at processQueueWorker (/Users/administrator_1/Documents/Flix/react-native-flix-snackbar/doc/node_modules/webpack/lib/MultiCompiler.js:491:6)
      at process.processTicksAndRejections (node:internal/process/task_queues:77:11)
}

[INFO] Docusaurus version: 3.0.1
Node version: v18.19.0
```

### Reproducible demo

https://github.com/flixyudh/react-native-flix-snackbar

### Steps to reproduce

use this command in terminal of cloned/forked repo

```
yarn && yarn doc build
```

### Expected behavior

same result as i see in development env

### Actual behavior

error when building for production env

### Your environment

- Public source code: https://github.com/flixyudh/react-native-flix-snackbar
- Public site URL: not yet
- Docusaurus version used: 3.0.1
- Environment name and version (e.g. Chrome 89, Node.js 16.4): Node version: v18.19.0
- Operating system and version (e.g. Ubuntu 20.04.2 LTS): macOS Monterey 12.5

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by slorber** [comment]
Please create a minimal repro, not using a monorepo.

Most likely it's a dependency problem and docusaurus is using the wrong version of a dependency such as webpack due to the code you have alongside Docusaurus. 

You can also try to configure your package manager to disable dependency hoisting, which might fix your problem.

**Comment by flixyudh** [comment]
Sorry i don't know if my project called monorepo, i just start to create my first React Native Library using [CRNL](https://callstack.github.io/react-native-builder-bob/create#usage) and add web documentation in it.

I've create a minimal repro about my case in [StackBlitz](https://stackblitz.com/edit/stackblitz-starters-vgya1z?file=docusaurus.config.js), can you take a look @slorber ?

**Comment by flixyudh** [comment]
hi @slorber, any update about the issue?

or maybe can you tell me how do i build `debug` mode in github pages? so anyone used my library at least know what it do

**Comment by slorber** [comment]
@flixyudh your repro is not a minimal repo, you have many things related to your snackbar lib.

Still, on your repro, the error is now different:

![CleanShot 2024-01-02 at 15 16 41@2x](https://github.com/facebook/docusaurus/assets/749374/894821cb-39b4-4c6d-8b1d-3a9ccbc87c96)

`sb_expose`, I assume, is a concept related to your lib, as sb can be the shorthand for "snackbar". The problem is likely related to your lib and how you integrate it with Docusaurus, and not Docusaurus itself.

Please create a real minimal repro if you want help. For each line of code you add, run `npm run build` until you clearly identify which step leads to the error above. Only then we'll be able to help.

**Comment by flixyudh** [comment]
Hi @slorber , thank you for the feedback, but can you help me how do i integrating `react-native-web` into Docusaurus?

the main reason I installing third-party like `@gorhom/docusaurus-react-native-plugin` because i'm not familiar with webpack and i don't see any documentation (or at least an example) about how to integrate `react-native` with Docusaurus,

Before using Docusaurus, I've used [react-styleguidist](https://react-styleguidist.js.org/docs/getting-started/) as it has an [example](https://github.com/styleguidist/react-styleguidist/tree/master/examples/react-native) setup adding `react-native[-web]` into the docs

or should i requesting it in another Issue-Type?

**Comment by slorber** [comment]
> Hi @slorber , thank you for the feedback, but can you help me how do i integrating `react-native-web` into Docusaurus?

No I can't do that unfortunately.

I don't have an expertise on how to use RNW with Docusaurus, I can't help on that without investing time.

The ROI is better for me to implement new Docusaurus features for everyone, rather than spending time helping a single user.


> the main reason I installing third-party like `@gorhom/docusaurus-react-native-plugin` 


You should rather contact the author of this third-party plugin for help directly, they know better than us about how to integrate RNW in Docusaurus. Again providing a clear minimal repro, making it very clear at which step the build starts to fail, will be helpful to them.

> because i'm not familiar with webpack and i don't see any documentation (or at least an example) about how to integrate `react-native` with Docusaurus.

If you are unfamiliar with Webpack, you should get familiar with it, because it is useful to have a basic understanding of how it works to get RNW running. As far as I remember you have to configure it to transpile your lib and alias rn to rnw imports (which looks like what you tried to do 👍 )

> I think it might be good if Docusaurus can provide an example of Docusaurus with `react-native` or should i requesting it in another Issue-Type?

The RNW integration can be implemented outside of the official repo through plugins, as some sites using RNW already show it is possible.

There are popular RN sites running RNW, for example Reanimated:
https://github.com/software-mansion/react-native-reanimated/blob/main/docs/docusaurus.config.js
If they can do it, you probably can too.


We don't have that documentation and don't plan to create it. If you figure out how to integrate RNW, you can then publish a blog post explaining your setup, that will help the community. But it will be your burden to maintain the post over the years so that it stays relevant.

---

This is a support request, not a Docusaurus bug, so an issue is not the appropriate place to discuss all this. 

Please ask for support in priority through the community, on Discord, Twitter or StackOverflow if you need help.
