### ISSUE TITLE
Missing href when linking to some static files in JSX

### ISSUE THREAD

**Issue by simon-leber** [facebook/docusaurus#9760]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [X] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

While linking to assets in Markdown works for most file formats, it works only for a handful of formats in JSX (MDX). The generated link does not have a `href` attribute.

I assume the files are missing from this list in the `FileLoaderUtils`: https://github.com/facebook/docusaurus/blob/bed11f62bce0632fc0b227ceeb9d2025323c4004/packages/docusaurus-utils/src/webpackUtils.ts#L170

### Reproducible demo

https://stackblitz.com/edit/github-a18bvz?file=docs%2Fintro.md

### Steps to reproduce

1. In a Markdown file, create a JSX link to an asset, for example `<a href={require('./test.csv').default}>CSV</a>`

### Expected behavior

A HTML `a` tag with an `href` attribute is created.

`<a target="_blank" href="/assets/files/test-31d6cfe0d16ae931b73c59d7e0c089c0.csv">CSV</a>`

### Actual behavior

A HTML `a` tag is created, but the `href` attribute is missing.

`<a>CSV</a>`

### Your environment

Docusaurus playground with Docusaurus version 3.1.0

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by slorber** [comment]
I understand how it can be confusing, but this is how Webpack loaders work.


JSX tags (both in MDX and React files) are rendered as-is, unprocessed, so it is your responsibility to ensure that the `<a>` `href` prop you provide to them is correct. For Markdown files.

For Markdown files, we make the assumption that a link with an extension is likely to download the file. This is fine because user still has the possibility to use JSX to opt-out of this Markdown link behavior, and having a different behavior for JSX is there on purpose.


Please consider the following JSX:

```tsx
<div>
  <a href={require('./test.csv').default}>Download test.csv</a>
</div>

<div>
  The CSV file content is:
  <pre>{require('./test.csv').default}
</div>
```

As you can see, requiring a CSV file can mean different things to different people. They might want to provide a link to that CSV, or they might want to display the content of the file itself. When using Markdown, the case is more limited because the 2nd case doesn't apply here.

It's impossible for Docusaurus to provide an opinion on how files should be loaded that would make all users happy, for that reason we only provide an opinion on the most common media files, and let users add their own opinions through custom Webpack config if they want to.

It's impossible for us to automatically support CSV as a downloadable format in Docusaurus, because many users will not want that. But if on your site, you are sure all CSV files are downloadable files and not rendered inline, you can use the [`configureWebpack`](https://docusaurus.io/docs/api/plugin-methods/lifecycle-apis#configureWebpack) hook to register your own Webpack loader


---

## Demo time


https://stackblitz.com/edit/github-a18bvz-rmfzbj?file=docs%2Fintro.md

```md
<ul>
  <li>{JSON.stringify(require('./test.docx'))}</li>
  <li>{JSON.stringify(require('./test.csv'))}</li>
  <li>{JSON.stringify(require('!file-loader?name=assets/files/[name]-[contenthash].[ext]!./test.csv'))}</li>
</ul>
```

<img width="604" alt="CleanShot 2024-01-18 at 17 09 05@2x" src="https://github.com/facebook/docusaurus/assets/749374/71f23b76-a17d-4791-ac1d-1244a3e55035">


An alternative to using `configureWebpack` could be to use [inline webpack loaders](https://webpack.js.org/concepts/loaders/#inline). In practice this is what we actually do with Markdown links. 

You can provide a sensible default thanks to the Webpack global config, but you can also decide on a case-by-case basis what does it mean for Webpack to require a file, overriding that default config.
