### ISSUE TITLE
'baseUrl' is ignored in Production routing

### ISSUE THREAD

**Issue by PJUllrich** [facebook/docusaurus#9836]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [ ] I have tried the `npm run clear` or `yarn clear` command.
- [ ] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [ ] I have tried creating a repro with https://new.docusaurus.io.
- [ ] I have read the console error message carefully (if applicable).

### Description

TLDR: When I set a `baseUrl` in the `docusaurus.config.js`, it is respected in localhost, but ignored in production in the page routing. 

## Summary

When I set the `baseUrl` of a newly created Docusaurus project, it is ignored when the project is deployed to production. For example, if I set the `baseUrl` to `/docs/` and start the server locally, it server the project from `localhost:3000/docs` and all generated links include the `baseUrl`-path. However, when I deploy the project to a production server, the `baseUrl` is ignored and the project is served from `example.com` instead of `example.com/docs` as was expected.

I created a demo repo that reproduces the bug here: https://github.com/PJUllrich/docusaurus-bug

And I deployed a demo to Nelify here: https://docusaurus-bug.netlify.app

## Config

```javascript
const config = {
  url: "https://docusaurus-bug.netlify.com",
  baseUrl: "/docs/",
  presets: [
    [
      "classic",
      ({
        docs: {
          routeBasePath: "/",
       },
       blog: {
          routeBasePath: "/blog"
       }
 // other stuff
}
```

### Result

When I access the project at `docusaurus-bug.netlify.com/docs`, I see the default `Page not found` error. if I navigate to the root domain of `docusaurus-bug.netlify.com`, I see the welcome page but also this error:

```
Your Docusaurus site did not load properly.
A very common reason is a wrong site [baseUrl configuration](https://docusaurus.io/docs/docusaurus.config.js/#baseUrl).
Current configured baseUrl = /docs/
We suggest trying baseUrl = /
```

So, for whatever reason, the `baseUrl` is correctly configured in production, but it isn't used in the routing of the pages.

### Reproducible demo

https://github.com/PJUllrich/docusaurus-bug

### Steps to reproduce

1. Set the `baseUrl` in a project to something like `/test/`.
2. Deploy the project to a server somewhere, like e.g. on Netlify.
3. Try to access the project at `https://my-app.netlify.com/test`. It will return the default `Page not Found` reply by Docusaurus.
4. Access the project at `https://my-app.netlify.com`. It will return the page as expected.

### Expected behavior

If I access the project through the full page path `https://my-app.netlify.com/test`, it should return the project.

### Actual behavior

It returns a `404`. I have to remove the `baseUrl` from the request URL to get a `200` response.

### Your environment

- Public source code: https://github.com/PJUllrich/docusaurus-bug/
- Public site URL: [https://docusaurus-bug.netlify.app/](https://docusaurus-bug.netlify.app/)
- Docusaurus version used: `3.1.1`
- Environment name and version (e.g. Chrome 89, Node.js 16.4):  `Arc 1.28.0`
- Operating system and version (e.g. Ubuntu 20.04.2 LTS): `macOS` for local develepment.

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by PJUllrich** [comment]
Sorry, I'm confused. What's the purpose of the 'baseUrl' config then? 

I thought the output would mirror the generated routing as it was described in the docs.

**Comment by slorber** [comment]
The baseUrl config permits to build a website and load assets, css and images from a base url.

Your static HTML pages will have `<script src="/baseUrl/code.js">` instead of `<script src="/code.js">`, that's all. 

Now that remains your responsibility to ensure the static files are served from `/baseUrl`: this is a configuration on your host provider and not something we can enforce through Docusaurus.

**Comment by slorber** [comment]
Afaik with older versions of npm you have to use an extra `--` to pass params:

`docusaurus build -- --out-dir build/docs`

---

> On another note, the new build folder path didn't fix my issue though. 

It should fix your issue, you probably didn't configure it properly then.
Note that in such case you also have to configure additional things on Netlify because it is not able to understand anymore the conventions of your static site. 

Notably, CDNs like Netlify know how to serve a `404.html` static file on not found urls, but now that you have `docs/404.html`, it becomes your responsibility to tell Netlify to serve this file on not found routes through the `_redirect`

```
/docs/*           /docs/404             404
```

---

> Eventually, I my docs worked fine, but my blog threw the hydration Issues #418 and #423. I never figured out the problem though.

That looks like a totally different problem. I can't help without a repro.
