### ISSUE TITLE
 Error when importing Docusaurus Swizzle component into Netlify CMS

### ISSUE THREAD

**Issue by niravbhuva99** [facebook/docusaurus#9837]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [ ] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

I am encountering an error when attempting to import a Docusaurus Swizzle component into Netlify CMS. For each Docusaurus client API component used within the Swizzle component, Webpack throws an error.

### Steps to reproduce

1. [ Navigate to the repository](https://github.com/niravbhuva99/Docusaurus-Cms).
2. Run npm install to install all the dependencies.
3. Go to the static/admin/customEditor/editor.tsx file.
4. Import any Swizzle component from the src/theme directory that uses Docusaurus client API components.
5. Run npm start to start the development server.
6. Observe the error thrown by webpack when trying to import the Swizzle component.

### Expected behavior

Upon importing a Docusaurus Swizzle component into Netlify CMS, webpack should successfully resolve the imports of Docusaurus client API components within the Swizzle component without throwing any errors.

### Error Example

When including a Docusaurus component such as `Link` within the Swizzle component, Webpack throws the following error:

![Screenshot 2024-02-08 at 17 28 21](https://github.com/facebook/docusaurus/assets/91559189/a342e3de-294e-47ad-90a2-d3c78ac55e6f)

### Your environment

- Public source code:yes
- Public site URL:no
- Docusaurus version used:3.1.1

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by slorber** [comment]
This is not related to Docusaurus.

You are getting this error while running `webpack --mode production` on a custom Webpack config file you have in your project, which we are not responsible for because it is not something we provide you.

So, this is not a Docusaurus bug.
At best, I can help you if you have specific questions. 
But please assume I don't know anything about NetlifyCMS and don't plan to study your custom setup in depth to figure out what you are doing.

Note that NetlifyCMS is not maintained anymore, and has a new name DecapCMS now:
https://www.netlify.com/blog/netlify-cms-to-become-decap-cms/

You are not even using the latest version of Docusaurus.

---

You probably misunderstand how Webpack resolves aliases, and should read more carefully this documentation:

https://webpack.js.org/configuration/resolve/#resolvealias

I'd suggest using absolute paths instead of relative paths, and use an exhaustive list of exact match aliases instead of `@docusaurus`, because `@docusaurus` will also match `@docusaurus/whatever/comes/after`.
