### ISSUE TITLE
SPA opt-out: make prefetching/preloading and routing configurable

### ISSUE THREAD

**Issue by pkowaluk** [facebook/docusaurus#9990]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Description

This feature allows the user to opt out of SPA features in Docusaurus. If they choose, they can cause the following behavior:

- opening a new page always causes the HTML file to load
- there is no pre-fetching
- there is **no** asset map in the main bundle which would allow the user access partial JS files which contain content of pages

### Has this been requested on Canny?

No

### Motivation

We host static sites though a server app which controls access to pages based on user rights. We use a variety of static site generators, one of them being Docusaurus. Docusaurus is my personal favorite for these purposes because of MDX and i18n.

When a user tries to access a URL, our server checks if they should have the access. This normally works great, but not when Docusaurus is the SSG in question. The first URL they access goes through the server and get access to the page, e.g.,

```
https://out.app.com/sites/docs/welcome
```

At this point, React Router kicks in and our server does not hear from the user anymore. Now the browser manages the URL and the pages. If there's a page in this Docusaurus site which should not be available to the user:

```
https://out.app.com/sites/docs/top-secret/birthday-party-plans
```

This page is free game. Even if we implement some client side redirects, the user can hack through in the browser and they can read the contents of the pages using the bundle files.

## `docusaurus.config.js`

Add a prop called `disableSpaFeatures` (default is `false`)

## When creating a theme/plugin

I'm not sure how that should work. theoretically, you can grab `siteConfig` mid-air in your plugin's `index.ts` and change a prop value, but maybe there should be a more canonical way of doing this?

## Effects

When that happens:
- the `preload` and `prefetch` functions are not appended to the `window.docusaurus` object
- pages don't prefetch content from other pages
- pages can still hydrate from bundle files, but there's a link to the specific bundle in ach page HTML file, there is no map in the main `bundle.js`
- opening a new page causes the HTML file to load and that file hydrates

### Have you tried building it?

We've used a [client module](https://docusaurus.io/docs/api/plugin-methods/lifecycle-apis#getClientModules) in our plugin to remove the prefetch and preload functions from the `window` object

```ts
import ExecutionEnvironment from '@docusaurus/ExecutionEnvironment';
import { ClientModule } from '@docusaurus/types';

const module: ClientModule = {
  onRouteUpdate({ location, previousLocation }) {
    if (!ExecutionEnvironment.canUseDOM) {
      return;
    }

    window.docusaurus = {
      prefetch: (url: string) => false,
      preload: (url: string) => false,
    };
  },
};

export default module;
```

And this blocks pages from prefetching, but the list of file names can still be reverse-engineered from the main `bundle.js`. The names of these .js files do not contain any information we can use to block them, and even if we did block them, this would break the pages.

React Router takes over. We've tried hacking our way out of it. We included a `useEffect` in the `Root` component which does something to the effect of:

```js
const response = await fetch(fetchUrl);

switch (response.status) {
  case 200:
    return;
  case 403:
    return window.location.replace(`/internal?restricted=${location.pathname}`);
  case 404:
    return window.location.replace(`/404?notFound=${location.pathname}`);
  default:
    return window.location.replace(`/gw-login?redirectTo=${location.pathname}`);
```

But this is happening client-side, so there are ways the user could prevent this.

### Self-service

- [X] I'd be willing to contribute this feature to Docusaurus myself.

**Comment by slorber** [comment]
HI. 

I understand that you want to drive the discussion to a concrete technical solution, but to me, it is more important that you explain the business use case, and the outcome you want from all this. This way, I can figure out the technical solution, and maybe propose you an alternative/workaround.

Can you explain:
- why you want to protect a single URL in the first place? 
- why did you choose Docusaurus given that constraint?
- why you want to link to it from a public page, and what should be the experience for a user when they click on the link considering they are not authenticated?



---

What you need looks complicated to implement and is not really an initial goal of Docusaurus. I doubt we'll make this kind of use case a priority because the ROI would be quite low considering only you ask for something like this so far.

Even if we disable the SPA navigation, prefetching and everything, the secret page bundles remain emitted, are available publicly through an URL `/assets/js/bundleX.js` that hackers can guess with brute force.  One solution could 

A possible solution could be to colocate the page JS bundle near close the HTML file. This way even if the JS bundle is referenced in a map, it can't be downloaded if you protect the `/docs/top-secret/birthday-party-plans` path. It is probably possible to use `configureWebpack` plugin lifecycle today to achieve that.

**Comment by pkowaluk** [comment]
Thanks for taking on the discussion.


   - why you want to protect a single URL in the first place?

We want to decide on a page-by-page basis. About half the pages will need
to be public, and the rest password-protected.

   - why did you choose Docusaurus given that constraint?

It's a new requirement. We've been using Docusaurus for a while and our
approach so far was that we decided about access on a site level - either
the entire Docusaurus site is public or not. Now we want to have more
fine-grained control. We could switch to a different SSG, but that would be
a significant investment, so we're trying to figure out if we can stay with
Docusaurus and still accomplish our goals

   - why you want to link to it from a public page, and what should be the
   experience for a user when they click on the link considering they are not
   authenticated?

Given that some pages are public and some are not, we want to maintain the
current punks. If a user clicks a link the don't have access to, our server
can handle it - redirect them to a login page.

I understand that this is not a core use case for you guys, and we'd be
willing to contribute this feature ourselves. Of course, given your
guidance and following all your rules. For example, that idea about
collocated bundles is a great suggestion.

Let me know if I can do anything to help move this forward. At the same
time I understand you have different priorities and I understand if you
don't want to support us in this. Docusaurus remains an awesome SSG and a
real gem for the open source community.

**Comment by slorber** [comment]
Thanks

So you want only some pages to be "protected". 

Are all the logged-in users of your site able to access the exact same pages, or each user can see a different set of protected pages?

**Comment by pkowaluk** [comment]
Yes, only some pages are to be protected.

We're experimenting with adding a custom prop in the prolog called `public`
which can be set to either `true` or `false` and some way to set a default.

Now, we also have a prop called `internal` which makes pages available only
to employees, so not all users are meant to see the same pages. This prop
is tricky because we've implemented it in the front end and we didn't
really care about the contents being secure. We could leave it as is, but
maybe there's a way to set it up so that it's similarly protected. 🤔

**Comment by slorber** [comment]
I'm not sure to understand sorry 😅

If logged in users see the exact same content, you could build the same site in 2 variants, one public, one authenticated. Then deploy both to a CDN and use a Middleware proxy to serve one site or the author depending on auth status. For example, try Vercel + edge Middleware or Cloudflare + Worker.

**Comment by pkowaluk** [comment]
Good suggestion, Sebastien. That's our plan B if we cannot find a way to
make "one site" work.

So, are you saying we should not move forward with the feature and build
two sites instead?

**Comment by slorber** [comment]
Building 2 sites will give a better experience in this case IMHO, because it would be secure and you would keep the SPA behavior, which is important not only to improve the navigation experience but also to preserve the state when navigating. For example, if you navigate through regular links, the docs sidebar items collapsed state would reset.

I would do something like:

```bash
VARIANT=public docusaurus build --out-dir build/public
VARIANT=private docusaurus build --out-dir build/private
```

Based on env variables you could use `include` / `exclude` params in the docs plugin to choose which docs to include.

Then I would use a Vercel Edge auth middleware. You'd have to figure out the details but here are some refs and examples:
- https://vercel.com/docs/functions/edge-middleware/middleware-api
- https://github.com/vercel/examples/tree/main/edge-middleware


I guess something like this could work:

```ts
import { rewrite } from '@vercel/edge';
 
export default function middleware(request: Request) {
  const url = new URL(request.url);
  if (isAuthenticated(req)) {
    url.pathname = "/private" + url.pathname;
  }
  else {
    url.pathname = "/public" + url.pathname;
  }
  return rewrite(url);
}
```

Now it's your responsibility to implement the `isAuthenticated() method`.

Note: you shouldn't use `baseUrl: '/public/'` and `baseUrl: '/private/'` when building because, even though the files will be deployed under a subpath, you'd still serve them from the root without any prefix. 

Now if you want you can also keep the prefix in the URL and use a redirect instead of a rewrite.
And you are not forced to use subpaths either. Using subdomains like `private.myDoc.com` and `public.myDoc.com` or whatever else you want can also work with both subpath and subdomains strategies.

**Comment by pkowaluk** [comment]
This is great, Sébastien, thanks for sharing this detailed recipe. We will
go that route for sure. You are right that preserving the SPA functionality
makes for a better user experience.

Feel free to close this feature request.
